### ISSUE TITLE
ESQL: Tracker for tests impacted by the circuit breaker

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#100147]
### Description

We currently have a flurry of tests that are impacted by the circuit breaker work - while this is a 'transient' stage, we want to make sure we're not forgetting re-enabling the tests back hence why this ticket was created - to centralize the various disabled/ignored tests.

- [ ] https://github.com/elastic/elasticsearch/issues/100145
- [ ] https://github.com/elastic/elasticsearch/issues/100142
- [ ] https://github.com/elastic/elasticsearch/issues/100114
- [ ] grokStats https://github.com/elastic/elasticsearch/pull/100139/files#diff-3cb8845c42f66b20f5a5e7a277b0933262c1591e2046238a1696b85523b887e0
- [ ] dissectStats - https://github.com/elastic/elasticsearch/pull/100140/files#diff-39b970c27ab73579101dc3225d515a29f33a61c74024ac97a621ec4dd18e723bR103

**Comment by nik9000** [comment]
closing this for 8.11. 8.12 should contain #100528.
