### ISSUE TITLE
ESQL: More love for functions

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#100558]
I'd like to make sure that every function has:
* Unit tests containing
  * Comprehensive type coverage
  * Null inputs, usually generated by `anyNullIsNull`
  * Type error inputs, usually generated by `errorsForCasesWithoutExamples`
* ~~A documentation page containing~~ Covered by the checklist in https://github.com/elastic/elasticsearch/issues/104247#issuecomment-2018954169
* In `SHOW FUNCTIONS`
  * A description
  * Parameter names
  * Parameter types

Here's a list of all the functions. At the time of first writing *some* of these have some of these things, but few have all of them.

- [ ] `%` (Mark)
- [ ] `*` (Mark)
- [ ] `+` (Mark)
    - [x] full null testing is blocked on the date math nulls issue(https://github.com/elastic/elasticsearch/issues/103085)
    - [ ] https://github.com/elastic/elasticsearch/issues/102935 is a blocker for type checking in binary arithmetic operations
- [ ] `-` (Mark)
- [ ] `/` (Mark)
- [x] `==`
- [x] `!=`
- [x] `>`
- [x] `>=`
- [x] `<`
- [x] `<=`
- [ ] `Abs`
- [x] `Acos` https://github.com/elastic/elasticsearch/pull/105525
- [x] `Asin` https://github.com/elastic/elasticsearch/pull/105525
- [x] `Atan` https://github.com/elastic/elasticsearch/pull/105525
- [x] `Atan2` https://github.com/elastic/elasticsearch/pull/105525
- [ ] `AutoBucket`
- [ ] `Case`
- [ ] `Ceil`
- [x] `CIDRMatch`
- [x] `Coalesce`
- [ ] `Concat`
- [x] `Cos`  #103205
- [x] `Cosh`  #103205
- [ ] `DateExtract`
- [ ] `DateFormat`
- [ ] `DateParse`
- [ ] `DateTrunc`
- [ ] `E`
- [ ] `EndsWith`
- [ ] `Floor`
- [ ] `Greatest`
- [x] `IsFinite` https://github.com/elastic/elasticsearch/pull/104091
- [x] `IsInfinite` https://github.com/elastic/elasticsearch/pull/104091
- [x] `IsNaN` https://github.com/elastic/elasticsearch/pull/104091
- [ ] `Least`
- [ ] `Left`
- [ ] `Length`
- [ ] `Log` #106963
- [ ] `Log10` #106963
- [x] `LTrim` #102308
- [ ] `MvAvg`
- [ ] `MvConcat` #100564
- [x] `MvCount` #100564
- [x] `MvDedupe` #100564
- [x] `MvMax` #100564
- [ ] `MvMedian`
- [x] `MvMin` #100564
- [ ] `MvSum`
- [ ] `Neg`
- [x] `Now`
- [x] `Pow` #102183
- [x] `Pi`
- [ ] `Replace`
- [ ] `Right`
- [ ] `Round`
- [x] `RTrim`  #102308
- [x] `Sin`
- [x] `Sinh`  #103205
- [ ] `Split`
- [ ] `Sqrt`
- [ ] `StartsWith`
- [ ] `Substring`
- [x] `Tan`  #103205
- [x] `Tanh`  #103205
- [x] `Tau`
- [x] `ToBoolean`
- [x] `ToCartesianPoint` #103507 
- [x] `ToDatetime`
- [x] `ToDegrees`
- [x] `ToDegrees`
- [x] `ToDouble`
- [x] `ToGeoPoint` #103507 
- [x] `ToInteger`
- [x] `ToIP`
- [x] `ToLong`
- [x] `ToRadians`
- [x] `ToRadians`
- [x] `ToString`
- [x] `ToString`
- [x] `ToUnsignedLong`
- [x] `ToVersion`
- [x] `Trim`  #102308

After we've done this we can:
- [x] Remove `AbstractScalarFunctionTestCase` - all this class does is provide a weaker version of the `anyNullIsNull` assertions.

**Comment by nik9000** [comment]
I think we're not entirely done, but #112401 includes *many* of the things we need to check CASE off the list.

**Comment by nik9000** [comment]
Replacing this one with https://github.com/elastic/elasticsearch/issues/134155
