### ISSUE TITLE
Block and Vector creation can start to use a block factory that performs circuit breaking - 8.12

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#100528]
Extends https://github.com/elastic/elasticsearch/issues/99173

### Description

This meta issue lists a number of places in the ESQL runtime where Block and Vector creation can start to use a block factory that performs breaking/accountancy that needs to land in 8.12.

- [ ] #100678
- [x] #100640
- [x] #102683
 - [x] Reference tracking https://github.com/elastic/elasticsearch/pull/100408
 - [ ] Remove copy operations
   - [x] Deep copy on aliases https://github.com/elastic/elasticsearch/pull/100408
   - [x] Deep copy in eval https://github.com/elastic/elasticsearch/pull/100408
   - [ ] ~Copy in filter @alex-spies~ **Update:** not planned, currently not clear whether this really improves performance.
   - [x] Copy in expand https://github.com/elastic/elasticsearch/pull/103681
 - [x] operators (all not covered in #99826
   - [x] Enrich @dnhatn 
   - [x] LuceneSource @nik9000 #101396
   - [x] doc values reading @nik9000  #101383
   - [x] stored field reading @nik9000  #101383
   - [x] dissect #101400
 - [x] generate `toString` for `ExpressionEvaluator.Factory` and remove `ThrowingDriverContext` from `EvalOperatorFactory.describe` #100516
 - [x] Move BlockFactory.getNonBreakingInstance() to tests only (https://github.com/elastic/elasticsearch/pull/103661)
 - [ ] Make sure that many many many small pages don't fill up memory without filling the breaker. See `testTooManyEval`.
- [x] Remove Block.Ref (https://github.com/elastic/elasticsearch/pull/102513)
- [x] Remove deprecated Block methods
- [x] BytesRef does allocation that can’t be tracked when going across a page boundary (#102350)

**Comment by alex-spies** [comment]
Sorry, the GH bot auto-closed this.

**Comment by dnhatn** [comment]
Closing this in favor of #104110 for remaining items.
