### ISSUE TITLE
Clean up threading model for Repository#getRepositoryData

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#101445]
`Repository#getRepositoryData` usually completes its listener on the calling thread, but may sometimes end up using some other thread instead, possibly even a low-latency one such as a transport worker or the master service thread. That makes it pretty trappy to use and forces the caller to fork to do any nontrivial work even though it's usually unnecessary. We should instead use the same pattern as with `SubscribableListener#addListener` and take an executor argument which is only used if the listener is not completed on the calling thread.

- [ ] Add executor parameter to `Repository#getRepositoryData`
- [ ] Clean up threading in callers
  - [ ] `org.elasticsearch.index.shard.StoreRecovery#restore`
  - [ ] `org.elasticsearch.repositories.IndexSnapshotsService#getLatestSuccessfulSnapshotForShard`
  - [ ] `org.elasticsearch.repositories.RepositoriesService#registerRepository`
  - [ ] `org.elasticsearch.repositories.RepositoriesService#getRepositoryData`
  - [ ] `org.elasticsearch.snapshots.RestoreService#restoreSnapshot`
  - [ ] `org.elasticsearch.snapshots.RestoreService#refreshRepositoryUuids`
  - [ ] `org.elasticsearch.snapshots.SnapshotsService#startCloning`
  - [ ] `org.elasticsearch.snapshots.SnapshotsService#endSnapshot`
  - [ ] `org.elasticsearch.snapshots.SnapshotsService#executeConsistentStateUpdate`
  - [ ] `org.elasticsearch.xpack.searchablesnapshots.action.TransportMountSearchableSnapshotAction#masterOperation`
  - [ ] `org.elasticsearch.xpack.slm.SLMGetExpiredSnapshotsAction.LocalAction#doExecute`
