### ISSUE TITLE
Reduce usage of `TransportMasterNodeReadAction`

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#101805]
`TransportMasterNodeReadAction` is intended for cases where we need to collect some state held only on the master, for instance related to shard allocation or data stream errors. However, many `TransportMasterNodeReadAction` implementations work as a pure function of the cluster state, which is held on every node, so there is no need to route these requests to the master for processing. Moreover, some of these requests may be quite expensive to process in large clusters, so routing them all to the master represents a scalability bottleneck. We should reconsider each usage of `TransportMasterNodeReadAction` and decide whether it needs to run on the master or not. If not, we should convert them to regular local-only transport actions.

Note that attempting to route these requests to the current master does not give them any stronger consistency guarantees, because the node that does the work does not validate that it is the master before responding. It's possible that a new master has been elected, and the cluster state updated, without the responding node knowing about it.

- [ ] `GetDataStreamsTransportAction` (`org.elasticsearch.datastreams.action`)
- [ ] `GetPipelineTransportAction` (`org.elasticsearch.action.ingest`)
- [ ] `TransportClusterGetSettingsAction` (`org.elasticsearch.action.admin.cluster.settings`)
- [ ] `TransportClusterHealthAction` (`org.elasticsearch.action.admin.cluster.health`)
- [ ] `TransportClusterInfoAction` (`org.elasticsearch.action.support.master.info`)
- [ ] `TransportExplainLifecycleAction` (`org.elasticsearch.xpack.ilm.action`)
- [ ] `TransportGetIndexAction` (`org.elasticsearch.action.admin.indices.get`)
- [ ] `TransportGetMappingsAction` (`org.elasticsearch.action.admin.indices.mapping.get`)
- [ ] `TransportClusterSearchShardsAction` (`org.elasticsearch.action.admin.cluster.shards`)
- [ ] `TransportClusterStateAction` (`org.elasticsearch.action.admin.cluster.state`)
- [ ] `TransportDeprecationInfoAction` (`org.elasticsearch.xpack.deprecation`)
- [ ] `TransportExplainDataStreamLifecycleAction` (`org.elasticsearch.datastreams.lifecycle.action`)
- [ ] `TransportFollowInfoAction` (`org.elasticsearch.xpack.ccr.action`)
- [ ] `TransportGetAnalyticsCollectionAction` (`org.elasticsearch.xpack.application.analytics.action`)
- [ ] `TransportGetAutoFollowPatternAction` (`org.elasticsearch.xpack.ccr.action`)
- [ ] `TransportGetBasicStatusAction` (`org.elasticsearch.license`)
- [ ] `TransportGetComponentTemplateAction` (`org.elasticsearch.action.admin.indices.template.get`)
- [ ] `TransportGetComposableIndexTemplateAction` (`org.elasticsearch.action.admin.indices.template.get`)
- [ ] `TransportGetDatafeedsAction` (`org.elasticsearch.xpack.ml.action`)
- [ ] `TransportGetDataStreamLifecycleAction` (`org.elasticsearch.datastreams.lifecycle.action`)
- [ ] `TransportGetDesiredBalanceAction` (`org.elasticsearch.action.admin.cluster.allocation`)
- [ ] `TransportGetDesiredNodesAction` (`org.elasticsearch.action.admin.cluster.desirednodes`)
- [ ] `TransportGetEnrichPolicyAction` (`org.elasticsearch.xpack.enrich.action`)
- [ ] `TransportGetIndexTemplatesAction` (`org.elasticsearch.action.admin.indices.template.get`)
- [ ] `TransportGetJobModelSnapshotsUpgradeStatsAction` (`org.elasticsearch.xpack.ml.action`)
- [ ] `TransportGetJobsAction` (`org.elasticsearch.xpack.ml.action`)
- [ ] `TransportGetLicenseAction` (`org.elasticsearch.license`)
- [ ] `TransportGetRepositoriesAction` (`org.elasticsearch.action.admin.cluster.repositories.get`)
- [ ] `TransportGetSettingsAction` (`org.elasticsearch.action.admin.indices.settings.get`)
- [ ] `TransportGetStoredScriptAction` (`org.elasticsearch.action.admin.cluster.storedscripts`)
- [ ] `TransportGetTrialStatusAction` (`org.elasticsearch.license`)
- [ ] `TransportIndicesShardStoresAction` (`org.elasticsearch.action.admin.indices.shards`)
- [ ] `TransportPendingClusterTasksAction` (`org.elasticsearch.action.admin.cluster.tasks`)
- [ ] `TransportPrevalidateNodeRemovalAction` (`org.elasticsearch.action.admin.cluster.node.shutdown`)
- [ ] `TransportSimulateIndexTemplateAction` (`org.elasticsearch.action.admin.indices.template.post`)
- [ ] `TransportSimulateTemplateAction` (`org.elasticsearch.action.admin.indices.template.post`)
- [ ] any other `TransportMasterNodeReadAction` implementations added since this list was created

Relates #77466

**Comment by idegtiarenko** [comment]
I believe TransportGetDesiredBalanceAction is required to run on **elected** as it response contains `DesiredBalanceStats` that are computed in the allocator during execution. I think the same is true regarding ClusterInfo. Alternatively we can update the action to run anywhere in the cluster and read only the stats and clusterInfo from elected master.

**Comment by DaveCTurner** [comment]
> I believe TransportGetDesiredBalanceAction is required to run on elected

Me too - please feel free to cross it off the list in the OP with a comment to that effect.

**Comment by nielsbauman** [comment]
I'm adding `TransportGetStatusAction` (`org.elasticsearch.xpack.ilm.action`) to the list. It doesn't extend `TransportMasterNodeReadAction` (it extends `TransportMasterNodeAction`), but it's also a pure function of the cluster state.

**Comment by burqen** [comment]
I believe `TransportClusterHealthAction` must be run on master. Here are the things I believe point in this direction, given my current, admittedly limited, understanding:
- We provide an option in the rest API to run on local non-master node and this option is `false` by default. Changing this behavior to only run locally instead of on master would be a breaking change, I assume. [Documentation](https://www.elastic.co/docs/api/doc/elasticsearch/operation/operation-cluster-health#operation-cluster-health-local)
- `number_of_pending_tasks` is only available on master
- `number_of_in_flight_fetch ` is only available on master
- `task_max_waiting_in_queue` and `task_max_waiting_in_queue_millis` is only available on master (I believe this correlates with `MasterService#getMaxTaskWaitTime()` but not sure)

Can I please have another set of eyes on this @nielsbauman or @DaveCTurner ?

**Comment by DaveCTurner** [comment]
> Changing this behavior to only run locally instead of on master would be a breaking change, I assume.

No I don't think so - running an action on the master doesn't change its semantics (or even offer any stronger consistency guarantees) compared with running it on the coordinating node, because the `isLocalNodeElectedMaster` check in `TransportMasterNodeAction.AsyncSingleAction#doStart` isn't a strongly-consistent read: a new master may have been elected but if the old master doesn't know about it yet then it may proceed with the execution of the action and return stale information here.

> `number_of_pending_tasks`, `number_of_in_flight_fetch`, `task_max_waiting_in_queue` and `task_max_waiting_in_queue_millis` are only available on master

That's correct, and a compelling reason not to migrate this API. We also cannot support the `?wait_for_events` parameter elsewhere.

Thanks for updating the checklist in the OP; I'd suggest we either mark this one as done or else just remove it from the list entirely.

**Comment by burqen** [comment]
`TransportClusterInfoAction` seem to have been deleted somewhere between `9.0.8` and `9.1.0`. Marking as done.

**Comment by DaveCTurner** [comment]
> `TransportClusterInfoAction` seem to have been deleted somewhere between `9.0.8` and `9.1.0`. Marking as done.

Pro-tip: `git log -G` is a good way to pin this kind of thing down quickly:

```
$ git log -G TransportClusterInfoAction -n1
commit 483f97915c654878d7b5bbce707216979f962e91
Author: Niels Bauman <33722607+nielsbauman@users.noreply.github.com>
Date:   Wed Apr 2 18:41:35 2025 +0100

    Run `TransportGetIndexAction` on local node (#125652)

    This action solely needs the cluster state, it can run on any node.
    Since this is the last class/action that extends the `ClusterInfo`
    abstract classes, we remove those classes too as they're not required
    anymore.

    Relates #101805
```

So yeah this was an abstract base class, we already migrated all its subclasses to use the local node, and it wasn't necessary any more. Done and done.

**Comment by burqen** [comment]
Thanks Dave, that's super useful!
