### ISSUE TITLE
[Meta] Make SearchResponse use pooled buffers for search hits

### ISSUE THREAD

**Issue by original-brownbear** [elastic/elasticsearch#102030]
WIP issue but lets start collecting related PRs here already:

Test work:

* [x] https://github.com/elastic/elasticsearch/pull/102040
* [x] https://github.com/elastic/elasticsearch/pull/102031
* [x] https://github.com/elastic/elasticsearch/pull/102024
* [x] https://github.com/elastic/elasticsearch/pull/102021
* [x] https://github.com/elastic/elasticsearch/pull/102019
* [x] https://github.com/elastic/elasticsearch/pull/102008
* [x] https://github.com/elastic/elasticsearch/pull/101999
* [x] https://github.com/elastic/elasticsearch/pull/101996
* [x] https://github.com/elastic/elasticsearch/pull/101992
* [x] https://github.com/elastic/elasticsearch/pull/101196
* [x] https://github.com/elastic/elasticsearch/pull/102035
* [x] https://github.com/elastic/elasticsearch/pull/102036
* [x] https://github.com/elastic/elasticsearch/pull/102037
* [x] https://github.com/elastic/elasticsearch/pull/102038
* [x] https://github.com/elastic/elasticsearch/pull/102054
* [x] https://github.com/elastic/elasticsearch/pull/102053 (example of scroll search)
* [x] https://github.com/elastic/elasticsearch/pull/102044
* [x] https://github.com/elastic/elasticsearch/pull/102003
* [x] https://github.com/elastic/elasticsearch/pull/102029
* [x] https://github.com/elastic/elasticsearch/pull/102074
* [x] https://github.com/elastic/elasticsearch/pull/102076
* [x] https://github.com/elastic/elasticsearch/pull/102087
* [x] https://github.com/elastic/elasticsearch/pull/102090
* [x] https://github.com/elastic/elasticsearch/pull/102095
* [x] https://github.com/elastic/elasticsearch/pull/102098
* [x] https://github.com/elastic/elasticsearch/pull/102117
* [x] https://github.com/elastic/elasticsearch/pull/102119
* [x] https://github.com/elastic/elasticsearch/pull/102129
* [x] https://github.com/elastic/elasticsearch/pull/102131
* [x] https://github.com/elastic/elasticsearch/pull/102132
* [x] https://github.com/elastic/elasticsearch/pull/102139
* [x] https://github.com/elastic/elasticsearch/pull/102141
* [x] https://github.com/elastic/elasticsearch/pull/102189
* [x] https://github.com/elastic/elasticsearch/pull/102224
* [x] https://github.com/elastic/elasticsearch/pull/102534
* [x] https://github.com/elastic/elasticsearch/pull/102536
* [x] https://github.com/elastic/elasticsearch/pull/102539
* [x] https://github.com/elastic/elasticsearch/pull/102542
* [x] https://github.com/elastic/elasticsearch/pull/102604
* [x] https://github.com/elastic/elasticsearch/pull/102669
* [x] https://github.com/elastic/elasticsearch/pull/102694
* [x] https://github.com/elastic/elasticsearch/pull/102822
* [x] https://github.com/elastic/elasticsearch/pull/102896
* [x] https://github.com/elastic/elasticsearch/pull/102897
* [x] https://github.com/elastic/elasticsearch/pull/103068
* [x] https://github.com/elastic/elasticsearch/pull/103239
* [x] https://github.com/elastic/elasticsearch/pull/103118
* [x] https://github.com/elastic/elasticsearch/pull/103240
* [x] https://github.com/elastic/elasticsearch/pull/103265
* [x] https://github.com/elastic/elasticsearch/pull/103269
* [x] https://github.com/elastic/elasticsearch/pull/103532
* [x] https://github.com/elastic/elasticsearch/pull/103533
* [x] https://github.com/elastic/elasticsearch/pull/103617
* [x] https://github.com/elastic/elasticsearch/pull/103956
* [x] https://github.com/elastic/elasticsearch/pull/103957
* [x] https://github.com/elastic/elasticsearch/pull/104022

Production work:
* [x] https://github.com/elastic/elasticsearch/pull/102052
* [x] https://github.com/elastic/elasticsearch/pull/102179
* [x] https://github.com/elastic/elasticsearch/pull/102274
* [x] https://github.com/elastic/elasticsearch/pull/102551
* [x] https://github.com/elastic/elasticsearch/pull/102607
* [x] https://github.com/elastic/elasticsearch/pull/102638
* [x] https://github.com/elastic/elasticsearch/pull/102900
* [x] https://github.com/elastic/elasticsearch/pull/102989
* [x] https://github.com/elastic/elasticsearch/pull/103009
* [x] https://github.com/elastic/elasticsearch/pull/103021
* [x] https://github.com/elastic/elasticsearch/pull/103118
* [x] https://github.com/elastic/elasticsearch/pull/103583
* [x] https://github.com/elastic/elasticsearch/pull/103637
* [x] https://github.com/elastic/elasticsearch/pull/103803
* [x] https://github.com/elastic/elasticsearch/pull/103931
* [x] https://github.com/elastic/elasticsearch/pull/103929
* [x] https://github.com/elastic/elasticsearch/pull/103961
* [x] https://github.com/elastic/elasticsearch/pull/103983
* [x] https://github.com/elastic/elasticsearch/pull/104060
* [x] https://github.com/elastic/elasticsearch/pull/104128
* [ ] https://github.com/elastic/elasticsearch/pull/104196
* [ ] once tests are done read sliced releasable bytes ref for search hit source and adjust all classes referring to search hits to have proper reference counting as well
