### ISSUE TITLE
Refactor parsing of queries/filters, aggs, suggester APIs

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#10217]
Copied from #9901:

Today we have a massive infrastructure to parse all our requests. We have client side builders and server side parsers but no real representation of the query, filter, aggregation etc until it's executed. What is produced from a XContent binary is a Lucene query directly which causes huge parse methods in separate classes etc. that hare hard to test and don't allow decoupled modifications or actions on the query itself between parsing and executing. 

This refactoring splits the parsing and the creation of the lucene query, this has a couple of advantages
- XContent parsing creation are in one file and can be tested more easily
- the class allows a typed in-memory representation of the query that can be modified before a lucene query is build
- the query can be normalized and serialized via Streamable to be used as a normalized cache key (not depending on the order of the keys in the XContent)
- the query can be parsed on the coordinating node to allow document prefetching etc. forwarding to the executing nodes would work via Streamable binary representation --> https://github.com/elasticsearch/elasticsearch/issues/8150
- for the query cache a query tree can be "walked" to rewrite range queries into match all queries with MIN/MAX terms to get cache hits for sliding windows --> https://github.com/elasticsearch/elasticsearch/issues/9526
- code wise two classes are merged into one which is nice
## Queries (Completed)
- [x] AndQueryBuilder  (https://github.com/elastic/elasticsearch/pull/11628) 
- [x] BoolQueryBuilder (https://github.com/elastic/elasticsearch/pull/11121)
- [x] BoostingQueryBuilder (https://github.com/elastic/elasticsearch/pull/11621)
- [x] CommonTermsQueryBuilder (https://github.com/elastic/elasticsearch/pull/11345)
- [x] ConstantScoreQueryBuilder (https://github.com/elastic/elasticsearch/pull/11629)
- [x] DisMaxQueryBuilder (https://github.com/elastic/elasticsearch/pull/11703)
- [x] ExistsQueryBuilder (https://github.com/elastic/elasticsearch/pull/11427)
- [x] FieldMaskingSpanQueryBuilder (https://github.com/elastic/elasticsearch/pull/11717)
- [x] FilteredQueryBuilder (https://github.com/elastic/elasticsearch/pull/11885)
- [x] FQueryFilterBuilder (https://github.com/elastic/elasticsearch/pull/11729)
- [x] FunctionScoreQueryBuilder (#13653)
- [x] FuzzyQueryBuilder (https://github.com/elastic/elasticsearch/pull/11865)
- [x] GeoBoundingBoxQueryBuilder (https://github.com/elastic/elasticsearch/pull/11969)
- [x] GeoDistanceQueryBuilder(https://github.com/elastic/elasticsearch/pull/13496)
- [x] GeoDistanceRangeQueryBuilder (https://github.com/elastic/elasticsearch/pull/13496)
- [x] GeohashCellQuery (#13393)
- [x] GeoPolygonQueryBuilder (#13426)
- [x] GeoShapeQueryBuilder (https://github.com/elastic/elasticsearch/pull/13466)
- [x] HasChildQueryBuilder (#13333)
- [x] HasParentQueryBuilder (#13408)
- [x] IdsQueryBuilder (#10670)
- [x] IndicesQueryBuilder (https://github.com/elastic/elasticsearch/pull/12031)
- [x] LimitQueryBuilder (#11551)
- [x] MatchAllQueryBuilder (#10668)
- [x] MatchQueryBuilder (#13402)
- [x] MissingQueryBuilder (https://github.com/elastic/elasticsearch/pull/12030)
- [x] MoreLikeThisQueryBuilder (https://github.com/elastic/elasticsearch/pull/13486)
- [x] MultiMatchQueryBuilder (#13405)
- [x] NestedQueryBuilder (https://github.com/elastic/elasticsearch/pull/13424)
- [x] NotQueryBuilder (https://github.com/elastic/elasticsearch/pull/11823)
- [x] OrQueryBuilder (https://github.com/elastic/elasticsearch/pull/11817)
- [x] PrefixQueryBuilder (https://github.com/elastic/elasticsearch/pull/12032)
- [x] QueryFilterBuilder (https://github.com/elastic/elasticsearch/pull/11729)
- [x] QueryStringQueryBuilder (#13284)
- [x] QueryWrappingQueryBuilder (will be removed once all queries refactored)
- [x] RangeQueryBuilder (#11108)
- [x] RegexpQueryBuilder (https://github.com/elastic/elasticsearch/pull/11896)
- [x] ScriptQueryBuilder (https://github.com/elastic/elasticsearch/pull/12115)
- [x] SimpleQueryStringBuilder (https://github.com/elastic/elasticsearch/pull/11274)
- [x] SpanContainingQueryBuilder (https://github.com/elastic/elasticsearch/pull/12057)
- [x] SpanFirstQueryBuilder (https://github.com/elastic/elasticsearch/pull/12073)
- [x] SpanMultiTermQueryBuilder (https://github.com/elastic/elasticsearch/pull/12182)
- [x] SpanNearQueryBuilder (https://github.com/elastic/elasticsearch/pull/12156)
- [x] SpanNotQueryBuilder (https://github.com/elastic/elasticsearch/pull/12365)
- [x] SpanOrQueryBuilder (https://github.com/elastic/elasticsearch/pull/12342)
- [x] SpanTermQueryBuilder (#11005)
- [x] SpanWithinQueryBuilder (#12396)
- [x] TemplateQueryBuilder (https://github.com/elastic/elasticsearch/pull/13253)
- [x] TermQueryBuilder (#10669)
- [x] TermsLookupQueryBuilder (https://github.com/elastic/elasticsearch/pull/12042)
- [x] TermsQueryBuilder (https://github.com/elastic/elasticsearch/pull/12042)
- [x] TypeQueryBuilder (https://github.com/elastic/elasticsearch/pull/12035)
- [x] WildcardQueryBuilder (https://github.com/elastic/elasticsearch/pull/12110)
- [x] WrapperQueryBuilder (https://github.com/elastic/elasticsearch/pull/12037)

Total of 54 Queries
54 done

Former filters were mostly merged or converted to queries and are included in this list.
## Aggregations (Completed - https://github.com/elastic/elasticsearch/pull/14136)
- [x] Min Aggregation (https://github.com/elastic/elasticsearch/pull/12832)
- [x] Max Aggregation (https://github.com/elastic/elasticsearch/pull/14687)
- [x] Sum Aggregation (https://github.com/elastic/elasticsearch/pull/14687)
- [x] Avg Aggregation (https://github.com/elastic/elasticsearch/pull/14687)
- [x] Stats Aggregation (https://github.com/elastic/elasticsearch/pull/14688)
- [x] Extended Stats Aggregation (https://github.com/elastic/elasticsearch/pull/14688)
- [x] Value Count Aggregation (https://github.com/elastic/elasticsearch/pull/14689)
- [x] Percentiles Aggregation (https://github.com/elastic/elasticsearch/pull/14836)
- [x] Percentile Ranks Aggregation (https://github.com/elastic/elasticsearch/pull/14836)
- [x] Cardinality Aggregation (https://github.com/elastic/elasticsearch/pull/14893)
- [x] Geo Bounds Aggregation (https://github.com/elastic/elasticsearch/pull/14934)
- [x] Top hits Aggregation (https://github.com/elastic/elasticsearch/pull/15566)
- [x] Scripted Metric Aggregation (https://github.com/elastic/elasticsearch/pull/14966)
- [x] Global Aggregation (https://github.com/elastic/elasticsearch/pull/14139)
- [x] Filter Aggregation (https://github.com/elastic/elasticsearch/pull/14974)
- [x] Filters Aggregation (https://github.com/elastic/elasticsearch/pull/15437)
- [x] Missing Aggregation (https://github.com/elastic/elasticsearch/pull/14975)
- [x] Nested Aggregation (https://github.com/elastic/elasticsearch/pull/15006)
- [x] Reverse nested Aggregation (https://github.com/elastic/elasticsearch/pull/15006)
- [x] Children Aggregation (https://github.com/elastic/elasticsearch/pull/15008)
- [x] Terms Aggregation (https://github.com/elastic/elasticsearch/pull/15386)
- [x] Significant Terms Aggregation (https://github.com/elastic/elasticsearch/pull/15386)
- [x] Sampler Aggregation (https://github.com/elastic/elasticsearch/pull/15418)
- [x] Range Aggregation (https://github.com/elastic/elasticsearch/pull/15399)
- [x] Date Range Aggregation (https://github.com/elastic/elasticsearch/pull/15399)
- [x] IPv4 Range Aggregation (https://github.com/elastic/elasticsearch/pull/15399)
- [x] Histogram Aggregation (https://github.com/elastic/elasticsearch/pull/14140)
- [x] Date Histogram Aggregation (https://github.com/elastic/elasticsearch/pull/14140)
- [x] Geo Distance Aggregation (https://github.com/elastic/elasticsearch/pull/15399)
- [x] GeoHash grid Aggregation (https://github.com/elastic/elasticsearch/pull/14138)
- [x] Geo Centroid Aggregation (https://github.com/elastic/elasticsearch/pull/15002)
- [x] Min Bucket Aggregation (https://github.com/elastic/elasticsearch/pull/15009)
- [x] Max Bucket Aggregation (https://github.com/elastic/elasticsearch/pull/15009)
- [x] Avg Bucket Aggregation (https://github.com/elastic/elasticsearch/pull/15009)
- [x] Sum Bucket Aggregation (https://github.com/elastic/elasticsearch/pull/15009)
- [x] Stats Bucket Aggregation (https://github.com/elastic/elasticsearch/pull/15009)
- [x] Extended Stats Bucket Aggregation (https://github.com/elastic/elasticsearch/pull/15009)
- [x] Percentiles Bucket Aggregation (https://github.com/elastic/elasticsearch/pull/15009)
- [x] Bucket Script Aggregation (https://github.com/elastic/elasticsearch/pull/15014)
- [x] Cumulative Sum Aggregation (https://github.com/elastic/elasticsearch/pull/15015)
- [x] Derivative Aggregation (https://github.com/elastic/elasticsearch/pull/14137)
- [x] Bucket Selector Aggregation (https://github.com/elastic/elasticsearch/pull/15147)
- [x] Moving Average Aggregation (https://github.com/elastic/elasticsearch/pull/15180)
- [x] Serial Differencing Aggregation (https://github.com/elastic/elasticsearch/pull/15058)

Total of 44 Aggregations
44 done
## Suggesters
- [x] Term suggester
- [x] Phrase Suggester
- [x] Completion Suggester
- [x] Context Suggester

Total of 4 Suggesters
4 done, 0 in open PRs
## Highlighters
- [x] plain
- [x] fvh
- [x] postings

Total of 3 Highlighters
3 done
## Others
- [x] from (https://github.com/elastic/elasticsearch/pull/13752)
- [x] size (https://github.com/elastic/elasticsearch/pull/13752)
- [x] min_score (https://github.com/elastic/elasticsearch/pull/13752)
- [x] fields (https://github.com/elastic/elasticsearch/pull/13752)
- [x] script_fields (https://github.com/elastic/elasticsearch/pull/13752)
- [x] fielddata_fields (https://github.com/elastic/elasticsearch/pull/13752)
- [x] _source (https://github.com/elastic/elasticsearch/pull/13752)
- [x] sort (https://github.com/elastic/elasticsearch/pull/17205)
- [x] timeout (https://github.com/elastic/elasticsearch/pull/13752)
- [x] explain (https://github.com/elastic/elasticsearch/pull/13752)
- [x] terminate_after (https://github.com/elastic/elasticsearch/pull/13752)
- [x] version (https://github.com/elastic/elasticsearch/pull/13752)
- [x] stats (https://github.com/elastic/elasticsearch/pull/13752)
- [x] indices_boost (https://github.com/elastic/elasticsearch/pull/13752)
- [x] track_scores (https://github.com/elastic/elasticsearch/pull/13752)
- [x] inner_hits (https://github.com/elastic/elasticsearch/pull/17291)
- [x] ~~query_binary~~: (removed, queries should only be specified via type-safe builders in the Java API, see #14308)
- [x] ~~filter_binary~~: (removed, filters should only be specified via type-safe builders in the Java API, see #14308)
- [x] ~~aggregations_binary~~: (to be removed, aggregations should only be specified via type-safe builders in the Java API, see #14308 and #14136)
- [x] rescore (https://github.com/elastic/elasticsearch/issues/15559)
- [x] post_filter (https://github.com/elastic/elasticsearch/pull/13752)
## APIs to be adapted/revised besides _search
- [x] ~~search exists api~~ (removed, see #13911)
- [x] explain api: (#14270)
- [x] validate query api: (#14384)
- [x] suggest api (#17198)
- [x] percolator (Planned to be removed, see #16349)
- [x] ~~index warmers~~ (removed, see #15614)
- [ ] alias filters

The above apis don't necessarily have to change to parse queries in our intermediate format, for instance the percolator will still need to parse to lucene query straight-away, but we should still have a look at each of those and double check if anything needs to be adjusted after all the infra changes we have made.

**Comment by mattweber** [comment]
+1, In #3278 I perform a terms lookup after parsing but this happened on all shards and resulted in multiple lookup requests for a single query.  This would allow the expensive lookup to be performed once on the coordinating node which would be very beneficial!

**Comment by javanna** [comment]
Here is our rough plan:

First step (everything still happens on the nodes that hold the relevant shards):
- move all the *QueryParser code to the corresponding *QueryBuilder, make all Builders implement `QueryParser`, so that we have building and parsing code on the same class
- split existing `parse()` method into `fromXContent()` that parses the query but allows to have an intermediate format for it and `toQuery()` that allows to create the lucene query ouf the intermediate query. Keep the exisiting `Query parse()` method around temporarily, which will call both `fromXContent` and `toQuery`.
- make all the QueryBuilders implement `Streamable` so that the intermediate query format can be sent over the wire between the nodes (will be unused at first)

Second step (query parsing moved to the coordinating node):
- call `fromXContent` on the coordinating node and make use of `Streamable` methods to send queries over the wire
- delete `parse` method from all QueryBuilders, not needed anymore
- delete `toXContent` method from all QueryBuilders, nodes will not use `ToXContent` format anymore to serialize queries over the wire


Things we are not too happy about and might need improvement, will be tackled later on:
- rename QueryBuilders by removing the Builders suffix, as they will not be really just builders anymore
- java api side of things is heavier on users, since a single class exposes a lot of internal aspects, we might be able to make methods package private
- a lot of null checks will be needed
- define what we have to do with filters (they will be merged with queries in lucene?)
- define if we can make the switch for queries (and filters) only or whether we need to convert every single part of a search request, which is at the moment entirely serialized over the wire in `ToXContent` format

**Comment by dakrone** [comment]
@clintongormley et al,

Because we are touching every single query in this change, it also gives us the ability to remove support for camel-casing in queries where it exists. How do we feel about removing the camel casing in these PRs as well?

**Comment by clintongormley** [comment]
@dakrone ++ - should we be doing this by using parseField and then later using https://github.com/elastic/elasticsearch/issues/8963 to warn about the deprecations?

**Comment by cbuescher** [comment]
We decided to reset the feature branch to the current tip of master and branch from there starting with #10580.

**Comment by javanna** [comment]
I've just updated the description of this issue and added all the other search sections that will need to be refactored, along with queries and aggregations.

**Comment by colings86** [comment]
I'm for closing this issue. The few issues which are still open and tagged as `:Search Refactoring` can stand alone as issues and the success of this issue doesn't rely directly on them (though it would be nice to fix those issues. As for the alias filters maybe we can open a separate issue for them too?

**Comment by cbuescher** [comment]
+1 on closing and opening a separate issue for the alias filters. Are they part of the SearchSourceBuilder? Just curious what place they have in terms of parsing incoming requests.

**Comment by colings86** [comment]
@cbuescher I think the reason alias filter were on the list was because they are represented by a QueryBuilder object and could be stored as a serialised QueryBuilder rather than JSON. I agree though that it's not directly connected to this issue

**Comment by javanna** [comment]
What was most important to do for alias filters was done with #20916. Each search request against filtered indices was previously sending the filter as a string all the way to the shards, where the actual filter was parsed and converted to lucene query. Now the parsing happens once on the coordinating node, only `toFilter` gets called on each shard to get the corresponding lucene query. We still store alias filters in compressed XContent format as part of the cluster state, but I don't think that is going to change anytime soon. That said we can close this issue, nothing left to be done. Yay!
