### ISSUE TITLE
ESQL: Meta-ticket for 8.12

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#102272]
### Description

A meta ticket tracking the main issues we want to solve for the 8.12 release:

#### New Features
- [ ]  Async query - https://github.com/elastic/elasticsearch/issues/99533
- [ ]  Cross Cluster Querying (CCS) - https://github.com/elastic/elasticsearch/pull/101640

#### Language
- [ ]  Grammar for . fields - https://github.com/elastic/elasticsearch/pull/100740

#### Memory tracking 
- [ ] block ref tracking - https://github.com/elastic/elasticsearch/pull/100408
- [ ] Enrich memory usage - https://github.com/elastic/elasticsearch/pull/102184

#### Data loading
- [ ] expose source as a metadata field - https://github.com/elastic/elasticsearch/issues/99456
- [ ] multi-field extraction at once - https://github.com/elastic/elasticsearch/issues/101322 (https://github.com/elastic/elasticsearch/pull/102192)
- [ ] fallback to source extraction for fields that have field data disabled - https://github.com/elastic/elasticsearch/issues/99213

#### Resilience
- [ ] Random generation of random queries - https://github.com/elastic/elasticsearch/pull/102073
- [ ] Enrich enhancements -https://github.com/elastic/elasticsearch/issues/101654

Bugs
