### ISSUE TITLE
Support ST_INTERSECTS in ES|QL

### ISSUE THREAD

**Issue by craigtaverner** [elastic/elasticsearch#104874]
### Description

This is a path-finder feature that could open the door to a large number of similar features.

```
FROM airports
| EVAL polygon = TO_GEOSHAPE("POLYGON((...))")
| WHERE ST_INTERSECTS(location, polygon)
```

See the PostGIS documentation for inspiration: https://postgis.net/docs/ST_Intersects.html

The feature can be developed in two phases:

* Bring back from prototype from last summer
  * Expects constant string WKT
  * Does in-memory constant->triangle-tree and then internal intersects
* LocalPhysicalPlanner support for push-down to Lucene
  * Lucene has native support for this, so we can optimize to use that

```[tasklist]
### Tasks
- [x] Bring back prototype from last summer (geo_point in polygon)
- [x] Support cartesian point in polygon
- [x] Support polyon intersects polygon
- [ ] Support any geometry intersects any geometry
- [ ] Support doc-values for point in polygon
- [ ] Support doc-values for geometry intersects geometry
```

**Comment by nik9000** [comment]
At least they all start with ST_!
