### ISSUE TITLE
[7.17][CI] Timezone related test failures 

### ISSUE THREAD

**Issue by mosche** [elastic/elasticsearch#106005]
`7.17` is still based on joda time. When testing with random timezones we occasionally hit timezones that are out of sync between various tested Jdks  (oracle, adoptopenjdk, openjdk etc) and joda. 

This should be fixed by #105989, excluding any troublesome timezone ids.

```[tasklist]
### Test failures
- [ ] #105975: `Unknown time-zone ID: Europe/Kyiv`
- [ ] #105841: `Unknown time-zone ID: Europe/Kyiv`
- [ ] #105866: `Unknown time-zone ID: America/Ciudad_Juarez`
- [ ] #105867: `Unknown time-zone ID: Europe/Kyiv`
- [ ] #105840: `Unknown time-zone ID: America/Ciudad_Juarez`
- [ ] #95951: `Unknown time-zone ID: Europe/Kyiv`
- [ ] #95044: `Unknown time-zone ID: America/Ciudad_Juarez` - also on `main`?
```

**Comment by mosche** [comment]
Observing this over the past few days it seems that problems on 7.17 have resolved with #105989.

**Comment by nielsbauman** [comment]
Reopening this due to new failure: https://gradle-enterprise.elastic.co/s/chldihevcnmak

**Comment by pgomulka** [comment]
I don’t think so timezone related failures should be marked as blocker. This is related to old timezonedb being used in a test. In that [recent one](https://github.com/elastic/elasticsearch/issues/106005#issuecomment-2129602456) I think it is due to a jvm being used in gradle is used on the 'jdbc client side'
so it is using 17.0.2 (too old) instead of latest with at least `tzdata2022c`. I think we should look in upgrading jdk on those ci machines to `17.0.11` 
this test run on linux and latest configured of it is 17.0.2+8 https://github.com/elastic/infra/blob/master/serverless/jvm-catalog-service/manifest.yml#L125
