### ISSUE TITLE
[Meta] Data stream lifecycle global retention 

### ISSUE THREAD

**Issue by gmarouli** [elastic/elasticsearch#106169]
### Description

With this issue we define the global retention for data stream lifecycle and we track the progress. 

We would like to introduce a global retention configuration that would enable the project owners to introduce default and max retention for all data streams managed by data stream lifecycle.

The work will be completed in the following steps:

- [ ] Introduce the cluster state metadata that will store the global retention.
- [ ] Use the global retention in the data stream lifecycle
- [ ] Introduce `PUT`, `GET`, `DELETE` REST APIs to enable the user with the correct privileges to manage the global retention.
- [ ] Add telemetry about the global retention
