### ISSUE TITLE
Universal Profiling cleanups for 9.0.0

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/elasticsearch#106592]
This is a meta-issue to collect all cleanups to be done for the next major version.

```[tasklist]
### Tasks
- [ ] https://github.com/elastic/elasticsearch/issues/106593
- [ ] https://github.com/elastic/elasticsearch/issues/106596
- [ ] https://github.com/elastic/elasticsearch/issues/106597
- [ ] https://github.com/elastic/elasticsearch/issues/106681
- [ ] https://github.com/elastic/kibana/issues/204024
```

**Comment by DaveCTurner** [comment]
I'd suggest adding the `@UpdateForV9` annotation to relevant points in the code to keep track of these things today. When we decide to start working on v9, we'll go through all the places where this annotation is used to make sure we don't miss anything.

**Comment by danielmitterdorfer** [comment]
> I'd suggest adding the @UpdateForV9 annotation to relevant points in the code to keep track of these things [...]

Thanks. I've pushed https://github.com/elastic/elasticsearch/pull/107150.

**Comment by simitt** [comment]
@rockdaboot my understanding is that this meta issue was closed based on some `9.0 annotations` being added to Elasticsearch. How are the annotations used now that we get close to `9.0` - do we still need to put up PRs to actually remove the logic or is there some automation happening around these annotations?

**Comment by simitt** [comment]
Reopening this github card to not lose track of the work that needs to go into `9.0` then. @paulb-elastic this task was labeled for the `UniversalProfiling/Application`, and skimming through the sections I believe this is the correct label, hence IMO this would fall into the @elastic/obs-ux-infra_services-team .

**Comment by rockdaboot** [comment]
Thanks for the clarification. So far, i assumed some automation with 9.0 to make the annotations visible and/or ping teams. What exactly are those annotations used for?

**Comment by DaveCTurner** [comment]
They exist to prevent us from releasing v9 without addressing all the things that need addressing first: we will not release v9 without deleting [this file](https://github.com/elastic/elasticsearch/blob/main/libs/core/src/main/java/org/elasticsearch/core/UpdateForV9.java), and we cannot do that while the `@UpdateForV9` annotation is still in use.

In principle we could write a bot to go around pinging teams about the work that they must do, but so far we've just been tracking this manually at the team level (see e.g. ES-9364). It's very easy to ask IntelliJ to find all the outstanding actions for a specific team in the codebase - just look for usages of the relevant `UpdateForV9.Owner` constant.

It's likely that this work will only proceed in earnest after the 8.last feature freeze. Until that happens, we're required to keep the transport protocol aligned between the `8.x` and `main` branches, and that prevents us from addressing many of the tasks on this list.

I do note that the profiling team's work is not being tracked in Jira right now. I'm not sure why that is.

**Comment by paulb-elastic** [comment]
@smith I have added a link to this to our main tracking meta https://github.com/elastic/observability-dev/issues/4143 for your team's v9 activities

**Comment by rockdaboot** [comment]
Just to be clear: the issues listed in the description are **non-blocking for V9**, as they are all cleanups. V9 gives us the chance to cut some old ropes in order to improve readability and maintainability.

**Comment by miloszmarcinkowski** [comment]
The UI part has been adjusted according to refinement made in [#204024](https://github.com/elastic/kibana/issues/204024).
