### ISSUE TITLE
[ES|QL] generate function docs and definitions for agg functions

### ISSUE THREAD

**Issue by drewdaemon** [elastic/elasticsearch#107219]
### Description

With https://github.com/elastic/elasticsearch/pull/106782, we will get function definitions for `eval` functions. We'd also like them for `stats` functions.

**Comment by nik9000** [comment]
The last person who touched this was @ivancea. Because I asked him to. But I think that means he's probably the right person to officially assign here. I think this is basically shaped like:

## Phase 1 - Infrastructure (@ivancea )
* [ ] Build a basic test class to run some aggs tests, adapting concepts from `AbstractFunctionTestCase`.
* [ ] Expand that basic test case for
  * [ ] randomized inputs
  * [ ] multiphased execution (INITIAL/FINAL, INITIAL/INTERMEDIATE/FINAL, and SINGLE or whatever we call it)
  * [ ] type errors
* [ ] apply the basic test case for a hand full of aggs to prove it

## Phase 2 - Apply all the places(shared)
* [ ] AVG
* [ ] COUNT
* [ ] COUNT_DISTINCT
* [ ] MAX
* [ ] MEDIAN
* [ ] MEDIAN_ABSOLUTE_DEVIATION
* [ ] MIN
* [ ] PERCENTILE
* [ ] ST_CENTROID_AGG
* [ ] SUM
* [ ] VALUES

**once this phase is really happening @drewdaemon can start picking up the generated files and integrate them into Kibana's editor**

## Phase 3 - Only semi-related
* [ ] Infrastructure for testing surrogate expressions

**Comment by ivancea** [comment]
@drewdaemon All aggregations should already have their kibana docs and json generated :blob_dance:
