### ISSUE TITLE
[Transform] Elasticsearch upgrades make transforms fail easily

### ISSUE THREAD

**Issue by przemekwitek** [elastic/elasticsearch#107251]
### Elasticsearch Version

main

### Java Version

_bundled_

### OS Version

serverless, Cloud

### Problem Description

Users are noticing transforms failing when there is an Elasticsearch version upgrade.
This came up in serverless and on the Cloud. I'm not sure if this also affect stateful ES.
Each such upgrade can make a transform fail. Once the transform fails, the user has to manually stop and delete it and create a new transform.

The primary purpose of this GH issue is to reduce the volume of the transform alerts and users complaints.
Some questions/ideas that need to be addressed:
- [ ] We've seen the problem happening for the transforms with `unattended` set to `false`. Does the problem also occur when `unattended` is `true`? If so, this is a bug as we expect `unattended` transforms to never fail.
- [ ] Even when `unattended` is `false`, what can we do to make the transform more robust during these upgrades? Maybe we can make all the transforms slightly more "unattended", i.e. less prone to intermittent issues.
- [ ] Maybe the transforms should treat all the error types as recoverable?
- [ ] What is the right retrying strategy for a non-unattended transform?
- [ ] Does the problem happen for a version upgrade only or does it also happen for a full cluster restart (but without changing the version)?

### Steps to Reproduce

It happens during Cloud upgrades. 

```[tasklist]
### Tasks
- [ ] https://github.com/elastic/elasticsearch/issues/107215
- [ ] https://github.com/elastic/elasticsearch/issues/100891
- [ ] https://github.com/elastic/elasticsearch/issues/107263
- [ ] https://github.com/elastic/elasticsearch/issues/107266
```

**Comment by prwhelan** [comment]
1719 instances of `Transform has failed` errors on serverless over the last 90 days:
- 14 of `The object cannot be set twice` -> https://github.com/elastic/elasticsearch/issues/107215
- 25 of `Failed to reload transform configuration for transform <>` -> https://github.com/elastic/ml-team/issues/1152
- 846 of `[parent] Data too large, data for [indices:data/read/search[phase/query]] would be [4092117844/3.8gb], which is larger than the limit of [4080218931/3.7gb], real usage: [4092117096/3.8gb], new bytes reserved: [748/748b], usages [model_inference=0/0b, eql_sequence=0/0b, fielddata=394234840/375.9mb, request=0/0b, inflight_requests=2244/2.1kb]`
- 9 of `Failed to persist transform statistics for transform`
- 3-5 per rollout that are similar to `Bulk index experienced [2] failures and at least 1 irrecoverable [org.elasticsearch.index.IndexNotFoundException: no such index [.metrics-endpoint.metadata_united_default]].`
- 2 of `rejected execution of TimedRunnable`

**Comment by prwhelan** [comment]
> To help focus investigations, I would suggest we look at the behaviour of transforms whilst nodes leave and join the cluster. I believe it is likely we have some code paths here which can lead to errors and race conditions depending on the order and time it takes for these things to happen. Transforms may not react quickly enough when a node is shutting down. Transform may be too eager to start when a node is joining.

This makes sense, and I'll try to keep the task list ordered by priority.

**Comment by prwhelan** [comment]
Will look into this as well: https://github.com/elastic/elasticsearch/issues/100891

It's likely we don't have to worry about some of these inconsistencies during a rollout if we can handle the rollout

**Comment by prwhelan** [comment]
Related to `data too large`: https://github.com/elastic/elasticsearch/issues/60391

**Comment by prwhelan** [comment]
> [endpoint.metadata_current-default-8.14.0] transform has failed; experienced: [task encountered irrecoverable failure: org.elasticsearch.index.shard.IllegalIndexShardStateException: CurrentState[RECOVERING] operations only allowed when shard state is one of [POST_RECOVERY, STARTED]].

**Comment by nerophon** [comment]
A user also found these after upgrade from `8.11.1` to `8.13.2`:
```
Transform task state is [failed]
task encountered more than 10 failures; latest failure: read past EOF: MemorySegmentIndexInput(path="/app/data/indices/mtc6-NYrQPi_irBUjusHPA/0/index/_5ro.cfs") [slice=_5ro_ES87TSDB_0.dvd] [slice=values]
```

**Comment by prwhelan** [comment]
A few new ones
```
Caused by: java.lang.IllegalArgumentException: field [message] not present as part of path [message]
```
Doesn't seem to reoccur

There are still a lot of WARNS due to node disconnects, missing shards, etc, that happen during nodes joining/leaving the cluster.  We could potentially listen for shutdown events and handle accordingly, but there doesn't seem to be any transforms moving into failure due to these reasons

**Comment by prwhelan** [comment]
We haven't seen unrecoverable failures in the last month - I think it is safe to mark this closed, and we can prioritize new issues outside of this meta-issue
