### ISSUE TITLE
Support spatial distance search in ES|QL (ST_DISTANCE)

### ISSUE THREAD

**Issue by craigtaverner** [elastic/elasticsearch#108212]
### Description

The Elasticsearch `_search` API supports distance filtering and [sorting](https://www.elastic.co/guide/en/elasticsearch/reference/current/sort-search-results.html#geo-sorting):

* Sorting using the [_geo_distance](https://www.elastic.co/guide/en/elasticsearch/reference/current/sort-search-results.html#geo-sorting) sort field
* Filtering using [geo_distance](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-geo-distance-query.html#query-dsl-geo-distance-query)

In PostGIS there are two related functions:

* [`ST_DWITHIN`](https://postgis.net/docs/ST_Distance.html) for filtering by distance
* [`ST_DISTANCE`](https://postgis.net/docs/ST_DWithin.html) for calculating a distance, also usable for sorting

These features can be implemented in ES|QL, but we believe we do not need to implement both functions, as we can perform Lucene-pushdown optimization identically in both cases, so we'll implement the more generic function only: `double ST_DISTANCE(geomA, geomB)`.

This can be used for calculating a distance, filter and sorting based on the context in the query:

#### Distance calculations

```
FROM airports
| EVAL distance = ST_DISTANCE(location, city_location)
```

#### Filtering results

```
FROM airports
| WHERE ST_DISTANCE(location, TO_GEOPOINT("POINT(12 55)")) < 500000
```

#### Sorting results

```
FROM airports
| EVAL distance = ST_DISTANCE(location, TO_GEOPOINT("POINT(12 55)"))
| SORT distance ASC
```

```[tasklist]
### Tasks
- [x] Review existing Elasticsearch support for distance filtering and sorting
- [x] Review PostGIS and OGC specifications for these functions
- [x] Implement raw ST_DISTANCE function
- [x] Support distance filtering
- [x] Support distance calculations
- [x] Support distance sorting
- [ ] https://github.com/elastic/elasticsearch/issues/109972
- [ ] https://github.com/elastic/elasticsearch/issues/109973
- [x] Documentation
```

**Comment by craigtaverner** [comment]
We should also keep in mind use cases involving speed, as discussed at https://github.com/elastic/elasticsearch/issues/108332#issuecomment-2097795599

**Comment by craigtaverner** [comment]
Since the lucene pushdown for spatial sort has it's own issue, now moved to 8.16, we'll mark this main issue as DONE for 8.15.
