### ISSUE TITLE
ESQL tests: replace IT_test_only.csv-spec with `required_feature`

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#108319]
### Description

We end files with `IT_test_only` for ESQL's csv-spec tests to skip tests in our stripped down test runner, `CsvTests`, and just run them in our integration tests. We use `required_features` for versioning. Nik doesn't like the file ending version - it's not pretty! Let's use the `required_featues` for skipping `CsvTests`. It's pretty easy if you already have a feature - and if you don't, we should be adding those so we don't need the node version anyway.

Here's the list of files to rename:
* [x] blog-IT_tests_only.csv-spec #108377
* [x] metadata-IT_tests_only.csv-spec https://github.com/elastic/elasticsearch/pull/108313
* [x] enrich-IT_tests_only.csv-spec #108377
* [x] docs-IT_tests_only.csv-spec #108434

**Comment by nik9000** [comment]
All done.
