### ISSUE TITLE
Add support for Azure Managed Identity & Azure Workload Identity

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#111346]
These features should be supported by the Azure SDK, so in theory this is just a question of letting the SDK do its thing.

- [x] Decide whether `DefaultAzureCredential` is suitable or whether we want to customize the chain.
- [x] Add support for `DefaultAzureCredential` (or a custom chain if applicable). https://github.com/elastic/elasticsearch/pull/111344
- [x] Enhance test fixture to cover Azure Managed Identity https://github.com/elastic/elasticsearch/pull/111344
- [x] Enhance test fixture to cover Azure Workload Identity #111414
- [x] Adjust documentation to reflect the new functionality #111577
- [ ] ~Add information about the usage of this feature to phone-home telemetry~ (tracked elsewhere)

**Comment by piyushkp** [comment]
@DaveCTurner  can you provide the sample and detail documentation on how to use Managed identity for Azure repository ? 

do we have to provide Managed identity resourceID along with the Account name ?

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch @piyushkp.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

**Comment by DaveCTurner** [comment]
I'm marking this as done, the only remaining task is the telemetry component which is now tracked as a separate work item.
