### ISSUE TITLE
Support semantic_text in ES|QL

### ISSUE THREAD

**Issue by ChrisHegarty** [elastic/elasticsearch#115103]
This meta issue tracks adding support for `semantic_text` to ES|QL. 

- [x]  #113920
- [ ] #115166
- [x] #115243
- [x] https://github.com/elastic/elasticsearch/pull/118355
- [x]  Add support for semantic_text in the `match` function  https://github.com/elastic/elasticsearch/pull/118676
- [x] Enhance support for `semantic_text` such that it has the same support as keyword and text which are simply seen as string fields:
      https://github.com/elastic/elasticsearch/blob/dcbbbabd3d1b78bd4658ab69e85e7c55bcc8fced/x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/type/DataType.java#L356-L358
      With this change we will be able to use `semantic_text` fields in the same way we use `keyword` and `text` and be able to pass `semantic_text` field to any function/operator that can accept string fields. 
   - support for functions/operators #115243 
   - support for all commands https://github.com/elastic/elasticsearch/pull/117337
- [x] https://github.com/elastic/elasticsearch/pull/119667
- [x] https://github.com/elastic/elasticsearch/pull/119792
- [x] https://github.com/elastic/elasticsearch/pull/120052
- [x] Full support in Kibana (it should just work since field caps will return text for semantic_text fields?)

Follow-ups:

- [ ] enable integration tests for multi clusters and mixed nodes 
- [x] add semantic_text to `mapping-all-types.json` and test semantic-text fields within `LocalPhysicalPlanOptimizerTests.java`
 https://github.com/elastic/elasticsearch/pull/118676#discussion_r1887229582 
fixed with https://github.com/elastic/elasticsearch/pull/118982
- [ ] address difference in score between multi vs single node https://github.com/elastic/elasticsearch/pull/118676#discussion_r1889988873
- [x] https://github.com/elastic/elasticsearch/pull/125581

Refactor work (might be done separate from the semantic_text support project but tracking here):

- [x] https://github.com/elastic/elasticsearch/pull/118355#discussion_r1882193089
- [x] ~look into whether we can do async mapping/physical planning using a `CoordinatorMappingPreProcessor` (from Esql expression lifecycle events proposal)~ Bogdan made this happen 🎉  https://github.com/elastic/elasticsearch/pull/121260

**Comment by ioanatia** [comment]
Since field caps will report `semantic_text` fields as `text`, the initial plan on how we want to support semantic_text in ES|QL changes.
ES|QL will handle `semantic_text` fields as `text` fields.
We already support `semantic_text` as part of the match query and match function (through the query builder rewrite (https://github.com/elastic/elasticsearch/pull/118676).

After the field caps change is merged, we might need to go back and clean up some of the changes that specifically accounted for a `semantic_text` field type in ES|QL. These changes are under snapshot (under the the `SEMANTIC_TEXT_FIELD_TYPE` capability), so there are no bwc concerns.

**Comment by ioanatia** [comment]
closing this issue - we do have an outstanding issue with https://github.com/elastic/elasticsearch/issues/115166 that does not allow us to test semantic search in ES|QL with mixed version clusters.
this is a larger issue that's not specific just to semantic search in ES|QL.

we do test for single-node/multi-node clusters and the rest of the follow ups have been addressed so I think we can just close this one.
