### ISSUE TITLE
ESQL: Lookup Join meta issue

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#116208]
### Description

Meta ticket around the main implementation topics required for lookup join

- [x] add grammar / parser `LOOKUP JOIN`
- [x] Make it execute correctly on data nodes, too, and enable csv tests `...OnTheDataNode`. See (reproducible) failed runs from https://github.com/elastic/elasticsearch/pull/117639's branch:
  - https://gradle-enterprise.elastic.co/s/5cihyuwehu2lu
  - https://gradle-enterprise.elastic.co/s/aox7wtnevoij2
  - https://github.com/elastic/elasticsearch/pull/117843
- [x] `ON` condition
    - [ ] ~rewrite into JOIN equi-join~ **maybe later**
    - [x] make `ON field`  alias to `USING field` (syntax already used in enrich) - alternative is to deprecate this syntax
    - [x] change index name grammar for identifier to source (to allow date math and others)
    - [x] enhance the field matching grammar against various declarations such as `parent.subfield` & co.

- [x] CSV tests (some suggestions to start with: https://github.com/elastic/elasticsearch/pull/116515#discussion_r1846386923)
  - [x] Cover primary use cases: https://github.com/elastic/elasticsearch/pull/117843/
  - [x] Add tests for using timeseries indices in the `FROM`
- [ ] Known bugs
  - [x] Make `PushDownAndCombineLimits` work for `Join`s https://github.com/elastic/elasticsearch/issues/117698
  - [x] Additional `null` rows https://github.com/elastic/elasticsearch/issues/117702
  - [x] EsqlSession.fieldNames does not handle lookup references that are also mentioned in aliases (erases them)
  - [x] EsqlSession calls `preAnalyzeLookupIndices` asking for all the lookup index' fields all the time, c.f. https://github.com/elastic/elasticsearch/pull/117843#discussion_r1868123620
  - [x] Using an index alias makes it fail with a 500
  - [x] Filtering right side columns removes all data https://github.com/elastic/elasticsearch/pull/118658
  - [x] using same lookup index in FROM breaks an internal assumption https://github.com/elastic/elasticsearch/issues/118865
  - [x] duplicate rows in some specific cases https://github.com/elastic/elasticsearch/issues/118852
  - [x] https://github.com/elastic/elasticsearch/issues/120817
  - [ ] https://github.com/elastic/elasticsearch/issues/120272
- [x] field resolution
    - [x] establish shadowing rules
    - [x] clarify in USING/ON pattern the rules around the join key which are following downstream (left vs right)
    - [x] make the other side fields [nullable](https://github.com/elastic/elasticsearch/pull/116515/files#r1842280850) (this changes the equality for existing fields causing side-effects) create new fields or update the entire field declaration.
    - [x] check resolution exception to differentiate between 500 and 400  https://github.com/elastic/elasticsearch/pull/118826(https://github.com/elastic/elasticsearch/pull/116515#discussion_r1845526933)
- [x] clarify output order rules in case of common keys (join keys and columns with same names) for consistency
     - SQL JOIN: 
          - columns are kept in place and in lacking qualifiers, lead to ambiguation errors
          - JOIN USING moves the join keys in front followed by the columns in table declaration order
     - in ESQL the columns override each other:
          - in EVAL, the latest declaration wins alongside its position - all previous declarations are _hidden_ as if they were removed
          - existing LOOKUP and INLINESTATS return left columns, join keys, right columns using EVAL rules for non-joining keys
          - STATS BY x, returns grouping keys last (declaration order)
     - proposal: 
        - a. return join keys first (like SQL first)
        - b. return join keys last (declaration order, similar to STATS BY - clashes with USING)
        - c. we use `ON`, which is not a thing in SQL, and have it behave similar to ENRICH: join columns in `ON` remain in place, right hand side columns are added on the right (like ENRICH) and shadow any left hand side columns with conflicting names.
     - (c.f. output computation in Analyzer (https://github.com/elastic/elasticsearch/pull/116515#discussion_r1845526358))
     - **We decided on Proposal c.**
     
- [x] Filter pushdown (on the left/main branch) - see #118410
- [x] Fetch only the required fields (relates to field extraction + fieldNames), resp. prune irrelevant lookup index fields from the plan.  https://github.com/elastic/elasticsearch/pull/118808
- [x] Look whether the LookupJoin output could be computed inside the class https://github.com/elastic/elasticsearch/pull/117639
- [x] Resolve lookup table mappings - https://github.com/elastic/elasticsearch/pull/117246
  - [x] Update lookup table mappings solution to support multiple join commands - Craig
- [x] Update verifier and add corresponding tests https://github.com/elastic/elasticsearch/pull/116515#discussion_r1845504613.
  - [x] disallow lookup joins on remote clusters/validate against CCQ
  - [x] disallow lookup joins on more than 1 join field
  - [x] Have validation for stuff that the grammar permits but we can't actually handle yet, like `LOOKUP JOIN idx ON a == b AND to_upper(c) LIKE d`
- [x] Enhance tests
  - [x] Cover primary use cases: https://github.com/elastic/elasticsearch/pull/117843/
  - [x] Add negative tests (missing indexes, indexes with wrong mode, unresolvable field references, etc.) https://github.com/elastic/elasticsearch/pull/117922

#### Compute
- [ ] ~Make field extractor work with LookupOperators (keep field extraction in one place)~
- [ ] ~Bifurcate join operator/allow other operators between join and Lookup source (eval, filter, etc..)~
- [ ] ~Align LookupJoin and LookupJoinExec - the first allows branching, the second does not.~

**Update:** decided to postpone all this until we either evolve the way we perform the actual lookup join, or allow more features like actual condition expressions.

#### Later
- [x] Pushdown optimizations https://github.com/elastic/elasticsearch/issues/119082

#### Maybe
- [x] obtain IndexMode inside IndexResolver (FieldCaps)
- [ ] ReplaceMissingFieldWithNull rule does not have access to SearchStats for lookup indices https://github.com/elastic/elasticsearch/issues/118690
- [ ] refactor JoinConfig into general Expression 
- [ ] rewrite into JOIN equi-join
- [ ] name qualifiers (for disambiguation) (look to descope)

**Comment by nicpenning** [comment]
I have been monitoring this feature and looking forward to it's capabilities.

I noticed this PR (https://github.com/elastic/kibana/issues/207350) came down the pipeline and it made me wonder.

For LOOKUP to be usable on multiple indices, does it require the indices that will be joined to have Lookup Index mode or is that just a more efficient way to perform the operation?

I ask because I am trying to understand how the LOOKUP varies from some of the way that ENRICH works. It is painful today having to create Enrich policy after Enrich policy on the same dataset because you can only have 1 match field. 

One of many use cases is enriching data from 1 source with another. Let's say I have firewall logs with source.ip : 1.2.3.4, event.action : block, url.domain : bad.xyz and I want to join that with DHCP data around that same time with the host.ip : 1.2.3.4., host.name : computer1, I would want to combine this into a single row showing something like:
host.ip : 1.2.3.4, host.name : computer 1, source.ip : 1.2.3.4, url.domain: bad.xyz, event.action : block

This would allow for joining data in way to simplify outcomes of multiple data sources.

Another use case is simply enriching without the need for enrich policies as stated above and just "enrich" using other indices ad-hoc. However, from what I have observed so far, there may be additional steps to perform this LOOKUP.

Any additional details on what the goal here is with some examples could help understand what is to come. 

Thanks!

**Comment by nik9000** [comment]
> For LOOKUP to be usable on multiple indices, does it require the indices that will be joined to have Lookup Index mode or is that just a more efficient way to perform the operation?

The `LOOKUP JOIN` will require that the index we join into the main stream has the `lookup` mode. Fundamentally it's about having a single sharded index which made the problem simpler. It was easier to get there from our ENRICH behavior than arbitrary joining.

**Comment by nicpenning** [comment]
Thanks for the clarification!

**Comment by getkub** [comment]
This feature is so important, for many of Enterprise customers like ours which are now exporting data outside Elastic to do the same. Can we have an example docs page to show the various abilities of these commands please? 

When we say 'lookup' join searchtime , it is broad statement (for instance we are really looking for joining with ANOTHER index). So the ability to do 'sub-search' is quite important too as part of lookup. Hence if we can update into a list or preview of Elastic v9.x somewhere please I can produce some list of lookup examples and update you for testing ? Thanks again

**Comment by tylerperk** [comment]
Hi @getkub Lookup Join was released as Tech Preview in 8.18. Please check the [announcement blog](https://www.elastic.co/blog/esql-lookup-join-elasticsearch) and the [docs](https://www.elastic.co/docs/reference/query-languages/esql/commands/processing-commands#esql-lookup-join) for more information. 

We are aware of the need for joining against any index and sub searches - both are on the future roadmap.

**Comment by getkub** [comment]
> We are aware of the need for joining against any index and sub searches - both are on the future roadmap.

Great progress. 
In the blogpost, if you can solve it using another index subsearch, that would have ideal
```
FROM kibana_sample_data_logs | WHERE response.keyword != "200" 
| LOOKUP JOIN  [ FROM env_index |  stats count(*) by client.ip, environment | keep client.ip, environment]
| STATS COUNT(*) by response, environment
```

**Comment by alex-spies** [comment]
I think we can close this in favor of more granular issues going forward.

(@bpintea , I think you reviewed this issue not too long ago - please comment if you think there is actually something here that needs to go into a separate issue for follow-up.)
