### ISSUE TITLE
Testing and packaging changes for 2.0

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#12768]
This is a meta issue listing the testing and packaging we should add before 2.0:

* [x] Extend integration testing to multi-node #12718 (Simon)
* [x] Install and test core plugins in vagrant tests #12717 (Nik)
* [x] Test command line tools with custom paths #12712 (Britta, PR #12954)
* [x] improve plugin integration tests #12654 (Clint)
* [x] Bats tests should use plugins built in the elasticsearch repository #12651 (Nik)
* [x] [cloud-gce] Move integration tests to unit tests #12786 (David)
* [x] try to improve integration tests setup/teardown #12063 (Britta, PR #12961)
* [x] Make sure all distribution modules have description in pom.xml #12550
* [x] Don't expand wildcards in command line options #12689 (depends on #12677)
* [x] elasticsearch script does not work with arguments that have spaces #12677 (PR #12710)
* [x] Add "name" to the plugin descriptor file #12715 (cbuescher, PR #12775)
* [x] Plugin manager should verify that it can write to all directories #12749 (AlexR, PR #12851)
* [x] Plugin manager should download only from https by default #12748 (AlexR, PR #12824)
* [x] Plugin manager should validate the SHA, where possible #12750 (Lee, PR #12888)
* [x] Plugin script fails when memory parameters are defined in environment file #12479 (AlexR, PR #12801)
* [x] Make sure elasticsearch.bat works with spaces #12848 (Martijn L, PR #12910)

**Comment by nik9000** [comment]
Finally closed #12717 today! Hurray!

**Comment by dadoonet** [comment]
Note that for #12719, I won't be able to make it for 2.0. So for now, we decided to do some manual testing.
