### ISSUE TITLE
Remove in-memory fielddata support

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#14113]
Now that doc values have become the default fielddata implementation, we should progressively deprecate in-memory fielddata so that doc values would be the only way to sort or aggregate on fields.

* [x] #14082 Numerics, dates and booleans
* [x] #16589 Not-analyzed strings
* [x] Geo-points (need to add doc values by default first)

**Comment by astefan** [comment]
This is to track the removal of fielddata support for those fields that can use doc_values, not all fields. So, analyzed string fields will still use in-memory fielddata. The title of the issue kind of suggests the removal of in-memory fielddata overall.

Also, I'm wondering why we don't keep the option of having in-memory fielddata. For those use-cases where fielddata memory pressure is not a problem and the response time should be the fastest possible (considering that doc_values are slower than in-memory fielddata).

**Comment by s1monw** [comment]
> (considering that doc_values are slower than in-memory fielddata).

our benchmarks show that this is not true. The perf tests are in the noise range and that is in an isolated env. ie. if you have pressure it might even be faster?

**Comment by astefan** [comment]
@s1monw did anything change related to the doc_values implementation, so that we can start saying that doc_values are as fast as in-memory fielddata? Or we just performed different tests that show the same speed, and the tests themselves are now targeting different scenarios?

**Comment by jpountz** [comment]
There have been significant improvements in versions 1.3 and 1.4 that made doc values perform within 15% of in-memory fielddata for fielddata-heavy use-cases (meaning it's likely less if the query is not trivial). But doc values have numerous benefits over in-memory fielddata:
 - more NRT-friendly
 - off-heap
 - keep working if the data are larger than the size of the main memory
 - don't remove duplicates for numeric fields so that eg sums or averages are correct

In my opinion, the fact that doc values are off-heap alone is worth the move to doc values. Eventually I'd love to see all users move to heaps below 4GB which would mean you would almost not have to worry about garbage collection anymore. This is why eg we also moved norms to disk in 2.1 with no way to go back to memory and reduced the memory usage of multi-valued doc values fields in the upcoming 2.2 release.

**Comment by s1monw** [comment]
what @jpountz said... ;)

**Comment by mkobrosli** [comment]
I feel like this is too much of an opinionated choice for a system to enforce.  Why force something on people if people can get top speed and scalability that matches their needs, indexing strategy and field design.  It just seems like a strange choice to make.  doc values serve a purpose clearly, but not for everything.  There are iops considerations that come into play in quota enforced environments, as well as more OS context switching which becomes very relevant under high load public facing sites.  

The only way I could see this not angering a lot of people is to complement this in 3.0 by changing aggregation strategies to utilize the filter cache to implement aggregations.  Otherwise you are basically conceding the battle of speed and Solr becomes the only alternative to real scalable faceting.  I really hope we can at least get aggs cached properly if you do decide on killing fielddata.

I really think this shows to much direction starting to move to big data / ELK usage and core search gets burned :( :-1:

**Comment by clintongormley** [comment]
@mkobrosli see https://github.com/elastic/elasticsearch/issues/16108#issuecomment-173171419

**Comment by lusid** [comment]
I second what @mkobrosli is saying. We have manually disabled doc_values on all 1000+ fields in our ElasticSearch index because the performance loss for our application once doc_values is enabled is completely unacceptable. I haven't had a chance to do extensive testing using Google Cloud local SSDs to determine if doc_values could work in our scenario, but the few tests I have done after some short conversations with Peter Kim on the topic haven't given me much hope that this is going to improve our particular situation where aggregation and sorting performance is imperative across nearly any field in our index. The 10-15% loss of performance on some of our queries seems to take us back to the performance issues we were having with facets back in the v0.90 days.

We hate the fact that we are memory bound and want to be able to use doc_values exclusively, but at the end of the day, we are not yet confident that we can trade memory for disk IO. We also have concerns surrounding the fact we wouldn't have persistent disk to rely on in the case of a server failure since local SSDs would be wiped.

I'm going to continue my testing first chance I get with v5 alpha, but I wanted to be sure I publicly stated our concern before it is too late.

**Comment by jpountz** [comment]
In-memory fielddata will not come back. It only existed because elasticsearch was created at a time when Lucene did not support columnar storage, but now it is part of the index format, just like the inverted index, norms, term vectors or stored fields, which cannot be loaded in memory.

We think enforcing doc values is good because even though it results in slow-downs for requests whose runtime is dominated by sorting or aggregations, the fact that we are not loading gigabytes in RAM anymore improved cluster stability and tail latencies since you are now less likely to have issues because of long garbage collections. Realtimeness also got better since you can now expect to see your indexed data after 1 second rather than 1 second + the time it takes to load fielddata from the inverted index.

**Comment by clintongormley** [comment]
>  the fact that we are not loading gigabytes in RAM 

This should really say: "loading gigabytes into the heap".  Doc values still end up in RAM in the file system cache.  This makes them fast - they are not disk bound.  And you can fit a whole lot more doc values into the file system cache than you could into the limited java heap.

**Comment by jpountz** [comment]
Done.
