### ISSUE TITLE
Allocate primary shard based on allocation IDs

### ISSUE THREAD

**Issue by ywelsch** [elastic/elasticsearch#14739]
Persist allocation IDs of active shards in cluster state and use them to recover correct shards upon cluster restart (i.e., we can recover with only one copy and we make sure we recover the right ones and not a stale copy left around).

Relates to #14671

Steps
----
- [x] Persist allocation ID with shard state metadata on nodes (#14831).
- [x] Persist currently started allocation IDs to index metadata (#14964).
- [x] Add allocation IDs to TransportNodesListGatewayStartedShards action. Use the above to assign a primary shard on recovery. In particular, don't assign a stale copy (#15281).
- [x] Extend reroute with an option to force assign a stale copy. This is only relevant for primaries (#15708).
- [x] Prioritize old primaries when choosing out existing *and* previously active allocationIds (#16096).
- [x] Persist shard state immediately and not only on shard activation. This will help solving a race condition on primary relocation where the master has activated the target shard (removing old copy from the active set list) but the cluster crashes before the target node persisted the shard state (#16625)
- [x] Remove version from ShardRouting (#16243).
