### ISSUE TITLE
Task Management

### ISSUE THREAD

**Issue by imotov** [elastic/elasticsearch#15117]
We have identified several potential features of elasticsearch that can spawn long running tasks and therefore require a common management mechanism for this tasks. This issue will introduce task management API that will provide a mechanism for communicating with and controlling currently running tasks. The task management API will be based on the top of existing TransportAction framework, which will allow any transport action to become a task. 

The tasks will maintain parent/child relationship between tasks running on the coordinating nodes and subtasks that are spawn by the coordinating node on other nodes.

The task management will be introduced in several iterations. The first phase will be back-ported to 2.x and the second phase will be only available in 5.0.
Phase I
- [X] #15347 Create framework for registering and communicating with tasks. 
- [X] #16033 Make the Task object available to the action caller
- [X] #15931 Establish parent/child relationship for master node, replication and broadcast actions
- [X] #16320 Add support for task cancellation
- [X] #16356 Add a task status field to the task info object
- [X] #16586 Add wait for task registration to testCanFetchIndexStatus
- [X] #16744 Combine node name and task id into single string task id
- [X] #16829 Store and report task start time and duration

Phase II
- [X] #17383 Add Task Management API Documentation
- [X] #17551 Add cat API version of task management APIs
- [X] #17928 Provide a generic mechanism for storing results of long running tasks
- [x] Add ability for a task to survive restart of coordinating node

**Comment by nik9000** [comment]
I wonder if we need a way to store the results of a task until they are fetched? I'm thinking of something like update-by-query which would be a task because it is long running, cancelable, etc. But it wants to return counts of how many documents it updated and things like that. Maybe just write them to an index? Maybe with a ttl?

**Comment by raf64flo** [comment]
Nice remark of @nik9000 about long task results availability after its end, as it is already done for snapshots.
But I'd prefer a TTL or/and a dedicated query to drop the result instead of only drop on fetch, which could be problematic in my opinion.

**Comment by nik9000** [comment]
> But I'd prefer a TTL or/and a dedicated query to drop the result instead of only drop on fetch, which could be problematic in my opinion.

Yeah - drop on fetch would be rough.

Not all tasks will want to do this but I think some would like it.

**Comment by imotov** [comment]
@nik9000 is the goal to make results available after the task finished?

**Comment by nik9000** [comment]
> @nik9000 is the goal to make results available after the task finished?

Yeah. In the case of update-by-query it'd be just to make the status available. The most "convenient" way to do it seems like write it to an index with a ttl - but I think I'm just stuck on that idea because it came to me. The point is that after the task is done you'll want to see what its results were for some period of time. You'd want some place you could fetch the results by task id, some way to clear out results when you've finished with them, some way for them to clear themselves out if you don't read them back soon enough.

I don't think it needs to come at iteration 1, but at some point it'd be nice.

Look at delete-by-query, it makes some effort to build a nice results object. Once it becomes a "task" it'll have nothing to do with the fancy result object.

Another thing that might be useful is to make an API that'd block until the task was finished and return the result of it. Or just fetch the result if it was already finished. This'd be super useful in general but kind of required for the REST tests because they don't have loops and things.

**Comment by imotov** [comment]
I think traditionally we do that in two places - 1) log files for per-operation level and 2) in stats as combined metric. I can see how we might want to have a third way, but I think the biggest question here is lifecycle of this result. Persistence (even temporary persistence) of results is very unclear to me unless the result is associated with some persistent object (such as snapshot). So, I would rather make it an option to block and get result if you are interested in the result.

**Comment by nik9000** [comment]
> So, I would rather make it an option to block and get result if you are interested in the result

I don't know if that'll be enough in the end though. Imagine the delete-by-query operation that takes 30 minutes too complete. Its too long for any blocking to be reliable - all kinds of http equipment will time you out after 5 minutes and something is bound to sneak in and get you a `connection reset by peer`.

So you'd have to build in a retry to the blocking. But if results aren't persisted, at least for a little while, then there is always the possibility that the job will finish between one request timing out and the next one starting. A low possibility but an icky one.

Something like a TTL on the result with explicit commands to read the result and delete it would work. These results wouldn't be huge documents so we could probably keep them in memory, certainly if they were serialized xContent or implemented Accountable or something.

Its complicated but I can't think of how else to report on tasks that are "do a thing" rather than "make a thing".

**Comment by niemyjski** [comment]
+1

**Comment by clintongormley** [comment]
Another user of task mgmt: the forced merge API

**Comment by nik9000** [comment]
> Another user of task mgmt: the forced merge API

I wonder if we should add a list of users to the top, like, below the requirements. I'm happy to work on retrofitting some of our long running requests to make their status more fetch-able and to make them more cancel-able but we should should make a list/tag the old issues.

**Comment by jprante** [comment]
Will it be possible to suspend/resume tasks by API? For perpetual tasks? Or to schedule tasks by a cron-like specification? It seems not, since the task design discusses TransportAction only, which means the lifetime of a task is "one-shot", corresponding to a request/response roundtrip of an action executed by a user?

**Comment by imotov** [comment]
@jprante at the moment we are targeting use cases where tasks have clear start, stop and finite running time. We might extend it to perpetual tasks in the future, but this is not on the immediate road map.

**Comment by nik9000** [comment]
> Will it be possible to suspend/resume tasks by API?

I suspect that'll be opt-in in the same way that cancel will be opt-in. Reindex will probably opt in because it'll want to have API controlled throttling. So you could set the throttle to 0 and it'd just stop.  The bulk request powering it would timeout pretty soon, making the whole thing fail though.

**Comment by wuranbo** [comment]
We will has the internal result of a long-term-running task? For example:
The query will retrieve total 100 shards on 10 elastic node, each node has 10 shards. We can get the result immediately when the first shard is done. Then the second shard is done, we reduce the result to the former, send notify to the API, so the user can update their view. When all the shards are done, send notify that the task is done.
So we can execute this long-term-running task in background with less thread one shard by another, release the CPU resources for the high-priority task. And the user can update the views of long-term-running task frequently, got a better user experience.

**Comment by imotov** [comment]
@wuranbo you don't need task manager to do that. You can do it already by simply sending 100 requests with different [shards preferences](https://www.elastic.co/guide/en/elasticsearch/reference/2.1/search-request-preference.html) and then keep track of the responses on the client side. When you get 100th response - the "task" is done. Since sort keys are returned with every result you can easily merge sort the results as they are coming in. Personally, I don't think that the complexity of such solution and overhead of communication will make it worthwhile but all technical capability are already there, so you can give it a shot.

**Comment by wuranbo** [comment]
@imotov　thanks very much for your reply. You are right! This can pleasure most needs I want. I have checked out the shards preferences API. The shards preferences looks only set the shards (lucene's index) where the query retrieve from. The only API which can not be merged simply is cardinality, unless with a huge communication cost. Am I right? For the others, the cost looks like fine.

**Comment by imotov** [comment]
@wuranbo it depends. In some use cases the communication and retrieval overhead can be overwhelming. Let's say you would like to show 25 results on the page. If you let elasticsearch to do its thing, it will only have to pull 25 results from the disk thanks to the [query_then_fetch execution](https://www.elastic.co/guide/en/elasticsearch/reference/2.1/search-request-search-type.html#query-then-fetch) strategy. However, if you will execute a request against each shard separately, you will get first 25 results that you can display as soon as the first shard finishes, but eventually elasticsearch will have to pull 2500 results from the disk since each shard doesn't know which records to pull and has to pull all top 25 in case one of them should be displayed in the top 25. So, unless your intention is to retrieve everything, the overhead of populating top N results can be quite big. 

Since it turns into a search strategy discussion, let's move it to https://discuss.elastic.co/ if you have any other questions. I would like to keep the discussion here focused on Task Management.

**Comment by wuranbo** [comment]
@imotov got it , I have moved to https://discuss.elastic.co/t/how-get-the-just-enough-information-when-manually-merge-the-search-result-by-shards/39184/1 . Thank you very much again.

**Comment by clintongormley** [comment]
@imotov would be good to report how long a task has been running in the tasks API as well.

**Comment by imotov** [comment]
@clintongormley good idea, I have added it to the description

**Comment by nik9000** [comment]
@imotov, is this done now? I think we've decided not to do the "task can survive restart" thing, right?

**Comment by oleg-andreyev** [comment]
About #15975, it was closed in favor of this ticket, so can we retrieve information about _forcemerge?

**Comment by imotov** [comment]
@oleg-andreyev thanks! I have reopened #15975.
