### ISSUE TITLE
Elasticsearch side changes so Elastic can run vagrant tests in its continuous integration

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#16854]
**Describe the feature**:
It'd be super helpful if we could run the vagrant tests in continuous integration at Elastic ([here](http://build.elastic.co/), search from "ES server master"). That way we know when we break scripts or the deb or rpm or something. I'm going to use this ticket to track effort:

* [x] Get the tests passing again. We need to do this to make sure we don't break anything in the next step. #17152 
* [ ] Switch the boxes to those that Elastic has on Vagrant Atlas ([here](https://atlas.hashicorp.com/elastic)). We need to do this because those are easier to host in Elastic's CI - mostly because they have lxc versions which can be spun up in AWS. #17195 
* [x] Add sles-11 checks. Elastic added a sles-11 box to vagrant atlas. We should use it!

**Comment by jasontedor** [comment]
The first task

> Get the tests passing again. We need to do this to make sure we don't break anything in the next step.

is being tracked in #17152.

**Comment by jasontedor** [comment]
The second task

>  Switch the boxes to those that Elastic has on Vagrant Atlas (here). We need to do this because those are easier to host in Elastic's CI - mostly because they have lxc versions which can be spun up in AWS.

is being tracked in #17195.

**Comment by jasontedor** [comment]
The third task

> Add sles-11 checks. Elastic added a sles-11 box to vagrant atlas. We should use it!

I lumped into #17195 as well.
