### ISSUE TITLE
Add deprecation logging for deprecated functionality

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#16910]
There are a number of things that have been deprecated in 2.x but are not logged in the deprecation logs.  This issue is a meta issue to track these:

* [x] Mapper attachment plugin (5.0.0 only) (@dadoonet) See #16948
* [x] Multicast plugin (@dadoonet) See #16949 
* [x] Mapping `_source` transform (@danielmitterdorfer) See #16952
* [x] Geo mapping params like `validate_*` (@nknize) See #17015
* [x] Use of `scan` search type (@jpountz) See #16980
* [x] Use of old script/template syntax (@colings86) See #16950

**Comment by dadoonet** [comment]
@clintongormley About mapper attachment plugin there is no alternative before 5.0. So I think we should only use the deprecation logger in master branch for this plugin. WDYT?

**Comment by clintongormley** [comment]
@dadoonet makes sense

**Comment by jpountz** [comment]
@clintongormley warmers should not be necessary: we just ignore warmers when parsing the cluster state in 5.0.
