### ISSUE TITLE
Backport Reindex to 2.3 tracker

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#17031]
I'm starting to end up with lots of PRs that need to be backported to 2.3 for reindex. I'm going to use this issue as a tracking list:

Required:

* [x] Merging reindex branch into 2.3/2.x branch (to master was #16861) #17060
* [x] Wait for tasks to finish support for Task list API (required so tests pass consistently) (master was #16914) 5b6779ed54b2c628e1fbb4c18518d96b8f6cec4e
* [x] Test for script changing destination index (master was #17023) 61415dccafc09f9b108c896628238c2fc9879ef3
* [x] Timeout reindex if any sub requests timeout (master was #16962) 014475d6fda038992455be35f25338f13ed83ec2
* [x] Search failures make reindex fail (master was #16889) 7b1d567cd21c7dc3d7f2cd7fad889826125cd627
* [x] Make reindex requests implement interfaces that plugins like (master was #17032) 6e6769eaaa507928d2e643287592e548aa8d8601
* [x] Fix a test that fails sporadically (master was #17057) 2e7d479e8c5e219a9e6001cc24f94d005c003180

Would be nice:

<s>* [ ] Throttling support (master is #17039)</s> Not happening. 2.3 is eminent and throttling still hasn't been merged to master.

**Comment by BrandesEric** [comment]
Quick question @nik9000.  I am anxiously awaiting "official" reindexing functionality.  I've been following your commits and the Github issues as best I can, but I confess I'm a bit confused on when this will be RTMed?  Will there be an ES 2.3?  Or will the new "5.0" branding be the next version?  Either way, will reindexing go live as part of the next significant release (that is, either 2.3 or 5.0?)

**Comment by nik9000** [comment]
It'll go live with both 2.3 and 5.0 with 2.3 coming sooner than 5.0.

**Comment by BrandesEric** [comment]
@nik9000 that's great, thanks!

**Comment by russcam** [comment]
@nik9000 are there plans to backport reindex throttling to `2.x`?

**Comment by clintongormley** [comment]
@russcam see https://github.com/elastic/elasticsearch/pull/18020
