### ISSUE TITLE
Not all features work on ip fields

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#17971]
Since we switched to points to index ip addresses, a couple things are not working anymore:
 - [x] range queries only support inclusive bounds (#17777)
 - [x] range aggregations do not work anymore (#17859)
 - [x] sorting on ip addresses fails since it tries to write binary bytes as an utf8 string when rendering sort values (#17959)
 - [x] sorting and aggregations across old and new indices do not work since the coordinating node gets longs from some shards and binary values from other shards and does not know how to reconcile them (#18593)
 - [x] terms aggregations return binary keys (#18003)
