### ISSUE TITLE
Ongoing Painless Improvements

### ISSUE THREAD

**Issue by jdconrad** [elastic/elasticsearch#17992]
Ongoing:
- More Tests -- Any tests added on their own. (#18538) (#18560)
- Any Bug Fixes -- Any and all bug fixes. (#18871) (elastic/x-plugins/issues/2587)
- General Usability - Improve syntax for usability. (#18241) (#18287) (elastic/x-plugins/pull/2225)
- Better Dev - Improve ease of development. (#18288) (#18350) (#18463) (#18951) (#19459)
- Def Performance - Improve performance for dynamic types. 
  (#18151) (#18201) (#18232) (#18234) (#18359) (#18379) (#18425) (#18849) (#18867) (#18899) (#18958)
- General Performance - Improve overall performance. (#18247) (#18262) (#18264) (#18284)
- Grammar Changes -- Any and all grammar changes. (#18531) (#18827) (#18931) (#19092)
- Better Error Messages - Make error messages bubble to the top level.  Make better error messages for syntax errors caught during the ANTLR lexing/parsing phases. (#18298) (#18319) (#18600) (#18711)
- Anything Else - Any other changes not falling into a category. (#19936)

Documentation:
- [ ] Split Pages: Painless has a large feature set, so it needs to be split into multiple pages.
- [ ] New Examples: Painless documentation needs new examples.
- [ ] Updated Examples: Update the script examples used by other pieces of Elasticsearch to use Painless instead. (elastic/x-plugins/pull/2327) (elastic/x-plugins/pull/2449) (elastic/x-plugins/pull/2571)

Tasks:
- [x] Date API - Add a Date API. (#18621) (#18658)
- [x] Internal AST -- Decouple ANTLR from Painless to allow for other possible uses of the compilation unit. (#18286)
- [x] Generics - Remove all generics for simplicity.
- [x] Overload - Allow for arity overloaded methods/constructors. (#18385)
- [x] Regular Expressions - Add some form of regular expressions. (#18842) (#18858) (#19070)
- [x] Strings - Allow single-quoted strings to be used. (#18150)
- [x] Foreach - Allow the foreach shortcut in for loops. (#18757)
- [x] Properties - Expose properties for the different field types including geopoint support (#18169)
- [x] .value - Add .value for field access. (#18169) 
- [x] Improved API -- Any updates to the whitelist. (#18372) (#18533)
- [x] Colon Syntax -- Add method pointers using colon syntax.
- [x] Lambda Functions -- Anything lambda related. (#18578) (#18748) (#18818) (#18824) (#18828) (#18911) (#18924) (#18954) (#18983) (#19003)
- [x] Custom Functions -- Add user defined functions. (#18810)
- [x] Type Initializers -- Add initializers for arrays, lists, and maps. (#19012)
- [x] Instanceof Operator -- Add an instanceof operator. (#19065)

**Comment by jdconrad** [comment]
I am currently making progress on the internal AST.

**Comment by clintongormley** [comment]
@jdconrad are you going to expose the methods/properties listed here? https://www.elastic.co/guide/en/elasticsearch/reference/2.3/modules-scripting.html#_document_fields

**Comment by jdconrad** [comment]
@clintongormley I'll add it to the list.

**Comment by jdconrad** [comment]
Single-quoted strings is in (https://github.com/elastic/elasticsearch/pull/18150).

@rmuir Has checked in some code to improve def performance a bit (https://github.com/elastic/elasticsearch/pull/18151)

**Comment by jdconrad** [comment]
@rmuir has done .value + perf improvements. (#18169)

**Comment by clintongormley** [comment]
Here's an example of an exception that could be improved.  In groovy, if you run:

    PUT foo/bar/1
    {}
    
    POST foo/bar/1/_update
    {
      "upsert": {},
      "script": {
        "lang": "groovy",
        "inline": "ctx._source.foo.bar = 18"
      }
    }

You get:

    {
      "error": {
        "root_cause": [
          {
            "type": "remote_transport_exception",
            "reason": "[Coachwhip][127.0.0.1:9300][indices:data/write/update[s]]"
          }
        ],
        "type": "illegal_argument_exception",
        "reason": "failed to execute script",
        "caused_by": {
          "type": "script_exception",
          "reason": "failed to run inline script [ctx._source.foo.bar = 18] using lang [groovy]",
          "caused_by": {
            "type": "null_pointer_exception",
            "reason": "Cannot set property 'bar' on null object"
          }
        }
      },
      "status": 400
    }


If you do the same in painless:

    PUT foo/bar/1
    {}
    
    POST foo/bar/1/_update
    {
      "upsert": {},
      "script": {
        "lang": "painless",
        "inline": "input.ctx._source.foo.bar = 18"
      }
    }

You get the same NPE but with less context, which makes it harder to debug:

    {
      "error": {
        "root_cause": [
          {
            "type": "remote_transport_exception",
            "reason": "[Coachwhip][127.0.0.1:9300][indices:data/write/update[s]]"
          }
        ],
        "type": "illegal_argument_exception",
        "reason": "failed to execute script",
        "caused_by": {
          "type": "null_pointer_exception",
          "reason": null
        }
      },
      "status": 400
    }

**Comment by jdconrad** [comment]
PR out for internal AST (#18286)

**Comment by rmuir** [comment]
@clintongormley i don't think we should hurt performance to try to be like groovy. If we want, we can be slow like groovy as well. In this case, the biggest problem is that the stacktrace is completely lost. We have good stacktraces which tell you what is going on, but ES throws them away. So I don't think its a painless problem, and I dont think we should be trying to wrap and wrap them to hack around this issue.

**Comment by jdconrad** [comment]
Added links to the numerous performance PR's by @rmuir

**Comment by uschindler** [comment]
@jdconrad can you also add PR #18232 (DEF performance), #18241 (usability)?

**Comment by jdconrad** [comment]
@uschindler Added those to the list.  Sorry, there's been quite a few lately, so those two slipped through the cracks.

**Comment by jdconrad** [comment]
Large API additions by @rmuir (#18533)

**Comment by ppf2** [comment]
Can we also add a print function so we can print out the values of variables for easier debugging purposes?  This is possible using groovy and other languages.

**Comment by jdconrad** [comment]
@ppf2 How are you doing this with Groovy?

**Comment by ppf2** [comment]
With groovy, you can print info like the following as part of a script and it gets written to the console.

```     
        "inline": "print 'hello';"
```

**Comment by uschindler** [comment]
I'd not add printing to stdout. I think something like `print` or, better, `log` should go to a logger with the script name as logging class. The logger could be added as a static field to every script class and used then by some alias mapping.

**Comment by rmuir** [comment]
I don't think scripts should do any logging or I/O at all. Perhaps groovy does that, but groovy caused a whole lot of problems due to what it does.

In a lot of ways, if groovy does something, we might want to investigate doing the opposite.

**Comment by s1monw** [comment]
> I don't think scripts should do any logging or I/O at all. Perhaps groovy does that, but groovy caused a whole lot of problems due to what it does.

+1 to not do any IO here! can we support asserts maybe then we can debug via exception and asserts?

**Comment by jdconrad** [comment]
+1 to @s1monw suggestion.  You can throw several different types of exceptions right now in the same way that Java does including IllegalArgumentException and IllegalStateException.

**Comment by nik9000** [comment]
> Regular Expressions - Add some form of regular expressions.

I think something like this would be useful for using painless during reindex/update. No a good choice during search scripts, but such is life. We could even disable it by default in that context.

Anyway, if we have special syntax I think we should copy some language that folks are used to so that we can tell people "it should work just like X" and then we have an automatic spec. That being said I'd like to propose we pick between groovy's syntax, perl's syntax, or something else I haven't thought of. Or having no special regex syntax.

This is my memory of groovy's regex syntax:
* `/` is a string delimiter.
* `~STRING` is sugar for `Pattern.compile(STRING)`.
* `lhs=STRING =~ rhs=STRING` is sugar for `Pattern.compile(rhs).matcher(lhs)`.
* `lhs=STRING ==~ rhs=STRING` is sugar for `Pattern.compile(rhs).matcher(lhs).matches().
* Flags live in the front of the pattern and look like `(?i)`
* Groovy's matchers are Iterable in a kind of messy way I don't think we should copy at all/without some modification.

I like the groovy choice because it is fairly explicit (less magic) and maps fairly easily to Java. And if people are using regexes now with groovy it should mostly "just work".

It looks like perl's syntax is:
* `/` is a special string delimiter that builds patterns
* flags go after the last `/`
* `=~` returns a boolean (or some truthy thing, 5 minutes of internet research isn't an exhaustive study) on match and sets special `$_` and `$1`, `$2`, etc...

I think perl's regex is much more popular than Groovy's syntax and it is fairly "natural". Maybe because we're all so used to it. I think the disadvantage of it is that it doesn't map as easily to java with the magic variables. OTOH we can absolutely make them work because we're writing the language.

Maybe because I don't know it as well, I think that perl's regex syntax is deeper and we'd have trouble ever saying "painless's regexes are just like perl" because there is so much magic in the language around regexes. Also, our regexes would be java regexes, not perl regexes.

**Comment by nik9000** [comment]
Also, I think that implementing goovy's regex syntax would be a lot easier. But I if we decide we really want some glorious syntax we shouldn't limit ourselves to groovy.

**Comment by rmuir** [comment]
I think it should only be `/regex/`, which acts a static final Pattern constant. We can add some of the groovy operators too to make regexes easier, but otherwise add all of java.util.regex, except ability to Pattern.compile. So no computed Strings at all. It means regexes will never compile for every document and so on.

**Comment by jdconrad** [comment]
+1 to having all regexes be static constants.  Otherwise, it will be insanely slow for per-document operations.

**Comment by uschindler** [comment]
+1 to have static final constants. The parser should just collect all those regexes and then add them as private static fields + `<clinit>` after the logic is written (see #18828 where we implemented this already). Just see it as "constant pool" of patterns.

**Comment by nik9000** [comment]
> The parser should just collect all those regexes and then add them as private static fields + <clinit> after the main execute method was written

I took a crack at it this weekend and made #18842. It is far from perfect but generally does what @uschindler described.

**Comment by nik9000** [comment]
I opened #18858 to pick up `=~` and `==~` from groovy. You can call `/pattern/.matcher(str).matches()` if you like but `str ==~ /pattern/` feels much more natural to me given all the regex work I've done with groovy in the past month or two.

I think this is required before we can tick the regex box:
* Flags support after the pattern. It'd look like `/pattern/i`.

I'd like to do two more things because I feel like they'd be useful:
* Support syntax like `(str =~ /bar/).somemethod()`
* It'd be super lovely to have a replaceAll that takes a closure. So if `str`=`cat` then `(str =~ /bar/).replaceAll(m -> m.group().toUpperCase(Locale.ROOT))`=`cAt`. This kind of thing is fairly useful for stuff like normalizing addresses which I see as something someone might want to do with the update-by-query API. I think this is a long ways out because I don't think painless has closures, only method refs?

**Comment by rmuir** [comment]
> I think this is a long ways out because I don't think painless has closures, only method refs?

Well technically we have a stub for lambdas: not closures, there is a difference :)
I think its something we can hack out in a day or so honestly. This is only syntactic sugar at the moment, the stuff we need is there. I had planned to work on it but took a break from that stuff to try to improve the math performance.  Will look in fairly soon as that stuff should be winding down.

Thanks for tackling the regex issues!

**Comment by nik9000** [comment]
I'm going to call regexes "done" for now. We have regex syntax, flags, and matcher syntax. And documentation for all of those things.

**Comment by nik9000** [comment]
> It'd be super lovely to have a replaceAll that takes a closure.

I opened #19070 for this.

**Comment by EricMCornelius** [comment]
Based on the discussion here, am I correct in thinking it's not possible to pass a regex parameter into a painless script?

Is there any discussion of exposing a context initialization phase, so that we can do things like compile dynamic/parameterized regexes which are passed via the context for use in scripts without the overhead mentioned above?

**Comment by nik9000** [comment]
Not currently, but an initialization phase is certainly something I've
thought about in the past.

**Comment by jdconrad** [comment]
I'm going to close this as it was really meant for the initial release tracking.  We should open new issues for any new improvements.
