### ISSUE TITLE
Remove unbounded queues from thread pool executors

### ISSUE THREAD

**Issue by jasontedor** [elastic/elasticsearch#18491]
Today, the scaling thread pool executors have unbounded queues by default, and the fixed thread pool executors can have unbounded queues if their size is set to a negative value. Unbounded queues are dangerous and should be eliminated. I think we should remove the ability for any of the thread pool executors to have unbounded queues but maybe (some of?) the scaling thread pool executors should get a caller-runs rejection policy?

Relates #14448

**Comment by jasontedor** [comment]
We discussed this in Fix-it-Friday and arrived at the following proposal:
 - [ ] remove custom thread pools #17915 
 - [ ] register proper settings for thread pools
 - [ ] remove unbounded queues #18491
 - [ ] place a hard bound of 256 * max number of threads in pool for a bound on the queue #14448

**Comment by jasontedor** [comment]
Closed in favor of #18613
