### ISSUE TITLE
Improve thread pools

### ISSUE THREAD

**Issue by jasontedor** [elastic/elasticsearch#18613]
This issue is a meta-issue for collapsing several sub-issues for improving thread pools in core Elasticsearch:
 - [ ] remove built-in support for custom executors #17915 
 - [ ] provide hook for plugins to register a thread pool stats provider for custom executors
 - [ ] register proper settings for thread pools
 - [ ] remove unbounded queues #18491 
 - [ ] place a hard bound of 256 * max number of threads in pool for a bound on the queue #14448 

The proposal here is that core Elasticsearch will no longer provide support for custom executors. Of course, a plugin can always create an executor on its own and so core Elasticsearch will provide an extension point for such plugins to provide stats back to core Elasticsearch for reading in node stats API and cat thread pools API.

Relates #17915, relates #18491, relates #14448

**Comment by rjernst** [comment]
This issue has been stalled due to complexities of the general threadpool (and others) that are currently unbounded. The concern is that bounding them may cause contention, and could (in theory?) cause deadlocks. I don't think this will be theoretically resolved. We know that having unbounded queues has problems of its own, as outlined here. I propose that we move forward now by implementing the hard bound on queues suggested here (256 * max threads) in master for 8.0. This gives us sufficient time to test through our own daily performance tests, as well as users to test in the alphas/betas for 8.0.

**Comment by ldematte** [comment]
@rjernst can you comment on what is still missing and what we would need to do next (if anything?)
