### ISSUE TITLE
Netty 4 improvements

### ISSUE THREAD

**Issue by jasontedor** [elastic/elasticsearch#19562]
This is a meta issue to track some known issues with the Netty 4 implementation:
 - [x] port #19522 to Netty 4 #19874
 - [ ] enable advanced leak detection in tests and fail the build if there is a leak #20398
 - [x] upgrade to a non-snapshot build of 4.1.4.Final+ of Netty 4 #19689
 - [x] set `io.netty.noUnsafe` to `true` by default? (probably) #19786
 - [x] investigate performance

**Comment by jasontedor** [comment]
> investigate performance

I did some simple benchmarking with Rally, and the performance numbers are basically the same between Netty 3 and Netty 4. Now that Netty 4 is the default, we can also watch for this in the nightly benchmarks.

**Comment by Scottmitch** [comment]
just curious are you using the [PooledByteBufAllocator](https://github.com/netty/netty/blob/4.1/buffer/src/main/java/io/netty/buffer/PooledByteBufAllocator.java)? Do you notice any differences in memory / GC profile?

**Comment by s1monw** [comment]
@jasontedor can we have a dedicated issue for that last checkbox open here?

**Comment by jasontedor** [comment]
> can we have a dedicated issue for that last checkbox open here?

@s1monw I opened #20398.

**Comment by s1monw** [comment]
w00t

**Comment by jasontedor** [comment]
Closing since the last remaining item has a dedicated issue, #20398.
