### ISSUE TITLE
Move analysis components to a module

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#23658]
We'd like to move the analyzers from Elasticsearch core into a module. They would still ship with Elasticsearch, just not with the Elasticsearch jar. We like this for a few reasons:
1. It reduces the size of the high level rest client and the transport client. They don't need to reference analyzers.
2. It proves that analysis plugins are first class citizens by consuming the plugin API for setting up the analyzers.
3. It forces us to develop features a little more generically, not relying on specific analyzers, which is a good thing if you are going to have a first class plugin API.

At this point I propose we move analysis components a few at a time. Claim the components you'd like to move before doing the move using the list below. We're doing this directly in master and 5.x. There is no need for a long running branch for this.

Keep in mind when claiming components that moving the code is not time consuming but fixing tests that rely on the components might be.

Analyzers
--------
* [x] Standard Analyzer (This one will stay in core. It isn't part of the `lucene-analzyers-common.jar` and it will keep testing easier to keep it in core.)
* [ ] Simple Analyzer
* [ ] Whitespace Analyzer
* [ ] Stop Analyzer
* [ ] Keyword Analyzer
* [ ] Pattern Analyzer
* [ ] Language Analyzers
* [ ] Fingerprint Analyzer

Tokenizers
--------
* [x] Standard Tokenizer (I believe this one will also stay in core for the same reasons Standard Analyzer is staying.)
* [ ] Letter Tokenizer
* [ ] Lowercase Tokenizer
* [ ] Whitespace Tokenizer
* [ ] UAX URL Email Tokenizer
* [ ] Classic Tokenizer
* [ ] Thai Tokenizer
* [ ] N-Gram Tokenizer
* [ ] Edge N-Gram Tokenizer
* [ ] Keyword Tokenizer
* [ ] Pattern Tokenizer
* [ ] Path Tokenizer

Token Filters
--------
* [ ] Standard Token Filter
* [ ] ASCII Folding Token Filter (#23614)
* [ ] Flatten Graph Token Filter
* [ ] Length Token Filter
* [ ] Lowercase Token Filter
* [ ] Uppercase Token Filter
* [ ] NGram Token Filter
* [ ] Edge NGram Token Filter
* [ ] Porter Stem Token Filter
* [ ] Shingle Token Filter
* [ ] Stop Token Filter
* [ ] Word Delimiter Token Filter (#23614)
* [ ] Stemmer Token Filter
* [ ] Stemmer Override Token Filter
* [ ] Keyword Marker Token Filter
* [ ] Keyword Repeat Token Filter
* [ ] KStem Token Filter
* [ ] Snowball Token Filter
* [ ] Phonetic Token Filter
* [ ] Synonym Token Filter
* [ ] Synonym Graph Token Filter
* [ ] Compound Word Token Filter
* [ ] Reverse Token Filter
* [ ] Elision Token Filter
* [ ] Truncate Token Filter
* [ ] Unique Token Filter
* [ ] Pattern Capture Token Filter
* [ ] Pattern Replace Token Filter
* [ ] Trim Token Filter
* [ ] Limit Token Count Token Filter
* [ ] Hunspell Token Filter
* [ ] Common Grams Token Filter
* [ ] Normalization Token Filter
* [ ] CJK Width Token Filter
* [ ] CJK Bigram Token Filter
* [ ] Delimited Payload Token Filter
* [ ] Keep Words Token Filter
* [ ] Keep Types Token Filter
* [ ] Classic Token Filter
* [ ] Apostrophe Token Filter
* [ ] Decimal Digit Token Filter
* [ ] Fingerprint Token Filter
* [ ] Minhash Token Filter

Character Filters
---------
* [ ] HTML Strip Char Filter
* [ ] Mapping Char Filter
* [ ] Pattern Replace Char Filter

Misc
-------
* [ ] Remove core's dependency on `lucene-analzyers-common.jar`.

**Comment by mayya-sharipova** [comment]
cc @elastic/es-search-aggs
