### ISSUE TITLE
Migrate static backwards compatibility indices tests to qa:full-cluster-restart project

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#24939]
In #24846 we started migrating the static index backwards compatibility tests to a gradle project. We did this for a few reasons:
1. The static tests played a lot of tricks to get everything to run in the same JVM so they weren't "real". This caused them to miss things from time to time. The `qa:full-cluster-restart` project has no such problems.
2. It is more difficult to reason about the static backwards compatibility tests because the static indexes are just binary blobs built by a python script. We have to be careful to keep it up to date, etc. The indices built by `qa:full-cluster-restart` are built at testing time so any changes to the index building code apply immediately.
3. Checking binary blobs into the code is icky.

There are a bunch of pieces left to port from the static tests to `qa:full-cluster-restart`:
* [x] RestoreBackwardsCompatIT.testRestoreOldSnapshots @nik9000 #25296
* [x] RepositoryUpgradabilityIT @nik9000 #25296
* [x] OldIndexBackwardsCompatibilityIT#assertBasicSearchWorks @martijnvg #24954
* [x] OldIndexBackwardsCompatibilityIT#assertAllSearchWorks @martijnvg #25173
* [x] OldIndexBackwardsCompatibilityIT#assertBasicAggregationWorks @martijnvg #25173
* [x] OldIndexBackwardsCompatibilityIT#assertRealtimeGetWorks @martijnvg #25173
* [x] OldIndexBackwardsCompatibilityIT#assertNewReplicasWork @martijnvg #25173
* [x] OldIndexBackwardsCompatibilityIT#assertUpgradeWorks @martijnvg #25275
* [x] ~~OldIndexBackwardsCompatibilityIT#assertPositionIncrementGapDefaults (maybe not a big deal anymore because these are mostly for the 2.x -> 5.0 upgrade)~~
* [x] OldIndexBackwardsCompatibilityIT#assertAliasWithBadName @martijnvg #25275
* [x] OldIndexBackwardsCompatibilityIT#assertStoredBinaryFields @martijnvg #25275

There are a few things we need to clean up before we can remove a bunch of infrastructure for static bwc tests. I don't claim to know how to clean them all up:
* [ ] RestoreBackwardsCompatIT.testRestoreUnsupportedSnapshots
* [ ] RecoveryWithUnsupportedIndicesIT and StaticIndexBackwardCompatibilityIT
* [x] Remove create_bwc_index.py #26109
* [x] Update "how to release" docs to remove "run create_bwc_index.py" (https://github.com/elastic/dev/commit/f12bf0a50bd4534942142b8904481acd8440033b)
* [x] Remove static indices and repositories #26109

And there are a bunch of things to add:
* [ ] Lenient boolean backwards compatibility tests
* [x] Shrunken indexes (we've had trouble with them in the past) #25720

**Comment by nik9000** [comment]
@martijnvg I edited the issue description to add a few more things to clean up. I'm almost done with the snapshot/restore stuff and I'll open a PR for that soon.

**Comment by nik9000** [comment]
I believe we've migrated all of the remaining static bwc tests. A few month ago, actually. I just hadn't payed attention to this issue in the mean time.
