### ISSUE TITLE
Make `mapping.single_type` only settable if the index is a 5.x index

### ISSUE THREAD

**Issue by s1monw** [elastic/elasticsearch#24961]
`mapping.single_type` allows to add multiple types which is something that 6.x indices must not allow. Yet, today this setting is still modifiable while it defaults to `true` In order to move make it only settable on 5.x indices and read-only in 6.0 we need to fix several things like:

- [x] Fix `PercolatorFieldMapperTests` to use a single type #24958 / #24963
- [x] Move Rest tests that use multiple types into a mixed cluster scenario such that indices that are tested against are created with a 5.x version. #24965
- [x] Remove this setting from `AbstractQueryTestCase`
- [x] disallow setting `index.mapper.single_type` on 6.x indices #25375
- [x] Fix Parent/Child to work without multiple types #20257
- [x] Fix Documentation do not use multiple types #25401

**Comment by nik9000** [comment]
> Move Rest tests that use multiple types into a mixed cluster scenario such that indices that are tested against are created with a 5.x version.

The `qa:full-cluster-restart` project might be useful here.

**Comment by s1monw** [comment]
> The qa:full-cluster-restart project might be useful here.

I don't think it needs to be that complicated we can just use the `qa:mixed-cluster` project

**Comment by s1monw** [comment]
All tasks done. Thanks everyone

**Comment by dcorking** [comment]
The Upgrade Assistant in X-Pack doesn't seem to be able to handle this.

```json
Index name: .kibana
Required action: reindex
Failed to create index.

{
  "statusCode": 500,
  "error": "Internal Server Error",
  "message": "An internal server error occurred",
  "code": "ERR_CREATE_INDEX_FAILED",
  "root_cause": [
    {
      "type": "illegal_argument_exception",
      "reason": "unknown setting [index.mapping.single_type] please check that any required plugins are installed, or check the breaking changes documentation for removed settings"
    }
  ],
  "type": "illegal_argument_exception",
  "reason": "unknown setting [index.mapping.single_type] please check that any required plugins are installed, or check the breaking changes documentation for removed settings",
  "reindexedIndexName": ".kibana-6"
}
```
The breaking changes documentation [mentions the removed setting](https://www.elastic.co/guide/en/elasticsearch/reference/6.2/removal-of-types.html#_migrating_multi_type_indices_to_single_type)
> In 6.x, there is no need to specify index.mapping.single_type as that is the default.

 But it doesn't mention how to use the Upgrade Assistant to deal with it.

A web search led me here.  But where is the right place to report this error?

**Comment by dcorking** [comment]
Good news. Although I was disappointed that the recommended upgrade path of the Upgrade Assistant's Reindex Helper didn't work (with the error reported above), I was able to successfully upgrade the internal index for Kibana from 5.6 to 6.2 following the manual instructions at https://www.elastic.co/guide/en/kibana/6.2/migrating-6.0-index.html

It only took a few seconds.
