### ISSUE TITLE
Sequence Numbers related work slated for 6.0.0

### ISSUE THREAD

**Issue by bleskes** [elastic/elasticsearch#25355]
This is a meta issue to track the subset of th the Sequence Numbers work required for 6.0.0 . This is to increase visibility to those items out of the full long list in  #10708. 

- [x] Current 6.0 BWC layer mutates IndexRequest. This should be removed and pushed to 5.x (@bleskes)
- [x] Transfer sequence number "primary context" (i.e., in sync shards, tracked local checkpoints etc) upon primary relocation AND don't allow the old primary to operate as primary anymore (see IndexShard#verifyPrimary) (@jasontedor, #25122)
- [x] After recovering, a primary should update its knowledge of its own local checkpoint (@ywelsch, #25468)
- [x] When a replica shard increases its primary term under the mandate of a new primary, it should also update its global checkpoint; this gives us the guarantee that its global checkpoint is at least as high as the new primary and gives a starting point for the primary/replica resync (@ywelsch, #25422)
- [x] Replicas should throw their local checkpoint to the global checkpoint when detected a new primary. (@jasontedor, #25452)
- [x] On primary promotion, the local checkpoint tracker should be realigned with the translog before filling the gaps. (@jasontedor, #25553)
- [x] Shrunk indices - When recovering the primary shard we need to set its max_unsafe_auto_id_timestamp @jasontedor, #25356)
- [x] how do we deal with the BWC aspects in the case that - a primary is running on a new node will one replica is on an old node and one replica is on a new one. In that case the primary will maintain seq# and checkpoints for itself and the replica on the new node. However if the primary fails it may be the case that the old replica is elected as primary. That means that the other replica will suddenly stop receiving sequence numbers. It is not clear if this really a problem and if so what the best approach to solve it. (@dakrone, #25277)
- [x] A primary that's allocated when in sync replicas aren't can advance the global checkpoint to a region that's unsafe - the primary doesn't about the it's local ops, which are above the global checkpoint actually exists on the other replicas. (@ywelsch, #25468)

**Comment by bleskes** [comment]
Thanks @jasontedor, @ywelsch & @dakrone for all the hard work.
