### ISSUE TITLE
Improve percolator performance

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#25445]
There are several tasks left around from when the percolator was rewritten in 5.0 that can be done in order to improve the percolator's performance.

* [x]  ~~support for selecting percolator query candidate matches containing wildcard / prefix queries.~~#25351
* [x] Document how to deal with wildcard and prefix queries. #27831
* [x] Add support for selecting percolator query candidate matches containing range queries. #25647
* [ ] Add support for selecting percolator query candidate matches containing `geo_distance`, `geo_bounding_box`, `geo_polygon` and `geo_shape` queries. #26040
* [ ] Add support for selecting percolator query candidate matches containing `geo_shape` queries.
* [x] Today the percolator query's xcontent representation is stored. Alternatively the percolator could also store the percolator query's `Writable` representation. This could speed up percolating because parsing the latter format has less overhead. I expect the this improvement to be more noticeable when a percolator query is somewhat more complex (bool query with several clauses) compared to a simple `term` query. #25456
* [x] ~~In case of phrase queries and conjunction queries the percolator only extracts the longest term at index time. The idea here is that only a single term needs to be indexed for the selecting of percolator query candidate matches at search time to work and the longest term is picked because in general that is the rarest term. However that may not always be the case and it would be great if that logic is configurable.~~ #26081 (this change has been superseded by #26307)
* [x] Change the `percolate` query the accept multiple documents (via `documents` json object array). This can speed percolation when many documents need to be percolated. The price for parsing and matching percolator queries is only paid once per batch of documents instead of for each document to percolate. #26418
 * [x] Improve extraction of conjunctions in order to have fewer false positives. #26307

**Comment by jpountz** [comment]
@martijnvg Looks like "Document how to deal with wildcard and prefix queries." would be a low hanging fruit?

cc @elastic/es-search-aggs

**Comment by martijnvg** [comment]
@jpountz I forgot to update this ticket. I added docs about this topic via #27831.

**Comment by javanna** [comment]
heya @martijnvg it looks like this issue is not being worked for a while, can we close it?

**Comment by martijnvg** [comment]
Agreed @javanna, let close this is. The only work left is around optimizing geo queries.
