### ISSUE TITLE
Use soft-deletes to maintain document history

### ISSUE THREAD

**Issue by dnhatn** [elastic/elasticsearch#29530]
With the introduction of [soft-delete]((https://issues.apache.org/jira/browse/LUCENE-8200)) in Lucene, a history of a document can be maintained. This meta issue tracks work on migrating from hard-deletes to soft-deletes.

Cut over
--------
- [x] Replace hard-updates by soft-updates (https://github.com/elastic/elasticsearch/pull/29458)
- [x] Replace hard-deletes by soft-deletes (https://github.com/elastic/elasticsearch/pull/29549)
- [x] Index no-op (https://github.com/elastic/elasticsearch/pull/30226) 
- [x] Index stale operations (i.e. out of order) on replicas (https://github.com/elastic/elasticsearch/pull/29679)

Retention and source
--------------------
- [x] Use SoftDeletesRetentionMergePolicy to maintain only the recent history (https://github.com/elastic/elasticsearch/pull/30335)
- [x] Special merge strategy when `_source` is disabled (https://github.com/elastic/elasticsearch/pull/31106)
- ~~Do not keep delete tombstones in version map. Delete tombstones can be queried from Lucene~~ (to be done in https://github.com/elastic/elasticsearch/issues/31637)

Translog
--------
- [x] Add API allows querying operations given a range of seq# (https://github.com/elastic/elasticsearch/pull/30120)
- ~~Use `maxTimestamp` from engine for `autoGeneratedIdTimestamp`~~ (migrated to #30086)
- [x] Replace translog by Lucene history in peer-recovery (https://github.com/elastic/elasticsearch/pull/30522)
- [x] Replace translog by Lucene history in primary-replica resync (#33178)
- [x] Only sends operations after the local checkpoint in peer-recovery (#33190)

TBD
-------
- ~~Avoid having multiple docs for the same stale operation. We currently defer the dedup until the search time but we might revisit this decision to do it at the index time~~(to be done in #31637). 

Misc
-------
- [x] Store the reason of noop in its document tombstone (https://github.com/elastic/elasticsearch/pull/30570)
- [x] Use exact numDocs in synced-flush (https://github.com/elastic/elasticsearch/pull/30228)
- [x] Randomize soft-deletes settings (https://github.com/elastic/elasticsearch/pull/31585)
- [x] Do not expose hard-deleted documents (#32333)

**Comment by bleskes** [comment]
👍
