### ISSUE TITLE
Cat APIs for X-Pack

### ISSUE THREAD

**Issue by elasticmachine** [elastic/elasticsearch#29690]
There are many configuration related entities now in xpack that are either stored
in an index or cluster state. Almost all of these entities have dedicated crud APIs.
But none of them can be retrieved from a _cat api. We should add support for this. 

This meta issue keeps track of the xpack related config entities that should be exposed
in a _cat api.

- [ ] watches
- [ ] users, roles
- [ ] datafeeds and ml jobs
- [ ] Auto follow patterns
- [ ] Ilm & slm policies
- [ ] Enrich policies
- [ ] Rollup policies

*Original comment by @uboness:*

_From @MarxDimitri on May 1, 2015 17:20_

Searching on .watches is OK but not that convenient and efficient especially given a big number of watches. It would be good to have something like cat api for watches.

**Comment by dakrone** [comment]
This has been open for quite a while, and hasn't had a lot of interest. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
