### ISSUE TITLE
Changelog issue tracking

### ISSUE THREAD

**Issue by pcsanwald** [elastic/elasticsearch#30425]
our move to using `docs/CHANGELOG.asciidoc` has introduced a number of problems, we can use this meta issue to track various things that need to be fixed.

- [ ] cherry-picks are not clean. [recent change in master](https://github.com/elastic/elasticsearch/commit/beee5fe0043a71fe8967069e3b6200929095106e#diff-297418c07078d2b31d8e94a7d34b5255R110), Here is [how the cherry-pick ended up](https://github.com/elastic/elasticsearch/commit/ffe1ca462720c01e1506636ad730435aacaf269f#diff-297418c07078d2b31d8e94a7d34b5255R229)

- [ ] Merge-ability: Github's merge-ability checker doesn't apply `merge=union` when checking merge-ability, which means PR authors can get incorrect auto-merge warnings.[GH Issue here](https://github.com/isaacs/github/issues/560#issuecomment-329128262)

- [ ] Merge-ability 2: When fragments of the changelog are moved around in master and master is merged into a PR these moved fragments appear twice in the PR due to the `merge=union` setting.

- [ ] Backporting (via cherry picking) occasionally re-orders things in a very strange way.

- [ ] Respin process problem: I made a bug fix that I have pushed to 6.3 (for 6.3.1), 6.x (for 6.4.0), and master (for 7.0.0). I have placed an entry for this in the 6.3.1 section of the changelog. Here is where this breaks: if there is a respin of 6.3.0, my change will be in 6.3.0 but still in the 6.3.1 section of the changelog.

- [ ] Changelog entries for 6.x are [filled with entries from 5.x](https://github.com/elastic/elasticsearch/blob/ffe1ca462720c01e1506636ad730435aacaf269f/docs/CHANGELOG.asciidoc)

- [ ] Changelog entries for 6.2.3 are appearing under 6.2.3 incorrectly, [for example, nori](https://github.com/elastic/elasticsearch/blob/ffe1ca462720c01e1506636ad730435aacaf269f/docs/CHANGELOG.asciidoc#es-version-623)
