### ISSUE TITLE
Painless: Roadmap

### ISSUE THREAD

**Issue by jdconrad** [elastic/elasticsearch#31009]
This issue is to track all upcoming feature/refactor work on the Painless project.

* [ ]  (1) Documentation - Improved documentation including getting started guide, Painless specification, API, available contexts, and examples. (jdconrad)  (in progress) (https://github.com/elastic/elasticsearch/issues/23777)
* [x] (1) Types Removal - Replace the Painless Type with Java Class to reduce code complexity and be able to potentially take advantage of Java's upcoming value types. (jdconrad) (https://github.com/elastic/elasticsearch/pull/27847) (https://github.com/elastic/elasticsearch/pull/28329) (https://github.com/elastic/elasticsearch/pull/28346) (https://github.com/elastic/elasticsearch/pull/28364) (https://github.com/elastic/elasticsearch/pull/28429) (https://github.com/elastic/elasticsearch/pull/28433) (https://github.com/elastic/elasticsearch/pull/28466) (https://github.com/elastic/elasticsearch/pull/28471) (https://github.com/elastic/elasticsearch/pull/31699) 
* [ ] (5) Jar Separation - Separate Painless into it's own jar for consumption within other projects. (rjernst/jdconrad)
* [ ] (2) Multi-pass Compiler - Restructure compilation into a larger amount of passes doing a smaller amount of work.  Also allow for custom passes/nodes.  (jdconrad)
* [ ] (3) Safety Features - Improved safety features to prevent runaway loops and large memory allocations. (https://github.com/elastic/elasticsearch/issues/30139)
* [ ] (5) Benchmarks - Improved benchmarking allowing for individual scripts to compared against each other with changes to the compiler.
* [x] (1) Bindings - Add ability to cache values for certain methods when the values are read-only. (jdconrad) (in progress) (https://github.com/elastic/elasticsearch/pull/33042) (https://github.com/elastic/elasticsearch/pull/33274) (https://github.com/elastic/elasticsearch/pull/33440) (https://github.com/elastic/elasticsearch/pull/33865) (https://github.com/elastic/elasticsearch/pull/34370) (https://github.com/elastic/elasticsearch/pull/34410) (https://github.com/elastic/elasticsearch/pull/34424)
* [ ] (3) Factory Refactor - Clean up the code used to generate the factories for contexts. (jdconrad)
* [x] (2) Definition Refactor - Clean up definition to have default types and data structures that make more sense. (jdconrad) (https://github.com/elastic/elasticsearch/pull/31879) (https://github.com/elastic/elasticsearch/pull/32017) (https://github.com/elastic/elasticsearch/pull/32105) (https://github.com/elastic/elasticsearch/pull/32110) (https://github.com/elastic/elasticsearch/pull/32141) (https://github.com/elastic/elasticsearch/pull/32142) (https://github.com/elastic/elasticsearch/pull/32177) (https://github.com/elastic/elasticsearch/pull/32258) (https://github.com/elastic/elasticsearch/pull/32305) (https://github.com/elastic/elasticsearch/pull/32346) (https://github.com/elastic/elasticsearch/pull/32441) (https://github.com/elastic/elasticsearch/pull/32447) (https://github.com/elastic/elasticsearch/pull/32476) (https://github.com/elastic/elasticsearch/pull/32525) (https://github.com/elastic/elasticsearch/pull/32565) (https://github.com/elastic/elasticsearch/pull/32599) (https://github.com/elastic/elasticsearch/pull/32644) (https://github.com/elastic/elasticsearch/pull/32689) (https://github.com/elastic/elasticsearch/pull/32754) (https://github.com/elastic/elasticsearch/pull/32791) (https://github.com/elastic/elasticsearch/pull/32817) (https://github.com/elastic/elasticsearch/pull/33963)
* [ ] (3) Improved Debugging - Add improved debugging features.
* [ ] (3) Better Error Messages - Most of the error messages in Painless that get hit are fairly abstract and could use improvement.
* [ ]  (6) IDE Support - Exploration of adding an IDE support in Elipse/Intellij for Painless scripts or possibly Kibana.
* [x] (2) Improved Contexts - Refactor existing contexts to give them the appropriate types/variables and whitelists along with adding new ones where necessary. (rjernst)
* [ ] (3) Grammar Improvements - Refactor the grammar to remove the need for type context/regex context if possible. (jdconrad)
* [ ] (4) Template Language - Make Painless a JSON friendly template language.  (https://github.com/elastic/elasticsearch/issues/24529)
* [ ] (5) Whitelist Versioning - Explore ideas for how to properly deprecate classes/methods from the whitelist.
* [ ] ~~(5) Internal Methods - Explore ideas for how to enable/disable internal methods within the whitelist.~~
* [x] (2) Script Size - Make the size of a script based on the context its run in. (https://github.com/elastic/elasticsearch/pull/35184)
* [ ] (2) Documentation API - Create a REST API to return information about a specified context's available classes, methods, and fields along the execute method signature.  Create a gradle task to convert these to a nicely documented API.
* [ ] ~~(3) JSON AST - Create a version of the Painless AST in JSON that is easy to pass over a wire.~~
* [x] (2) Casting Consistency - Make casts in Painless have symmetry and consistency. (jdconrad) (https://github.com/elastic/elasticsearch/pull/36097) (https://github.com/elastic/elasticsearch/pull/36455) (https://github.com/elastic/elasticsearch/pull/36506) (https://github.com/elastic/elasticsearch/pull/36571) (https://github.com/elastic/elasticsearch/pull/36747) (https://github.com/elastic/elasticsearch/pull/36804) (https://github.com/elastic/elasticsearch/pull/36945)
* [x] (3) Dynamic Map Access - Create a utility method to allow maps to be accessed across multiple levels using a String with a dot delimiter from params. (stu-elastic) (https://github.com/elastic/elasticsearch/pull/43606) 
* [ ] (3) Read Only Variables - Allow variables passed into Painless to be read-only to allow for more efficient usage.

**Comment by jasontedor** [comment]
@jdconrad Thank you for pulling this together, this is wonderful to see. I would like to propose #24529 for consideration of being on this roadmap as well. What do you think?

**Comment by jdconrad** [comment]
@jasontedor Added https://github.com/elastic/elasticsearch/issues/24529 to the list.  Thanks!

**Comment by csenol** [comment]
Hi @jdconrad 
Until you separate painless as a jar , I created this project. https://github.com/csenol/plsd
It is a painless script development toolkit and might be useful.

**Comment by stu-elastic** [comment]
> Internal Methods - Explore ideas for how to enable/disable internal methods within the whitelist.

SKIPPED

> JSON AST - Create a version of the Painless AST in JSON that is easy to pass over a wire.

SKIPPED

Migrated everything to our internal project board.
