### ISSUE TITLE
Replicate closed indices

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#31141]
Closed indices currently have the downside that they are not replicated, so it's possible for an index to be closed, then the data lost because the node was terminated without saving the data.

We'd like to be able to close indices to remove any memory overhead of them, but still have the indices available for replication.

Steps to accomplish this (not necessarily in order):

- [x] Add an engine implementation that is essentially a "noop" that has no memory overhead #31163
- [x] ~~Change engine factory pluggability to be lazy so engine factory can be changed for an existing shard~~ #31409
- [ ] Add transition from open (InternalEngine) to the new noop engine implementation when an index is closed #31745
- [ ] Keep closed indices in the routing table so their allocation can be managed #31745
- [ ] Ensure closed indices show up correctly in administrative APIs (such as `/_cat/indices`) #31745
- [ ] Handle peer recovery for closed indices correctly #31745
- [ ] Handle store recovery for closed indices correctly #31745
- [ ] Handle rolling upgrade from a version of ES that does not allocated closed indices to a version that does

There are a number of currently unresolved questions about this also:

- ~~Should we continue to allow restoring snapshots into closed indices?~~ closed indices can't currently be snapshotted, so no breakage there
- What should be done for indices restored from local store that contain an invalid index setting (we currently restore these as "closed")?
- How should be handle settings that can only be changed when an index is closed and reopened, will they continue to work?

**Comment by tlrx** [comment]
Closed in favor of #33888
