### ISSUE TITLE
SQL: JDBC 4.3 spec support

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#31881]
[Java 9](https://docs.oracle.com/javase/9/docs/api/java/sql/package-summary.html) introduces some minor changes to the JDBC 4.3 API ([diff changes](https://jcp.org/aboutJava/communityprocess/maintenance/jsr221/221ChangeLog.html)).
#### java.sql and javax.sql Features Introduced in the JDBC 4.3 API
```
Added Sharding support
Enhanced Connection to be able to provide hints to the driver that a request, an independent unit of work, is beginning or ending
Enhanced DatabaseMetaData to determine if Sharding is supported
Added the method drivers to DriverManager to return a Stream of the currently loaded and available JDBC drivers
Added support to Statement for enquoting literals and simple identifiers
Clarified the Java SE version that methods were deprecated
```

- [ ] Sharding Support (including DatabaseMetaData enhancements regarding supportability) https://github.com/elastic/elasticsearch/issues/32081
- [ ] Enhanced Connection to be able to provide hints to the driver that a request is beginning or ending https://github.com/elastic/elasticsearch/issues/32082
- [ ] new `DriverManager` `driver` method https://github.com/elastic/elasticsearch/issues/32083
- [ ] Added support to Statement for enquoting literals and simple identifiers https://github.com/elastic/elasticsearch/issues/32084

Thanks to default methods hopefully the breakage of backwards compatibility is small - however it's worth investigating whether we need implementing some methods, in particular on the `DatabaseMetaData`, `Connection` and `Statement`.

**Comment by wchaparro** [comment]
superceded by ES|QL
