### ISSUE TITLE
[meta] Alias is_write_index feature tracking

### ISSUE THREAD

**Issue by talevy** [elastic/elasticsearch#31959]
The purpose of this issue is track the progress of the `is_write_index` flag on aliases. 

origin story: https://github.com/elastic/elasticsearch/issues/30061

Documentation: https://www.elastic.co/guide/en/elasticsearch/reference/master/indices-aliases.html#aliases-write-index

#### TODO

- [x] add `is_write_index` to metadata  https://github.com/elastic/elasticsearch/pull/30942
- [x] bugfix: PUT alias api did not support is_write_index parsing https://github.com/elastic/elasticsearch/pull/31674
- [x] leverage write indices for indexing/updating/deleting: https://github.com/elastic/elasticsearch/pull/31520
- [x] resolve how to handle alias routing values when alias points to multiple indices https://github.com/elastic/elasticsearch/issues/31936
- [x] Update Rollover to swap `is_write_index` true toggles when rolling over, instead of removing alias (https://github.com/elastic/elasticsearch/pull/32216)

**Comment by talevy** [comment]
all tasks are done!
