### ISSUE TITLE
Logging: Clean up logger building

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#32174]
We build loggers in about 15 different ways right now. After #31588 we'll only really need about 3 different ways. We should remove all of the confusing "variety".

**Comment by nik9000** [comment]
I've been working on this one on and off for a while. Right now we have this remaining:

* [ ] Remove `Loggers.getLogger(String)` #34520
* [ ] Replace calls to `Loggers.getLogger(Class)` with `LogManager.getLogger(Class)`
  * [ ] In `server`
  * [ ] In `modules`
  * [ ] In `plugins`
  * [ ] In `test`
  * [ ] In `x-pack`
* [ ] Remove `LogManager.getLogger(Class)`
* [ ] Remove `ESLoggerFactory`

Removing some of the calls to `Loggers.getLogger` feels like it'd be a pretty good first contribution so I'm going to mark this issue that way.

**Comment by lipsill** [comment]
Hey @nik9000, what do you mean by: 
> Replace calls to Loggers.getLogger(Class) with LogManager.getLogger(Class)

> Remove LogManager.getLogger(Class)

**Comment by nik9000** [comment]
We have this `Loggers` class that had a lot use historically but for the most part it is just a pass through to Log4j2's `LogManager`. I'm trying to remove all of the methods from it that I deprecated a few weeks ago.

This is one of those "lets not have 12 ways of doing things just because we accumulated them over the years" initiatives. For the most part the change it super easy and mechanical, it is just that someone has to do them. I've been doing a bunch of them over the past few months but some helpful folks told me last week that I should document my plan for the end state. This is that.

**Comment by lipsill** [comment]
Got it! Thanks! So basically step 3. is to finally remove `Loggers.getLogger(Class)`
I will take over `server` + `server-tests`

**Comment by nik9000** [comment]
> Got it! Thanks! So basically step 3. is to finally remove `Loggers.getLogger(Class)`

Right!



>  I will take over `server` + `server-tests`

Awesome!

**Comment by nik9000** [comment]
Thanks @pratiksanglikar  and @lipsill for doing the heavy lifting here!
