### ISSUE TITLE
Lucene 8 upgrade checklist

### ISSUE THREAD

**Issue by jimczi** [elastic/elasticsearch#32899]
This is a meta issue to track the progress of upgrading master to Lucene 8. The branch can be found [here](https://github.com/elastic/elasticsearch/tree/upgrade/lucene-8). Below is the list of things to be changed/removed for the upgrade:
- [x] Levenstein distance renaming.
- [x] TermContext renaming (TermStates).
- [x] Collectors should implement `scoreMode` instead of `needsScore`. (@jpountz)
- [x] IndexSearcher#createNormalizedWeight has been removed. (@jpountz)
- [x] StandardFilter removal. (@jimczi)
- [x] EarlyTerminatingSortingCollector removal. (@jpountz)
- [x] BoostingQuery removal (replaced with `FunctionScoreQuery#boostByQuery`). (@jimczi)
- [x] Similarity#SimWeight removal. (@jpountz)
- [x] BasicModel removals (`after effects`, `BE`, `D `and `P`). (@jpountz)
- [x] Version#LUCENE_6* removal. (@jimczi #32937)
- [x] TopDocs#totalHits rewriting.
- [x] TopDocs#computeMaxScore replacement
- [x] Explanation#getValue() is a Number instead of a float

#### Test failures
- [x] `PercolateQueryBuilder#createMultiDocumentSearcher`, `PercolatorQuerySearchIT`: @jpountz 
- [x] `FunctionScoreTests#testSimpleWeightedFunction`: produces negative scores (#31927)
- [x] `ScriptedSimilarityTests#testBasics`, `ScriptedSimilarityTests#testInit`: score is called on non-scoring clauses (to get the max score, see ImpactsDISI)
- [ ] `FieldSubsetReaderTests#testFieldNames`, `FieldSubsetReaderTests#testFieldNamesMissing`, `FieldSubsetReaderTests#testFieldThreeFields`: FieldNamesTerms return invalid statistics (e.g. -1) https://github.com/elastic/elasticsearch/pull/33261
- [x] `TransportTwoNodesSearchIT#testDfsQueryThenFetch`, `TransportTwoNodesSearchIT#testDfsQueryThenFetchWithSort`: new explanation format and message

\cc @elastic/es-distributed to sync up.

**Comment by jasontedor** [comment]
Pinging @dnhatn
