### ISSUE TITLE
Java high-level REST client completeness for ILM APIs

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch#33100]
**Note: these APIs are on the `index-lifecycle` branch at the moment so will need to be implemented on that branch until its ready to merge to master, see https://github.com/elastic/elasticsearch/issues/29823**
- [x] Put lifecycle (@gwbrown) https://github.com/elastic/elasticsearch/pull/33250
- [x] Get lifecycle (@gwbrown) https://github.com/elastic/elasticsearch/pull/33323
- [x] Delete lifecycle (@gwbrown) https://github.com/elastic/elasticsearch/pull/33142
- [x] Explain lifecycle (@colings86) https://github.com/elastic/elasticsearch/pull/32606
  - [x] Port to new HLRC structure (@gwbrown) #34922
- [x] Get status (@jakelandis) https://github.com/elastic/elasticsearch/pull/33283
- [x] Start ILM (@colings86) https://github.com/elastic/elasticsearch/pull/32609 
  - [x] Port to new HLRC structure https://github.com/elastic/elasticsearch/pull/34242
- [x] Stop ILM (@colings86) https://github.com/elastic/elasticsearch/pull/32609
  - [x] Port to new HLRC structure https://github.com/elastic/elasticsearch/pull/34242
- ~~Move to step~~ (Not implementing as this is an expert API that should not be called programatically)
- [x] Retry step (@original-brownbear) https://github.com/elastic/elasticsearch/pull/33990
- [x] Remove policy from index (@jdconrad) https://github.com/elastic/elasticsearch/pull/34204
- [x] ~~Set policy for index (@dakrone) https://github.com/elastic/elasticsearch/pull/32443~~ (being removed)
  - ~~Port to new HLRC structure https://github.com/elastic/elasticsearch/pull/34248~~

**Comment by talevy** [comment]
All of the endpoints were implemented, and it is time to focus on documentation https://github.com/elastic/elasticsearch/issues/34935. Closing this issue
