### ISSUE TITLE
ingest: Documentation improvements for ingest node

### ISSUE THREAD

**Issue by jakelandis** [elastic/elasticsearch#33188]
- [x] document the use of `tag` [1] (@jakelandis) https://github.com/elastic/elasticsearch/pull/35091
- [x] call out which field/processors support templating [2] #34536 (@jakelandis)
- [x] raise visibility of the plugin processors [3]  (@jakelandis) https://github.com/elastic/elasticsearch/pull/35048
- [x] default pipeline and index settings [4] #34500 (@jakelandis)
- [x] Pipeline processor : https://github.com/elastic/elasticsearch/pull/33418 (@original-brownbear)
- [x] Processor conditional: https://github.com/elastic/elasticsearch/pull/33388 (@original-brownbear)
- [x] Drop processor #34570 (@jakelandis )
- [x] Additional examples for conditionals. Regex, Drop, Pipelines (@jakelandis) https://github.com/elastic/elasticsearch/pull/35044
- [ ] Calling processors from the script processor. (@jakelandis) 
- [x] Kibana console updates https://github.com/elastic/kibana/pull/24100 and https://github.com/elastic/kibana/pull/24400 (@jakelandis)
- [x] include some mention of `if` and `on_failure` (maybe tag too?) on every processor's doc. https://github.com/elastic/elasticsearch/pull/35091

[1] 
```
POST _ingest/pipeline/_simulate?verbose
{
  "pipeline" :
  {
    "description": "_description",
    "processors": [
      {
        "set" : {
          "tag": "my_set1",
          "field" : "field1",
          "value" : "value1"
        }
      },
      {
        "set" : {
          "tag": "my_set2",
          "field" : "field2",
          "value" : "value1"
        }
      }
    ]
  },
  "docs": [
    {
      "_index": "index",
      "_type": "_doc",
      "_id": "id",
      "_source": {
        "a": "foo-bar",
        "b": "bar"
      }
    }
  ]
}
```

[2]
```
POST _ingest/pipeline/_simulate?verbose
{
  "pipeline": {
    "processors": [
      {
        "set": {
          "field": "field1",
          "value": "{{a}}"
        }
      }
    ]
  },
  "docs": [
    {
      "_index": "index",
      "_type": "_doc",
      "_id": "id",
      "_source": {
        "a": "foo-bar"
      }
    }
  ]
}
```

[3]
https://www.elastic.co/guide/en/elasticsearch/plugins/current/ingest-geoip.html
https://www.elastic.co/guide/en/elasticsearch/plugins/current/ingest-user-agent.html
https://www.elastic.co/guide/en/elasticsearch/plugins/current/ingest-attachment.html
https://www.elastic.co/guide/en/elastic-stack-overview/6.4/field-and-document-access-control.html#set-security-user-processor

[4]
https://github.com/elastic/elasticsearch/pull/32286
https://github.com/elastic/elasticsearch/pull/32591
https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules.html#index-modules-settings

**Comment by tomcallahan** [comment]
This is a great list @jakelandis .  Is this issue a good place for @eskibars to discuss some documentation items as well or do you want to keep this one tightly scoped?

**Comment by jakelandis** [comment]
@tomcallahan @eskibars - please add/discuss at will. This is meant to be more of a meta issue and changes will come in multiple pr's.

**Comment by jakelandis** [comment]
added a few items above. @original-brownbear if you pick up any of these please put your name next to it so we don't collide.

**Comment by original-brownbear** [comment]
Added item for drop processor

**Comment by martijnvg** [comment]
@jakelandis What is the status of this meta issue?

**Comment by jakelandis** [comment]
@martijnvg - thanks for the ping. This can be considered done. The outstanding task was documenting the methods via Painless which is done here: https://www.elastic.co/guide/en/elasticsearch/painless/7.2/painless-api-reference-ingest-org-elasticsearch-ingest-common.html#painless-api-reference-ingest-Processors ...That doc could probably be beefed up some, but for now it is good enough.
