### ISSUE TITLE
[ML-Dataframe] Dataframe Builder Breadcrumbs - A Meta Issue

### ISSUE THREAD

**Issue by hendrikmuhs** [elastic/elasticsearch#33600]
Meta issue for https://github.com/elastic/elasticsearch/tree/feature/fib

Unsorted (and therefore not prioritized), incomplete list of todo's (living document):

#### Must
 - [ ] move actions into xpack.core 
 - [ ] Job robustness 
   - [ ] forgiving parsing (strict on creation and lenient on load)
   - [ ] config validation
     - [ ] SourceConfig
     - [ ] AggregationConfig

#### On hold

- [ ] rename feature
- [ ] how much ML branding?

#### Nice to have

- [ ] HLRC support

**Comment by droberts195** [comment]
I think HLRC support is a must for 7.0 GA, but if this feature is delivered in time for a 6.x release then it's a nice to have in that 6.x release.

**Comment by hendrikmuhs** [comment]
moving into team backlog, closing here
