### ISSUE TITLE
Fix port assignment and discovery in tests

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#33675]
Today when configuring nodes for tests we use a variety of mechanisms to ensure that they can find each other and form a cluster. At least one of these mechanisms is racy, leading to occasional test failures (#29244), and few of them implement our documented recommendation:

> that the unicast hosts list be maintained as the list of master-eligible nodes in the cluster.

The main obstacle to fixing this was the difficulty of dynamically configuring the unicast hosts list in tests.

- [x] Move file-based discovery into core Elasticsearch (#33241)
- [x] Stop using `MockUncasedHostProvider` in most `ESIntegTestCase`s (#33554, #33658)
- [x] Use file-based discovery for forming clusters in `AbstractDisruptionTestCase` (#34461)
- [x] Tidy up settings management in `AbstractDisruptionTestCase`, overriding `nodeSettings` rather than making a separate `NodeConfigurationSource`, and using `ESIntegTestCase` to manage `minimum_master_nodes` etc. (#34808)
- [x] Use file-based discovery for forming clusters of real nodes in REST tests (#34560)
- [x] Prevent tests in 5.6 from binding to port 30210 (see below) (#34955)

In the REST tests, we currently start up one seed node and then have this node as the single host in all other nodes' unicast lists, but this means that the cluster can sometimes form without the seed node knowing about it, and it then cannot ping any of the other nodes to join. Unfortunately these tests include BWC ones so we can only reasonably make this change in `master` once 6.5 is released, or else we will be trying to configure nodes that do not natively support file-based discovery.

The racy one is the AbstractDisruption test case, which attempts to find a free port by binding to it, then releasing it, and then telling the node to use that, and for some reason port 30210 is occasionally in use by something else. It really does seem to be just this port that causes issues, and we don't want to backport all this work to 5.6, but we do want to avoid test failures like this in 5.6, so let's just avoid this particular port in that branch.

**Comment by original-brownbear** [comment]
@DaveCTurner all points handled I think :) Good to close here?

**Comment by DaveCTurner** [comment]
Yes, all done.
