### ISSUE TITLE
Java high-level REST client completeness for CCR APIs

### ISSUE THREAD

**Issue by hub-cap** [elastic/elasticsearch#33824]
- [x] Put Follow API #35409
- [x] Pause Follow API #35216
- [x] Resume Follow API #35638
- [x] Unfollow API #35693
- [x] Put Auto Follow Pattern API #35780
- [x] Get Auto Follow Pattern API #36049
- [x] Delete Auto Follow Pattern API #35981
- [x] CCR Stats API #36213
- [x] CCR Follow stats API #36253
