### ISSUE TITLE
Replicate closed indices

### ISSUE THREAD

**Issue by tlrx** [elastic/elasticsearch#33888]
Closed indices currently have the downside that they are not replicated, so it's possible for an index to be closed, then the data lost because the node was terminated without saving the data.

We'd like to be able to close indices to remove any memory overhead of them, but still have the indices available for replication.

Steps to accomplish this (not necessarily in order):

Routing Table
- [x] Keep closed indices in the routing table and reinitialize shards when closing an index (#38024)
- [x] Add the no op engine (from #31141) and plug it as the default engine for closed index shards (#33903)
- [x] Change the Gateway service to create routing table also for closed indices (#39249)
- [x] Adapt the Synced Flush Service to work when routing table exist for closed indices (#37691)
- [x] Ignore shard started requests when primary term does not match (#37899)
- [x] Change IndexService so that it does not instantiates a mapper service/ index analyzers for closed indices (#40423)

Open/Close Index APIs
- [x] Close Index API should wait for closed shards to be started after an index is closed (#38854 )
- [x] Before closing an index, the Close Index API should mark the index as read-only, wait for replication operations to be terminated, flush the index and then close it (#36354). It requires:
- [x] Change IndexShardOperationPermits.asyncBlockOperations to use an action listener with a Releasable (#34902)
- [x] Add methods to IndexShard that allow to acquire all index operations permits (#35540)
- [x] Transport Replication Action must check blocks while having the index operation permit (#35332, #35795, #36116)
- [x] Add new type of TransportReplicationAction that can acquire all index operations permits during execution (#36249)
- [x] Add unique id to cluster block (#36775)
- [x] Release fresh listeners created by `?refresh=wait_for` when close indices or relocating shards (#36835)
- [x] Close Index API should force a flush if a sync is needed (#37961)
- [x] Close Index API should issue a synced-flush so recoveries can be noop (#41400)
- [x] Remove index routing table of closed indices in mixed versions clusters (#38955)
- [x] What if the primaries are not all allocated? The verification step cannot go through or shards might not be properly flushed. Should we close the close index API? Should we allocate an empty routing table that cannot be allocated at all? (#40867) Perhaps add a "force" option to close index API so that by default the closing fails on unallocated primaries, but is ignored when explicitly forcing it. (We discussed this during GAH and agreed not to make this change. Users can reopen the closed index in this case).
- [x] Improve Close Index and Freeze Index responses to report acknowledgments and shard failures per indices (and adapt High Level Rest client) (https://github.com/elastic/elasticsearch/pull/39687) (We still need to adopt this enhancement in HLRC).
- [x]  Flush shard at the end of recovery (so that newly recovered replica shard that are not yet in the in-sync allocations ids have 0 operations in translog if they are later opened as frozen) and add a test that closes an index under complex situations (e.g. network partitions) and checks that we can always allocate a "closed" or "frozen" primary. This is also the case with relocating shards (see https://github.com/elastic/elasticsearch/pull/37348#discussion_r247082240) (https://github.com/elastic/elasticsearch/pull/41660)

Engine/Translog
- [x] Add NoOpEngine as engine implementation to use for closed shards (#33903)
- [x] Ensure that max seq # is equal to the global checkpoint when creating ReadOnlyEngines(#37426)
- [x] Relax NoOpEngine constraints on translog (#37413)
- [x] ReadOnlyEngine should update translog recovery state information (#39238)
- [x] Should we clean/trim the translog when an index is closed?  (https://github.com/elastic/elasticsearch/issues/42445)
- [x] Should we enforce a single index commit when an index is closed? (see [comment](https://github.com/elastic/elasticsearch/pull/38024/files#r252732420)) (https://github.com/elastic/elasticsearch/issues/42445)

Tests
- [x] Add test for peer recovery of closed shard (#38421)
- [x] Add test for replica-to-primary promotion of closed shard (#39110)
- [x] Add test for closed indices and full cluster restart (#39249)
- [x] Add test for closed indices and shard allocation filtering/awareness (#39186)
- [x] Add test for closed indices and Cluster Reroute API (#39186) (#38421)
- [x] Test restoring a snapshot into a closed index
- [x] Handle rolling upgrade from a version of ES that does not allocated closed indices to a version that does (maybe just an allocation decider that prevents the closed index shards to be assigned as long as all node are not on the current version?)
- [x] Adapt IndexShardIT.testIndexCanChangeCustomDataPath() to closed indices (#38327)
- [x] Adapt IndicesServicesTests.testPendingTasks() to closed indices (#38326)
- [x] Test the Cluster Shard Allocation Explain API with closed indices (#38631)
- [x] Test that the "direct close" method still work in 7.x (removed in 8.0 with #38955, see https://github.com/elastic/elasticsearch/pull/38955/files#r257718054)

Others
- [x] Cluster Reroute API and force allocation of closed primary shard (#42458)?
- [x] Cluster Health API and closed indices (#39364)
- [x] Recovery API and closed indices (#38421)
- [x] Indices Stats for closed indices will report 0 docs for closed indices/shards (#34079 #39698)
- [x] TransportUnfollowAction should increase settings version (#37859)
- [x] Freezing an index should increase its index settings version (#37813)
- [x]  RestoreService should update primary terms when restoring shards of existing indices (#38177)
- [x] Do not schedule refresh/translog fsync/translog trim/globalcheckpoint sync tasks for closed indices (#38329)
- [x] Investigate the behavior of retention leases sync task with replicated closed indices (see https://github.com/elastic/elasticsearch/pull/38329#discussion_r255407823) (won't do)
- [x] Closing an index was sometimes used to change the custom data path setting (see #38327) but with replicated closed indices it means copying files of a live index. We can maybe extend the shrink/split API to do this instead or maybe just don't support changing the setting. (We discussed and agreed not to implement this feature for now given its complexity. We will revisit it in the future.)
- [x] Investigate how to snapshot closed indices (#39644)
- [x] How to integrate closed replicated indices with closed follower indices (see https://github.com/elastic/elasticsearch/pull/38767#issuecomment-463095506) (https://github.com/elastic/elasticsearch/issues/42442)
- [x] GlobalCheckpointSyncAction triggers some warnings in logs after a replica to primary promotion. Should we just prevent maybeSyncGlobalCheckpoint() to be executed if the shard is closed? (#41874)

**Comment by dnhatn** [comment]
> Investigate the behavior of retention leases sync task with replicated closed indices

We don't have to run AsyncRetentionLeaseSyncTask for closed indices:
- We won't trim anything if an index is closed regardless of the state of its retention leases.
- If a retention lease gets expired when an index is closed, that lease should also be expired when an index is reopened and synced across all copies in peer recovery; thus all shard copies should expunge that expired lease.
- A leader index requires to be open. Thus, follower indices won't renew (i.e., advance) its leases on the leader if the leader index is closed.

**Comment by dnhatn** [comment]
> GlobalCheckpointSyncAction triggers some warnings in logs after a replica to primary promotion. 

GlobalCheckpointSyncAction that generates warning logs is triggered by primary-replica resync on a new primary promotion. The primary-replica resync action does not perform the reroute phase; hence bypass both closed -block and closed-state check. It's safe to run or skip primary-replica resync action for a closed index for it's a noop (ReadOnlyEngine returns empty translog snapshots).

> Should we just prevent maybeSyncGlobalCheckpoint() to be executed if the shard is closed?

I opened #41874. Another option is to make GlobalCheckpointSyncAction skip Reroute Phase.

**Comment by dnhatn** [comment]
I am closing this meta-issue given all items are completed or spun off (https://github.com/elastic/elasticsearch/issues/42442 and https://github.com/elastic/elasticsearch/issues/42445) . All kudos to @tlrx for hist great job 🎉.
