### ISSUE TITLE
[ML] Remove hard limit for maximum forecast interval 

### ISSUE THREAD

**Issue by hendrikmuhs** [elastic/elasticsearch#34054]
Forecasts are limit to a maximum of `8 weeks`, this limit has been put into place early. Meanwhile several improvements have been made, so we are confident to remove this limitation.

In order to remove the limit, these changes are required:

 - [x] ml-cpp: https://github.com/elastic/ml-cpp/pull/214 (@tveasey)
 - [x] elasticsearch: https://github.com/elastic/elasticsearch/issues/41103 (@przemekwitek)
 - [x] Kibana: https://github.com/elastic/kibana/issues/22681 (@peteharverson)

**Comment by hendrikmuhs** [comment]
implemented and merged, target release: 7.1
