### ISSUE TITLE
Per index data path setting

### ISSUE THREAD

**Issue by jkakavas** [elastic/elasticsearch#34446]
We should document the settings that enable setting a per index data path

Tasks:

- [ ] Revisit the implementation of per index data paths (from shadow replicas) and the name of the current setting (`path.shared_data`)
- [ ] Document the use of the setting outside the context of shadow replicas.
- [ ] Document and publicize use cases that take advantage of the setting ( i.e. satisfying the per index encryption use case )

**Comment by jrodewig** [comment]
[docs issue triage]

Leaving open. This is still relevant.

**Comment by gwbrown** [comment]
Marking this `team-discuss` to discuss whether, when, and how this should be addressed. Last I was aware, there were ongoing questions surrounding multiple data paths.

**Comment by jasontedor** [comment]
@gwbrown This is separate from multiple data paths. This about allowing a custom data path per index, but note that they must be a sub-directory of a common path (`path.shared_data`).

**Comment by bytebilly** [comment]
I think we should discuss our plans for this feature sooner than later, as it is currently our "suggested" way to provide per-index encryption-at-rest, but customers are not fully comfortable since it's not documented and officially supported.

As far as I know, there are also other implications to consider, for example that the translog is not stored in that folder and so it is not encrypted with the per-index key.

**Comment by bytebilly** [comment]
As agreed in the Core/Infra weekly, this issue should be discussed with the broader Elasticsearch team.

**Comment by henningandersen** [comment]
Notice that properly supporting shared path/custom data path settings also requires changes to the disk allocation decider and monitor. These currently do not properly handle these extra paths. This can cause several issues, at least:
* Running out of disk space on one of the custom paths.
* Over filling a node, since it looks empty on its regular data paths.
 I wonder if folder level encryption could suffice? Such that we can let the custom data paths exist under the regular data path rather than a separate one.

**Comment by rjernst** [comment]
We plan to remove the per index data path. You can read about the reasoning in the meta issue: https://github.com/elastic/elasticsearch/issues/73168. Given that, I'm going to close this issue.
