### ISSUE TITLE
HLRC XPack protocol clean up

### ISSUE THREAD

**Issue by vladimirdolzhenko** [elastic/elasticsearch#34451]
Relates to XPack HLRC [#29827](https://github.com/elastic/elasticsearch/issues/29827)

There are some requests/responses in **xpack protocol**, while most requests/responses are in **client/rest-high-level** (proper place)

Move ( + clean up ) HLRC located at [xpack protocol](https://github.com/elastic/elasticsearch/tree/master/x-pack/protocol/src/main/java/org/elasticsearch/protocol/xpack) to [client/rest-high-level](https://github.com/elastic/elasticsearch/tree/master/client/rest-high-level/src/main/java/org/elasticsearch/client)

Note: In most cases everything is there, except maybe some tests like _RequestConvertersTests_ and unit tests.

- [x] Watcher API #34639, #34964
  -  put watch 
  -  delete watch 
- [x] Miscellaneous API #34469
  - xpack info
  - xpack usage
- [x] Graph API  #34639, #34964
  - graph explore 
- [x] Licensing API #34469
  - put license
  - get license
  - delete license
- [x] Drop protocol module  #34639, #34964
- [x] cross XPack HLRC compatibility tests #34547 , #35129
- [ ] migrate other XPack request / responses tests to a new cross XPack HLRC compatibility approach

Clean up assumes don't extend `AcknowledgedRequest`, `readFrom(StreamInput in)` / `writeTo(StreamOutput out)`

**Comment by hub-cap** [comment]
I think it would be good to also clean up the existing actions we moved from, for instance, we tended to add some XContent methods to the existing request/response that are not needed, so lets try to also revert the history of the moved code in the x-pack directory to something that was before we started the migration.

**Comment by hub-cap** [comment]
This can be closed as we will likely not modify them, and instead wait to do the work of generation of the code.
