### ISSUE TITLE
[Painless] Context Doc Examples

### ISSUE THREAD

**Issue by jdconrad** [elastic/elasticsearch#34829]
Painless has some basic documentation for contexts at https://www.elastic.co/guide/en/elasticsearch/painless/master/painless-contexts.html .  Each context has a separate page that describes the what variables are available to a Painless script such as `doc` and `params`.  These contexts each need to be reviewed by someone familiar with the related code and have one or more examples added.

There is a data set for examples already available for download and steps to setup the an ES cluster with that data set at https://www.elastic.co/guide/en/elasticsearch/painless/master/painless-context-examples.html .  For consistency it would be ideal if any examples generated were based on this data set and the contexts put in order of dependency within the index contexts page.  (Ingest needs to go first.)  Each example also has a test along with the curl commands as comments in the ContextExampleTests under Painless.

Several contexts have changed recently and will need to updated to reflect those changes such as `search` -> `score`.

The following contexts need review and/or examples:
* [x] ingest (https://www.elastic.co/guide/en/elasticsearch/painless/master/painless-ingest-processor-context.html) @jdconrad (#32302) (This could an expert review of the available variables still.)
* [ ] reindex (https://www.elastic.co/guide/en/elasticsearch/painless/master/painless-reindex-context.html) @jdconrad (#34024) (This could an expert review of the available variables still.)
* [x] update (https://www.elastic.co/guide/en/elasticsearch/painless/master/painless-update-context.html) @rjernst (#37943)
* [x] update by query (https://www.elastic.co/guide/en/elasticsearch/painless/master/painless-update-by-query-context.html) @rjernst (#37943)
* [x] sort (https://www.elastic.co/guide/en/elasticsearch/painless/master/painless-sort-context.html) @romseygeek
* [x] similarity (https://www.elastic.co/guide/en/elasticsearch/painless/master/painless-similarity-context.html) @romseygeek
* [x] weight (https://www.elastic.co/guide/en/elasticsearch/painless/master/painless-weight-context.html) @romseygeek
* [x] score (https://www.elastic.co/guide/en/elasticsearch/painless/master/painless-score-context.html) @romseygeek
* [x] field (https://www.elastic.co/guide/en/elasticsearch/painless/master/painless-field-context.html) (#35130) @mayya-sharipova 
* [x] filter (https://www.elastic.co/guide/en/elasticsearch/painless/master/painless-filter-context.html) (#35305) @mayya-sharipova 
* [x] minimum should match (https://www.elastic.co/guide/en/elasticsearch/painless/master/painless-min-should-match-context.html) (#35423) @mayya-sharipova 
* [ ] metric aggregation initialization/map/combine/reduce (https://www.elastic.co/guide/en/elasticsearch/painless/master/painless-metric-agg-init-context.html) @polyfractal 
* [x] bucket script aggregation (https://www.elastic.co/guide/en/elasticsearch/painless/master/painless-bucket-agg-context.html) (#35142) @polyfractal 
* [x] bucket_selector aggregation (https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-pipeline-bucket-selector-aggregation.html) (#35162) @polyfractal
* [ ] general aggregation script @andyb-elastic  
* [ ] watcher condition (https://www.elastic.co/guide/en/elasticsearch/painless/master/painless-watcher-condition-context.html) @hub-cap
* [ ] watcher transform https://www.elastic.co/guide/en/elasticsearch/painless/master/painless-watcher-transform-context.html @hub-cap

**Comment by nik9000** [comment]
Do you think we should document these contexts along side the documentation for the API that they are used in?

**Comment by rjernst** [comment]
We should probably at least cross link.

**Comment by jdconrad** [comment]
I would strongly prefer cross-links here as the examples will have possibly depend on each other so that users can fire up a cluster and run through them like a tutorial.  This way each page can come in order.  And while Painless is the primary language now for most of these, there are other languages too, so I would like to keep this as part of the Painless docs.

**Comment by jdconrad** [comment]
Closing this as there are examples for the majority of contexts as this point.
