### ISSUE TITLE
Remove checkstyle line length suppressions

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#34884]
We've carried these suppressions around for a long time, so this is a meta issue to track removal of the suppressions

They are roughly separated into the following packages (when you assign one, please do the work for both master and 6.x branches):

- [x] org.elasticsearch.action.admin.cluster @tomcallahan #35156 
- [x] org.elasticsearch.action.admin.indices @gwbrown #34890
- [x] org.elasticsearch.action.bulk/delete/explain/get/index @jakelandis #34885
- [x] org.elasticsearch.action.ingest @jdconrad https://github.com/elastic/elasticsearch/pull/34886
- [x] org.elasticsearch.action.support @not-napoleon #34924 and #34889
- [x] org.elasticsearch.action.* (other than the above) @dakrone #35607
- [x] org.elasticsearch.cluster @rjernst #34923, #34941
- [x] org.elasticsearch.common @dakrone #34888
- [x] org.elasticsearch.bootstrap/client/discovery/gateway @imotov #34905
- [x] org.elasticsearch.index.fielddata @original-brownbear #34891, #34919
- [x] org.elasticsearch.index.mapper @vladimirdolzhenko #35087 , #35101
- [x] org.elasticsearch.index.* (the rest other than `fielddata` and `mapper`) @jimczi #35652
- [x] org.elasticsearch.indices @martijnvg #35647
- [x] org.elasticsearch.search @jpountz  #36223
- [x] leftovers @gwbrown https://github.com/elastic/elasticsearch/pull/35650
- [x] org.elasticsearch.node @dliappis  https://github.com/elastic/elasticsearch/pull/37454
- [x] org.elasticsearch.repositories @rjernst (#36735)
- [x] org.elasticsearch.snapshots @pgomulka https://github.com/elastic/elasticsearch/pull/36646
- [x] org.elasticsearch.threadpool @jdconrad (#37205)
- [x] org.elasticsearch.VersionTests @danielmitterdorfer https://github.com/elastic/elasticsearch/pull/36585
- [x] org.elasticsearch.aliases @dliappis https://github.com/elastic/elasticsearch/pull/37455
- [x] org.elasticsearch.deps @atorok (#36708)
- [x] org.elasticsearch.env @ebadyano (#36657)
- [x] org.elasticsearch.explain @rjernst (#36735)
- [x] org.elasticsearch.get @pgomulka (https://github.com/elastic/elasticsearch/pull/37071)
- [x] org.elasticsearch.indexing @jdconrad (#37205)
- [x] org.elasticsearch.indexlifecycle @danielmitterdorfer https://github.com/elastic/elasticsearch/pull/36586
- [x] org.elasticsearch.monitor @dliappis https://github.com/elastic/elasticsearch/pull/37456
- [x] org.elasticsearch.plugins @atorok (#36708)
- [x] org.elasticsearch.recovery @ebadyano (#36657)
- [x] org.elasticsearch.rest @rjernst (#36735)
- [x] org.elasticsearch.routing @pgomulka (https://github.com/elastic/elasticsearch/pull/37253)
- [x] org.elasticsearch.script @jdconrad  (#37205)

**Comment by colings86** [comment]
Please remember to add relevant labels to all issues created. At the very least this should include an area label since without and area label issues may fall through the cracks and be missed by teams

**Comment by danielmitterdorfer** [comment]
Closing as all related PRs have been merged now.
