### ISSUE TITLE
OpenID Connect realm support

### ISSUE THREAD

**Issue by jkakavas** [elastic/elasticsearch#35339]
This issue tracks the effort to offer an OpenID Connect authentication realm in Elasticsearch. 

Relevant specifications:
- [OpenID Connect core](http://openid.net/specs/openid-connect-core-1_0.html)
- [OpenID Connect dynamic registration](http://openid.net/specs/openid-connect-discovery-1_0.html)
- [Implementer's drafts](https://openid.net/developers/specs/)

Elasticsearch will implement and OpenID Connect Relying Party (RP). The initial idea is that this will be handled in a similar way to the SAML Authentication realm where
- Elasticsearch will implement all the necessary OpenID Connect related functionality
- Elasticsearch will expose the necessary REST API endpoints
- Users will be able to authenticate with OIDC via a _facilitator_ which can be Kibana (in which case the Elastic stack is the RP) or a custom web application
- At the successful completion of an OIDC flow, Elasticsearch will exchange the OIDC ID token it receives from an OIDC Provider with an Elasticsearch token that can be used to authenticate future requests to Elasticsearch. 

Tasks :

- [x] Support for oAuth2 implicit flow ( as a client )
- [x] Support for oAuth2 authorization code flow ( as a client )
- [x] Support client (ES) authentication.
- [x] Support ~OP discovery~ and static OP configuration
- [x] `JWS` and `JWE` support
- [x] OIDC Rest endpoints for _facilitator_ communication 
- [x] ID token parsing and validation
- [x] Support for requests to the `userinfo` endpoint
- [x] Map claims to attributes ( and thus roles )
- ~Submit request for the OpenID Foundation [conformance certification](https://openid.net/certification/rp_testing)~
- ~Support dynamic registration with an OP~

**Comment by jkakavas** [comment]
Implemented in https://github.com/elastic/elasticsearch/pull/40674
