### ISSUE TITLE
Deprecate X-Pack centric REST endpoints

### ISSUE THREAD

**Issue by jasontedor** [elastic/elasticsearch#35958]
We want to remove `_xpack` from our REST endpoints that currently have this as part of their path. We will deprecate these endpoints in 7.0.0 and remove them in 8.0.0. This is a meta-issue to track progress on deprecating these endpoints:
 - [x] cross-cluster replication APIs (never released with `_xpack`) @jasontedor #32563
 - [x] deprecation APIs (ha!) @gwbrown #35976
 - [x] graph APIs @jasontedor #36010
 - [x] index lifecycle management APIs (never released with `_xpack`) @jasontedor #32564
 - [x] license APIs @jasontedor #35959
 - [x] machine learning APIs @droberts195 #36315
 - [x] monitoring APIs @jakelandis #36130
 - [x] rollup APIs @jasontedor #35962 
 - [x] security APIs @jkakavas #36293
 - [x] SQL APIs @jasontedor #35964
 - [x] watcher APIs @hub-cap #36218

**Comment by lcawl** [comment]
Is the following API also deprecated?: https://www.elastic.co/guide/en/elasticsearch/reference/master/info-api.html

**Comment by jasontedor** [comment]
@lcawl I was not planning to deprecate those, as I am not sure what we would replace them. I am open to suggestions, but for now those endpoints are for getting information about X-Pack functionality as a whole, to which we are still using the "X-Pack" to refer to (the source code folder too).

**Comment by jasontedor** [comment]
Thank you everyone for the help!

**Comment by ycombinator** [comment]
Hey @jasontedor, if we extrapolate our [Beats-ES compatibility matrix](https://www.elastic.co/support/matrix#matrix_compatibility) to 7.0.x+, it looks like we would allow users to run Beats 7.0.x with ES 6.7.x. Given that, we can't replace the deprecated X-Pack endpoints in Beats code in 7.0.0 unless those endpoints are deprecated in ES 6.7.0 as well. So do you think we should backport the ES deprecation PRs linked off this issue to 6.x as well?

Related: https://github.com/elastic/beats/pull/9656

**Comment by droberts195** [comment]
> Given that, we can't replace the deprecated X-Pack endpoints in Beats code in 7.0.0 unless those endpoints are deprecated in ES 6.7.0 as well

Did you mean _available_ in ES 6.7.0 rather than deprecated in ES 6.7.0?

I think for most components they are available, albeit undocumented.  For example, #36373 for ML, #36379 for security, #36269 for watcher.  Do you need any others?

**Comment by ycombinator** [comment]
You are right indeed. The new APIs being available in 6.7.0 is sufficient. I checked the Beats codebase for which X-Pack APIs we're using and all of their new cousins exist in 6.7.0 already. So nothing to do here. Thanks!

**Comment by ycombinator** [comment]
@droberts195 In my previous comment I said:

> I checked the Beats codebase for which X-Pack APIs we're using and all of their new cousins exist in 6.7.0 already

However, it appears I missed one newer API endpoint. Evidently the `POST _license/start_trial` API isn't available in 6.7.0. Any chance we could make this available?

**Comment by jkakavas** [comment]
It would most probably make sense to add support for all license related endpoints. I can take this up for 6.7.0 if you can can open an issue about it @ycombinator (so that I don't forget :) )

**Comment by ycombinator** [comment]
@jkakavas Thanks! Here's the issue: https://github.com/elastic/elasticsearch/issues/37139
