### ISSUE TITLE
Implement CCR bootstrap from remote

### ISSUE THREAD

**Issue by tbrooks8** [elastic/elasticsearch#35975]
# CCR Bootstrap from Remote

## Pre-feature freeze

- [x] Create a `CcrRepository` for each remote cluster
	* Do we want to store in cluster state? An alternative option would be to introduce “internal repositories” that are not stored in the cluster state and are local to a node. #36086 prototypes storing the repository in the cluster state.
	* How do we handle name conflicts with installed user repositories?
	* How do we ensure consistency across nodes if we go with the internal repository route?
	* If we go with internal repository route, we do want to provide any introspection capabilities for end users?
- [x] Initialize `CcrRepositorys` based on settings at node start.
- [x] Initialize empty shards through `Repository#restoreShard`.
- [x] Add restore source service for leader cluster to hold state about in-progess restores. (#36578)
- [x] Initialize restore session on leader when we start restoring a shard. (#36578)
	* This restore session will need to have hooks to be cleaned up when the restore is complete. 
- [x] Implement local timeouts on leader to clean-up resources used by in-progess restores. (#37438)
- [x] Handle the failure of the leader primary shard during a restore and clean-up resources on leader (#36578)
- [x] Ensure `CcrRepository` restore works with security enabled (#37508)
	* Currently the repository is performing requests under the system context. Any actions that are proxy actions will be rejected using this context.
- [x] Route `PutFollowAction` through the `RestoreService` using the `CcrRepository`.
	* #35719 prototypes this work
- [x] Determine `PutFollowAction` semantics regards whether it should wait for restore to complete. (#35719 )
- [x] Determine how we want to handle pause follow actions
	* No action needed
- [x] Allow multiple concurrent restores. (#36397)
- [x] Ensure that the mapping versions are kept in-sync with the leader during a restore. (#36879)
	* The `ShardFollowTasksExecutor` and `ShardFollowNodeTask` have existing mechanisms for followers to update mapping versions as the leader mappings change.
- [x] Implement a transport mechanism to direct a request to a specific node on the remote cluster. (#36805) 
	* This functionality is not currently exposed on the remote client.
	* It is necessary for the request for a file chunk and to delete the session. We do not want to route the file chunks through an intermediate node if possible.
- [x] Restore the shards by fetching files from the leader cluster (#37130)
- [x] Recycle byte arrays on file transfer (#37130)
- [x] Potentially add rate-limiting for the restore similar to what we do in the blob store repository.
	* Follower side (#37449)
	* Leader side (#37677)
- [x] Add a test that a follower can be closed and `put` again if it falls behind (#38236)

## Post-feature freeze

- [x] Set an increased master node timeout on the call to update mappings. (#38439)
- [x] Implement timeouts or retry policy on the follower
	* Individual action timeouts (#37840)
- [x] Ensure that we have mixed version tests (#38277)
- [x] Look into how we do BWC logic. Currently we only allow the restore if the follower master is the same version or higher as the highest versioned leader data node.
	* Add test that we disallow `PutFollowAction` and throw exception if leader cluster is on higher version than follower (#38277)
	* Related issue #39230
- [x] Document `ccr.indices.recovery.max_bytes_per_sec` (#39483)
- [x] Document `ccr.indices.recovery.recovery_activity_timeout` (#39483)
- [x] Document `ccr.indices.recovery.internal_action_timeout` (#39483)
- [x] Document `ccr.indices.recovery.chunk_size` (#39483)
- [x] Document `ccr.indices.recovery.max_concurrent_file_chunks` (#39483)
- [x] Document behavior about an index falling behind (#39936)
- [x] Considering splitting `overview` docs information into a mechanics of replication page.
- [x] Considering moving information about leader index falling behind into troubleshooting.
- [x] Determine the ideal buffer size for file transfers.
	* In the original PR, we are using 64KB. But his is something that probably should be benchmarked.
	* #38370 changes this to 1 MB and makes it configurable as we determine the best approach.
- [ ] Determine what types of connections we want to use for recovery
	* 6 connections of type `TransportRequestOptions.Type.REG, TransportRequestOptions.Type.PING`. The recovery actions use the `REG` channel type. However, we do support dedicated `RECOVERY` channel types. We could consider adding `RECOVERY` channels to the remote cluster connection profile and use those.

**Comment by tbrooks8** [comment]
My work does not currently included any new external APIs. The recovery from remote is implemented as a normal recovery (through a repository). There are pre-existing apis for recoveries: https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-recovery.html.

If we need new APIs for information, that work still needs to be scoped out and those discussions should include people like @ywelsch and @jasontedor. My work primarily involves transferring segment files from the leader to the follower through our existing recovery infrastructure.

**Comment by sebelga** [comment]
@tbrooks8 thanks for clarifying. This sounds like something to add in the detail panel of _Index Management_ under the Summary tab. What do you think @bmcconaghy @yaronp68 ?

**Comment by ywelsch** [comment]
@tbrooks8 can you check what remains to be done here so that we can close this issue?
