### ISSUE TITLE
Update Deprecation Info API for 7.0 breaking changes

### ISSUE THREAD

**Issue by gwbrown** [elastic/elasticsearch#36024]
The Deprecation Info API should be updated to check for breaking changes coming in the next major version.

Here is a list created by looking through the breaking changes list in the docs and `>breaking` PRs.  I have not verified each one of these, it will likely be necessary to add and/or remove items from this list.

## Cluster
* [x] `:` is no longer allowed in the cluster name (change in #26247) https://github.com/elastic/elasticsearch/pull/36185
* [] ~Shard preferences `_primary`, `_primary_first`, `_replica`, and `_replica_first` are removed (change in #26335)~
[^^ This is a query-time parameter]
* [x] Cluster-wide shard soft limit (change in #34892)
* [x] Renamed no-master-block setting (changes in https://github.com/elastic/elasticsearch/pull/38350) https://github.com/elastic/elasticsearch/pull/38383

## Indices
* [x] Check for multiple types in indices created in 5.x, as this prevents automatic reindexing (see https://github.com/elastic/elasticsearch/issues/35190) https://github.com/elastic/elasticsearch/pull/36952
* ~[] `standard` token filter removal (does this need a check?) (change in #33310)~
[^^ this does not need a check, as it is special-cased in 7.0 for indices created in 6.x and this token filter is a no-op anyway]
* [x] `delimited_payload_filter` renamed (changes in #27705) #27704
* [x] `:` is no longer allowed in index name (change in #26247) https://github.com/elastic/elasticsearch/pull/36185
* [x] `index.unassigned.node_left.delayed_timeout` may no longer be negative (change in #26828) (#36454)
* [x] `fix` value for `index.shard.check_on_startup` is removed (change in #33194) (#36458)
* ~[] `index_options` for numeric fields has been removed (change in #26668)~
[^^ this does not need a check as indices with `index_options` on numeric fields behave fine in 7.0 if they existed prior to upgrade]
* [] ~Limiting the number of `nested` json objects (?) (change in #27405)~
[^^ can't check this without running a query]
* [x] The `classic` similarity has been removed (change in #29187) https://github.com/elastic/elasticsearch/pull/36577
* [] ~Similarities fail when unsupported options are provided (change in #29187)~
[^^ this does not need a check as indices with unsupported similarity options behave fine in 7.0 if they existed prior to upgrade]
* [x] Deprecated `index.percolator.map_unmapped_fields_as_string` setting has been removed (changes in #28060) https://github.com/elastic/elasticsearch/pull/36460

## Nodes
* [x] Azure Repository plugin settings changes
* [x] Google Cloud Storage Repository plugin settings changes
* [x] File-based discovery plugin removed and path changed (changes in #33257) https://github.com/elastic/elasticsearch/pull/36190
* [] ~The default for `node.name` is now the hostname (changes in #33677)~ 
[^^ There doesn't appear to be a way to check this one]
* [x] Tribe node has been removed (changes in  #28443) https://github.com/elastic/elasticsearch/pull/36240
* [x] Http enabled setting removed (changes in #29601) #36394
* [x] Settings `thread_pool.index.size` and `thread_pool.index.queue_size` have been removed (changes in #29556) https://github.com/elastic/elasticsearch/pull/36520
* [x] Http pipelining setting removed (changes in #30695) https://github.com/elastic/elasticsearch/pull/36521
* [x] Audit logfile local node info settings removed (changes in #35205) https://github.com/elastic/elasticsearch/pull/36661
* [x] Write threadpool fallback removed (changes in #29609) https://github.com/elastic/elasticsearch/pull/36662
* [x] Security realms type setting removed (changes in #30241) https://github.com/elastic/elasticsearch/pull/36664
* [x] Discovery configuration is required in production (changes in #36215) https://github.com/elastic/elasticsearch/pull/36666
* [x] Watcher Notifications Account "unsecure" settings removed (changes in #36736 and #36403)  https://github.com/elastic/elasticsearch/pull/36907
* [x] SSL setting fallback removed (Changes in https://github.com/elastic/elasticsearch/pull/36846) #36847
* [x] TLS 1.0 removed from default protocols list (Changes in https://github.com/elastic/elasticsearch/pull/37512) #37793
* [x] User-Agent ingest plugin alignment with ECS (changes in https://github.com/elastic/elasticsearch/pull/37727) https://github.com/elastic/elasticsearch/pull/38362
* [x] Security is no longer implicitly enabled on trial licenses https://github.com/elastic/elasticsearch/pull/38295

**Comment by joshdover** [comment]
@gwbrown Will you be updating the [Migration Assistance API](https://www.elastic.co/guide/en/elasticsearch/reference/master/migration-api-assistance.html) as part of this as well or is that separate?

As it stands right now, I'm not sure we need this API going forward. Since the Deprecation Info API provides information about indexes that need to be reindexed and as far as I know, there won't be any internal indices requiring upgrade through the [Migration Upgrade API](https://www.elastic.co/guide/en/elasticsearch/reference/master/migration-api-upgrade.html) in the 7.0 upgrade, it seems like maybe we should remove this two APIs completely?

Whether or not we remove them, I will need to know whether or not we anticipate any useful data coming from these in 6.7 or not. If not, I'd like to drop our usage of them completely in Kibana to simplify things quite a bit.

**Comment by gwbrown** [comment]
All items on the checklist above are complete, but I'm going to leave this issue open for another day or two just in case, even though I believe we're past the point of adding more. I'll continue to monitor for any new breaking changes and close this in a few days if nothing comes up.

**Comment by gwbrown** [comment]
Closing this as nothing else has come up.
