### ISSUE TITLE
Disable TLSv1.0 by default

### ISSUE THREAD

**Issue by jaymode** [elastic/elasticsearch#36021]
TLSv1.0 is an older protocol that has known security issues. Given the age of this protocol and support for TLSv1.1 and TLSv1.2, we should disable TLSv1.0 by default. A user will still be able to enable TLSv1.0 if they have a need for this.

As part of this, in 6.x we need to provide a deprecation warning when a connection is made with the TLSv1.0 protocol.

---

**Tasks**
- [x] Revmoe TLS 1.0 from defaults in 7.0 #37512
- [x] Add deprecation warnings / logs if TLS 1.0 is used in 6.x #37788
- [x] Add TLS 1.0 warning to deprecation / migration API #37793

**Comment by tvernum** [comment]
Resolved in #37512, #37788,  #37793
