### ISSUE TITLE
Use scheduleUnlessShuttingDown when appropriate

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#36318]
Today we catch `ESRejectedExecutionException` in the following files:
- [ ] [InternalClusterInfoService](https://github.com/elastic/elasticsearch/blob/afeb3992b3bfc8587de7d1acd074b9efeb3ac775/server/src/main/java/org/elasticsearch/cluster/InternalClusterInfoService.java)
- [ ] [ClusterApplierService](https://github.com/elastic/elasticsearch/blob/afeb3992b3bfc8587de7d1acd074b9efeb3ac775/server/src/main/java/org/elasticsearch/cluster/service/ClusterApplierService.java)
- [ ] [MasterService](https://github.com/elastic/elasticsearch/blob/afeb3992b3bfc8587de7d1acd074b9efeb3ac775/server/src/main/java/org/elasticsearch/cluster/service/MasterService.java)
- [ ] [EsThreadPoolExecutor](https://github.com/elastic/elasticsearch/blob/afeb3992b3bfc8587de7d1acd074b9efeb3ac775/server/src/main/java/org/elasticsearch/common/util/concurrent/EsThreadPoolExecutor.java)
- [ ] [MasterFaultDetection](https://github.com/elastic/elasticsearch/blob/afeb3992b3bfc8587de7d1acd074b9efeb3ac775/server/src/main/java/org/elasticsearch/discovery/zen/MasterFaultDetection.java)
- [ ] [NodesFaultDetection](https://github.com/elastic/elasticsearch/blob/afeb3992b3bfc8587de7d1acd074b9efeb3ac775/server/src/main/java/org/elasticsearch/discovery/zen/NodesFaultDetection.java)
- [ ] [WorkerBulkByScrollTaskState](https://github.com/elastic/elasticsearch/blob/afeb3992b3bfc8587de7d1acd074b9efeb3ac775/server/src/main/java/org/elasticsearch/index/reindex/WorkerBulkByScrollTaskState.java)
- [ ] [IndicesStore](https://github.com/elastic/elasticsearch/blob/afeb3992b3bfc8587de7d1acd074b9efeb3ac775/server/src/main/java/org/elasticsearch/indices/store/IndicesStore.java)
- [ ] [Scheduler](https://github.com/elastic/elasticsearch/blob/afeb3992b3bfc8587de7d1acd074b9efeb3ac775/server/src/main/java/org/elasticsearch/threadpool/Scheduler.java)
- [ ] [ThreadPool](https://github.com/elastic/elasticsearch/blob/afeb3992b3bfc8587de7d1acd074b9efeb3ac775/server/src/main/java/org/elasticsearch/threadpool/ThreadPool.java)
- [ ] [TransportKeepAlive](https://github.com/elastic/elasticsearch/blob/afeb3992b3bfc8587de7d1acd074b9efeb3ac775/server/src/main/java/org/elasticsearch/transport/TransportKeepAlive.java)
- [ ] [TransportService](https://github.com/elastic/elasticsearch/blob/afeb3992b3bfc8587de7d1acd074b9efeb3ac775/server/src/main/java/org/elasticsearch/transport/TransportService.java)
- [ ] [EsExecutorsTests](https://github.com/elastic/elasticsearch/blob/afeb3992b3bfc8587de7d1acd074b9efeb3ac775/server/src/test/java/org/elasticsearch/common/util/concurrent/EsExecutorsTests.java)
- [ ] [FixedThreadPoolTests](https://github.com/elastic/elasticsearch/blob/afeb3992b3bfc8587de7d1acd074b9efeb3ac775/server/src/test/java/org/elasticsearch/threadpool/FixedThreadPoolTests.java)
- [ ] [ShardFollowTasksExecutor](https://github.com/elastic/elasticsearch/blob/afeb3992b3bfc8587de7d1acd074b9efeb3ac775/x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/ShardFollowTasksExecutor.java)
- [ ] [MlDailyMaintenanceService](https://github.com/elastic/elasticsearch/blob/afeb3992b3bfc8587de7d1acd074b9efeb3ac775/x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/MlDailyMaintenanceService.java)
- [ ] [AutodetectProcessManager](https://github.com/elastic/elasticsearch/blob/afeb3992b3bfc8587de7d1acd074b9efeb3ac775/x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/process/autodetect/AutodetectProcessManager.java)
- [ ] [NativeAutodetectProcessFactory](https://github.com/elastic/elasticsearch/blob/afeb3992b3bfc8587de7d1acd074b9efeb3ac775/x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/process/autodetect/NativeAutodetectProcessFactory.java)
- [ ] [AutoDetectResultProcessor](https://github.com/elastic/elasticsearch/blob/afeb3992b3bfc8587de7d1acd074b9efeb3ac775/x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/process/autodetect/output/AutoDetectResultProcessor.java)
- [ ] [NativeNormalizerProcessFactory](https://github.com/elastic/elasticsearch/blob/afeb3992b3bfc8587de7d1acd074b9efeb3ac775/x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/process/normalizer/NativeNormalizerProcessFactory.java)
- [ ] [CleanerService](https://github.com/elastic/elasticsearch/blob/afeb3992b3bfc8587de7d1acd074b9efeb3ac775/x-pack/plugin/monitoring/src/main/java/org/elasticsearch/xpack/monitoring/cleaner/CleanerService.java)
- [ ] [ExecutionService](https://github.com/elastic/elasticsearch/blob/afeb3992b3bfc8587de7d1acd074b9efeb3ac775/x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/execution/ExecutionService.java)

Many of these cases follow this pattern:

https://github.com/elastic/elasticsearch/blob/f1135ef0ceb9c8d74ba4589c285d3cb05e908bcb/x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/process/autodetect/output/AutoDetectResultProcessor.java#L387-L397

They could therefore perhaps mostly be replaced by calls to `ThreadPool#scheduleUnlessShuttingDown()`:

https://github.com/elastic/elasticsearch/blob/6ac0cb1842b85d5a93f036c9d0790ecb4b2b1fc3/server/src/main/java/org/elasticsearch/threadpool/ThreadPool.java#L355-L366

This is a meta-issue to investigate this refactoring in case it's too big to do in one step.

**Comment by dliappis** [comment]
## Files updated in [PR#37709](https://github.com/elastic/elasticsearch/pull/37709)

- [x] InternalClusterInfoService
- [x] TransportKeepAlive
- [x] ShardFollowTasksExecutor

## The following files aren't applicable to this refactoring pattern

- [ClusterApplierService](https://github.com/elastic/elasticsearch/blob/e9fcb25a2876594cbadbc6f229e524e3dde8875d/server/src/main/java/org/elasticsearch/cluster/service/ClusterApplierService.java#L278-L298)
    We need to ensure `listener.onClose()` in catch block when `lifecycle.stoppedOrClosed()` thus can't be directly be replaced by a call to [ThreadPool#sechduleUnlessShuttingDown()](https://github.com/elastic/elasticsearch/blob/6ac0cb1842b85d5a93f036c9d0790ecb4b2b1fc3/server/src/main/java/org/elasticsearch/threadpool/ThreadPool.java#L355-L366).

- [MasterService](https://github.com/elastic/elasticsearch/blob/e9fcb25a2876594cbadbc6f229e524e3dde8875d/server/src/main/java/org/elasticsearch/cluster/service/MasterService.java#L780-L794)
    Doesn't call `schedule()` in the `try { }` block.

- [EsThreadPoolExecutor](https://github.com/elastic/elasticsearch/blob/74d1cfbf7e748868fed35bd2fe55f2788cded7b8/server/src/main/java/org/elasticsearch/common/util/concurrent/EsThreadPoolExecutor.java#L97-L113)
    Doesn't call `schedule()` in the `try { }` block.

- [MasterFaultDetection](https://github.com/elastic/elasticsearch/blob/74d1cfbf7e748868fed35bd2fe55f2788cded7b8/server/src/main/java/org/elasticsearch/discovery/zen/MasterFaultDetection.java#L191-L199)
    Doesn't call `schedule()` in the `try { }` block.

- [NodesFaultDetection](https://github.com/elastic/elasticsearch/blob/74d1cfbf7e748868fed35bd2fe55f2788cded7b8/server/src/main/java/org/elasticsearch/discovery/zen/NodesFaultDetection.java#L178-L191)
    Doesn't call `schedule()` in the `try { }` block.

- [WorkerBulkByScrollTaskState](https://github.com/elastic/elasticsearch/blob/74d1cfbf7e748868fed35bd2fe55f2788cded7b8/server/src/main/java/org/elasticsearch/index/reindex/WorkerBulkByScrollTaskState.java#L192-L199)
    Doesn't call `schedule()` in the `try { }` block.

- [IndicesStore](https://github.com/elastic/elasticsearch/blob/74d1cfbf7e748868fed35bd2fe55f2788cded7b8/server/src/main/java/org/elasticsearch/indices/store/IndicesStore.java#L346-L355)
    Doesn't call `schedule()` in the `try { }` block.

- [Scheduler](https://github.com/elastic/elasticsearch/blob/e9fcb25a2876594cbadbc6f229e524e3dde8875d/server/src/main/java/org/elasticsearch/threadpool/Scheduler.java#L200-L210)
    We don't call `logger.debug()` in the catch block.

- [ThreadPool](https://github.com/elastic/elasticsearch/blob/e9fcb25a2876594cbadbc6f229e524e3dde8875d/server/src/main/java/org/elasticsearch/threadpool/ThreadPool.java#L357-L368)
    This is the `scheduleUnlessShuttingDown()` method itself.

- [TransportService](https://github.com/elastic/elasticsearch/blob/afeb3992b3bfc8587de7d1acd074b9efeb3ac775/server/src/main/java/org/elasticsearch/transport/TransportService.java#L975-L990)
    Doesn't call `schedule()` in the `try { }` block.

- [EsExecutorTests](https://github.com/elastic/elasticsearch/blob/e9fcb25a2876594cbadbc6f229e524e3dde8875d/server/src/test/java/org/elasticsearch/common/util/concurrent/EsExecutorsTests.java#L145-L155)
    Doesn't call `schedule()` in the `try { }` block.

- [FixedThreadPoolTests](https://github.com/elastic/elasticsearch/blob/757932a9751757c9c3689032fc4190dbfbe831a6/server/src/test/java/org/elasticsearch/threadpool/FixedThreadPoolTests.java#L76-L82)
    Doesn't call `schedule()` in the `try { }` block.

- [MlDailyMaintenanceService](https://github.com/elastic/elasticsearch/blob/757932a9751757c9c3689032fc4190dbfbe831a6/x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/MlDailyMaintenanceService.java#L99-L109)
    Requires returned future object from `threadPool.schedule()` to stop scheduled task. Perhaps we could support returning the ScheduledFuture in [scheduleUnlessShuttingDown](https://github.com/elastic/elasticsearch/blob/6ac0cb1842b85d5a93f036c9d0790ecb4b2b1fc3/server/src/main/java/org/elasticsearch/threadpool/ThreadPool.java#L355-L366) in a future PR?

- [AutoDetectProcessManager](https://github.com/elastic/elasticsearch/blob/757932a9751757c9c3689032fc4190dbfbe831a6/x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/process/autodetect/AutodetectProcessManager.java#L539-L551)
    Doesn't call `schedule()` in the `try { }` block.

- [NativeAutodetectProcessFactory](https://github.com/elastic/elasticsearch/blob/757932a9751757c9c3689032fc4190dbfbe831a6/x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/process/autodetect/NativeAutodetectProcessFactory.java#L76-L87)
    Doesn't call `schedule()` in the `try { }` block but `start()` from an instance of `NativeAutodetectProcess` instead.

- [AutoDetectResultProcessor](https://github.com/elastic/elasticsearch/blob/afeb3992b3bfc8587de7d1acd074b9efeb3ac775/x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/process/autodetect/output/AutoDetectResultProcessor.java)
   Doesn't call `schedule()` or catch `EsRejectedExecutionException` anymore, already removed in https://github.com/elastic/elasticsearch/pull/36702/files.

- [NativeNormalizerProcessFactory](https://github.com/elastic/elasticsearch/blob/0a93a0358bfed106bf397a24c0590008225ad21f/x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/process/normalizer/NativeNormalizerProcessFactory.java#L48-L59)
    Doesn't call `schedule()` in the `try { }` block but `start()` from an instance of `NativeNormalizerProcess` instead.

- [CleanerService](https://github.com/elastic/elasticsearch/blob/34f2d2ec916909e107a85c26b1cccdda3026aac9/x-pack/plugin/monitoring/src/main/java/org/elasticsearch/xpack/monitoring/cleaner/CleanerService.java#L199-L208)
    Relies on future object returned by `threadPool.schedule()`; see also `MlDailyMaintenanceService` above.

- [ExecutionService](https://github.com/elastic/elasticsearch/blob/7507af29fa0ae8569e3551d7815fc55afe5af014/x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/execution/ExecutionService.java#L204-L211)
    Doesn't call `schedule()` inside the lambda function or [here](https://github.com/elastic/elasticsearch/blob/7507af29fa0ae8569e3551d7815fc55afe5af014/x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/execution/ExecutionService.java#L396-L399).
