### ISSUE TITLE
[HLRC] Ensure that response parsers support unknown fields

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#36938]
In the HLRC code response parsers using object parsers need to support handeling of unknown field. Otherwise a released HLRC may fail parsing responses from ES nodes released after it. All HLRC areas need to be checked.

After a quick check the follow hlrc areas use `ConstructingObjectParser` with `ignoreUnknownFields` flag set to `false`:
- [x] indices.getTemplate #38448
- [x] ingest.getPipeline #38352 
- [x] snapshot.verifyRepository #37619
- [x] rollup.getRollupCapabilities #38339
- [x] rollup.getRollupIndexCapabilities #38339 
- [x] watcher.deleteWatch #37435
- [x] watcher.putWatch #37494
- [x] watcher.executeWatch #37498
- [x] ilm.getLifecyclePolicy #38041
- [x] ilm.lifecycleManagementStatus #38043
- [x] ilm.explainLifecycle #38054
- [x] security.getUsers #37593
- [x] security.enableUser (EmptyResponse) #37540
- [x] security.disableUser (EmptyResponse) #37540
- [x] security.authenticate #37713
- [x] ~security.getUserPrivileges~ wont fix re https://github.com/elastic/elasticsearch/issues/36938#issuecomment-456909085
- [x] ~security.clearRealmCache~ wont fix re https://github.com/elastic/elasticsearch/issues/36938#issuecomment-456909085
- [x] ~security.clearRolesCache~ wont fix re https://github.com/elastic/elasticsearch/issues/36938#issuecomment-456909085
- [x] security.changePassword (EmptyResponse) #37540
- [x] ~security.getRoles~ wont fix re https://github.com/elastic/elasticsearch/issues/36938#issuecomment-456909085

The following use old school parsing and will (likely) fail with unknown fields. FWIW, some of these are just a guess as to how bad they will behave.
- [ ] bulk
- [ ] getMapping (has some asserts, could fail)
- [ ] snapshot.getRepository
- [ ] license.get (just returns whatever json it gets, so its questionable)
- [ ] security.putPrivileges

Disclaimer: It is possible that other old school parsers will *quite easily* bomb out given unknown fields. This list is likely not exhaustive depending on where the json fields are added.

Maybe we need make an automated check for this? (maybe forbidden apis that checks response classes in hlrc module only)

**Comment by hub-cap** [comment]
in chatting with @albertzaharovits , he pointed out a potential issue with lenient parsers in the security codebase. Lets say, for example, the `User` structure has added true/false field that defaults to false. Someone comes in and creates the user in kibana (or anything *not* their application that is using the HLRC), and sets that true/false field to true, the non default. Some time later, the application, using an older version of HLRC, calls `getUser`, and it parses the User back to the structure it knows about, which does not contain the true/false field. The application then calls `updateUser` with the freshly parsed `User` without the true/false, and the server side sets this field to false, since it does not exist, whilst updating the `User`. This is, of course, going to change the behavior of what the original creator wanted, and because all of our other tools such as Kibana would be updated when the server is updated, then its not a big deal because it will be able to parse and set the true/false field if it was displayed for edit, and it would set it properly when issuing the `PUT user`.

I think there might be cases outside of security where this is the case, but I can definitely see it happening in Security.

**Comment by hub-cap** [comment]
We have decided to keep some of the security parsers to strict, and these will be the only things that default to strict. I will be updating the issue. Parsers that do not need to do any round tripping can be strict.

**Comment by hub-cap** [comment]
I wonder if we can close this. Im leaning toward yes. @martijnvg what do you think?

**Comment by swallez** [comment]
This issue surfaced in https://github.com/elastic/sdh-elasticsearch/issues/5275 where a 7.10 HLRC fails to parse an `ApiKey` returned by a 7.14 cluster because of the new `metadata` field that was introduced in 7.13.

**Comment by dakrone** [comment]
Closing this as we've removed the high level rest client in favor of the [Java client](https://github.com/elastic/elasticsearch-java/).
