### ISSUE TITLE
Shard history retention leases

### ISSUE THREAD

**Issue by jasontedor** [elastic/elasticsearch#37165]
When a shard of a follower index is consuming shard history from its corresponding shard of its leader index, it could be that the history operations is no longer available on any of the leader shard copies. This can happen if some operations were soft deleted and subsequently merged away before the shard of the following index had a chance to replicate these operations. This has catastrophic consequences for the follower index though as now the only option for the follower index to recover is a full file-based recovery. In the context of cross-cluster replication, this can potentially be over a WAN with limited networking resources. During this file-based recovery, the follower index becomes unavailable, defeating the purpose of being an available copy of the leader index in another cluster.

One idea towards solving this problem is for the shard of a follower index to be able to leave a marker on the corresponding shard of its leader index to notate where in shard history the following shard is. This marker would prevent any operations with sequence number at least at that marker from being eligible to be merged away.

And thus was born the idea of shard history retention leases. Shard history retention leases are aimed at preventing shard history consumers from having to fallback to expensive file copy operations if shard history is not available from a certain point. These consumers include following indices in cross-cluster replication, and local shard recoveries. A future consumer will be the changes API.

Further, index lifecycle management requires coordinating with some of these consumers otherwise it could remove the source before all consumers have finished reading all operations. The notion of shard history retention leases that we are introducing here will also be used to address this problem.

Shard history retention leases are a property of the replication group managed under the authority of the primary. A shard history retention lease is a combination of an identifier, a retaining sequence number, a timestamp indicating when the lease was acquired or renewed, and a string indicating the source of the lease. Being leases they have a limited lifespan that will expire if not renewed. The idea of these leases is that all operations above the minimum of all retaining sequence numbers will be retained during merges (which would otherwise clear away operations that are soft deleted). These leases will be periodically persisted to ~~Lucene~~ a dedicated state file and restored during recovery, and broadcast to replicas under certain circumstances.

This issue is a meta-issue for tracking the progress of implementing shard history retention leases. We will proceed with implementing shard history retention leases along the following rough plan:
 - [x] introduce the basics of shard history retention leases @jasontedor #37167 
 - [x] introduce timestamps on and expiration of shard history retention leases @jasontedor #37195
 - [x] ~~persist retention leases in Lucene~~ switched to persisting in a dedicated state file #39004
    - [x] introduce persistence to and recovery from Lucene @jasontedor #37375
    - [x] soft deletes policy should always fetch the latest shard history retention leases @dnhatn #37940
    - [x] [copy retention leases when trimming unsafe commits](
https://github.com/elastic/elasticsearch/pull/37398#discussion_r251209265) @dnhatn  #37995
 - [x] share shard history retention leases with replicas @jasontedor
    - [x] introduce shard history retention lease syncing when retention leases are created @jasontedor  #37398
    - [x] sync shard history retention leases when a retention lease expires @jasontedor #37902
    - [x] introduce periodic background syncing of shard history retention leases (to capture renewals) @jasontedor #38262 #38380
 - [x] enable removal of retention leases @jasontedor #38751 
 - [x] introduce dedicated exceptions for retention lease already exists and retention lease not found @jasontedor #38754
 - [x] introduce external APIs for retention lease management (add/renew/remove) @jasontedor #38756
 - [x] add retention lease infrastructure to index level replication test case infrastructure @dnhatn #38857
 - [x] introduce version on retention lease collections @jasontedor #37951
 - [x] handoff shard history retention leases during recovery @jasontedor #38435
 - [x] expose shard history retention leases in shard-level statistics @jasontedor #37991
 - [x] integrate shard history retention leases with cross-cluster replication @jasontedor 
    - [x] integrate shard history retention leases with recovery from remote @jasontedor #38829
    - [x] integrate shard history retention leases with index following @jasontedor #39335
    - [x] when the unfollow API is invoked the shard history retention leases should be removed @jasontedor #39088
 - [x] switch retention leases to be persisted in a dedicated state file @jasontedor #39004
 - [ ] integrate shard history retention leases with recovery @DaveCTurner  
 - [x] integrate shard history retention leases with index lifecycle management @gwbrown @martijnvg https://github.com/elastic/elasticsearch/pull/38140

**Comment by dnhatn** [comment]
Closing since the work to integrate shard history retention leases with recovery is tracked #41536.
