### ISSUE TITLE
Doc values support for geo shapes.

### ISSUE THREAD

**Issue by imotov** [elastic/elasticsearch#37206]
There are several features that we would like to add that require fast retrieval of geo shapes and can greatly benefit from having docvalues support for geo shapes.

**EDIT**
I intend to leverage this issue to track progress on this effort since it will 
consist of multiple PRs.

There are a few steps that need to be done to support geo-shapes:

- need a structure to hold LinearRings/Polygons to enable contains/crosses queries
- need a structure that holds a collection of these separate polygon trees in order to represent a GeometryCollection
- these structures need to support different types of query inputs
   - relate shape to bounding-box queries
   - relate shape to triangle queries

**feature branch:** [geoshape-doc-values](https://github.com/elastic/elasticsearch/tree/geoshape-doc-values)

Proposed steps needed:

- [x] add circuit-breaker for the tile-hash array created in CellIdSource (GeoGridAggregator) (https://github.com/elastic/elasticsearch/pull/50720)
- [x] update centroid calculator to take dimension and mass into consideration (https://github.com/elastic/elasticsearch/pull/50297)
- [x] include `bounds` as an additional parameter to geogrid aggregations
   - [x] support against `master` https://github.com/elastic/elasticsearch/pull/50002
   - [x] support geo_shapes (TODO)
- [x] support `doc_values` parameter in geo_shape field mapper (https://github.com/elastic/elasticsearch/pull/47519)
- [ ] test script usage and make sure gracefully not supported
- [ ] Documentation
- [x] evaluation Triangle Tree approach in comparison to edge-tree (#47903)
- [x] reduce allocations of Extent and Rectangle objects in geo aggs
- [x] add support for geometry-collections and multi-polygons.(#49610)
- [x] reduce Extent serialized size (#49611)
- [x] investigate Point2D compression
- [x] use rasterization strategy for geohash_grid aggregations (use faster Geohash.toBoundingBox as well)
- [x] store sub-trees in GeometryTree as a tree for more efficient spatial traversal/partitioning
- [x] benchmark doc value (add to `benchmarks` module)
   - [x] indexing memory cost
   - [x] indexing cpu cost
   - [x] read serialization cost
   - [x] on-disk cost
- [x] add more edge-case tests for all aggregations
- [x] reduce storage space of edgetree using variable-length encoding
- [x] rasterize shapes in geo grid aggregations instead of iterating bounding box (#49065)
- [x] improve trig function performance (#49009)
- [x] Leverage GeoValues of both points and shapes in geo-aggregations
  - [x] geo_bounds
  - [x] geo_*_grid (#46513)
  - [x] geo_centroid (#46299)
  - [ ] ~~geo_distance (not going to implement in first pass)~~
- [x] EdgeTree implementation (#40810)
- [x] PolygonTree implementation (edge-tree with holes)
- [x] LineTree implementation (#43949)
- [x] PointTree implementation
- [x] GeometryTree to wrap all the sub-shapes (#44428 )
- [x] Create DocValue object and integrate into GeoShapeFieldMapper (#42863)

**Comment by babadofar** [comment]
What is the status on this? I really need this for my maps. Anything I could help you out with? the @elastic/es-analytics-geo repo is not public, I guess.

**Comment by polyfractal** [comment]
No concrete status update right now.  We're still discussing how to go about encoding shapes into doc values (there are several limitations/considerations that we need to work around).  When we have some news moving forward -- a plan or something similar -- we'll make an update here :)

> the elastic/es-analytics-geo repo is not public, I guess.

The `@elastic/es-analytics-geo` team is just an alias that we use to ping internal email lists, so that different sub-teams can get notified about new issues in their area.  There's no additional repo or anything like that :)

**Comment by thomasneirynck** [comment]
This would be a prerequisite for enabling layer-fitting in the Kibana Maps-app. This is now not possible. cf. https://github.com/elastic/kibana/issues/33509

**Comment by jpountz** [comment]
I had a look at the in-progress branch, this looks great. I also have some thoughts, which I'm logging here for the record:
 - EdgeTree only indexes the minY values, should it also index the maxY, minX and maxX values by alternatively splitting on each of these fields like we do for multi-points?
 - Serialization is a bit wasteful in terms of space: we don't need to serialize separately minY, maxY, y1 and y2: we could just recompute minY and maxY at deserialization time? Furthermore we could move from a fixed-length encoding to variable-length. My understanding is that we only leverage fixed length encoding in order to know how many bytes serializing the left child requires before actually serializing it. We could do it by serializing into a BytesStreamOutput first. It makes indexing a bit more memory-intensive, but this sounds worth the space savings to me.
 - GeometryTreeReader#intersects iterates over sub geometries linearly and returns true as soon as one matches. Should we build a tree there as well to avoid this linear scan?
 - This is the kind of functionality that it would be nice to have microbenchmarks for (the `benchmarks` sub folder in the root directory).

**Comment by talevy** [comment]
thank you for taking a look, Adrien! I generally agree with all of your bullet points.
responses inline...

> I had a look at the in-progress branch, this looks great. I also have some thoughts, which I'm logging here for the record:
> 
> * EdgeTree only indexes the minY values, should it also index the maxY, minX and maxX values by alternatively splitting on each of these fields like we do for multi-points?

I will discuss this with Ignacio and Nick, It follows the existing edgetree implementation in Lucene, and it does not do this, most likely for more efficient point-in-polygon calculation using the infinite ray algorithm.

> * Serialization is a bit wasteful in terms of space: we don't need to serialize separately minY, maxY, y1 and y2: we could just recompute minY and maxY at deserialization time? Furthermore we could move from a fixed-length encoding to variable-length. My understanding is that we only leverage fixed length encoding in order to know how many bytes serializing the left child requires before actually serializing it. We could do it by serializing into a BytesStreamOutput first. It makes indexing a bit more memory-intensive, but this sounds worth the space savings to me.

I will explore this! I wanted to first get something to benchmark, and then we can iterate to see the tradeoffs in more quantitative terms. I do agree, though, it would be great to reduce the storage size.

> * GeometryTreeReader#intersects iterates over sub geometries linearly and returns true as soon as one matches. Should we build a tree there as well to avoid this linear scan?

I forgot to comment this as a TODO, but this is very much a TODO item to make this into a tree. it was left as a linear scan for now to focus on the sub-trees first.

> * This is the kind of functionality that it would be nice to have microbenchmarks for (the `benchmarks` sub folder in the root directory).

I wasn't too familiar with this module, I will add a TODO in the meta-issue to add micro-benchmarks here! thank you for the suggestion.

**Comment by talevy** [comment]
This issue has gone through a lot of evolution, so this comment is meant to give an update on where things landed.

The work for adding geo_shape support for geo_centroid, geo_bounds, geotile_grid, geohash_grid aggregations was accomplished in x-pack by way of the following PRs:

- geotile_grid/geohash_grid (https://github.com/elastic/elasticsearch/pull/55966)
- geo_centroid (https://github.com/elastic/elasticsearch/pull/55602)
- geo_bounds (https://github.com/elastic/elasticsearch/pull/55328)

This is achieved by implementing by migrating geo_shape mapper registration
to a module (https://github.com/elastic/elasticsearch/pull/53562) and then defining the geo_shape with doc values in the spatial plugin (https://github.com/elastic/elasticsearch/pull/55037)

**Comment by talevy** [comment]
update from the last comment above:

geo_bounds, geo_centroid, geotile_grid, geohash_grid support for geo_shape 
is now merged and supported in 7.8 and master (8.0).

Closing this issue to reflect that. at the time of closing Documentation and the topic of geo_distance agg support are still TODOs. documentation is happening shortly, while the geo_distance agg support will require more discussion and future development
