### ISSUE TITLE
[ML] Improve file structure finder timestamp recognition

### ISSUE THREAD

**Issue by droberts195** [elastic/elasticsearch#38086]
The file structure finder currently only supports a fixed set of timestamp formats.  If a file is uploaded that has a different timestamp format then the file structure finder can return a suboptimal config and even fail in a hard-to-diagnose manner.  See for example elastic/kibana#29578

For highly structured formats like JSON and CSV, if the timestamp is not recognised then the only problem is that the timestamp field will be classified as a `keyword` rather than a `date`.

For semi-structured text logs the problem is worse because the lines in the file are grouped into messages using the assumption that the timestamp will appear on the first line of each message, so failure to detect a timestamp has a catastrophic effect on the understanding of the file structure.  In this case we at least return an error saying we couldn't find the timestamp format.  An even worse case is when we don't detect the real timestamp format that appears in every message, but a tiny fraction of messages also contain some other timestamp that we do recognise the format of.  This causes us to group huge numbers of lines into messages leading to timeouts or confusing error messages that don't sensibly say what the underlying problem is - see https://github.com/elastic/kibana/issues/29578#issuecomment-459317274

There are a number of things that could be done to improve this:

- [ ] For semi-structured text logs, cap the number of characters (default 10000, arg to override) that can be combined into a single message.  Then if a very small proportion of long lines contain a timestamp we'll fail with an error instead of timing out.  The error could suggest that the underlying problem might be failure to detect the real per-message timestamp format.
- [x] Allow an arbitrary timestamp format to be supplied as an override, not just one from the list of built-in formats.  (This requires code to build an appropriate Grok pattern from the supplied timestamp format, which is non-trivial and the reason why arbitrary overrides were not permitted in the initial release.)
- [x] Be more advanced in automatically finding timestamp formats.  This breaks down into:
  - [x] Consider the `%{DATE}` and `%{DATESTAMP}` Grok patterns, which correspond to dd/MM/yyyy or MM/dd/yyyy (followed by a time in the case of the second).
  - [x] Look across messages and also at the current locale to pick which of dd/MM and MM/dd is most likely.

**Comment by droberts195** [comment]
#41948 checked the last four checkboxes in the description and #42501 checks the first one.
