### ISSUE TITLE
Convert everything to use testclsuters 

### ISSUE THREAD

**Issue by atorok** [elastic/elasticsearch#40862]
List of feature to add to testlusters: 

Now that we have a fair amount of features in testclusters and `module` and most `plugin` tests are using it, time to make a list of what's left. 

- [x] support security with username and password - by convention [1]
- [x] support security with https [2]
- [x] DSL for adding users [3]
- [ ] add support (and tests) for all versions newer then `6.0` [4]
- [x] add support for upgrading clusters or individual nodes [5]

List of projects to convert [with required features]: 
- [x] client/rest-high-level, (elasticsearch.rest-test) [1]
- [x] docs (docs-test)
- [x] plugins
     - [x] repository-hdfs ( elasticsearch-rest-test , elasticsearch.esplugin )
     - [x] examples (elasticsearch.esplugin)
          - [x] custom-settings 
          - [x] custom-suggester
          - [X] painless-whitelist
          - [x] rescore
          - [x] rest-handler
          - [x] script-expert-scrolling
          - [x] security-authorization-engine [3] 
- qa 
     - [x] ccs-unavailable-clusters (  elasticsearch-standalone-rest-test )
     - [x] die-with-dignity (elasticsearch.esplugin) -- requires exposing the pid of the `ElasticsearchNode`
     - :[x] imp: evil-tests (elasticsearch.standalone-test)  
     - [x] full-cluster-restart [4, 5]
     - [x] mixed-cluster [4, 5] 
     - [x] multi-cluster-search 
     - [x] rolling-upgrade [4, 5]
     - [X] smoke-test-client
     - [x] smoke-test-http
     - [x] smoke-test-ingest-disabled
     - [x] smoke-test-ingest-with-all-dependencies
     - [x] smoke-test-multinode
     - [x] smoke-test-plugins
     - [x] unconfigured-node-name - might be better to move it to a packaging test as it's a snowflake that requires defaults such as discoery and cluster name to be changed 
     - [x] wildfly
- x-pack  
     - [x] docs [1]
     - plugin 
         -  [x] ccr/qa             
         - [x] data-frame/qa/single-node-tests [1]
         - [x] graph/qa/with-security [3]
         - [x] ilm/qa               
         - [x] ml/qa/            
         - [x] sql/qa            
     - qa 
         - [x] core-rest-tests-with-security [1]
         - [x] full-cluster-restart [1, 4, 5]
         - [x] kerberos-tests [1]        
         - [x] multi-cluster-search-security [1]
         - [x] multi-node [3]
         - [x] reindex-tests-with-security [1]
         - [x] rolling -uograde [1 , 4, 5] 
         - [x] rolling-upgrade-basic [1, 4 ,5]
         - [x] rolling-upgrade-multi-cluster  [4, 5]
         - [x] saml-idp-tests [1]
         - [x] security-client-tests [3]
         - [x] security-example-spi-extension [1]
         - [x] security-migrate-tests [3]
         - [x] security-setup-password-tests [1]
         - [x] smoke-test-monitoring-with-watcher
         - [x] smoke-test-plugins [1]
         - [x] smoke-test-plugins-ssl [3, 6]  
         - [x] smoke-test-security-with-mustache [1]
         - [x] smoke-test-watcher 
         - [x] smoke-test-watcher-with-security [3]
         - [x] third-party/jira
         - [x] third-party/pagerduty
         - [x] third-party/slack
               
 We __are__ starting to see the light at the end of the tunnel.

**Comment by atorok** [comment]
We now use testclusters for all rest tests.
