### ISSUE TITLE
[DOCS] Standardize query documentation

### ISSUE THREAD

**Issue by jrodewig** [elastic/elasticsearch#40977]
Where possible, we should standardize documentation of the different query types. This can include a common structure that includes (but is not limited to) the following:
- Request example
- Top-level parameters
- Options

#### Queries to revisit
- [x] Query and filter context (#44975)
- [ ] Match All Query 
- [ ] Full text queries
    - [x] Match Query (#45152)
    - [ ] Match Boolean Prefix Query
    - [ ] Match Phrase Query
    - [x] Match Phrase Prefix Query (#45209)
    - [ ] Multi Match Query
    - [x] Query String Query (#45296)
    - [x] Simple Query String Query (#45343)
    - [x] Intervals Query (#45350)
- [x] Term level queries (#43337)
    - [x] Term Query (#41498)
    - [x] Terms Query (#42889)
    - [x] Terms Set Query (#43060)
    - [x] Range Query (#43282)
    - [x] Exists Query (#41868)
    - [x] Prefix Query (#41955)
    - [x] Wildcard Query (#42670)
    - [x] Regexp Query (#42711)
    - [x] Fuzzy Query (#42078)
    - [x] Type Query (Deprecated)
    - [x] Ids Query (#41077)
- [ ] Compound queries
    - [x] Constant Score Query (#43374)
    - [ ] Bool Query
    - [x] Dis Max Query (#43586)
    - [x] Function Score Query (deprecated? #27588)
    - [x] Boosting Query (#43647)
- [x] Joining queries (unneeded)
    - [x] Nested Query (#44130)
    - [x] Has Child Query (#44190)
    - [x] Has Parent Query (#44443)
    - [x] Parent Id Query (#44449)
- [ ] Geo queries
    - [ ] GeoShape Query
    - [ ] Geo Bounding Box Query
    - [ ] Geo Distance Query
    - [ ] Geo Polygon Query
- [ ] Specalized queries
    - [x] Distance Feature Query (#44916)
    - [ ] More Like This Query
    - [x] Script Query (#44882)
    - [x] Script Score Query (#45087)
    - [ ] Percolate Query
    - [x] Rank Feature Query (#44975)
    - [ ] Wrapper Query
- [ ] Span queries
    - [ ] Span Term Query
    - [ ] Span Multi Term Query
    - [ ] Span First Query
    - [ ] Span Near Query
    - [ ] Span Or Query
    - [ ] Span Not Query
    - [ ] Span Containing Query
    - [ ] Span Within Query
    - [ ] Span Field Masking Query
- [ ] Minimum Should Match
- [x] Multi Term Query Rewrite (#42018)
- [ ] Boost

## Additional changes
- [x] Switch titles to sentence case (#43935)
- [x] Add title abbrevs (#43935)

**Comment by jrodewig** [comment]
Added an item for boost. While working on the [term query](https://www.elastic.co/guide/en/elasticsearch/reference/master/query-dsl-term-query.html) doc, I realized that `boost` and other common parameters likely need their own home and examples.

**Comment by wchrisdean** [comment]
[doc issue triage]
