### ISSUE TITLE
Types removal in 8.0

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#41059]
This is a meta issue that tracks things that must or should be done before 8.0 in order to finalize the removal of types.

**MUST**
 * [ ] Remove typed URL paths
 * [ ] Remove support for `include_type_name` in index creation, mapping and template APIs.
 * [ ] Remove type names from serialized mappings of 8.0 indices in the cluster state.

**SHOULD**
 * [ ] Merge back FieldMapper and MappedFieldType (#41058)
 * [ ] Remove `String type` parameter from all internal code, eg. `MapperService`.
 * [ ] Remove code that is related to the `_default_` mapping.

**Comment by jtibshirani** [comment]
I came across #24362 and am wondering if we should remove the `_type` field in 8.0 as well.

**Comment by jpountz** [comment]
Added, thanks @jtibshirani.

**Comment by jtibshirani** [comment]
@colings86 @jpountz just a note that I created a new section for 'known traps' to list surprises we encountered during the 7.x types removal effort that are good to be aware of.

**Comment by colings86** [comment]
@jtibshirani thats a great idea, thanks

**Comment by jtibshirani** [comment]
> Longer term:
> * Remove String type parameter from all internal code, eg. MapperService.

My understanding is that in order to do this, we need to make sure mappings in cluster state don't contain a custom type name (held over from 7.x). Otherwise, we need some references to 'type' in internal code to load and parse these mappings correctly. 

Have we decided to make this change for 8.0, and introduce some process where mappings get rewritten to use `_doc` (or no type at all)? Or would we prefer to wait until 9.0, where we can force 7.x indices to be reindexed so that the mapping type is always `_doc`?

**Comment by pugnascotia** [comment]
@jpountz I assume we can close this now?
