### ISSUE TITLE
[DOCS] Fix Asciidoctor errors to prepare for migration

### ISSUE THREAD

**Issue by jrodewig** [elastic/elasticsearch#41128]
To prepare the [Elasticsearch Reference Guide](https://www.elastic.co/guide/en/elasticsearch/reference/current/index.html) for Asciidoctor migration, we need to find and fix any syntax that might cause errors.

You can view these errors using this `build_docs` command:
`$GIT_HOME/docs/build_docs --asciidoctor --doc $GIT_HOME/elasticsearch/docs/reference/index.asciidoc --resource=$GIT_HOME/elasticsearch/x-pack/docs/ --chunk 1 --lenient`

Below is a list of files containing errors. If you correct one of these errors, please check the appropriate box and reference this ticket in your PR.

- [x] setup/install/docker.asciidoc: line 85: MIGRATION: code block end doesn't match start (#41151)
- [x] search/rank-eval.asciidoc: line 47: MIGRATION: code block end doesn't match start (#41152)
- [x] search/rank-eval.asciidoc: line 80: MIGRATION: code block end doesn't match start (#41152)
- [x] indices/split-index.asciidoc: line 95: MIGRATION: code block end doesn't match start . (#41153)
- [x] query-dsl/script-score-query.asciidoc: line 109: no callout found for <1> (#41129)
- [x] index-modules.asciidoc: line 50: illegal block content outside of partintro block (#41168)
- [x] sql/endpoints/jdbc.asciidoc: line 57: no callout found for <1> (#41266)
- [x] sql/endpoints/jdbc.asciidoc: line 58: no callout found for <2> (#41266)
- [x] sql/endpoints/jdbc.asciidoc: line 59: no callout found for <3> (#41266)
- [x] sql/endpoints/jdbc.asciidoc: line 60: no callout found for <4> (#41266)
- [x] sql/endpoints/jdbc.asciidoc: line 61: no callout found for <5> (#41266)
- [x] sql/language/syntax/commands/describe-table.asciidoc: line 12: no callout found for <1> (#41276)
- [x] sql/language/syntax/commands/describe-table.asciidoc: line 13: no callout found for <2> (#41276)
- [x] sql/language/syntax/commands/describe-table.asciidoc: line 22: no callout found for <1> (#41276)
- [x] sql/language/syntax/commands/describe-table.asciidoc: line 23: no callout found for <2> (#41276)
- [x] sql/language/syntax/commands/show-columns.asciidoc: line 12: no callout found for <1> (#41276)
- [x] sql/language/syntax/commands/show-columns.asciidoc: line 13: no callout found for <2> (#41276)
- [x] sql/language/syntax/commands/show-functions.asciidoc: line 12: no callout found for <1> (#41276)
- [x] sql/language/syntax/commands/show-tables.asciidoc: line 12: no callout found for <1> (#41276)
- [x] sql/language/syntax/commands/show-tables.asciidoc: line 13: no callout found for <2> (#41276)
- [x] sql/functions/like-rlike.asciidoc: line 26: no callout found for <1> (#41309)
- [x] sql/functions/like-rlike.asciidoc: line 65: no callout found for <1> (#41309)
- [x] sql/functions/aggs.asciidoc: line 24: no callout found for <1> (#41309)
- [x] sql/functions/aggs.asciidoc: line 48: no callout found for <1> (#41309)
- [x] sql/functions/aggs.asciidoc: line 78: no callout found for <1> (#41309)
- [x] sql/functions/aggs.asciidoc: line 103: no callout found for <1> (#41309)
- [x] sql/functions/aggs.asciidoc: line 127: no callout found for <1> (#41309)
- [x] sql/functions/aggs.asciidoc: line 128: no callout found for <2> (#41309)
- [x] sql/functions/aggs.asciidoc: line 222: no callout found for <1> (#41309)
- [x] sql/functions/aggs.asciidoc: line 223: no callout found for <2> (#41309)
- [x] sql/functions/aggs.asciidoc: line 317: no callout found for <1> (#41309)
- [x] sql/functions/aggs.asciidoc: line 345: no callout found for <1> (#41309)
- [x] sql/functions/aggs.asciidoc: line 373: no callout found for <1> (#41309)
- [x] sql/functions/aggs.asciidoc: line 401: no callout found for <1> (#41309)
- [x] sql/functions/aggs.asciidoc: line 425: no callout found for <1> (#41309)
- [x] sql/functions/aggs.asciidoc: line 449: no callout found for <1> (#41309)
- [x] sql/functions/aggs.asciidoc: line 450: no callout found for <2> (#41309)
- [x] sql/functions/aggs.asciidoc: line 475: no callout found for <1> (#41309)
- [x] sql/functions/aggs.asciidoc: line 476: no callout found for <2> (#41309)
- [x] sql/functions/aggs.asciidoc: line 501: no callout found for <1> (#41309)
- [x] sql/functions/aggs.asciidoc: line 525: no callout found for <1> (#41309)
- [x] sql/functions/aggs.asciidoc: line 549: no callout found for <1> (#41309)
- [x] sql/functions/aggs.asciidoc: line 573: no callout found for <1> (#41309)
- [x] sql/functions/grouping.asciidoc: line 21: no callout found for <1> (#41309)
- [x] sql/functions/grouping.asciidoc: line 22: no callout found for <2> (#41309)
- [x] sql/functions/grouping.asciidoc: line 23: no callout found for <3> (#41309)
- [x] sql/functions/grouping.asciidoc: line 24: no callout found for <4> (#41309)
- [x] sql/functions/date-time.asciidoc: line 155: no callout found for <1> (#41309)
- [x] sql/functions/date-time.asciidoc: line 211: no callout found for <1> (#41309)
- [x] sql/functions/date-time.asciidoc: line 262: no callout found for <1> (#41309)
- [x] sql/functions/date-time.asciidoc: line 286: no callout found for <1> (#41309)
- [x] sql/functions/date-time.asciidoc: line 310: no callout found for <1> (#41309)
- [x] sql/functions/date-time.asciidoc: line 334: no callout found for <1> (#41309)
- [x] sql/functions/date-time.asciidoc: line 358: no callout found for <1> (#41309)
- [x] sql/functions/date-time.asciidoc: line 382: no callout found for <1> (#41309)
- [x] sql/functions/date-time.asciidoc: line 407: no callout found for <1> (#41309)
- [x] sql/functions/date-time.asciidoc: line 432: no callout found for <1> (#41309)
- [x] sql/functions/date-time.asciidoc: line 456: no callout found for <1> (#41309)
- [x] sql/functions/date-time.asciidoc: line 480: no callout found for <1> (#41309)
- [x] sql/functions/date-time.asciidoc: line 504: no callout found for <1> (#41309)
- [x] sql/functions/date-time.asciidoc: line 560: no callout found for <1> (#41309)
- [x] sql/functions/date-time.asciidoc: line 584: no callout found for <1> (#41309)
- [x] sql/functions/date-time.asciidoc: line 640: no callout found for <1> (#41309)
- [x] sql/functions/date-time.asciidoc: line 664: no callout found for <1> (#41309)
- [x] sql/functions/date-time.asciidoc: line 688: no callout found for <1> (#41309)
- [x] sql/functions/date-time.asciidoc: line 689: no callout found for <2> (#41309)
- [x] sql/functions/search.asciidoc: line 22: no callout found for <1> (#41309)
- [x] sql/functions/search.asciidoc: line 23: no callout found for <2> (#41309)
- [x] sql/functions/search.asciidoc: line 24: no callout found for <3> (#41309)
- [x] sql/functions/search.asciidoc: line 83: no callout found for <1> (#41309)
- [x] sql/functions/search.asciidoc: line 84: no callout found for <2> (#41309)
- [x] sql/functions/math.asciidoc: line 24: no callout found for <1> (#41309)
- [x] sql/functions/math.asciidoc: line 48: no callout found for <1> (#41309)
- [x] sql/functions/math.asciidoc: line 72: no callout found for <1> (#41309)
- [x] sql/functions/math.asciidoc: line 118: no callout found for <1> (#41309)
- [x] sql/functions/math.asciidoc: line 142: no callout found for <1> (#41309)
- [x] sql/functions/math.asciidoc: line 166: no callout found for <1> (#41309)
- [x] sql/functions/math.asciidoc: line 190: no callout found for <1> (#41309)
- [x] sql/functions/math.asciidoc: line 214: no callout found for <1> (#41309)
- [x] sql/functions/math.asciidoc: line 260: no callout found for <1> (#41309)
- [x] sql/functions/math.asciidoc: line 261: no callout found for <2> (#41309)
- [x] sql/functions/math.asciidoc: line 290: no callout found for <1> (#41309)
- [x] sql/functions/math.asciidoc: line 313: no callout found for <1> (#41309)
- [x] sql/functions/math.asciidoc: line 314: no callout found for <2> (#41309)
- [x] sql/functions/math.asciidoc: line 345: no callout found for <1> (#41309)
- [x] sql/functions/math.asciidoc: line 370: no callout found for <1> (#41309)
- [x] sql/functions/math.asciidoc: line 393: no callout found for <1> (#41309)
- [x] sql/functions/math.asciidoc: line 394: no callout found for <2> (#41309)
- [x] sql/functions/math.asciidoc: line 429: no callout found for <1> (#41309)
- [x] sql/functions/math.asciidoc: line 453: no callout found for <1> (#41309)
- [x] sql/functions/math.asciidoc: line 477: no callout found for <1> (#41309)
- [x] sql/functions/math.asciidoc: line 501: no callout found for <1> (#41309)
- [x] sql/functions/math.asciidoc: line 502: no callout found for <2> (#41309)
- [x] sql/functions/math.asciidoc: line 526: no callout found for <1> (#41309)
- [x] sql/functions/math.asciidoc: line 550: no callout found for <1> (#41309)
- [x] sql/functions/math.asciidoc: line 574: no callout found for <1> (#41309)
- [x] sql/functions/math.asciidoc: line 598: no callout found for <1> (#41309)
- [x] sql/functions/math.asciidoc: line 623: no callout found for <1> (#41309)
- [x] sql/functions/math.asciidoc: line 648: no callout found for <1> (#41309)
- [x] sql/functions/math.asciidoc: line 672: no callout found for <1> (#41309)
- [x] sql/functions/math.asciidoc: line 696: no callout found for <1> (#41309)
- [x] sql/functions/string.asciidoc: line 19: no callout found for <1> (#41270)
- [x] sql/functions/string.asciidoc: line 42: no callout found for <1> (#41270)
- [x] sql/functions/string.asciidoc: line 65: no callout found for <1> (#41270)
- [x] sql/functions/string.asciidoc: line 88: no callout found for <1> (#41270)
- [x] sql/functions/string.asciidoc: line 111: no callout found for <1> (#41270)
- [x] sql/functions/string.asciidoc: line 112: no callout found for <2> (#41270)
- [x] sql/functions/string.asciidoc: line 135: no callout found for <1> (#41270)
- [x] sql/functions/string.asciidoc: line 136: no callout found for <2> (#41270)
- [x] sql/functions/string.asciidoc: line 137: no callout found for <3> (#41270)
- [x] sql/functions/string.asciidoc: line 138: no callout found for <4> (#41270)
- [x] sql/functions/string.asciidoc: line 161: no callout found for <1> (#41270)
- [x] sql/functions/string.asciidoc: line 184: no callout found for <1> (#41270)
- [x] sql/functions/string.asciidoc: line 185: no callout found for <2> (#41270)
- [x] sql/functions/string.asciidoc: line 208: no callout found for <1> (#41270)
- [x] sql/functions/string.asciidoc: line 231: no callout found for <1> (#41270)
- [x] sql/functions/string.asciidoc: line 232: no callout found for <2> (#41270)
- [x] sql/functions/string.asciidoc: line 233: no callout found for <3> (#41270)
- [x] sql/functions/string.asciidoc: line 261: no callout found for <1> (#41270)
- [x] sql/functions/string.asciidoc: line 284: no callout found for <1> (#41270)
- [x] sql/functions/string.asciidoc: line 307: no callout found for <1> (#41270)
- [x] sql/functions/string.asciidoc: line 308: no callout found for <2> (#41270)
- [x] sql/functions/string.asciidoc: line 331: no callout found for <1> (#41270)
- [x] sql/functions/string.asciidoc: line 332: no callout found for <2> (#41270)
- [x] sql/functions/string.asciidoc: line 355: no callout found for <1> (#41270)
- [x] sql/functions/string.asciidoc: line 356: no callout found for <2> (#41270)
- [x] sql/functions/string.asciidoc: line 357: no callout found for <3> (#41270)
- [x] sql/functions/string.asciidoc: line 380: no callout found for <1> (#41270)
- [x] sql/functions/string.asciidoc: line 381: no callout found for <2> (#41270)
- [x] sql/functions/string.asciidoc: line 404: no callout found for <1> (#41270)
- [x] sql/functions/string.asciidoc: line 427: no callout found for <1> (#41270)
- [x] sql/functions/string.asciidoc: line 450: no callout found for <1> (#41270)
- [x] sql/functions/string.asciidoc: line 451: no callout found for <2> (#41270)
- [x] sql/functions/string.asciidoc: line 452: no callout found for <3> (#41270)
- [x] sql/functions/string.asciidoc: line 475: no callout found for <1> (#41270)
- [x] sql/functions/type-conversion.asciidoc: line 17: no callout found for <1> (#41270)
- [x] sql/functions/type-conversion.asciidoc: line 18: no callout found for <2> (#41270)
- [x] sql/functions/type-conversion.asciidoc: line 56: no callout found for <1> (#41270)
- [x] sql/functions/type-conversion.asciidoc: line 57: no callout found for <2> (#41270)
- [x] sql/functions/conditional.asciidoc: line 19: no callout found for <1> (#41205)
- [x] sql/functions/conditional.asciidoc: line 21: no callout found for <2> (#41205)
- [x] sql/functions/conditional.asciidoc: line 59: no callout found for <1> (#41205)
- [x] sql/functions/conditional.asciidoc: line 61: no callout found for <2> (#41205)
- [x] sql/functions/conditional.asciidoc: line 100: no callout found for <1> (#41205)
- [x] sql/functions/conditional.asciidoc: line 102: no callout found for <2> (#41205)
- [x] sql/functions/conditional.asciidoc: line 137: no callout found for <1> (#41205)
- [x] sql/functions/conditional.asciidoc: line 139: no callout found for <2> (#41205)
- [x] sql/functions/conditional.asciidoc: line 174: no callout found for <1> (#41205)
- [x] sql/functions/conditional.asciidoc: line 176: no callout found for <2> (#41205)
- [x] sql/functions/conditional.asciidoc: line 216: no callout found for <1> (#41205)
- [x] sql/functions/conditional.asciidoc: line 218: no callout found for <2> (#41205)
- [x] sql/functions/conditional.asciidoc: line 251: no callout found for <1> (#41205)
- [x] sql/functions/conditional.asciidoc: line 253: no callout found for <2> (#41205)
- [x] release-notes/highlights.asciidoc: line 4: partintro block can only be used when doctype is book and must be a child of a book part. Excluding block content. (#41366)
- [x] /out/html_docs/index.xml:12484: element chapter: validity error : Element chapter content does not follow the DTD (#41435)
- [x] /out/html_docs/index.xml:12715: element chapter: validity error : Element chapter content does not follow the DTD (#41435)

## Bad links
Asciidoc and Asciidoctor use different conventions to autogenerate IDs. In some cases, we've linked to sections using these autogenerated IDs.

To prevent those links from breaking, we'll need to explicitly set an ID for the target section, update the outgoing link, or both.

- [x] /tmp/docsbuild/target_repo/html/en/elasticsearch/client/java-rest/5.6/java-rest-high-search.html: (#41505)
    - en/elasticsearch/reference/5.6/_profiling_queries.html#_literal_collectors_literal_section
    - en/elasticsearch/reference/5.6/_profiling_queries.html#_literal_query_literal_section
- [x] /tmp/docsbuild/target_repo/html/en/elasticsearch/client/java-rest/6.0/java-rest-high-search.html:
    - en/elasticsearch/reference/6.0/_profiling_queries.html#_literal_collectors_literal_section
    - en/elasticsearch/reference/6.0/_profiling_queries.html#_literal_query_literal_section
- [x] /tmp/docsbuild/target_repo/html/en/elasticsearch/client/java-rest/6.1/java-rest-high-search.html: (#41505)
    - en/elasticsearch/reference/6.1/_profiling_queries.html#_literal_collectors_literal_section
    - en/elasticsearch/reference/6.1/_profiling_queries.html#_literal_query_literal_section
- [x] /tmp/docsbuild/target_repo/html/en/elasticsearch/client/java-rest/6.2/java-rest-high-search.html: (#41505)
    - en/elasticsearch/reference/6.2/_profiling_queries.html#_literal_collectors_literal_section
    - en/elasticsearch/reference/6.2/_profiling_queries.html#_literal_query_literal_section
- [x] /tmp/docsbuild/target_repo/html/en/elasticsearch/client/java-rest/6.3/java-rest-high-search.html: (#41505)
    - en/elasticsearch/reference/6.3/_profiling_queries.html#_literal_collectors_literal_section
    - en/elasticsearch/reference/6.3/_profiling_queries.html#_literal_query_literal_section
- [x] /tmp/docsbuild/target_repo/html/en/elasticsearch/client/java-rest/6.4/java-rest-high-search.html: (#41505)
    - en/elasticsearch/reference/6.4/_profiling_queries.html#_literal_collectors_literal_section
    - en/elasticsearch/reference/6.4/_profiling_queries.html#_literal_query_literal_section
- [x] /tmp/docsbuild/target_repo/html/en/elasticsearch/client/java-rest/6.5/java-rest-high-search.html: (#41505)
    - en/elasticsearch/reference/6.5/_profiling_queries.html#_literal_collectors_literal_section 
    - en/elasticsearch/reference/6.5/_profiling_queries.html#_literal_query_literal_section 
- [x] /tmp/docsbuild/target_repo/html/en/elasticsearch/client/net-api/5.x/nest-breaking-changes.html:
    - en/elasticsearch/reference/5.0/breaking_50_mapping_changes.html#_literal_index_literal_property (#41507)
    - en/elasticsearch/reference/5.6/breaking_50_mapping_changes.html#_literal_string_literal_fields_replaced_by_literal_text_literal_literal_keyword_literal_fields (#41506)
- [x] /tmp/docsbuild/target_repo/html/en/elasticsearch/reference/5.6/migration-api-deprecation.html: (#41512)
    - en/elasticsearch/reference/6.0/breaking_60_indices_changes.html#_index_templates_use_literal_index_patterns_literal_instead_of_literal_template_literal
- [x] /tmp/docsbuild/target_repo/html/en/elasticsearch/reference/6.0/migration-api-deprecation.html: (#41512)
    - en/elasticsearch/reference/6.0/breaking_60_indices_changes.html#_index_templates_use_literal_index_patterns_literal_instead_of_literal_template_literal
- [x] /tmp/docsbuild/target_repo/html/en/elasticsearch/reference/6.1/migration-api-deprecation.html: (#41512)
    - en/elasticsearch/reference/6.0/breaking_60_indices_changes.html#_index_templates_use_literal_index_patterns_literal_instead_of_literal_template_literal
- [x] /tmp/docsbuild/target_repo/html/en/elasticsearch/reference/6.2/migration-api-deprecation.html: (#41512)
    - en/elasticsearch/reference/6.0/breaking_60_indices_changes.html#_index_templates_use_literal_index_patterns_literal_instead_of_literal_template_literal
- [x] /tmp/docsbuild/target_repo/html/en/elasticsearch/reference/6.3/migration-api-deprecation.html: (#41512)
    - en/elasticsearch/reference/6.0/breaking_60_indices_changes.html#_index_templates_use_literal_index_patterns_literal_instead_of_literal_template_literal
- [x] /tmp/docsbuild/target_repo/html/en/elasticsearch/reference/6.4/migration-api-deprecation.html: (#41512)
    - en/elasticsearch/reference/6.0/breaking_60_indices_changes.html#_index_templates_use_literal_index_patterns_literal_instead_of_literal_template_literal
- [x] /tmp/docsbuild/target_repo/html/en/elasticsearch/reference/6.5/migration-api-deprecation.html: (#41512)
    - en/elasticsearch/reference/6.0/breaking_60_indices_changes.html#_index_templates_use_literal_index_patterns_literal_instead_of_literal_template_literal
- [x] /tmp/docsbuild/target_repo/html/en/elasticsearch/reference/6.6/migration-api-deprecation.html: (#41501)
    - en/elasticsearch/reference/7.0/breaking-changes-7.0.html#_literal_literal_is_no_longer_allowed_in_cluster_name
    - en/elasticsearch/reference/7.0/breaking-changes-7.0.html#_literal_literal_is_no_longer_allowed_in_index_name
- [x] /tmp/docsbuild/target_repo/html/en/elasticsearch/reference/6.7/migration-api-deprecation.html:  (#41501)
    - en/elasticsearch/reference/7.0/breaking-changes-7.0.html#_literal_literal_is_no_longer_allowed_in_cluster_name
    - en/elasticsearch/reference/7.0/breaking-changes-7.0.html#_literal_literal_is_no_longer_allowed_in_index_name
- [x] /tmp/docsbuild/target_repo/html/en/elasticsearch/reference/7.0/migration-api-deprecation.html:  (#41501)
    - en/elasticsearch/reference/7.0/breaking-changes-7.0.html#_literal_literal_is_no_longer_allowed_in_cluster_name
    - en/elasticsearch/reference/7.0/breaking-changes-7.0.html#_literal_literal_is_no_longer_allowed_in_index_name
- [x] /tmp/docsbuild/target_repo/html/en/elasticsearch/reference/current/migration-api-deprecation.html:  (#41501)
    - en/elasticsearch/reference/7.0/breaking-changes-7.0.html#_literal_literal_is_no_longer_allowed_in_cluster_name
    - en/elasticsearch/reference/7.0/breaking-changes-7.0.html#_literal_literal_is_no_longer_allowed_in_index_name
- [x] /tmp/docsbuild/target_repo/html/en/elasticsearch/reference/master/migration-api-deprecation.html:  (#41501)
    - en/elasticsearch/reference/7.0/breaking-changes-7.0.html#_literal_literal_is_no_longer_allowed_in_cluster_name
    - en/elasticsearch/reference/7.0/breaking-changes-7.0.html#_literal_literal_is_no_longer_allowed_in_index_name

## IDs to clean up
Asciidoc and Asciidoctor use different conventions to autogenerate IDs. Some page URLs contain these autogenerated IDs.

To prevent those URLs from breaking, we'll need to explicitly set an ID for the target sections.

- [x] html/en/elasticsearch/reference/2.2/_literal_collectors_literal_section.html -> html/en/elasticsearch/reference/2.2/_collectors_section.html (#41550)
- [x] html/en/elasticsearch/reference/2.2/_literal_query_literal_section.html -> html/en/elasticsearch/reference/2.2/_query_section.html (#41550)
- [x] html/en/elasticsearch/reference/2.2/_literal_rewrite_literal_section.html -> html/en/elasticsearch/reference/2.2/_rewrite_section.html (#41550)
- [x] html/en/elasticsearch/reference/2.3/_literal_collectors_literal_section.html -> html/en/elasticsearch/reference/2.3/_collectors_section.html (#41550)
- [x] html/en/elasticsearch/reference/2.3/_literal_query_literal_section.html -> html/en/elasticsearch/reference/2.3/_query_section.html (#41550)
- [x] html/en/elasticsearch/reference/2.3/_literal_rewrite_literal_section.html -> html/en/elasticsearch/reference/2.3/_rewrite_section.html (#41550)
- [x] html/en/elasticsearch/reference/2.4/_literal_collectors_literal_section.html -> html/en/elasticsearch/reference/2.4/_collectors_section.html (#41550)
- [x] html/en/elasticsearch/reference/2.4/_literal_query_literal_section.html -> html/en/elasticsearch/reference/2.4/_query_section.html (#41550)
- [x] html/en/elasticsearch/reference/2.4/_literal_rewrite_literal_section.html -> html/en/elasticsearch/reference/2.4/_rewrite_section.html (#41550)
- [x] html/en/elasticsearch/reference/current/_faster_phrase_queries_with_literal_index_phrases_literal.html -> html/en/elasticsearch/reference/7.0/_faster_phrase_queries_with_index_phrases.html (#41547)
- [x] html/en/elasticsearch/reference/7.0/_faster_prefix_queries_with_literal_index_prefixes_literal.html -> html/en/elasticsearch/reference/7.0/_faster_prefix_queries_with_index_prefixes.html (#41547)
- [x] html/en/elasticsearch/reference/7.x/_faster_phrase_queries_with_literal_index_phrases_literal.html -> html/en/elasticsearch/reference/7.x/_faster_phrase_queries_with_index_phrases.html (#41547)
- [x] html/en/elasticsearch/reference/7.x/_faster_prefix_queries_with_literal_index_prefixes_literal.html -> html/en/elasticsearch/reference/7.x/_faster_prefix_queries_with_index_prefixes.html (#41547)
- [x] html/en/elasticsearch/reference/7.0/_faster_phrase_queries_with_literal_index_phrases_literal.html -> html/en/elasticsearch/reference/current/_faster_phrase_queries_with_index_phrases.html (#41547)
- [x] html/en/elasticsearch/reference/current/_faster_prefix_queries_with_literal_index_prefixes_literal.html -> html/en/elasticsearch/reference/current/_faster_prefix_queries_with_index_prefixes.html (#41547)
- [x] html/en/elasticsearch/reference/master/_faster_phrase_queries_with_literal_index_phrases_literal.html -> html/en/elasticsearch/reference/master/_faster_phrase_queries_with_index_phrases.html (#41547)
- [x] html/en/elasticsearch/reference/master/_faster_prefix_queries_with_literal_index_prefixes_literal.html -> html/en/elasticsearch/reference/master/_faster_prefix_queries_with_index_prefixes.html (#41547)

**Comment by jrodewig** [comment]
We currently have open or closed PRs to address the above errors. I'll plan to merge any of my open PRs once I get dedicated time to backport or monitor the builds.

Big thanks to @lcawl and @nik9000 for their work and guidance!

**Comment by jrodewig** [comment]
Spoke to @nik9000 and discovered two more errors in `master` branch:

- [ ] /out/html_docs/index.xml:12475: element chapter: validity error : Element chapter content does not follow the DTD
- [ ] /out/html_docs/index.xml:12706: element chapter: validity error : Element chapter content does not follow the DTD

**Comment by jrodewig** [comment]
Added some bad links @nik9000 found in https://github.com/elastic/docs/pull/827#issuecomment-486371617

**Comment by jrodewig** [comment]
@nik9000 and I are tracking any remaining work in elastic/docs#827. Closing this so we don't have to maintain two sources.
