### ISSUE TITLE
Update Deprecation Info API checks for 8.0

### ISSUE THREAD

**Issue by gwbrown** [elastic/elasticsearch#42404]
This issue is intended to track breaking changes for 8.0 which need a deprecation check implemented in the Deprecation Info API as they are made.  While we will still need a review prior to the release of 8.0, the intention is that we can work on implementing these checks as the breaking changes are made, or at least keep a running list of which ones need checks rather than having to go through all `>breaking` PRs.

In order to be checkable by the Deprecation Info API, the issue must be detectable by examining one of the following:
1) `ClusterState`
2) `IndexMetaData`
3) Node-local information (e.g. settings, plugins, etc.)
4) `DatafeedConfig`

REST API changes, or problems which are only detectable by examining the **contents** of the index, rather than the mapping/settings, probably don't go here, but please ask if you're unsure.

Deprecation checks should generally be added to the 7.x branch. You can find the appropriate classes [here](https://github.com/elastic/elasticsearch/tree/7.x/x-pack/plugin/deprecation/src/main/java/org/elasticsearch/xpack/deprecation).  View the 6.8 branch for a number of examples if you need more examples than are present in 7.x.

## The List

- [x] Remove support for chained multi-fields https://github.com/elastic/elasticsearch/pull/41926 (check in https://github.com/elastic/elasticsearch/pull/42333) (This might be getting changed due to BWC concerns
- [x] Bump the minimum Java version to Java 11 https://github.com/elastic/elasticsearch/pull/40754 (check in https://github.com/elastic/elasticsearch/pull/41092)
- [x] Add lower bound on ILM poll_interval https://github.com/elastic/elasticsearch/pull/39593
- [x] Remove include_relocations setting https://github.com/elastic/elasticsearch/pull/47717 
- [x] Remove deprecated AUTH_PASSWORD setting https://github.com/elastic/elasticsearch/pull/54892 
- [x] Remove slowlog level https://github.com/elastic/elasticsearch/pull/57591 
- [x] Remove escape hatch permitting incompatible builds https://github.com/elastic/elasticsearch/pull/65753
- [x] disallow creating geo_shape mappings with deprecated parameters https://github.com/elastic/elasticsearch/pull/70850
- [x] Remove _tier allocation filtering settings https://github.com/elastic/elasticsearch/pull/73074
- [x] Revert per-context painless cache & compilation limit https://github.com/elastic/elasticsearch/issues/62899
- [x] Security enabled by default for all license types https://github.com/elastic/elasticsearch/pull/72300
- [x] Remove special handling of disk watermark for single data node https://github.com/elastic/elasticsearch/pull/73737 (PRs need to be merged)
- [x] Remove the pidfile setting  https://github.com/elastic/elasticsearch/pull/45940
- [x] Scripting: Remove general cache settings  https://github.com/elastic/elasticsearch/pull/59262
- [x] Remove legacy role settings
- [x] Disallow `_field_names` enabled setting  https://github.com/elastic/elasticsearch/pull/46681
- [x] Make remote cluster resolution stricter  https://github.com/elastic/elasticsearch/pull/40419
- [x] Remove deprecated search.remote settings  https://github.com/elastic/elasticsearch/pull/42381
- [x] Remove obsolete security settings https://github.com/elastic/elasticsearch/pull/40496
- [x] Remove node.max_local_storage_nodes https://github.com/elastic/elasticsearch/pull/42428
- [x] Remove fixed_auto_queue_size threadpool type https://github.com/elastic/elasticsearch/pull/52280 
- [x] Remove join timeout https://github.com/elastic/elasticsearch/pull/60873 
- [x] Remove the client transport profile filter https://github.com/elastic/elasticsearch/pull/43236
- [x] Remove support for delaying state recovery pending master https://github.com/elastic/elasticsearch/pull/53845
- [x] Remove support for fractional byte size values  https://github.com/elastic/elasticsearch/pull/53927
- [x] Remove frozen cache setting leniency https://github.com/elastic/elasticsearch/pull/71013
- [x] Reject misconfigured/ambiguous SSL server config  https://github.com/elastic/elasticsearch/pull/45892 
- [x] Remove support for sparse vectors https://github.com/elastic/elasticsearch/pull/48781 
- [x] Do not set a NameID format in Policy by default https://github.com/elastic/elasticsearch/pull/44090 
- [x] Setting: cluster.routing.allocation.shard_state.reroute.priority https://github.com/elastic/elasticsearch/pull/44433
- [x] Settings: discovery.zen.* https://github.com/elastic/elasticsearch/pull/38289
- [x] Setting: gateway.auto_import_dangling_indices https://github.com/elastic/elasticsearch/pull/49174
- [x] Setting: http.content_type.required https://github.com/elastic/elasticsearch/pull/23146
- [x] Setting: index.force_memory_term_dictionary https://github.com/elastic/elasticsearch/pull/42838
- [x] Setting: index.mapper.dynamic https://github.com/elastic/elasticsearch/pull/26603
- [x] Settings: node.data, node.data_cold, node.data_content, node.data_frozen, node.data_hot, node.data_warm, node.ingest, node.master, node.ml, node.remote_cluster_client, node.transform, node.voting_only https://github.com/elastic/elasticsearch/pull/58512
- [x] Setting: repositories.fs.compress https://github.com/elastic/elasticsearch/pull/39073
- [x] Settings: http.tcp_no_delay, network.tcp.connect_timeout, transport.tcp.connect_timeout, transport.tcp.port, transport.tcp_no_delay https://github.com/elastic/elasticsearch/pull/41229
- [x] Setting: transport.tcp.compress https://github.com/elastic/elasticsearch/pull/74719
- [x] Setting: xpack.data_frame.enabled https://github.com/elastic/elasticsearch/pull/46784
- [x] Setting: xpack.watcher.history.cleaner_service.enabled https://github.com/elastic/elasticsearch/pull/37782
- [x] Setting: indices.lifecycle.step.master_timeout https://github.com/elastic/elasticsearch/pull/74143
- [x] Setting: xpack.eql.enabled https://github.com/elastic/elasticsearch/pull/61375

## Not needed list

- [x] ~~Provide an Option to Use Path-Style-Access with S3 Repo https://github.com/elastic/elasticsearch/pull/41966~~
- [x] ~~Blob Store compress default to true https://github.com/elastic/elasticsearch/pull/40033 (is this worth warning about? not sure what this breaks)~~
- [x]  ~~Prevent PrefixTree strategies on new geo_shape indexes https://github.com/elastic/elasticsearch/pull/37152 (for index templates)~~
- [x] ~~Remove the 'template' field in index templates https://github.com/elastic/elasticsearch/pull/49460~~
- [x] ~~Remove type metadata from ingest documents https://github.com/elastic/elasticsearch/pull/50131~~
- [x] ~~Remove support for JAVA_HOME https://github.com/elastic/elasticsearch/pull/69149~~
- [x] ~~Parse empty first line in msearch request body as action metadata  https://github.com/elastic/elasticsearch/pull/41011~~
- [x] ~~Remove deprecated endpoints containing _xpack.  https://github.com/elastic/elasticsearch/pull/48170~~
- [x] ~~Remove the object format for indices_boost  https://github.com/elastic/elasticsearch/pull/55078~~
- [x] ~~Remove use_field_mapping format option for docvalue fields  https://github.com/elastic/elasticsearch/pull/55622~~
- [x] ~~Removes typed URLs  https://github.com/elastic/elasticsearch/pull/41636~~
- [x] ~~Removes tpyed endpoints for msearch and mtermvector APIs  https://github.com/elastic/elasticsearch/pull/41674~~
- [x] ~~Removes typed URLs from mapping APIs  https://github.com/elastic/elasticsearch/pull/41676~~
- [x] ~~Removes types from bulk API  https://github.com/elastic/elasticsearch/pull/42194~~
- [x] ~~Removes type from TermVectors APIs  https://github.com/elastic/elasticsearch/pull/42198~~
- [x] ~~Remove types from Get/MultiGet  https://github.com/elastic/elasticsearch/pull/46587~~
- [x] ~~Remove per-type indexing stats  https://github.com/elastic/elasticsearch/pull/47203~~
- [x] ~~Remove `type` query  https://github.com/elastic/elasticsearch/pull/47207~~
- [x] ~~Remove `include_type_name` parameter from REST layer  https://github.com/elastic/elasticsearch/pull/48632~~
- [x] ~~Remove support for _type in searches  https://github.com/elastic/elasticsearch/pull/68564~~
- [x] ~~Remove support for string in unmapped_type  https://github.com/elastic/elasticsearch/pull/45675~~
- [x] ~~Add declarative parameters to FieldMappers  https://github.com/elastic/elasticsearch/pull/58663~~
- [x] ~~Don't expose TextFieldMapper subfields  https://github.com/elastic/elasticsearch/pull/64597~~
- [x] ~~Allow parsing Content-Type and Accept headers with version  https://github.com/elastic/elasticsearch/pull/61427~~
- [x] ~~Highlighters skip ignored keyword values  https://github.com/elastic/elasticsearch/pull/53408~~
- [x] ~~Percentiles aggregation: disallow specifying same percentile values twice  https://github.com/elastic/elasticsearch/pull/52257~~
- [x] ~~Fix updating include_in_parent/include_in_root of nested field  https://github.com/elastic/elasticsearch/pull/54386~~
- [x] ~~Disallow changing 'enabled' on the root mapper  https://github.com/elastic/elasticsearch/pull/54463~~
- [x] ~~Remove TypeFieldMapper  https://github.com/elastic/elasticsearch/pull/53611~~
- [x] ~~Scripting: Move script_cache into _nodes/stats https://github.com/elastic/elasticsearch/pull/59265~~
- [x] ~~Remove the no-jdk distribution https://github.com/elastic/elasticsearch/issues/65109~~
- [x] ~~Fix range query on date fields for number inputs https://github.com/elastic/elasticsearch/pull/63692~~
- [x] ~~Kibana user renamed to kibana_system https://github.com/elastic/elasticsearch/pull/54967~~
- [x] ~~kibana_user role renamed to kibana_admin https://github.com/elastic/elasticsearch/pull/46456~~
- [x] ~~Add validation for dynamic templates https://github.com/elastic/elasticsearch/pull/51233~~
- [x] ~~Remove support for chained multi-fields.   https://github.com/elastic/elasticsearch/pull/42333~~
- [x] ~~Enforce Completion Context Limit  https://github.com/elastic/elasticsearch/pull/38675~~

**Comment by ppf2** [comment]
Curious about https://github.com/elastic/elasticsearch/pull/25127#issuecomment-307156889.  Are `inline` and `stored` still valid on 8.0 (despite previous deprecation) or will it be part of this list?

**Comment by gwbrown** [comment]
I don't see a PR labelled `>breaking` that removed `inline`/`stored` yet - this list only includes breaking changes that have a PR open or are already merged. The Deprecation Info API is intended to only include things that will either break or have different behavior in the next major version to make it easier for users to upgrade, rather than pointing out any usage of deprecated features.

I'm also not a painless expert, but it looks like `inline`/`stored` are primarily used as part of requests, rather than being part of the cluster/index configuration and metadata, which is outside the scope of the deprecation info API.  Correct me if I'm wrong here, though.

**Comment by ppf2** [comment]
I was previously thinking about scripts that may end up making it into the cluster state like ML datafeed configs, but those should have migrated to persistent tasks by 8.0, so you are right, the script thing is probably not relevant here :) thx!

**Comment by gwbrown** [comment]
This should have been closed a long time ago - 8.0 is long since out and these checks completed!
