### ISSUE TITLE
Refactor rollups meta (AKA Rollup V2)

### ISSUE THREAD

**Issue by polyfractal** [elastic/elasticsearch#42720]
This is a meta issue discussing a complete rewrite of the Elasticsearch rollup codebase with the aim to improve the following points:

- Drop rollup jobs in favour of integrating rollups with ILM. This means that rolling up an index will work similarly to shrinking an index. The rollup will be done when indexing is complete and the action will rollup the entire index at the same time. 
- Make rollup functionality easier to setup and administer from an operational point of view. For example, allow limited editing of existing rollup configuration (add new metrics etc)
- Make rollup indices behave much more like regular indices, simplifying querying and management.
- Improve reliability. Existing rollup jobs are not atomic and sometimes fail midway, leaving rollup indices that are not complete. We should make the rollup computation atomic.
- Improve performance of rollup jobs. Some large-scale use cases can run into bottlenecks where the search phase of rollup is not fast enough (due to limited thread involvement across cluster).
- Implement support for pre-aggregated data structures to enable cardinality, percentiles https://github.com/elastic/elasticsearch/issues/33214

Below we outline a high level plan of changes that will help us achieve the above goals:

 - [ ] Remove the `_rollup_search` endpoint in favour of [implementing search on rollup indexes within the `_search` endpoint](https://github.com/elastic/elasticsearch/issues/48005) (#67783) @csoulios 
 - [x] Create an `aggregate_metric` field type that will store pre-aggregated metrics (`min`, `max`, `sum` etc) for a specific rollup group. (#49830)
 - [x] Modify existing metric aggregations so that they operate on the `aggregate_metric` fields. The `aggregate_metric` field type will provide the correct metric to the requesting aggregator, while using the same field name. This field type will not be indexed but stored as a binary doc values. (#53986)
 - [x] Modify aggregators to pull doc count rather than just incrementing. Allows the aggregator framework to treat a single "rollup" document as if it were multiple "raw" documents. (#58339)
 - [x] Create a `rollup_meta` cluster metadata to store information such as date_histogram interval and timezone etc. (https://github.com/elastic/elasticsearch/pull/64680)
- [x] Create new Rollup endpoint to rollup indices based on the new model (https://github.com/elastic/elasticsearch/pull/64900)
 - [x] Create an ILM rollup action and remove the rollup job functionality. [issue](https://github.com/elastic/elasticsearch/issues/48003), [PR](https://github.com/elastic/elasticsearch/pull/65633) @talevy 
- [ ] Refactor out all the Rollup-V2 mentions in the code-base in favor of the Rollup-Action [issue](https://github.com/elastic/elasticsearch/issues/65621) @talevy
- [ ] [Docs] Rollup Documentation (meta tracking issue: #65515)
- [ ] Fix muted tests that are flaky (https://github.com/elastic/elasticsearch/issues/69799)
- [ ] Add ability for doing rollups of rollups. This means supporting `_doc_count` field and `aggregate_metric_double` fieldtypes (#70534)
- [ ] Rollup Action Improvements and Testing 
  - [ ] Action should ensure that relevant index-metadata/settings is copied to rollup index (hidden index?, tier?, ILM Execution state?)
  - [ ] Resolving simplification strategies (#70334)
  - [ ] (Maybe, depending on ILM Simplification) Add ability for Rollup ILM Action to optionally-delete original index upon rollup. This means atomically removing the original index and adding the rollup index into the datastream backing indices.
  - [x] Rollup Action must throw exception when rollup index already exists [issue](https://github.com/elastic/elasticsearch/issues/65769)
  - [x] DateHistogramGroupConfig is re-using the original config with a `delay` option, need to make a new Action-specific config without a delay
  - [x] add more config verification before executing the action
  - [x] Add more thorough tests for various groupings in the indexer
  - [ ] Add Rally benchmark for rolling up indices
  - [x] investigate Jim's new broadcast action [gh compare link](https://github.com/elastic/elasticsearch/compare/master...jimczi:rollup_action_shard_base?expand=1)

**Comment by exekias** [comment]
ey @polyfractal I see this concept of "Grouping Tuple" really interesting for the metrics use case. I think doesn't only apply to rollups, but can be used in some queries too!

It actually sounds familiar to what I did in Beats here: https://github.com/elastic/beats/pull/10293, where we want to have enough information to do downsampling on query time to make sure results actually make sense. I wonder if we could reuse this grouping tuple field here?

**Comment by pcsanwald** [comment]
Great outline! I think the additional thing that would be good to think about and add to the outline, is what the migration path looks like for users currently using roll ups (I’m assuming that the new field type would happen during a rollup ILM action and therefore wouldn’t require a full re-index or source index?) and also what breaking changes we are proposing (at least `_rollup_search` removal).

**Comment by giladgal** [comment]
Regarding the relation with the Rollup functionality that is already released: Rollup is currently an experimental feature in Elasticsearch. We plan to make Rollup GA when we release the refactored rollup which will make rolled up indices queryable through _search and _async_search and which will make rollup an action in ILM. We are not making Rollup GA before that because we know this change will bring a change in the API. We will make an effort to provide an upgrade path for Rollup indices created with the current Rollup processes to the new refactored Rollup system, which will make these indices queryable through the _search and _async_search API endpoints.

**Comment by mbudge** [comment]
Will rollups handle new fields arriving in the data?

For example winlogbeat adds new fields when one appears in the windows event log. 

Would this new field get rolled up automatically or would we have to manually modify the rollup job?

**Comment by polyfractal** [comment]
Hiya @mbudge.  The first iteration won't auto-add new fields arriving in the data, so it will require manually adjusting the "job" each time (although in v2 the "job" is just an ILM policy, so it'll be updating the policy so that new rollovers can handle the new fields).

But handling dynamic data is on our short-list of things to investigate after the first release, since it's a very common situation that we'd like to make easier.  Lots of different metric sources introduce new fields routinely so it's a common request by users.

**Comment by rokcarl** [comment]
How will v2 integration work with Kibana? Will additional work need to be done on Kibana as well to get the benefits of v2?

I would benefit from three improvements in the improved rollups in terms of data, but I would like to display the results on a dashboard, e.g. "give me the count of unique customers per week". It will be possible to get the data from Elasticsearch with the #33214 ticket for cardinality, but I'm not sure if this will then automatically work in Kibana and I'll be able to create the dashboards, or will we have to wait for that?

**Comment by polyfractal** [comment]
> How will v2 integration work with Kibana? Will additional work need to be done on Kibana as well to get the benefits of v2?

The way it is shaping up right now, v2 should "just work" in Kibana without extra configuration (unlike v1, which needs special Rollup index patterns).  Since we're building dedicated field types that store pre-aggregated rollup data, this means we can use the regular search endpoint to search both regular and rollup data.  So rollup data is treated just like any other data, which also means that Kibana shouldn't particularly care where the data is coming from (within the limits of the rollup, like matching timezones or date histogram intervals, etc).

We're still working out the details and I'm sure there will be situations that doesn't work quite as nicely, but it should be considerably more flexible than v1.  
> It will be possible to get the data from Elasticsearch with the #33214 ticket for cardinality, but I'm not sure if this will then automatically work in Kibana and I'll be able to create the dashboards, or will we have to wait for that?

This is a good example of where we hope it to "just work".  Once Rollup supports storing cardinality sketches in dedicated field types, the cardinality aggregation will be able to operate over it just like normal numerics, which then means dashboards won't care whether it's rollup or regular data.  Just like a cardinality agg doesn't care about `double` vs `long` today, in the future it will also know how to read the "cardinality" field type.

Hope that helps!

**Comment by ppf2** [comment]
The ability for rollup API to generate time-based indices that can be managed/retired over time is a common ask from the field.  +1 on ILM integration.

**Comment by csoulios** [comment]
The team has decided that there is a great fit between rollups and the new metrics database we are implementing (#74660). 

The fact that dimensions and metrics are first class citizens allows us to simplify the rollup configuration. Also, leveraging the index structure in TSDB results  in greatly improved performance. 

The team views rollups as a fundamental operation of a metrics database and we focus all our efforts to develop such a feature. Hence, I am closing this issue and work on rollups/downsampling will be tracked inside #74660.
