### ISSUE TITLE
Replace Agg integration tests with AggregatorTestCase

### ISSUE THREAD

**Issue by polyfractal** [elastic/elasticsearch#42893]
Similar in spirit to https://github.com/elastic/elasticsearch/issues/36015, but with the goal of removing unecessary metric/bucket agg IT.  Unlike the pipeline aggs, it should be very straightforward to replace, and I think we can probably remove most of the existing `ESIntegTestCase` tests

Some of these aggs do already have an `AggregatorTestCase`, so we should evaluate if the IT has something the unit test does not, migrate if possible and decide if the IT is useful otherwise.

A quick skim shows a lot of the IT deal with scripts, unmapped fields, formatting, etc.  It's not clear to me right now if we can test some of these (notably scripts) outside of an IT.  So that might be a reason to keep the IT around.

#### Metrics
- [x] AvgIT (https://github.com/elastic/elasticsearch/pull/44076)
- [x] CardinalityIT (https://github.com/elastic/elasticsearch/pull/80951)
- [ ] ExtendedStatsIT
- [ ] GeoBoundsIT
- [ ] GeoCentroidIT
- [ ] HDRPercentileRanksIT
- [ ] HDRPercentilesIT
- [x] MaxIT (https://github.com/elastic/elasticsearch/pull/45030)
- [x] MinIT (https://github.com/elastic/elasticsearch/pull/50053)
- [ ] ScriptedMetricIT
- [ ] StatsIT
- [ ] SumIT
- [ ] TDigestPercentileRanksIT
- [ ] TDigestPercentilesIT
- [ ] TopHitsIT
- [ ] ValueCountIT

#### Bucket
- [ ] StringTermsIT
- [ ] AdjacencyMatrixIT
- [ ] BooleanTermsIT
- [ ] DateHistogramIT
- [ ] DateHistogramOffsetIT
- [ ] DateRangeIT
- [ ] DiversifiedSamplerIT
- [ ] DoubleTermsIT
- [ ] FilterIT
- [ ] FiltersIT
- [ ] GeoDistanceIT
- [ ] GeoHashGridIT
- [ ] GeoDistanceIT
- [ ] GlobalIT
- [ ] HistogramIT
- [ ] IpRangeIT
- [ ] IpTermsIT
- [ ] LongTermsIT
- [ ] MinDocCountIT
- [x] MissingIT (#53448)
- [ ] NaNSortingIT
- [ ] RangeIT
- [ ] ReverseNestedIT
- [ ] SamplerIT
- [ ] ShardREduceIT
- [ ] ShardSizeTermsIT
- [ ] SignificantTermsSignificanceScoreIT
- [ ] NestedIT
- [ ] TermsDocCountErrorIT
- [ ] TermsShardMinDocCountIT
