### ISSUE TITLE
Refactor ValuesSource and related classes

### ISSUE THREAD

**Issue by not-napoleon** [elastic/elasticsearch#42949]
The aggregations framework defines several similar but subtly different classes & enums to represent what type of data an aggregation operates on.  Their correct usage and interaction is not obvious, especially to new developers.  This refactoring aims to make input type specification for aggregations easier to understand.
## Plan
To replace the assorted hard coded `ValuesSource` references, we want to build a dynamic registry which will map Field types to Values Sources and specific aggregator implementations.

### TODO - ~before~ Fast follow after merging to master
- [x] Get hard coded `ValuesSources` out of `ValuesSourceConfig`
    - [x] `toValuesSource` (#48320)
    - [x] `resolve` - This will get done with the registry prototype
- [x] Registry Prototype (#48758)
    - [x] Look up aggregators by `ValueSourceType` (working in prototype for simple case)
    - [x] Resolve `ValuesSourceType` dynamically
- [x] Formalize registration process
    - [x] Finalize where registration happens for core aggregations
    - [x] Finalize where registration happens for plugin aggregations & aggregators
    - [x] Replace prototype singleton with production-ready implemetation #51710
    - [x] Demonstrate that we can correctly register a new type from a plugin. #53298 
- [ ] Convert Aggregations
    - [ ] Core
        - [x] Geo Centroid (@talevy) #53040 
        - [x] Geo Hash Grid (@talevy) #53037
        - [x] Geo Tile Grid (@talevy) #53037
        - [x] Auto Date Histogram (Tozzi) #55687
        - [x] Date Histogram (Tozzi) #53484
        - [x] Histogram
        - [x] Missing #53511
        - [x] Date Range #52918
        - [x] Geo Distance (@talevy) (depends on RangeAggregator)
        - [x] IP Range #55831
        - [x] Range #52918
        - [x] Diversified
        - [x] Significant Terms #52590
        - ~[ ] Significant Text (@polyfractal  WIP)~ not VSAB
        - [x] Rare Terms #52166
        - [x] Terms -  #51182 
        - [x] Average - #52752
        - [x] Cardinality - #51337 
        - [x] Extended Stats - #53227
        - [x] Geo Bounds (@talevy) #53033 #53034
        - [x] Max - #52219 
        - [x] Median - #52945
        - [x] Min - #52219 
        - [x] Percentile Rank - #51693 
        - [x] Percentiles - #51639
        - [x] Histo field / percentiles @polyfractal #53298
        - [x] Stats - #52891
        - [x] Sum - #52571
        - [x] Value Count - #52225 
    - [ ] Analytics Package
        - [x] String Stats - #52875
        - [x] Boxplot - #53132
    - [x] Parent Join Package
        - [x] Children (Tozzi)
        - [x] Parent (Tozzi)
- [x] Remove the EquivalenceType/isA logic in `ValueType`.  This will involve changing how we do type checking of userValueTypeHints in the parser. #53198
- [ ] Additional Testing
    - [ ] Numeric metric aggs (e.g. Max) formatting for date values
    - [ ] Mock-script unit tests for `ValuesSource` based aggs
    - [ ] Unmapped & missing tests for Auto Date Histogram
    - [ ] Unmapped & Missing tests for Geo aggs
    - [ ] Add the supported type tests to the remaining aggs
    - [ ] Plugin support for automated field test
- [x] Remove (or at least dramatically decrease the surface area of) `ValueType`
    - Non-VSAB aggregations still use `ValueType`, but refactoring those is out of scope for the initial merge.
    - VSAB still uses `ValueType` for parsing user value hints.  There's a post-merge PR for removing that.
- [x] Remove `ValuesSourceType` info from `ValuesSourceAggregationBuilder` (#48638)
- [x] Remove generic from `ValuesSourceConfig` (and probably other places)
- [x] Remove remaining special behavior around `ValuesSourceType.ANY` & and remove ANY #51539
- [x] Don't rely on serializing `CoreValuesSourceType` #51276
- [ ] Remove any remaining hard coded `ValuesSource` references
- [x] Make `ValuesSourceConfig` immutable #52729
- [x] Package Docs for `o.e.s.aggregations.support` (Tozzi) #53427
- [ ] Ask Kibana QA to run their tests as a real-world integration/smoke test for missed or accidentally altered semantics - We'll get this for "free" once we merge to master
- [ ] CCS Testing with 7.x

### TODO - backport
- [x] Remove `List.of()` usage
- [ ] CCS Testing with 6.x
- [ ] Extra-careful review of exception types to make sure we don't have breaking changes
- [ ] PRs to cherry pick from master:
    - [x] Tests for agg missing values #51068 (Tozzi)
    - [x] Refactor Percentiles/Ranks aggregation builders and factories #51887 (PR: https://github.com/elastic/elasticsearch/pull/54537)
    - [x] Unit tests for Range and DateRange aggs #52380 (Tozzi)
    - [x] Comprehensively test supported/unsupported field type:agg combinations #52493 (PR: https://github.com/elastic/elasticsearch/pull/54451)
    - [x] Add supported type tests for Percentiles/Ranks #52597
    - [x] Use newIndexSearcher() to avoid incompatible readers in AggregatorTestCase#testSupportedFieldTypes #52723 (PR: https://github.com/elastic/elasticsearch/pull/54451)
    - [ ] Tests introduced in https://github.com/elastic/elasticsearch/issues/53431

### TODO - Post merge

- [x] After all VSAB aggregations are converted, remove the legacy shim from VSRegistry
- [x] Stop returning null ValuesSource from VSConfig for unmapped case - see #53238
- [ ] Deprecation plan for `serializeTargetValueType` (doesn't strictly need to be part of this refactor).  The following classes override this method:
    - `CardinalityAggregationBuilder`
    - `MissingAggregationBuilder`
    - `ValueCountAggregationBuilder`
    - `RareTermsAggregationBuilder`
    - `SignificantTermsAggregationBuilder`
    - `TermsAggregationBuilder`
- [x] Unify constructor signature (and thus `AggregatorSupplier`) between Min&Max and other metrics.
- [ ] Clean up user value hint parsing - see #53424
- [ ] ValuesSourceRegistry for `MultiValuesSourceAggregationBuilder` subclasses
- [ ] ValuesSourceRegistry for `ArrayValuesSourceAggregationBuilder` subclasses
- [ ] Remove remaining uses of `ValueType`
- [ ] Rename everything.

## Out of Scope:
After considerable discussion, we've decided to deal with the multivalued aggregations at a later point.  The current abstractions there aren't working as well as we'd like, so investing more in them right now doesn't seem like a good use of time.  

#### ValuesSource & its subclasses
These are thin wrappers which provide a unified interface to different ways of getting input data (e.g. DocValues from Lucene, or script output).  A class hierarchy defines the type of values returned by the source.

#### ValueSourceType
A small enum who's values roughly correspond to the first level subclasses of `ValuesSource`.  This gets passed as a constructor argument to `ValuesSourceConifg` as a hint for what type of values source it should later construct. 

#### ValueType
A more robust enum specifying a wider range of types than `ValuesSourceType`.  The instances of this enum provide a mapping back to a `ValuesSourceType`.  This is used when users supply type hints, e.g. as part of a missing value specification.

#### ValuesSourceConfig
This class resolves the actual `ValuesSource` to use on a given shard for the aggregation.  It considers script values, missing values, and mapped fields.

#### ValuesSourceAggregationBuilder
This is the base class for all aggregations using the value source model, and it ties together usage of all of the above classes.  It is generic over a `ValuesSource` class, and accepts a `ValuesSourceType` and two `ValueType` parameters.  How those different value classes interact is not at all obvious; a good first step at this refactoring would be just documenting those relationships.  

### Next Steps
I'm open to discussion as to what the best way to clean this up should be.  In the interest of seeding that discussion, the following are my first-pass suggestions.

#### Clarify ValuesSourceAggregationBuilder
This would consist of descriptive field names & comments around the intended use of the various type parameters `ValuesSourceAggregationBuilder` accepts.  Some javadoc on the intended roles of `ValueSourceType` and `ValueType` would help too.

#### Formalize relationship between `ValuesSourceType` and `ValuesSource`
Currently, these are related via some cascading `if` statements in `ValuesSourceConfig`, but this misses out on many of the benefits of having an enum in the first place.  Notably, nothing enforces that all enum values are accounted for, and developers wishing to understand the relationship between two classes must look to a third class for that information.

#### ValueSourceType.ANY
`ValuesSourceType.ANY` creates a few edge cases.  It's the only `ValuesSourceType` that doesn't map cleanly back to a `ValuesSource` subclass.  `ValuesSourceConfig` interprets it as a bytes source, except in the case of a script, which allows `BYTES` but not `ANY`.  Aggregations that can operate on multiple input types (e.g. TermsAggregation, which can operate on strings or numbers) use `ValuesSourceType.ANY` to indicate this, which is deceptive since later in the process they are restricted to more specific source types.

#### ValuesSourceType Ordinal Serialization Issue
In addition to any other refactoring work being done here, `ValuesSourceType` is an enum being serialized by ordinal value, which is prone to error.  If we keep this enum, we should adopt a pattern of serializing based on an ID we control, to allow for deletes & reorderings later.  See `ValueType`, which does this correctly.

#### `ValueType.NUMBER` and `ValueType.NUMERIC`
`ValueType` specifies both `NUMBER` and `NUMERIC`, which are apparently identical as far as the enum is concerned.  There's a five year old TODO asking about the difference between these two.  We should either merge them, or clarify why we need both.

#### Rename `ValuesSource`
`ValuesSource` is very close to `ValueSource`, which is an interface in `org.elasticsearch.ingest`.  It's easy to pull up the wrong class in Intellij, especially if you've only heard the name not seen it.

**Comment by not-napoleon** [comment]
# Notes from discussion on 2019-06-19

## `ValuesSourceType.ANY`
There are some aggregations, e.g. Value Count and Cardinality, which actually do accept any input type.  We need to continue to support this use case in some way, although it doesn't need to be specifically via `ValuesSourceType.ANY`.  We proposed using an array or enum set of `ValuesSourceType`s to represent the valid input types for an aggregation, at the builder level.  We agreed that we do not want to have type specific builder classes (e.g. `StringTermsAggregationBuilder`), although the actual aggregators can be type specific.

## Does `ValuesSourceAggregationBuilder` need to be generic over `ValuesSource`
VSAB takes a type parameter that extends `ValuesSource`, and we feel it is not clear why this is useful.  It seems redundant with the `ValuesSource` type hierarchy.  Aggregations which only operate on one `ValuesSource` know that, and aggregations which operate on multiple `ValuesSource`s just pass the base class as the type parameter.  (e.g. terms aggregation, which works on numbers and strings, declares its builder as `public class TermsAggregationBuilder extends ValuesSourceAggregationBuilder<ValuesSource, TermsAggregationBuilder>`)

**Comment by not-napoleon** [comment]
We should also make sure that type errors are consistent in how they are reported to the user.  Currently, some situations throw `IllegalArgumentException` and others throw `AggregationExecutionException`.  Ideally, we'd pick one for type errors and just use that.  Most important though is that we use a 400 class error - type errors are user fixable, and shouldn't return 500s.

**Comment by polyfractal** [comment]
Re: Immutability of VSConfig

Spotted a location where we use the mutability: [`ParentAggregationBuilder`](https://github.com/elastic/elasticsearch/blob/master/modules/parent-join/src/main/java/org/elasticsearch/join/aggregations/ParentAggregationBuilder.java#L107-L125).  We resolve the child field, then check to make sure the parent field is mapped.  If it's not mapped we set the config to unmapped, otherwise we set a new field context as the combined parent/child field context.

We can re-arrange the unmapped part (check parent first), but not sure how to handle the new fieldtype overwriting.  Maybe generate a new config builder from the first config, set the new context and re-build? Dunno. :)

**Comment by talevy** [comment]
hey @not-napoleon, I notice there is some interdependence on ValuesSource and the CompositeValuesSourceBuilder#innerBuild, which I believe gets built after parsing in CompositeAggregationBuilder's parser. Given that this parsing assumes a one-to-one relation between builders and their supported valuessource types, I am not sure how to best generalize it across potential the registered aggregators. 

Are there any aspects of this that you've run into and have thoughts about?

**Comment by not-napoleon** [comment]
@talevy Yeah, Composite aggs work on a whole parallel system.  That's one of the things (along with Array and Multi values source aggregations) that we cut from supporting in the refactor for now.  Obviously at some point we need to come back to that, but it's not currently on my todo list.

**Comment by not-napoleon** [comment]
With many thanks to everyone who's contributed code, reviews, comments, and moral support to this project, I'm happy to say that with #57762 merged, we can call this done.  There is still some related cleanup work that can be done, but it's pretty low priority right now and has other tickets tracking it (see #58139,  #58135, and #58136).  Please feel free to tag me with any values source related issues going forward.
