### ISSUE TITLE
[DOCS] Reformat index API documentation

### ISSUE THREAD

**Issue by jrodewig** [elastic/elasticsearch#43765]
Where possible, we should standardize our index API documentation to match the [Elastic API reference template](https://github.com/elastic/docs/blame/master/shared/api-ref-ex.asciidoc).

Relates to elastic/docs#937.

#### Index APIs to rewrite
- [x] Create Index (#45749)
- [x] Delete Index (#45755)
- [x] Get Index (#45758)
- [x] Indices Exists (#45918)
- [x] Close Index API (#45922)
- [x] Open Index API (#45921)
- [x] Shrink Index (#46711)
- [x] Split Index (#46713)
- [x] Rollover Index (#46778)
- [x] Clone Index (#46762)
- [x] Put Mapping (#45709)
- [x] Get Mapping (#45699)
- [x] Get Field Mapping (#45700)
- [x] Types Exists (#47601)
- [x] Add index alias (#46086)
- [x] Delete index alias (#46080)
- [x] Get index alias (#46046)
- [x] Index alias exists (#46042)
- [x] Update index alias (#46093)
- [x] Update Indices Settings (#45931)
- [x] Get Settings (#45924)
- [x] Analyze (#45986)
- [x] Put index template (#46297)
- [x] Delete index template (#46101)
- [x] Get index template (#46296)
- [x] Index template exists (#46095)
- [x] Indices Stats (#46322)
- [x] Indices Segments (#46345)
- [x] Indices Recovery (#46493)
- [x] Indices Shard Stores (#46504)
- [x] Clear Cache (#46512)
- [x] Flush (#46875)
- [x] Synced flush (#46634)
- [x] Refresh (#46634)
- [x] Force Merge (#46685)
