### ISSUE TITLE
Follow-up improvements to `flattened` object fields.

### ISSUE THREAD

**Issue by jtibshirani** [elastic/elasticsearch#43805]
This meta-issue tracks improvements to `flattened` object fields. The initial version of the feature was designed + tracked in #33003.

- [ ] Add support for additional query types like wildcard, regex, and fuzzy.
- [ ] Clean-up and add benchmarks to the metricbeat rally track.
- [ ] (needs research) Index all keys in the JSON object under a special subfield like `_keys`. Then a terms aggregation could be run on `my_flat_object._keys` to provide a list of available keys.
- [ ] (needs research) Changes needed in response to feedback from Kibana team.

**Comment by mrkamel** [comment]
+1 for supporting a numeric flattened type

**Comment by user718** [comment]
+1 on list of all available keys from flattened object

**Comment by TinaHeiligers** [comment]
+1 for supporting a numeric flattened type for `ui_metric` mappings in the Telemetry cluster `xpack-phone-home` and `all-xpack-phone-home` indices

**Comment by yshyshkin** [comment]
+1 for supporting a numeric flattened type

**Comment by Vasniktel** [comment]
+1 for wildcard and numeric types. Also, is there a timeline for this?

**Comment by mkolesnikov** [comment]
+1 for normalizer parameter like for keyword

**Comment by Rosomaha** [comment]
+1 for normalizer parameter like for keyword
