### ISSUE TITLE
[DOCS] Reorganize, rewrite and add examples to analysis topics

### ISSUE THREAD

**Issue by kat257** [elastic/elasticsearch#44726]
As part of the larger effort to update and improve Elasticsearch docs, the Analysis section is in need of a revamp. Relevant issues: the topics vary in depth and completeness; some have dated examples or examples that are not consistent; chunking may need to be removed or added; and the organization is arbitrary and does not always show the relationship between one topic and another. 

To make these changes, docs covered by this issue will incorporate a revised, standardized structure. For example, in token filters, I'll add examples, configuration parameters, and customization options, and replace circular definitions such as "NGram Token Filter: A token filter of type ngram" with a complete definition and explanation about when the user would expect to employ that filter. 

**Proposed structure:**

1. Title (Level 2): Definition and explanation of topic
2. Example (Level 3): Vanilla example and output
3. Configure parameters (Level 3): Parameters available with descriptions
4. Customize (Level 3): How to customize 
5. Example (Level 4): Customize example and output

PRs will be revised as I work through the topics. Some PRs may include more than one topic when changes are small and comparable across topics. 

**Top Level Docs**
- [x] analysis (nav +intro) #51184
- [x] overview #50515
- [x] concepts #50801
  - [x] Index time vs search time analysis #51184
  - [x] Stemming #55156
  - [x] Token graphs #53339
- [x] Configure text analysis #50809
  - [x] Specify an analyzer #51184

**Sections**
_Analyzers_ #58362
- [x] fingerprint-analyzer
- [x] keyword-analyzer
- [x] lang-analyzer
- [x] pattern-analyzer
- [x] simple-analyzer #58910
- [x] standard-analyzer
- [x] stop-analyzer
- [x] whitespace-analyzer

_Character Filters_
- [x] htmlstrip-charfilter #57764
- [x] mapping-charfilter #57818
- [x] pattern-replace-charfilter

_Token Filters_
- [x] apostrophe-tokenfilter #48076
- [x] asciifolding-tokenfilter #48143
- [x] cjk-bigram-tokenfilter #48210
- [x] cjk-width-tokenfilter #48210
- [x] classic-tokenfilter #48314
- [x] common-grams-tokenfilter #48426
- [x] compound-word-tokenfilter #49006
- [x] condition-tokenfilter #48775
- [x] decimal-digit-tokenfilter #48722
- [x] delimited-payload-tokenfilter #49380
- [x] edgengram-tokenfilter #49438
- [x] elision-tokenfilter #49262
- [x] fingerprint-tokenfilter #49311
- [x] flatten-graph-tokenfilter #54268
- [x] hunspell-tokenfilter #56955
- [x] keep-types-tokenfilter #49604
- [x] keep-words-tokenfilter  #49604
- [x] keyword-marker-tokenfilter #54076
- [x] keyword-repeat-tokenfilter #54428
- [x] kstem-tokenfilter #55823
- [x] length-tokenfilter #49805
- [x] limit-token-count-tokenfilter #49835
- [x] lowercase-tokenfilter #49935
- [x] minhash-tokenfilter #57181
- [x] multiplexer-tokenfilter #57555
- [x] ngram-tokenfilter #49438
- [x] normalization-tokenfilter
- [ ] pattern-capture-tokenfilter #57664
- [x] pattern_replace-tokenfilter #57699
- [x] phonetic-tokenfilter
- [x] porterstem-tokenfilter #56053
- [x] predicate-tokenfilter #57705
- [x] remove-duplicates-tokenfilter #53608
- [x] reverse-tokenfilter #50672
- [x] shingle-tokenfilter #57040
- [x] snowball-tokenfilter #56394
- [x] stemmer-override-tokenfilter #56840
- [x] stemmer-tokenfilter #55693
- [x] stop-tokenfilter #53059
- [x] synonym-graph-tokenfilter #53901
- [x] synonym-tokenfilter
- [x] trim-tokenfilter #51649
- [x] truncate-tokenfilter #50687
- [x] unique-tokenfilter #50748
- [x] uppercase-tokenfilter #50555
- [x] word-delimiter-graph-tokenfilter #53170
- [x] word-delimiter-tokenfilter #53387

_Tokenizers_ #58361
- [x] chargroup-tokenizer
- [x] classic-tokenizer
- [x] edgengram-tokenizer
- [x] keyword-tokenizer
- [x] letter-tokenizer
- [x] lowercase-tokenizer
- [x] ngram-tokenizer
- [x] pathhierarchy-tokenizer-examples
- [x] pathhierarchy-tokenizer
- [x] pattern-tokenizer
- [x] simplepattern-tokenizer
- [x] simplepatternsplit-tokenizer
- [x] standard-tokenizer
- [x] thai-tokenizer
- [x] uaxurlemail-tokenizer
- [x] whitespace-tokenizer

**Comment by debadair** [comment]
[docs issue triage]
