### ISSUE TITLE
Reformat Cluster API Reference Documentation 

### ISSUE THREAD

**Issue by jrodewig** [elastic/elasticsearch#45197]
Updates the cluster API documentation to match the [Elastic API reference template](https://github.com/elastic/docs/blame/master/shared/api-ref-ex.asciidoc).

Relates to elastic/docs#937 and #45195

- [x] Cluster Health (#45206)
- [x] Cluster State (#45206)
- [x] Cluster Stats (#45270)
- [x] Pending cluster tasks (#45280)
- [x] Cluster Reroute (#45328)
- [x] Cluster Update Settings (#45337)
- [x] Cluster Get Settings (#45337)
- [x] Nodes Stats (#45441)
- [x] Nodes Info (#45446)
- [x] Nodes Feature Usage (#45539)
- [x] Remote Cluster Info (#45545)
- [x] Task Management API (#45549)
- [x] Nodes hot_threads (#45597) 
- [x] Cluster Allocation Explain API (#45603)
- [x] Voting Configuration Exclusions (#45644)

**Comment by szabosteve** [comment]
Cluster API documentation has been updated. I close the issue.
