### ISSUE TITLE
Reformat ES API Reference Documentation

### ISSUE THREAD

**Issue by jrodewig** [elastic/elasticsearch#45195]
Updates the Elasticsearch API documentation to match the [Elastic API reference template](https://github.com/elastic/docs/blame/master/shared/api-ref-ex.asciidoc).

Relates to elastic/docs#937.

- [x] cat APIs (#45196)
- [x] Cluster APIs (#45197)
- [x] Cross-cluster replication APIs
- [x] Data frame transform APIs
- [x] Document APIs (#45365)
- [x] Explore API
- [x] Index APIs (#43765)
- [x] Index lifecycle management API
- [x] Ingest APIs (#47049)
- [x] Info API
- [x] Licensing APIs
- [x] Machine learning anomaly detection APIs
- [x] Machine learning data frame analytics APIs
- [x] Migration APIs
- [x] Reload Search Analyzers (#47824)
- [x] Rollup APIs
- [x] Search APIs (#45621)
- [x] Security APIs
- [x] Snapshot lifecycle management API (#45620)
- [x] Watcher APIs

**Comment by jrodewig** [comment]
[docs issue triage]

Leaving open as this is still relevant.
