### ISSUE TITLE
[DOCS] Reformat Document API Reference Documentation

### ISSUE THREAD

**Issue by debadair** [elastic/elasticsearch#45365]
Updates the document API documentation to match the Elastic API reference template.

- [x] Index (https://github.com/elastic/elasticsearch/pull/45415)
- [x] Get (https://github.com/elastic/elasticsearch/pull/45416)
- [x] Delete (https://github.com/elastic/elasticsearch/pull/45422)
- [x] Delete by query (https://github.com/elastic/elasticsearch/pull/46051)
- [x] Update (https://github.com/elastic/elasticsearch/pull/45423)
- [x] Update by query (https://github.com/elastic/elasticsearch/pull/46199)
- [x] Multi get (#47477) 
- [x] Bulk (#47479)
- [x] Reindex (#47483)
- [x] Term vectors (#47484)
- [x] Multi term vectors (#47484)

Relates to elastic/docs#937 and #45195

**Comment by jrodewig** [comment]
[docs issue triage]

Leaving open as this is still relevant.

**Comment by debadair** [comment]
The changes are all merged to master. Will close when I've finished the backports.

**Comment by debadair** [comment]
Backported.
