### ISSUE TITLE
[DOCS] [Roadmap] Add "Getting data into Elasticsearch" section

### ISSUE THREAD

**Issue by jrodewig** [elastic/elasticsearch#45471]
As part of our ongoing roadmap, we plan to add the following chapters to the Elasticsearch Reference Guide:

- Get data into Elasticsearch
	- Choose an ingest method
	- Configure data mappings
	- Analyze text strings

### Tasks

- [x] Rewrite [Mapping](https://www.elastic.co/guide/en/elasticsearch/reference/master/mapping.html) to include API examples and tutorial. (#45520)
- [ ] Add Field datatypes, Meta-Fields, and Mapping parameters to the Reference section
- [ ] Rewrite [Analysis](https://www.elastic.co/guide/en/elasticsearch/reference/master/analysis.html) to include API examples and tutorial.
- [ ] Move conceptual and tutorial information from [Ingest Nodes](https://www.elastic.co/guide/en/elasticsearch/reference/master/ingest.html) to the `Choose an ingest method` chapter
- [ ] Move conceptual and tutorial information from [Mapping](https://www.elastic.co/guide/en/elasticsearch/reference/master/mapping.html) to the `Configure data mappings` chapter
- [ ] Move conceptual and tutorial information from [Analysis](http://get-data.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/master/analysis.html) to the `Analyze text strings` chapter
- [ ] Create Reference section
- [ ] Relocate Ingest APIs to REST APIs section (#45812)
- [ ] Add Processors to the Reference section
- [ ] Add Analyzers, Normalizers, Tokenizers, Token Filters, and Character Filters  to the Reference section

FYI @debadair @wchrisdean
