### ISSUE TITLE
[DOCS] [Roadmap] Reorganize cross-cluster search docs

### ISSUE THREAD

**Issue by jrodewig** [elastic/elasticsearch#45570]
As part of our ongoing roadmap, we plan to reorganize the cross-cluster search documentation.

### Tasks

- [x] Add diagrams to how CCS works (#45569)
- [x] Rewrite CCS page (#45583)
- [x] Move CCS out of modules (#45608)
