### ISSUE TITLE
Reformat search API docs

### ISSUE THREAD

**Issue by jrodewig** [elastic/elasticsearch#45621]
Updates the search API documentation to match the [Elastic API reference template](https://github.com/elastic/docs/blame/master/shared/api-ref-ex.asciidoc).

Relates to elastic/docs#937 and #45195

- [x] Search (#45786)
- [x] URI Search (#45844)
- [x] Request Body Search (#46254)
- [x] Search Template (#46236)
- [x] Multi Search Template (#46236)
- [x] Search Shards API (#46240)
- [x] Suggesters (#47010)
- [x] Multi Search API (#46256) 
- [x] Count API (#46377)
- [x] Validate API (#46389) 
- [x] Explain API (#46857)
- [x] Profile API (#47168)
- [x] Field Capabilities API (#46866)
- [x] Ranking Evaluation API (#46974)

We are only backporting these changes to 7.x and 7.3.

If you begin working on an API, please indicate it as a WIP here to prevent duplicating efforts.

### Example
Before: https://www.elastic.co/guide/en/elasticsearch/reference/7.0/cat-indices.html
After: https://www.elastic.co/guide/en/elasticsearch/reference/master/cat-indices.html

Please feel free to reach out to @jrodewig or @lcawl if you run into issues or questions.
