### ISSUE TITLE
Reformat snapshot lifecycle policy API docs

### ISSUE THREAD

**Issue by jrodewig** [elastic/elasticsearch#45620]
Updates the snapshot lifecycle policy API documentation to match the [Elastic API reference template](https://github.com/elastic/docs/blame/master/shared/api-ref-ex.asciidoc).

Relates to elastic/docs#937 and #45195

- [x] Put Snapshot Lifecycle Policy API (#47811)
- [x] Get Snapshot Lifecycle Policy API (#47827)
- [ ] Execute Snapshot Lifecycle Policy API (#47998)
- [x] Get Snapshot Lifecycle Stats API (#47998)
- [x] Delete Snapshot Lifecycle Policy API (#47998)
- [x] Execute Snapshot Lifecycle Retention API (#47998)

We are only backporting these changes to 7.4.

Branch + file containing working changes:
https://github.com/jrodewig/elasticsearch/blob/reformat.slm-apis/docs/reference/ilm/apis/slm-api.asciidoc

**Comment by dakrone** [comment]
> We are only backporting these changes to 7.x and 7.3.

SLM is only in the 7.x branch (7.4+), so no need to backport to 7.3

**Comment by jrodewig** [comment]
Thanks @dakrone. I've amended the original description.

**Comment by wchrisdean** [comment]
[doc issue triage]
