### ISSUE TITLE
[DOCS] [Roadmap] Move CCR Docs to ES Reference Guide

### ISSUE THREAD

**Issue by jrodewig** [elastic/elasticsearch#45703]
Currently, [cross-cluster replication (CCR)](https://www.elastic.co/guide/en/elastic-stack-overview/master/xpack-ccr.html) documentation is located in the [Stack Overview](https://www.elastic.co/guide/en/elastic-stack-overview/master/index.html).

This relocates CCR documentation to the [Elasticsearch Reference Guide](https://www.elastic.co/guide/en/elasticsearch/reference/master/index.html).

### Tasks
- [x] Rename "Administering Elasticsearch" to "Set up Elasticsearch for high availability." (#45704)
- [x] Add CCR documentation to Elasticsearch Refererence Guide with level offset.  (#45704)
- [x] Redirect anchor links in APM server docs (elastic/apm-server#2589)
- [x] Redirect anchor links in Beats docs (elastic/beats#13288)
- [x] Redirect links in Kibana docs (elastic/kibana#44012)
- [x] Remove CCR documentation from the Stack Overview. (elastic/stack-docs#464)
- [x] Increment headings for CCR docs and remove level offset. (#46818)
