### ISSUE TITLE
Upgrade http-core to 4.4.12 once it gets released

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#45808]
We have recently merged #45379 , but we only later discovered through its tests a bug in the Apache Http Async Client which makes cancelling requests very delicate, as a race condition has been found which may cause the underlying IO Reactor to crash.  See #45577 and https://issues.apache.org/jira/browse/HTTPASYNC-152 . 

#45379 has not been backported. We will backport to 7.x only once the bug has been fixed upstream. We will leave the feature on master, but I am opening this blocker for 8.0.0 to make sure that we remember to:

- [x] upgrade the http-core library to 4.4.12 before releasing 8.0 (#46549)
- [x] unmute `RestClientMultipleHostsIntegTests#testCancelAsyncRequests` and close #45577
- [x] backport `RestSearchCancellationIT` to 7.x, as #43332 has been backported without such integration test given that the low-level REST client does not support cancelling requests

**Comment by javanna** [comment]
This has been addressed, requests cancellation has been backported. Closing.
