### ISSUE TITLE
Migrate bats tests to java

### ISSUE THREAD

**Issue by rjernst** [elastic/elasticsearch#46005]
The bats tests were the original packaging tests, allowing our distributions to be tested on each supported system through vagrant. However, the bats was difficult to write for, and is unmaintained. Writing bats tests was deprecated last year with the addition of the java packaging tests.

This is a meta issue to migrate the remaining bats tests to java. It is a spin off from #32143.

oss bats tests (`qa/os/bats/oss`):

- [x] 70_sysv_initd.bats -  tests for installation with sysvinit

default distribution bats tests (`qa/os/bats/default`):
- [x] 10_basic.bats - smoke tests. everything in here except for testing bin/elasticsearch-croneval is already covered in ported tests
- [x] 20_tar_bootstrap_password.bats and 25_package_bootstrap_password.bats - tests we can set bootstrap.password and that sql-cli handles it - these should be combined into one test case
- [x] 30_tar_setup_password.bats and 35_package_setup_password.bats - tests bin/elasticsearch-setup-passwords - these should be combined into one test case
- [x] 40_tar_certgen.bats and 45_package_certgen.bats - tests for ssl certificates - these should be combined into one test case

plugin bats tests (`qa/os/bats/plugins`):
- [x] 25_tar_plugins.bats and 50_modules_and_plugins.bats - tests plugins can be installed, these are the same for tar vs. packages and should be combined into a single test case

upgrade bats tests (`qa/os/bats/upgrade`):
- [ ] 80_upgrade.bats - tests that the package can be upgraded
