### ISSUE TITLE
Create reusable definition for index aliases

### ISSUE THREAD

**Issue by jrodewig** [elastic/elasticsearch#46098]
As part of #43765, we separated API documentation for index aliases.

#46042 added a definition for "index alias" that's reused across several of those pages.

This effort will:

- [x] Flesh out the "index alias" definition (#46339)
- [x] Migrate the definition to the Elasticsearch glossary(#46339)
- [x] Replace any references to the existing definition with the glossary version (#46339)
- [x] Add the definition to the Stack Overview docs (elastic/docs#1164, elastic/stack-docs#500)
