### ISSUE TITLE
Move the state of search requests to the coordinator node

### ISSUE THREAD

**Issue by jimczi** [elastic/elasticsearch#46523]
This is a meta issue to track the tasks to move the state of a search in the coordinator node.
Today the initial phase of any search creates a `SearchContext` on each node that contains a shard selected for the request. This `SearchContext` is then used as a state on each shard for the subsequent phases. This issue proposes to move from a `SearchContext` on each shard to a `ReaderContext` that would keep track of the index reader that should be used for the entire lifecycle of a search request and to move all the state of the search to the coordinating node.
To achieve this we need to re-create the search context for each phase based on the results of the previous phase. The state of the previous phase can be passed through the result of the phase and added to the request of the next one in order to be able to rebuild the search state.
Here is a list (hopefully exhaustive) of the tasks that need to be done to achieve this:

- [x] Replace the `SearchContext` with `QueryShardContext` when building aggregator factories (#46527)
- [x] Replace the `SearchContext` with `QueryShardContext` when building collapse context (#46543)
- [x] Delay the creation of inner hits's subcontext to the fetch subphase and add a validation when creating the inner hits builder (#46598)
- [x] Cleanup `SubSearchContext` and add a way to clone a `SearchContext` 
- [x] Immutable `SearchContext` that can be fully built from a `ShardSearchRequest`
- [x] Add the rewritten `ShardSearchRequest` to `QuerySearchResult` and ShardFetchRequest(+bwc).
- [x] Re-create the `SearchContext` on each phase in the `SearchService` and register a simple `ReaderContext` in the initial phase that can be used to build the `SearchContext` in the subsequent phase. The bwc layer must handle nodes in previous versions and scrolls so a special context could be used to reference old style requests.
- [x] Add a way to create and delete a `ReaderContext` that can be used as a point in time reader for multiple search requests.

There are plenty of follow ups that we could do once we move the state of the request to the coordinator node. For instance we could create a single reader context per directory reader based on sequence numbers that we could check when a replica fails in order to move the search to a different node if another replica is at the same checkpoint (always the case for read-only indices/frozen indices). 

Closes #26472

**Comment by jimczi** [comment]
The feature was merged in https://github.com/elastic/elasticsearch/pull/61062, hence closing.
