### ISSUE TITLE
[DOCS] ES Documentation Roadmap

### ISSUE THREAD

**Issue by jrodewig** [elastic/elasticsearch#46718]
A list of action items related to the ES documentation roadmap.

- [x] Move cross-cluster search out of modules section & edit (#45570)
- [ ] Add an introduction to Elasticsearch 
- [x] Move CCR into Elasticsearch Reference Guide (#45703)
- [ ] Relocate CCS into search section
- [ ] Revisit the text analysis content and provide more context (#44726)
- [ ] Reconcile the multiple installation sections
- [ ] Create a comprehensive settings reference
- [ ] Improve error messages
- [ ] Curate and improve SQL docs
- [x] Revisit query docs and rewrite where necessary (#40977)
- [ ] Improve breaking changes docs so it’s easier for users to discover breaking changes that affect them
- [x] Move Watcher docs into Elasticsearch Reference Guide (#46716)
- [x] Create "Secure a cluster" section: https://github.com/elastic/elasticsearch/pull/46883
- [x] Move additional security docs into Elasticsearch Reference Guide (#46880)
- [x] Add transform content and group it with rollup content: https://github.com/elastic/elasticsearch/pull/46882 https://github.com/elastic/elasticsearch/pull/46846 and https://github.com/elastic/stack-docs/pull/519
- [x] Create "Monitor a cluster" section: https://github.com/elastic/elasticsearch/pull/46885
- [x] Move additional monitoring docs into Elasticsearch book: https://github.com/elastic/stack-docs/pull/554, https://github.com/elastic/elasticsearch/pull/47184, https://github.com/elastic/kibana/pull/46737, https://github.com/elastic/logstash/pull/11166

**Comment by wchrisdean** [comment]
[doc issue triage]
