### ISSUE TITLE
Prepare for removal of the CMS garbage collector

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/elasticsearch#46973]
### Context

According to [JEP 363](https://openjdk.java.net/jeps/363) (originally [draft JEP 8229049](https://openjdk.java.net/jeps/8229049)) the CMS garbage collector will be removed from OpenJDK ([discussion of the patch](http://mail.openjdk.java.net/pipermail/hotspot-dev/2019-October/039787.html) and [commit](http://hg.openjdk.java.net/jdk/jdk/rev/ba6c248cae19)). The [corresponding discussion on the OpenJDK mailing list](https://mail.openjdk.java.net/pipermail/hotspot-gc-dev/2019-August/026655.html) mentions JDK 14 as targeted JDK. There is currently no release date for [JDK 14](https://openjdk.java.net/projects/jdk/14/) but based on past release cadence we should expect it to be released in late March 2020. As Elasticsearch currently recommends the CMS garbage collector we should be prepared for its removal.  I'm raising this issue as a meta-issue to collect our thoughts on what is missing to run Elasticsearch with a different garbage collector than CMS out of the box.

### Prior work

We have already investigated G1GC as an alternative garbage collector for Elasticsearch in https://github.com/elastic/elasticsearch/pull/33685 and have recently adjusted the out-of-the box settings in https://github.com/elastic/elasticsearch/pull/46169 to improve the effectiveness of Elasticsearch's real-memory circuit breaker with G1GC.

### Tasks

The following list may be incomplete, please add new tasks as needed:

* [x] Ensure we don't use CMS for JDK 14 anymore: https://github.com/elastic/elasticsearch/pull/49123
* [x] Investigate whether we always want to use G1 as the garbage collector (it *might* make sense to ergonomically choose parallel GC for smaller heaps) - see https://github.com/elastic/elasticsearch/issues/46973#issuecomment-565167478.
* [x] Update our default JVM configuration to not use CMS https://github.com/elastic/elasticsearch/pull/49123
* [x] Update our reference documentation to remove any references to CMS (e.g. our [bootstrap checks docs](https://github.com/elastic/elasticsearch/blob/master/docs/reference/setup/bootstrap-checks.asciidoc))

**Comment by ebadyano** [comment]
I did a few experiments with jdk13 G1GC, running `nyc_taxic`, 1 node benchmark on our original nightly benchmarks environment:

1. with 4G heap, I was previously triggering circuit breaker when running with jdk12 and G1GC enabled; with jdk13 I can run to completion fine with even with default (1G heap) and 4G heaps, although the total accumulated GC pauses are slightly higher than with CMS. Indexing throughout is regressed by ~5%

2. With 8G heap, I see an improvement in GC pauses when running with 8G heap and interestingly indexing throughout seems to improve by ~8% at least with `nyc_taxis-1-node`.

3. I tried running with `-XX:+UseStringDeduplication` + G1GC, and for some reason circuit breaker is triggered with 4G heap (didn't try with 1G heap). With 8G heap I see slightly higher accumulated GC pauses with `-XX:+UseStringDeduplication` and indexing throughput is regressed by ~6% compared to G1GC without `-XX:+UseStringDeduplication`

**Comment by ebadyano** [comment]
Logs for 4g heap, G1GC with jdk12 (intermittently fails with circuit breaker, logs with fail and completed runs),  and jdk13 run:
https://drive.google.com/open?id=16clDwJohf50-KA1YFuLzrc7WooUwi9Zg

**Comment by ebadyano** [comment]
Tried `-XX:++UseParallelOldGC` with default and 1g heap with http_logs, it keeps triggering circuit breaker. I tried running with `indices.breaker.total.limit: 99%` it takes a bit longer to trigger circuit breaker, but it still gets there during indexing. With `indices.breaker.total.limit: 99.9%` it triggers circuit breaker intermittently during queries.

**Comment by ebadyano** [comment]
when Parallel GC does finish, indexing and queries seem to be faster for 1g heap:
```
|                                                        Metric |                                        Task |   Baseline |   Contender |     Diff |    Unit |
|--------------------------------------------------------------:|--------------------------------------------:|-----------:|------------:|---------:|--------:|
|                    Cumulative indexing time of primary shards |                                             |    128.667 |     105.868 | -22.7986 |     min |
|             Min cumulative indexing time across primary shard |                                             |     0.4068 |      0.3474 |  -0.0594 |     min |
|          Median cumulative indexing time across primary shard |                                             |    1.26412 |      0.9528 | -0.31132 |     min |
|             Max cumulative indexing time across primary shard |                                             |     18.991 |     15.6193 | -3.37172 |     min |
|           Cumulative indexing throttle time of primary shards |                                             |          0 |           0 |        0 |     min |
|    Min cumulative indexing throttle time across primary shard |                                             |          0 |           0 |        0 |     min |
| Median cumulative indexing throttle time across primary shard |                                             |          0 |           0 |        0 |     min |
|    Max cumulative indexing throttle time across primary shard |                                             |          0 |           0 |        0 |     min |
|                       Cumulative merge time of primary shards |                                             |    111.338 |     105.281 | -6.05687 |     min |
|                      Cumulative merge count of primary shards |                                             |        526 |         523 |       -3 |         |
|                Min cumulative merge time across primary shard |                                             |  0.0459833 |   0.0406833 |  -0.0053 |     min |
|             Median cumulative merge time across primary shard |                                             |   0.279417 |      0.2484 | -0.03102 |     min |
|                Max cumulative merge time across primary shard |                                             |    22.1314 |     21.0968 | -1.03457 |     min |
|              Cumulative merge throttle time of primary shards |                                             |    68.1129 |     65.1518 | -2.96117 |     min |
|       Min cumulative merge throttle time across primary shard |                                             |          0 |           0 |        0 |     min |
|    Median cumulative merge throttle time across primary shard |                                             |          0 |           0 |        0 |     min |
|       Max cumulative merge throttle time across primary shard |                                             |     14.112 |     14.4817 |  0.36973 |     min |
|                     Cumulative refresh time of primary shards |                                             |    13.0514 |     13.4064 |  0.35507 |     min |
|                    Cumulative refresh count of primary shards |                                             |       2130 |        2293 |      163 |         |
|              Min cumulative refresh time across primary shard |                                             |    0.04335 |      0.0387 | -0.00465 |     min |
|           Median cumulative refresh time across primary shard |                                             |     0.1217 |    0.139367 |  0.01767 |     min |
|              Max cumulative refresh time across primary shard |                                             |    1.97307 |     1.96867 |  -0.0044 |     min |
|                       Cumulative flush time of primary shards |                                             |    4.22462 |       4.856 |  0.63138 |     min |
|                      Cumulative flush count of primary shards |                                             |        117 |         115 |       -2 |         |
|                Min cumulative flush time across primary shard |                                             |      0.001 |     0.00415 |  0.00315 |     min |
|             Median cumulative flush time across primary shard |                                             |  0.0108167 |   0.0139667 |  0.00315 |     min |
|                Max cumulative flush time across primary shard |                                             |   0.840933 |      0.9375 |  0.09657 |     min |
|                                            Total Young Gen GC |                                             |    105.258 |      88.501 |  -16.757 |       s |
|                                              Total Old Gen GC |                                             |          0 |      21.663 |   21.663 |       s |
|                                                    Store size |                                             |    19.1857 |     18.9982 | -0.18753 |      GB |
|                                                 Translog size |                                             | 1.7928e-06 |  1.7928e-06 |        0 |      GB |
|                                        Heap used for segments |                                             |    105.664 |     102.275 | -3.38937 |      MB |
|                                      Heap used for doc values |                                             | 0.00476456 |  0.00476456 |        0 |      MB |
|                                           Heap used for terms |                                             |    98.7018 |     95.3662 | -3.33561 |      MB |
|                                           Heap used for norms |                                             | 0.00213623 |  0.00213623 |        0 |      MB |
|                                          Heap used for points |                                             |          0 |           0 |        0 |      MB |
|                                   Heap used for stored fields |                                             |    6.95544 |     6.90169 | -0.05376 |      MB |
|                                                 Segment count |                                             |         35 |          35 |        0 |         |
|                                                Min Throughput |                                index-append |     150090 |      161244 |  11153.6 |  docs/s |
|                                             Median Throughput |                                index-append |     163942 |      170634 |  6692.13 |  docs/s |
|                                                Max Throughput |                                index-append |     195448 |      199597 |  4149.01 |  docs/s |
|                                       50th percentile latency |                                index-append |    234.193 |     208.972 | -25.2208 |      ms |
|                                       90th percentile latency |                                index-append |     359.03 |     339.721 | -19.3083 |      ms |
|                                       99th percentile latency |                                index-append |    1038.53 |     989.105 | -49.4283 |      ms |
|                                     99.9th percentile latency |                                index-append |    1858.92 |     1756.26 |  -102.66 |      ms |
|                                    99.99th percentile latency |                                index-append |    2853.51 |     2383.23 | -470.275 |      ms |
|                                      100th percentile latency |                                index-append |    2880.77 |     2675.52 | -205.252 |      ms |
|                                  50th percentile service time |                                index-append |    234.193 |     208.972 | -25.2208 |      ms |
|                                  90th percentile service time |                                index-append |     359.03 |     339.721 | -19.3083 |      ms |
|                                  99th percentile service time |                                index-append |    1038.53 |     989.105 | -49.4283 |      ms |
|                                99.9th percentile service time |                                index-append |    1858.92 |     1756.26 |  -102.66 |      ms |
|                               99.99th percentile service time |                                index-append |    2853.51 |     2383.23 | -470.275 |      ms |
|                                 100th percentile service time |                                index-append |    2880.77 |     2675.52 | -205.252 |      ms |
|                                                    error rate |                                index-append |          0 |           0 |        0 |       % |
|                                                Min Throughput |                                     default |    8.01299 |     8.01308 |    9e-05 |   ops/s |
|                                             Median Throughput |                                     default |    8.01403 |     8.01398 |   -6e-05 |   ops/s |
|                                                Max Throughput |                                     default |    8.01519 |     8.01524 |    5e-05 |   ops/s |
|                                       50th percentile latency |                                     default |    5.36415 |     5.00933 | -0.35483 |      ms |
|                                       90th percentile latency |                                     default |     5.6521 |     5.43838 | -0.21372 |      ms |
|                                       99th percentile latency |                                     default |    7.69529 |     5.78511 | -1.91017 |      ms |
|                                      100th percentile latency |                                     default |    8.21218 |     7.35293 | -0.85925 |      ms |
|                                  50th percentile service time |                                     default |    5.06884 |     4.70835 | -0.36049 |      ms |
|                                  90th percentile service time |                                     default |    5.35518 |     5.12218 | -0.23299 |      ms |
|                                  99th percentile service time |                                     default |    7.38002 |     5.47012 |  -1.9099 |      ms |
|                                 100th percentile service time |                                     default |    7.89408 |     7.03901 | -0.85508 |      ms |
|                                                    error rate |                                     default |          0 |           0 |        0 |       % |
|                                                Min Throughput |                                        term |    50.0332 |     50.0609 |  0.02773 |   ops/s |
|                                             Median Throughput |                                        term |    50.0368 |      50.061 |  0.02415 |   ops/s |
|                                                Max Throughput |                                        term |    50.0405 |      50.061 |  0.02057 |   ops/s |
|                                       50th percentile latency |                                        term |    12.0435 |     6.72208 | -5.32139 |      ms |
|                                       90th percentile latency |                                        term |    12.6216 |      7.9926 | -4.62904 |      ms |
|                                       99th percentile latency |                                        term |    16.6301 |     11.4386 | -5.19152 |      ms |
|                                      100th percentile latency |                                        term |    20.4803 |     11.9234 | -8.55687 |      ms |
|                                  50th percentile service time |                                        term |    11.8239 |     6.58407 |  -5.2398 |      ms |
|                                  90th percentile service time |                                        term |    12.3903 |     7.85069 |  -4.5396 |      ms |
|                                  99th percentile service time |                                        term |    16.4101 |     11.2991 | -5.11099 |      ms |
|                                 100th percentile service time |                                        term |    20.2541 |     11.7813 | -8.47277 |      ms |
|                                                    error rate |                                        term |          0 |           0 |        0 |       % |
|                                                Min Throughput |                                       range |    1.00494 |     1.00494 |    1e-05 |   ops/s |
|                                             Median Throughput |                                       range |    1.00658 |     1.00658 |    1e-05 |   ops/s |
|                                                Max Throughput |                                       range |    1.00983 |     1.00985 |    2e-05 |   ops/s |
|                                       50th percentile latency |                                       range |    16.4738 |     15.6901 |  -0.7837 |      ms |
|                                       90th percentile latency |                                       range |    17.1529 |      15.946 | -1.20687 |      ms |
|                                       99th percentile latency |                                       range |    19.1744 |     16.3289 | -2.84554 |      ms |
|                                      100th percentile latency |                                       range |    19.4498 |     19.1965 | -0.25334 |      ms |
|                                  50th percentile service time |                                       range |    15.2952 |     14.5162 |   -0.779 |      ms |
|                                  90th percentile service time |                                       range |    15.9749 |       14.76 | -1.21491 |      ms |
|                                  99th percentile service time |                                       range |    17.9938 |     15.1449 | -2.84887 |      ms |
|                                 100th percentile service time |                                       range |    18.2629 |     18.0331 | -0.22988 |      ms |
|                                                    error rate |                                       range |          0 |           0 |        0 |       % |
|                                                Min Throughput |                                  hourly_agg |   0.200472 |    0.200461 |   -1e-05 |   ops/s |
|                                             Median Throughput |                                  hourly_agg |   0.200628 |    0.200614 |   -1e-05 |   ops/s |
|                                                Max Throughput |                                  hourly_agg |   0.200941 |    0.200935 |   -1e-05 |   ops/s |
|                                       50th percentile latency |                                  hourly_agg |    2637.86 |     2671.83 |  33.9609 |      ms |
|                                       90th percentile latency |                                  hourly_agg |     2661.4 |     2707.89 |  46.4864 |      ms |
|                                       99th percentile latency |                                  hourly_agg |    2675.39 |     2725.14 |  49.7542 |      ms |
|                                      100th percentile latency |                                  hourly_agg |    2676.09 |     2730.02 |  53.9239 |      ms |
|                                  50th percentile service time |                                  hourly_agg |    2635.29 |     2669.32 |  34.0258 |      ms |
|                                  90th percentile service time |                                  hourly_agg |    2658.85 |     2705.36 |  46.5122 |      ms |
|                                  99th percentile service time |                                  hourly_agg |    2672.83 |     2722.64 |  49.8052 |      ms |
|                                 100th percentile service time |                                  hourly_agg |     2673.5 |     2727.54 |  54.0336 |      ms |
|                                                    error rate |                                  hourly_agg |          0 |           0 |        0 |       % |
|                                                Min Throughput |                                      scroll |    25.0149 |      25.014 | -0.00091 | pages/s |
|                                             Median Throughput |                                      scroll |    25.0315 |     25.0239 | -0.00756 | pages/s |
|                                                Max Throughput |                                      scroll |    25.1304 |     25.1191 | -0.01125 | pages/s |
|                                       50th percentile latency |                                      scroll |    777.278 |     810.028 |  32.7497 |      ms |
|                                       90th percentile latency |                                      scroll |    819.226 |     830.047 |  10.8214 |      ms |
|                                       99th percentile latency |                                      scroll |    829.322 |     844.551 |  15.2294 |      ms |
|                                      100th percentile latency |                                      scroll |    842.365 |     849.221 |  6.85621 |      ms |
|                                  50th percentile service time |                                      scroll |    776.894 |     809.656 |  32.7618 |      ms |
|                                  90th percentile service time |                                      scroll |    818.816 |     829.658 |   10.842 |      ms |
|                                  99th percentile service time |                                      scroll |    828.862 |     844.167 |  15.3056 |      ms |
|                                 100th percentile service time |                                      scroll |    841.959 |     848.848 |  6.88915 |      ms |
|                                                    error rate |                                      scroll |          0 |           0 |        0 |       % |
|                                                Min Throughput |                         desc_sort_timestamp |   0.501638 |    0.501645 |    1e-05 |   ops/s |
|                                             Median Throughput |                         desc_sort_timestamp |   0.501969 |    0.501972 |        0 |   ops/s |
|                                                Max Throughput |                         desc_sort_timestamp |   0.502457 |    0.502459 |        0 |   ops/s |
|                                       50th percentile latency |                         desc_sort_timestamp |    34.9101 |     32.3529 | -2.55717 |      ms |
|                                       90th percentile latency |                         desc_sort_timestamp |    36.8483 |     35.2537 | -1.59454 |      ms |
|                                       99th percentile latency |                         desc_sort_timestamp |    40.2969 |       37.66 | -2.63687 |      ms |
|                                      100th percentile latency |                         desc_sort_timestamp |    41.9122 |     38.7657 | -3.14649 |      ms |
|                                  50th percentile service time |                         desc_sort_timestamp |    32.7502 |     30.2327 | -2.51751 |      ms |
|                                  90th percentile service time |                         desc_sort_timestamp |    34.6973 |     33.0975 | -1.59983 |      ms |
|                                  99th percentile service time |                         desc_sort_timestamp |    38.1306 |     35.5072 | -2.62336 |      ms |
|                                 100th percentile service time |                         desc_sort_timestamp |    39.8577 |     38.3515 | -1.50618 |      ms |
|                                                    error rate |                         desc_sort_timestamp |          0 |           0 |        0 |       % |
|                                                Min Throughput |                          asc_sort_timestamp |    0.50162 |    0.501645 |    3e-05 |   ops/s |
|                                             Median Throughput |                          asc_sort_timestamp |   0.501942 |    0.501971 |    3e-05 |   ops/s |
|                                                Max Throughput |                          asc_sort_timestamp |    0.50241 |    0.502459 |    5e-05 |   ops/s |
|                                       50th percentile latency |                          asc_sort_timestamp |    62.5424 |     32.2299 | -30.3125 |      ms |
|                                       90th percentile latency |                          asc_sort_timestamp |    70.6123 |     34.3233 | -36.2889 |      ms |
|                                       99th percentile latency |                          asc_sort_timestamp |    73.8659 |     37.8268 | -36.0391 |      ms |
|                                      100th percentile latency |                          asc_sort_timestamp |    80.2303 |     39.4474 | -40.7829 |      ms |
|                                  50th percentile service time |                          asc_sort_timestamp |    60.4461 |     30.0738 | -30.3724 |      ms |
|                                  90th percentile service time |                          asc_sort_timestamp |    68.4823 |     32.1535 | -36.3288 |      ms |
|                                  99th percentile service time |                          asc_sort_timestamp |    71.7583 |     35.6573 | -36.1009 |      ms |
|                                 100th percentile service time |                          asc_sort_timestamp |    78.1952 |     37.2704 | -40.9248 |      ms |
|                                                    error rate |                          asc_sort_timestamp |          0 |           0 |        0 |       % |
|                                                Min Throughput | desc-sort-timestamp-after-force-merge-1-seg |   0.501474 |    0.501463 |   -1e-05 |   ops/s |
|                                             Median Throughput | desc-sort-timestamp-after-force-merge-1-seg |   0.501778 |    0.501825 |    5e-05 |   ops/s |
|                                                Max Throughput | desc-sort-timestamp-after-force-merge-1-seg |   0.502238 |    0.502286 |    5e-05 |   ops/s |
|                                       50th percentile latency | desc-sort-timestamp-after-force-merge-1-seg |    226.611 |     167.949 | -58.6622 |      ms |
|                                       90th percentile latency | desc-sort-timestamp-after-force-merge-1-seg |    236.714 |     174.961 | -61.7524 |      ms |
|                                       99th percentile latency | desc-sort-timestamp-after-force-merge-1-seg |    242.694 |     215.673 | -27.0209 |      ms |
|                                      100th percentile latency | desc-sort-timestamp-after-force-merge-1-seg |    244.922 |     267.275 |  22.3528 |      ms |
|                                  50th percentile service time | desc-sort-timestamp-after-force-merge-1-seg |    224.641 |     165.933 | -58.7081 |      ms |
|                                  90th percentile service time | desc-sort-timestamp-after-force-merge-1-seg |    234.722 |      172.93 | -61.7924 |      ms |
|                                  99th percentile service time | desc-sort-timestamp-after-force-merge-1-seg |    240.715 |     213.656 | -27.0583 |      ms |
|                                 100th percentile service time | desc-sort-timestamp-after-force-merge-1-seg |    242.962 |     265.244 |  22.2815 |      ms |
|                                                    error rate | desc-sort-timestamp-after-force-merge-1-seg |          0 |           0 |        0 |       % |
|                                                Min Throughput |  asc-sort-timestamp-after-force-merge-1-seg |   0.501561 |    0.501605 |    4e-05 |   ops/s |
|                                             Median Throughput |  asc-sort-timestamp-after-force-merge-1-seg |   0.501875 |    0.501926 |    5e-05 |   ops/s |
|                                                Max Throughput |  asc-sort-timestamp-after-force-merge-1-seg |   0.502342 |    0.502398 |    6e-05 |   ops/s |
|                                       50th percentile latency |  asc-sort-timestamp-after-force-merge-1-seg |    122.138 |     79.3329 | -42.8048 |      ms |
|                                       90th percentile latency |  asc-sort-timestamp-after-force-merge-1-seg |    129.641 |     83.0229 | -46.6184 |      ms |
|                                       99th percentile latency |  asc-sort-timestamp-after-force-merge-1-seg |     143.98 |     87.5347 | -56.4454 |      ms |
|                                      100th percentile latency |  asc-sort-timestamp-after-force-merge-1-seg |    145.287 |     87.9334 | -57.3537 |      ms |
|                                  50th percentile service time |  asc-sort-timestamp-after-force-merge-1-seg |    120.054 |     77.2313 | -42.8229 |      ms |
|                                  90th percentile service time |  asc-sort-timestamp-after-force-merge-1-seg |    127.579 |     80.8976 | -46.6814 |      ms |
|                                  99th percentile service time |  asc-sort-timestamp-after-force-merge-1-seg |    141.903 |      85.767 | -56.1359 |      ms |
|                                 100th percentile service time |  asc-sort-timestamp-after-force-merge-1-seg |    143.198 |     85.8129 |  -57.385 |      ms |
|                                                    error rate |  asc-sort-timestamp-after-force-merge-1-seg |          0 |           0 |        0 |       % |


```

**Comment by ebadyano** [comment]
1G heap experiments: 
`http_logs` Parallel GC vs G1GC indexing throughout is ~4% higher, for most queries latency is the same, except `*force-merge-1-seg` queries latency is 35% better.
`nyc_taxes` queries the same more or less, indexing throughput is 11% better. 
It seems Parallel GC shows advantage vs G1GC on smaller heaps, but even with  `indices.breaker.total.limit: 99.9%` we still sometimes trigger circuit breaker with Parallel GC while not with G1GC. @danielmitterdorfer  Do we want to investigate further if we want to use Parallel on smaller heaps?

**Comment by danielmitterdorfer** [comment]
> @danielmitterdorfer Do we want to investigate further if we want to use Parallel on smaller heaps?

Thanks for doing these experiments Evgenia! IMHO we should be good for now with what we have and we can tackle this question separately at a later point. I'd expect that ParallelGC would require us to investigate thoroughly also on other fronts to ensure cluster stability as this collector is working quite differently than CMS and G1 (it's blocking instead of concurrent).
