### ISSUE TITLE
[DOCS] Reformat ingest API docs

### ISSUE THREAD

**Issue by jrodewig** [elastic/elasticsearch#47049]
Where possible, we should standardize our ingest API documentation to match the [Elastic API reference template](https://github.com/elastic/docs/blame/master/shared/api-ref-ex.asciidoc).

Relates to #45195.

#### Ingest APIs to rewrite
- [x] Put Pipeline API: #47171
- [x] Get Pipeline API: #47131
- [x] Delete Pipeline API: #47172
- [x] Simulate Pipeline API: #47301
