### ISSUE TITLE
Reduce number of writes needed for metadata updates

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#48701]
Today we split the on-disk cluster metadata across many files: one file for the metadata of each index, plus one file for the global metadata and another for the manifest. Most metadata updates only touch a few of these files, but some must write them all. If a node holds a large number of indices then it's possible its disks are not fast enough to process a complete metadata update before timing out. In severe cases affecting master-eligible nodes this can prevent an election from succeeding.

We plan to change the format of on-disk metadata to reduce the number of writes needed during metadata updates. One option is a monolithic file containing the complete metadata, but this is inefficient in the common case that the metadata is mostly unchanged. Another option is to keep an append-only log of changes, but such a log must be compacted and this introduces quite some complexity. However we already have access to a very good storage mechanism that has the right kinds of properties: Lucene! We will use a dedicated Lucene index on each master-eligible node and replace each individual file with a document in this index. Most metadata updates will need only a few writes, and Lucene's background merging will take care of compaction.

On master-ineligible nodes we can keep the existing format and still reduce the writes required, because we can make better use of the fact that master-ineligible nodes only write committed metadata and therefore the version numbers are trustworthy. It may also be possible to avoid writing index metadata during cluster state application entirely and defer it until later.

- [x] Introduce Lucene-based storage mechanism for metadata on master-eligible nodes (#48733)
- [x] Stop writing file-based metadata for indices that aren't assigned to the node (#49234)
- [x] Deal with node repurposing (#50179)
- [x] BWC: upgrading from older storage mechanisms, dealing with cleanup and intermediate states left by failures
- [x] BWC: upgrading from 7.x to 8.x and dealing with the change in the Lucene version
- [x] (nice-to-have) Move metadata persistence on master-ineligible nodes off the critical path for cluster state application (#50782)
- [x] Reimplement unsafe bootstrapping & cluster detachment (including suppressed `CoordinatorTests#testCannotJoinClusterWithDifferentUUID` test case) (#50179)
- [x] Implement rescue tool to deal with broken settings/customs (#50694, #50813)
- [x] ~~Implement rescue tool for when the node ID file is lost (ref. https://github.com/elastic/elasticsearch/pull/48733#discussion_r345240833)~~ Replaced by folding node metadata into new storage and using that as authoritative source: #50741
- [x] Expose information on performance (warn on slow persistence, track time spent in background merges, number of segments, index size etc.) (#50956)

Later:

- [ ] Investigate alternative merging strategies -- is there a benefit in merging in the background after a commit rather than doing it inline while flushing?
- [ ] Investigate the performance of duplicated indexing across multiple data paths and contemplate alternatives (ref. https://github.com/elastic/elasticsearch/pull/48733#discussion_r343598526)
- [ ] Optimize file-based metadata storage to trust metadata versions
- [ ] Implement rescue tool for when global metadata document is missing or when there are duplicated docs (ref. https://github.com/elastic/elasticsearch/pull/48733#discussion_r345247959)

**Comment by ywelsch** [comment]
I've checked performance of the new storage layer using an EC2 `r4.8xlarge` instance (which is used for dedicated master nodes).

I've ran the following script:

```
#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

NUM_INDICES=100
NUM_FIELDS=200
NUM_ALL_INDEX_SETTING_UPDATES=10
NUM_SINGLE_INDEX_SETTING_UPDATES=200

# Start up elasticsearch using bin/elasticsearch -Epath.data=data1,data2,data3,data4 > /dev/null

# Do not show output of curl commands unless they fail
alias silentcurl='curl --silent --show-error --output /dev/null --fail'

# Disable allocation and shard limit
silentcurl -X PUT "localhost:9200/_cluster/settings?pretty" -H 'Content-Type: application/json' -d'
{
    "persistent" : {
        "cluster.routing.allocation.enable" : "none",
        "cluster.max_shards_per_node" : "99999999"
    }
}
'

# Delete all indices
silentcurl -X DELETE "localhost:9200/*"

# Create indices
time for ((i=1; i <= $NUM_INDICES; i++))
do
  printf '% -25s (%s)\r' "Creating $NUM_INDICES indices:" $i
  seq 1 $NUM_FIELDS | \
  jq -R '.' | \
  jq -s '{mappings:{properties:(map({("field"+.):{type:"keyword"}}) | add)}}' | \
  silentcurl -X PUT "localhost:9200/index${i}?wait_for_active_shards=0&pretty" -H 'Content-Type: application/json' -d @-
done

# First test: benchmark updating setting on all 1000 indices
printf "Updating an index setting $NUM_ALL_INDEX_SETTING_UPDATES times on all $NUM_INDICES indices:"
time for ((i=1; i <= $NUM_ALL_INDEX_SETTING_UPDATES; i++))
do
  silentcurl -X PUT "localhost:9200/index*/_settings?pretty" -H 'Content-Type: application/json' \
  -d "{ \"index.refresh_interval\" : \"${i}s\" }"
done

# Reset setting after first test
silentcurl -X PUT "localhost:9200/index*/_settings?pretty" -H 'Content-Type: application/json' \
  -d "{ \"index.refresh_interval\" : null }"

# Second test: benchmark updating setting on only one index
printf "Updating an index setting $NUM_SINGLE_INDEX_SETTING_UPDATES times on the first index:"
time for ((i=1; i <= $NUM_SINGLE_INDEX_SETTING_UPDATES; i++))
do
  silentcurl -X PUT "localhost:9200/index1/_settings?pretty" -H 'Content-Type: application/json' \
  -d "{ \"index.refresh_interval\" : \"${i}s\" }"
done

# Reset setting after second test
silentcurl -X PUT "localhost:9200/index*/_settings?pretty" -H 'Content-Type: application/json' \
  -d "{ \"index.refresh_interval\" : null }"

# Check on-disk cluster state size
printf "On-disk cluster state size\n"
du -h -d 1 data
```

# Results (always 2 runs shown)

- `master` branch with single data path, 100 indices

```
Creating 100 indices:     (100)
real	0m2.548s
user	0m0.988s
sys	0m0.403s
Updating an index setting 10 times on all 100 indices:
real	0m4.935s
user	0m0.038s
sys	0m0.028s
Updating an index setting 200 times on the first index:
real	0m3.419s
user	0m0.760s
sys	0m0.368s
On-disk cluster state size
16K	data/_state
408K	data/indices
424K	data

Creating 100 indices:     (100)
real	0m1.795s
user	0m1.005s
sys	0m0.350s
Updating an index setting 10 times on all 100 indices:
real	0m4.477s
user	0m0.046s
sys	0m0.019s
Updating an index setting 200 times on the first index:
real	0m3.225s
user	0m0.788s
sys	0m0.333s
On-disk cluster state size
20K	data/_state
408K	data/indices
428K	data
```

- `master` branch with single data path, 1000 indices

```
Creating 1000 indices:    (1000)
real	0m34.272s
user	0m10.297s
sys	0m3.390s
Updating an index setting 10 times on all 1000 indices:
real	0m51.559s
user	0m0.028s
sys	0m0.040s
Updating an index setting 200 times on the first index:
real	0m9.541s
user	0m0.770s
sys	0m0.392s
On-disk cluster state size
60K	data/_state
4.0M	data/indices
4.1M	data

Creating 1000 indices:    (1000)
real	0m37.330s
user	0m10.140s
sys	0m3.579s
Updating an index setting 10 times on all 1000 indices:
real	0m59.807s
user	0m0.042s
sys	0m0.026s
Updating an index setting 200 times on the first index:
real	0m9.844s
user	0m0.788s
sys	0m0.372s
On-disk cluster state size
72K	data/_state
4.0M	data/indices
4.1M	data
```

- `reduce-metadata-writes` branch (+ https://github.com/elastic/elasticsearch/pull/50901) with single data path, 100 indices

```
Creating 100 indices:     (100)
real	0m3.449s
user	0m1.059s
sys	0m0.340s
Updating an index setting 10 times on all 100 indices:
real	0m2.467s
user	0m0.039s
sys	0m0.027s
Updating an index setting 200 times on the first index:
real	0m4.339s
user	0m0.733s
sys	0m0.403s
On-disk cluster state size
92K	data/_state
92K	data

Creating 100 indices:     (100)
real	0m2.319s
user	0m1.060s
sys	0m0.312s
Updating an index setting 10 times on all 100 indices:
real	0m2.070s
user	0m0.059s
sys	0m0.007s
Updating an index setting 200 times on the first index:
real	0m4.109s
user	0m0.850s
sys	0m0.301s
On-disk cluster state size
92K	data/_state
92K	data
```

- `reduce-metadata-writes` branch (+ https://github.com/elastic/elasticsearch/pull/50901) with single data path, 1000 indices

```
Creating 1000 indices:    (1000)
real	0m38.793s
user	0m10.445s
sys	0m3.367s
Updating an index setting 10 times on all 1000 indices:
real	0m26.452s
user	0m0.056s
sys	0m0.011s
Updating an index setting 200 times on the first index:
real	0m10.410s
user	0m0.789s
sys	0m0.392s
On-disk cluster state size
244K	data/_state
244K	data

Creating 1000 indices:    (1000)
real	0m41.959s
user	0m10.453s
sys	0m3.313s
Updating an index setting 10 times on all 1000 indices:
real	0m34.161s
user	0m0.055s
sys	0m0.013s
Updating an index setting 200 times on the first index:
real	0m10.270s
user	0m0.788s
sys	0m0.384s
On-disk cluster state size
244K	data/_state
244K	data
```

- `master` branch with multi data path (4 paths), 1000 indices

```
Creating 1000 indices:    (1000)
real	0m53.603s
user	0m10.565s
sys	0m3.370s
Updating an index setting 10 times on all 1000 indices:
real	2m2.496s
user	0m0.045s
sys	0m0.026s
Updating an index setting 200 times on the first index:
real	0m13.476s
user	0m0.819s
sys	0m0.393s

Creating 1000 indices:    (1000)
real	0m52.598s
user	0m10.621s
sys	0m3.414s
Updating an index setting 10 times on all 1000 indices:
real	1m52.536s
user	0m0.047s
sys	0m0.023s
Updating an index setting 200 times on the first index:
real	0m13.189s
user	0m0.806s
sys	0m0.390s
```

- `reduce-metadata-writes` branch (+ https://github.com/elastic/elasticsearch/pull/50901) with multi data path (4 paths), 1000 indices

```
Creating 1000 indices:    (1000)
real	1m22.545s
user	0m10.684s
sys	0m3.750s
Updating an index setting 10 times on all 1000 indices:
real	0m25.183s
user	0m0.038s
sys	0m0.028s
Updating an index setting 200 times on the first index:
real	0m17.648s
user	0m0.827s
sys	0m0.440s

Creating 1000 indices:    (1000)
real	1m22.559s
user	0m10.758s
sys	0m3.664s
Updating an index setting 10 times on all 1000 indices:
real	0m32.036s
user	0m0.034s
sys	0m0.034s
Updating an index setting 200 times on the first index:
real	0m17.228s
user	0m0.856s
sys	0m0.414s
```

The new storage layer is slightly slower when only very little information is written out (e.g. only cluster state version changed), but works much better in case where large cluster states are updated.

**Comment by ywelsch** [comment]
Another test with a `d2.xlarge` instance (3 HDDs, single data path tests use just first HDD, multi data path tests use all 3):

- `master` branch with single data path, 100 indices

```
Creating 100 indices:     (100)
real	0m11.151s
user	0m1.383s
sys	0m0.504s
Updating an index setting 10 times on all 100 indices:
real	0m43.830s
user	0m0.038s
sys	0m0.032s
Updating an index setting 200 times on the first index:
real	0m20.208s
user	0m0.833s
sys	0m0.481s

Creating 100 indices:     (100)
real	0m10.090s
user	0m1.404s
sys	0m0.411s
Updating an index setting 10 times on all 100 indices:
real	0m44.041s
user	0m0.034s
sys	0m0.034s
Updating an index setting 200 times on the first index:
real	0m19.301s
user	0m0.822s
sys	0m0.473s
```

- `reduce-metadata-writes` branch (+ https://github.com/elastic/elasticsearch/pull/50901) with single data path, 100 indices

```
Creating 100 indices:     (100)
real	0m22.480s
user	0m1.436s
sys	0m0.424s
Updating an index setting 10 times on all 100 indices:
real	0m5.316s
user	0m0.050s
sys	0m0.018s
Updating an index setting 200 times on the first index:
real	0m35.772s
user	0m0.808s
sys	0m0.490s

Creating 100 indices:     (100)
real	0m19.036s
user	0m1.333s
sys	0m0.467s
Updating an index setting 10 times on all 100 indices:
real	0m3.760s
user	0m0.040s
sys	0m0.029s
Updating an index setting 200 times on the first index:
real	0m35.163s
user	0m0.855s
sys	0m0.432s
```

- `master` branch with single data path, 300 indices

```
Creating 300 indices:     (300)
real	0m32.569s
user	0m4.088s
sys	0m1.474s
Updating an index setting 10 times on all 300 indices:
real	2m13.866s
user	0m0.049s
sys	0m0.026s
Updating an index setting 200 times on the first index:
real	0m20.795s
user	0m0.827s
sys	0m0.423s

Creating 300 indices:     (300)
real	0m33.505s
user	0m3.994s
sys	0m1.314s
Updating an index setting 10 times on all 300 indices:
real	2m14.220s
user	0m0.032s
sys	0m0.036s
Updating an index setting 200 times on the first index:
real	0m21.040s
user	0m0.796s
sys	0m0.437s
```

- `reduce-metadata-writes` branch (+ https://github.com/elastic/elasticsearch/pull/50901) with single data path, 300 indices

```
Creating 300 indices:     (300)
real	0m58.257s
user	0m4.086s
sys	0m1.318s
Updating an index setting 10 times on all 300 indices:
real	0m7.818s
user	0m0.047s
sys	0m0.018s
Updating an index setting 200 times on the first index:
real	0m34.205s
user	0m0.845s
sys	0m0.411s

Creating 300 indices:     (300)
real	0m57.746s
user	0m4.111s
sys	0m1.262s
Updating an index setting 10 times on all 300 indices:
real	0m7.997s
user	0m0.048s
sys	0m0.022s
Updating an index setting 200 times on the first index:
real	0m33.881s
user	0m0.818s
sys	0m0.433s
```

- `master` branch with multi data path (3 paths), 100 indices

```
Creating 100 indices:     (100)
real	0m26.011s
user	0m1.372s
sys	0m0.503s
Updating an index setting 10 times on all 100 indices:
real	2m0.492s
user	0m0.058s
sys	0m0.013s
Updating an index setting 200 times on the first index:
real	0m48.323s
user	0m0.859s
sys	0m0.446s

Creating 100 indices:     (100)
real	0m26.063s
user	0m1.369s
sys	0m0.446s
Updating an index setting 10 times on all 100 indices:
real	2m1.355s
user	0m0.041s
sys	0m0.029s
Updating an index setting 200 times on the first index:
real	0m49.706s
user	0m0.933s
sys	0m0.342s
```

- `reduce-metadata-writes` branch (+ https://github.com/elastic/elasticsearch/pull/50901) with multi data path (3 paths), 100 indices

```
Creating 100 indices:     (100)
real	1m9.086s
user	0m1.318s
sys	0m0.521s
Updating an index setting 10 times on all 100 indices:
real	0m9.491s
user	0m0.046s
sys	0m0.022s
Updating an index setting 200 times on the first index:
real	1m57.110s
user	0m0.911s
sys	0m0.388s

Creating 100 indices:     (100)
real	0m57.128s
user	0m1.328s
sys	0m0.483s
Updating an index setting 10 times on all 100 indices:
real	0m6.625s
user	0m0.059s
sys	0m0.006s
Updating an index setting 200 times on the first index:
real	1m36.907s
user	0m0.876s
sys	0m0.418s
```

The test validates that the size of the cluster state does not impact the new storage mechanism.

**Comment by ywelsch** [comment]
Closing this issue as the work here was merged for 7.6.0
