### ISSUE TITLE
Enrich processor followup work

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#48988]
The issue contains improvements and new features that should be done for ingest in near to medium future.

- [ ] Add telemetry support for the enrich policy. Interesting information to capture is the number of enrich policies by policy type, last policy execution by type and size (doc count & index size in bytes) of the enrich policy indices per type. 
- [ ] Add range enrich policy type. The range policy allows for example to match whether an ip falls into a certain range. The match field can be of type: `ip_range`, `date_range`, `float_range`, `long_range`, `integer_range` and `double_range`.
- [ ] Extend the get policies api to include the status of a policy and the last time a policy executed.
- [ ] Optimize the enrich processor queue, so that when multiple search requests are executed then to combine identical search requests into a single search request in order to avoid duplicate searches in the same multi search request.
- [ ] Introduce a LRU cache to avoid repeatable searches from the enrich processor.
- [ ] Allow enrich policy execution to be cancellable.
- [ ] Allow enrich policy to use the source index directly. In cases where performance is not important, this would avoid the need to create an enrich index.

**Comment by bestpath-gb** [comment]
> Add range enrich policy type

> Explore allowing multiple match fields

Just wanted to add a vote for these. Being able to match on only a single field value is a blocker for us using enrich, so we're sticking with Logstash for now. All of our enrichment queries (done with the `elasticsearch` filter in Logstash) match on at least two fields.

Here's how I figured we could still use the enrich policy for some of our lookups:

- Where one of the matches is a static keyword filter (category, for example) and the other is dynamic, I can do this using a `query` in the enrich policy, then using the dynamic keyword as the `match_field`.
- When both the match fields are dynamic but still keywords, I can concatenate them into a new field, then match on that one field.

Our last use-case is two dynamic match fields where one is a keyword and the other is a range; either an IP range or integer range. I'm not able to figure out a way to deal with that at the moment.

**Comment by jkyamog** [comment]
We have encountered the issues describe above as well.

- enriching by matching multiple fields.  We can work around this by having many enrich processor for each field.  Not nice.
- we can't match with a `ip_range` type, which is a show stopper for us

So we have to keep on using logstash for this enrichment.  Subscribed to this, so we can move away from the logstash enrichment and use the elastic processor instead.

**Comment by abidub** [comment]
The ability to match on ip_range and the enrich processor would be great.

**Comment by sachin-frayne** [comment]
+1

**Comment by molekuul** [comment]
+1 The ability to match on ip_range would be great!

**Comment by sataman** [comment]
+1

**Comment by ChenTsungYu** [comment]
I also have the same issues above. 
Hope the feature:
1. enriching by matching multiple fields, not only one field.

**Comment by udungg** [comment]
+1

**Comment by leandrojmp** [comment]
I think that the option to Schedule the execution of Enrich Policy mentioned in this [feature request](https://github.com/elastic/elasticsearch/issues/50071) should also be listed in this issue.

**Comment by DiannaHohensee** [comment]
> Store the result of a policy execution in the .tasks index.

A SDHE is struggling from the lack of the above specifically.
