### ISSUE TITLE
New processors to expand ingest node's capabilities

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#48986]
This meta issue is keeping track of the new processor that should be added to ingest in the short to mid term. The addition of these new processors will make ingest more versatile and therefor easier to be used for different purposes.

New processors planned for development:
- [ ] Hash processor. See #34085 (in progress).
- [ ] Time duration processor. See #39857 (in progress).
- [ ] CSV processor. (more details follow)
- [ ] IP processor. See #38064.
- [ ] Language detection processor. See #29094
- [ ] Time processor. See #40615
- [ ] Unit conversion processor. See #31737
- [ ] Expose ML's `domainSplit()` function as processor. See #36359
- [ ] Percolate processor. (more details follow)
