### ISSUE TITLE
Improve ingest node usability 

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#48999]
There are number of improvements and bug fixes that improve the usability of ingest node. This meta issue includes a number of those fixes that should be done in the short to medium term.

- [x] Make `name` setting template-able in pipeline processor. See #39955
- [x] Add origin pipeline name to on_failure processor metadata. See #44920
- [x] Add pipeline name to ingest metadata. See #42106
- [ ] Bulk script upsert are executed after pipeline execution. See #36745
- [ ] Fail when accessing _id in pipeline when id is auto generated. See #41163
- [ ] Fail fast when specifying two processor type inside a single processor object element. See #36134
- [ ] Support pipeline processor in simulate api without requiring to create the pipeline it refers to. See #35495
- [ ] Allow Tika parsers to be configured from attachment processor. See #36890
- [x] Make the output date format of the date processor configurable. See #42523
- [ ] Support RFC7231 UserAgent scheme in User Agent processor. See #41001
- [ ] The put pipeline api should be able to create multiple pipelines in single API call. #35889
- [x] Add support for if_seq_no and if_primary_term to ingest. See #41255

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
