### ISSUE TITLE
Logging improvements

### ISSUE THREAD

**Issue by pgomulka** [elastic/elasticsearch#49087]
This is a meta issue to gather changes and improvements to Elasticsearch logging.

- [x] Allow adding custom new fields to JSON logs  https://github.com/elastic/elasticsearch/issues/46119 PR merged https://github.com/elastic/elasticsearch/pull/46702
- [x] Migrate JSON logs to ECS https://github.com/elastic/elasticsearch/issues/46119 with a possibility to fall back to old style JSON logs [PR](https://github.com/elastic/elasticsearch/pull/47105)
- [x] Remove plaintext slow log and deprecation logs https://github.com/elastic/elasticsearch/issues/46119
- [ ] Sanitise slow log request source https://github.com/elastic/elasticsearch/issues/47853
- [x] Filebeat changes to make it compatible with ES - ECS Json logs [filebeat PR](https://github.com/elastic/beats/issues/17715) and [branch with code to generate logs ](https://github.com/pgomulka/elasticsearch/commits/feature/logs_for_beats_testing)
- [ ] Updated documentation on ES JSON logging
- [ ] Rename custom log fields with `es` prefix
- [ ] Use ECS fields where possible (e.g. `node.name` -> `service.node.name`)
- [x] Write deprecation logs to an index https://github.com/elastic/elasticsearch/issues/46106
- [ ] Group slow logs fields per index/shard. At the moment it is not obvious if a field took or total_hits relates to an index or to a shard.
- [ ] Refactor ESLoggerUsageChecker - this is a static analysis tool to verify correct usages of logger. It is all in one class now and grew too big. Might do with refactoring
- [ ] (DeprecationLogger) Eliminate deprecation key by caching call site - https://github.com/elastic/elasticsearch/pull/55941/files#r424563049
- [x] considering reducing memory footprint/garbage creation within DeprecationLogger fluent builder (REMOVED fluent builder)
- [ ] Investigate `            name = "deprecation." + name;` in DeprecationLogger, was it working? is it broken? remove it?

**Comment by tumile** [comment]
@pgomulka Hi, I'd like to help with refactoring ESLoggerUsageChecker. Could you assign it to me?

**Comment by pgomulka** [comment]
@tumile I don't have the exact plan on how to refactor this yet. I was hoping there is a tool that would achieve what that tool is doing. If you came up with ideas, please share them with us (new issue would be good) before you start working on implementation.

**Comment by rjernst** [comment]
It's been a while since we've opened this, and most of the work here was completed. I'm going to close this given a lack of traction or priority on the remaining small issues.
