### ISSUE TITLE
Async search

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#49091]
This is a meta issue to monitor progress around adding support for asynchronous search.

The main goal is to launch a search request and, instead of waiting for its final response, let it run asynchronously while being able to monitor its progress. The progress of an async search includes how many operations have been performed compared to the total number of operations required for completion, as well as intermediate results that may be available before completion.

The high-level steps required for this feature are listed as follows, together with their corresponding licensing:

- [x] add ability to control the order in which shards are queried by the search API (OSS) #49092 
- [x] add ability to monitor progress of a search request through a listener that gets notified whenever new shard results are available (OSS) #49471
- [x] introduce new endpoints to submit, get and delete an async search (Basic) #49931 
- [x] Add tests for the AsyncSearchMaintenanceService
- [x] Add documentation for the APIs
- [x] Add support for the HLRC.

The resiliency of async search is besides the scope of the initial implementation. If the coordinating node goes down while an async search is running, the most recent intermediate results should be made available for retrieval, but the async search is aborted and never retried, hence it needs to be restarted manually.

**Comment by jimczi** [comment]
All the blockers have been merge in 7.7, hence closing. We'll create new issues for improvements related to async search in the future.
