### ISSUE TITLE
Remove synced-flush

### ISSUE THREAD

**Issue by dnhatn** [elastic/elasticsearch#50776]
To simplify rolling and full cluster restarts, we want to remove the need for a synced flush and allow quicker recoveries even if indexing is ongoing during the rolling restart. By moving everything to peer recovery retention leases, we can get rid of synced flush in 8.0, as a regular flush then has the same effect as a synced flush.

- [x] Replace a synced-flush with a regular flush on shard inactivity (need to backport to 7.x) (https://github.com/elastic/elasticsearch/pull/51365)
- [x] Deprecate synced-flush in 7.x (#50835)
- [x] Adjust full cluster restart guideline in 8.0 (done in #50882)
- [x] Remove synced-flush in 8.0 (#50882)
- [x] Remove sync_id logic in RecoverySourceHandler (must keep it in 8.0)
- [x] Remove syncedFlush logic in InternalEngine (#51450)
~- [ ] Flush does not need to hold Engine#readLock?~
- [x] Stronger tests for full cluster restart with synced flush without peer recovery retention leases (#51512)

**Comment by dnhatn** [comment]
All sub tasks are completed.
