### ISSUE TITLE
Make soft-deletes mandatory

### ISSUE THREAD

**Issue by dnhatn** [elastic/elasticsearch#50775]
Peer recoveries become faster and use less storage (i.e., no more extra translog) with soft-deletes. Soft-deletes has been enabled by default since 7.0. We should make it mandatory in 8.0, so we can simplify the logic in the engine, translog, recoveries, and other components. This meta issue tracks works to be done on this story.

- [x] Always enable soft-deletes in InternalEngine (#50415)
- [x] Deprecate indices without soft-deletes (#50502)
- [x] Prevent creating new indices without soft-deletes (#51122)
- [x] Uses Lucene index in primary promotion (#51189)
- [x] Uses Lucene index in peer recoveries (#51189)
- [x] Remove translog retention policy (#51417)
- [x] Deprecate translog retention settings (#51239) 
- [x] Reject translog retention settings in 8.0 (#51697)

More tests for corner cases 
- [x] Shrink/split indices (see #51122)
- [x] Indices without _source (#51189)
- [x] Frozen indices (see https://github.com/elastic/elasticsearch/pull/50415#pullrequestreview-336484758) (#51192)
- [x] Snapshot/restore (see #51125)

Cleanup:
- [x] Clean up soft-deletes setting in CCR (#51113)
- [x] ~Clean up soft-deletes setting in tests~ (let's do it in 9.0 so we can back port to 8.0)
