### ISSUE TITLE
Stack monitoring changes for Elasticsearch

### ISSUE THREAD

**Issue by danhermann** [elastic/elasticsearch#50770]
The following changes will be made to Elasticsearch monitoring to facilitate its inclusion in Stack Monitoring:

**Pre-8.0 (7.x branches)**
- [x] Deprecate settings that for removal in 8.0
  - [x] Ingest pipelines #77659 #78799
  - [x] Legacy Templates #78564 #78799
  - [x] All Monitoring settings https://github.com/elastic/elasticsearch/pull/79499
- [x] Provide an upgrade path during the 7.x timeline to replace Watcher alerts with Kibana alerting. #50032 #62668 #64373

**For 8.0.0**
- [x] Remove pipelines from Monitoring plugin #77459
- [x] Ensure that index template for the monitoring index is eagerly loaded independent of whether ES monitoring is enabled #44102 #51762 #78350
- [x] Change settings so cluster alerts are not installed by default (but will continue to be managed if explicitly enabled) https://github.com/elastic/elasticsearch/pull/79657

**For 8.x and beyond**
- [ ] Deprecate `_monitoring/bulk` endpoint for removal in 8.x
- [ ] Remove _monitoring/bulk endpoint #47213
- [ ] Remove internal collectors #47214
- [ ] Remove exporters #47215
- [ ] Remove watcher cluster alerts
- [ ] Remove the monitoring plugin, if possible

**Comment by dakrone** [comment]
Internal monitoring has been deprecated for quite a while, and we're no longer doing any active development on it. I'm going to close this issue.
