### ISSUE TITLE
Prepare autoscaling for release

### ISSUE THREAD

**Issue by jasontedor** [elastic/elasticsearch#51191]
This issue is a placeholder issue to track changes that are needed to prepare autoscaling for release.

- [x] register the `xpack.autoscaling.enabled` setting in release builds (cf. #51161)
- [x] include the autoscaling docs in release builds (cf. #51190)
- [x] remove enabling autoscaling in snapshot docs tests (it will be enabled by default) (cf. #51474)
- [x] remove ability to register autoscaling feature flag in release builds (cf. #52088)
- [x] remove registering autoscaling feature flag in release builds (cf. #52088, #52096)
  - [x] docs (cf. #52088)
  - [x] autoscaling REST tests (cf. #52096)
  - [x] autoscaling internal cluster tests (cf. db572afda8cbead464e1bb1f08a028d4201e464d)
- [ ] document these steps for the development team
