### ISSUE TITLE
EQL: Add support for existing functions

### ISSUE THREAD

**Issue by rw-access** [elastic/elasticsearch#51556]
We need to add support for the subset of functions that EQL supports. Some of these may already exist from SQL, and we may need to create additional ones.

The full list is below:
https://github.com/elastic/elasticsearch/blob/6f1890bf2d52cabdfd1e7848fb481cf54b895f25/x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/parser/EqlParser.java#L134-L153

Math functions were created before EQL had math operators. These should be easy to do, and can probably be done together
- [x] **add** `(number, number) -> number` https://github.com/elastic/elasticsearch/issues/54846
- [x] **divide** `(number, number) -> number` https://github.com/elastic/elasticsearch/issues/54846
- [x] **modulo** `(number, number) -> number` https://github.com/elastic/elasticsearch/issues/54846
- [x] **multiply** `(number, number) -> number` https://github.com/elastic/elasticsearch/issues/54846
- [x] **subtract** `(number, number) -> number` https://github.com/elastic/elasticsearch/issues/54846

Tracking remaining functions to be implemented
- [x] **between** `(str, str, str [, bool, bool]) -> str` https://github.com/elastic/elasticsearch/issues/54135
- [x] **cidrMatch** `(ip, static cidr, ...) -> bool` (convert to IP field match) https://github.com/elastic/elasticsearch/issues/54132
- [x] **concat** `(object, ...) -> str` https://github.com/elastic/elasticsearch/issues/55185
- [x] **endsWith** `(str, str) -> bool` https://github.com/elastic/elasticsearch/issues/53854
- [x]  **indexOf** `(str, str [, int]) -> int|null` https://github.com/elastic/elasticsearch/issues/53856
- [x] **length** `(str | array) -> int` https://github.com/elastic/elasticsearch/issues/53853
- [x] **match** `(str, static str, ...) -> bool` https://github.com/elastic/elasticsearch/issues/55182
- [x] **number** `(str, [int]) -> number` https://github.com/elastic/elasticsearch/issues/54471
- [x] **startsWith** `(str, str) -> bool` https://github.com/elastic/elasticsearch/issues/53855
- [x] **string** `(object) -> str` #54470
- [x] **stringContains** `(str, str) -> bool` https://github.com/elastic/elasticsearch/issues/54136
- [x] **substring** `(str, int [, int]) -> str)` (we may need to adjust for EQL's zero and negative-indexing into strings) ~~#53688~~
- [x] **wildcard** `(str, static str, ...) -> bool` (convert to Likes) - ~~#51901~~ and #54020

**Comment by costin** [comment]
I have updated the initial description with check boxes, as we go through the functions once https://github.com/elastic/elasticsearch/pull/53688 gets merged, we should mark them as done and indicate the relevant ticket.

I think the string functions are the first ones to be addressed as they are widely used. The operators one can be easily promoted into functions and so I would do them last as there is a workaround for them.

**Comment by costin** [comment]
Looks like this can be closed, with #54568 as a follow-up.
