### ISSUE TITLE
Prepare EQL for release

### ISSUE THREAD

**Issue by aleksmaus** [elastic/elasticsearch#51613]
This issue is a placeholder issue to track changes that are needed to prepare EQL for release.

- [x] register the `xpack.eql.enabled` setting in release builds (cf. #51370, #52201) #59331
- [x] include the EQL docs in release builds (cf. #51334) #59259
- [x] include the integration tests in release builds (presently excluded) (cf. #51624, #51699) #59331
- [x] remove enabling EQL in snapshot docs tests (it will be enabled by default) (cf. #51537) #59331
- [x] document these steps for the development team

**Comment by costin** [comment]
Closing this issue With EQL ready for the 7.9 release.
