### ISSUE TITLE
[DOCS] Breaking changes docs are difficult to use

### ISSUE THREAD

**Issue by jrodewig** [elastic/elasticsearch#53229]
Several users have notes that the Elasticsearch breaking changes is hard-to-digest and difficult to use.

### Running list of issues

- [ ] [The table of contents and headers](https://www.elastic.co/guide/en/elasticsearch/reference/7.6/breaking-changes-7.0.html) are grouped largely by team rather than feature or user group. This makes it difficult for users to discern what changes apply to them.
- [x] The current layout is very text-heavy with long headers that present as a "wall of text." This makes it difficult for users to quickly parse the changes and see what's applicable to them. #55629
- [x] In many cases, there is no clear workaround or solution presented. By incorporating a workaround section into the layout, we could encourage contributors to add that content. #55629
- [x] There is no sense of progressive disclosure. Users are assumed to be interested in every breaking change equally. Adding collapsible sections could help provide additional detail to users, but only if they decide it's interesting or applicable to them. #55629
- [ ] We should consider putting breaking changes for all versions of a major (7.x, 8.x, etc.) on the same page.

### Next steps

The @esdocs  team should explore a new template and/or layout for breaking changes to address some of these issues.

CC @zuketo

**Comment by jrodewig** [comment]
With ##55629, we creating a collapsible template for breaking docs that includes an *Impact* section for solutions/workarounds.

This should make it possible for us to keep breaking changes an a single page starting in 8.x. It should also make labelling easier.

Closing this ticket for now. We can re-open if further improvements or iterations are needed.
