### ISSUE TITLE
Agg test coverage for unmapped, scripting, supported-types

### ISSUE THREAD

**Issue by polyfractal** [elastic/elasticsearch#53431]
Before merging the VS refactoring work, we'd like to make sure all the converted aggs have tests for unmapped, scripting and "supported type" tests to avoid accidentally changing any behavior.  These corner cases have some nuanced behavior, and are not well tested in master today.  

I've randomly divided up the set of aggs below.  Many are already tested (either previously, or added for the VS refactoring), so just verify and check off.  If they are missing please work on a PR against master and the feature branch.

@polyfractal:
- [x] Histo field / percentiles 
- [x] Value Count https://github.com/elastic/elasticsearch/pull/53500
- [ ] Terms https://github.com/elastic/elasticsearch/pull/54128
- [ ] Cardinality
- [x] Boxplot https://github.com/elastic/elasticsearch/pull/53435
- [ ] Geo Tile Grid
- [ ] Percentiles
- [ ] Rare Terms
- [ ] Range

@csoulios:
- [x] Average (#44076, #54011)
- [x] Min (#50053, #54021)
- [x] Median (#54884)
- [ ] Extended Stats
- [ ] Significant Terms
- [ ] Geo Hash Grid
- [ ] Geo Bounds
- [ ] Percentile Rank

@andyb-elastic 
- [x] Sum #53568
- [ ] Date Range #55502
- [x] Missing #53214 #53448
- [ ] Histogram
- [x] String Stats #54033
- [x] Max #53701
- [ ] Geo Centroid
- [x] Stats #53768

New, whoever gets here first:
- [ ] Date Histogram
