### ISSUE TITLE
Pipeline aggregations are weird

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#53742]
Pipeline aggregations are weird!

* [x] They are validated on the data node rather than the coordinating node. (#53669 + #54298)
* [x] They are built on the data node and shipped back to the coordinating node (#53730 + #54282 + #54311 + #54298)
* [ ] Because of that they implement `NamedWriteable`, ~~`equals`, and `hashcode`~~. None of that is really important if we stop doing the above. (#54926 + #55026)

There are a few other things we could probably clean up here but this'd be a huge step for making pipeline aggregations simpler to implement. And, bonus, it'd save some space in the aggregation result tree.
