### ISSUE TITLE
[DOCS] Restructure and edit the ILM and SLM documentation

### ISSUE THREAD

**Issue by debadair** [elastic/elasticsearch#53894]
Meta issue for improvements to the ILM/SLM docs.

- [x] Move Snapshot/Restore out of modules. #49618
- [x] Align SLM API docs with ILM #48705
- [x] Rework ILM overview & split off to a separate topic #51287
- [x] Edit ILM GS tutorial #51513
- [x] Align ILM docs with standard structure #55632
- [x] Edit ILM task content #55632
- [x] Align SLM content with standard structure and ILM changes #56313
- [x] Fix #49151 (#56315)
- [x] Fix #42469 (#56317)
- [x] Fix #42080 (#56560)
- [x] Fix #37981 (#56561)

Related issues: #49151, #42469, #42080, #37981, #53209
