### ISSUE TITLE
Types removal - compatible changes

### ISSUE THREAD

**Issue by pgomulka** [elastic/elasticsearch#54160]
This issue is meant to track progress on types removal compatible changes. It is a copy of a https://github.com/elastic/elasticsearch/issues/41059 where types removal was tracked.
This is a meta issue that tracks things that must or should be done before 8.0 in order to finalize the removal of types.
relates: [the main meta issue](https://github.com/elastic/elasticsearch/issues/51816)
**MUST**
* [x] Remove typed URL paths
* [x] RestNoopBulkAction  (https://github.com/elastic/elasticsearch/pull/46668) internal api
* [x] RestNoopSearchAction  (https://github.com/elastic/elasticsearch/pull/46668) internal api
* [x] RestMultiSearchTemplateAction  (https://github.com/elastic/elasticsearch/pull/41640) **feature branch compatible https://github.com/elastic/elasticsearch/pull/54572** https://github.com/elastic/elasticsearch/pull/72155
* [x] RestSearchTemplateAction  (https://github.com/elastic/elasticsearch/pull/41640) **feature branch compatible https://github.com/elastic/elasticsearch/pull/54572** https://github.com/elastic/elasticsearch/pull/72155
* [x] RestDeleteByQueryAction  (https://github.com/elastic/elasticsearch/pull/41640) **feature branch compatible https://github.com/elastic/elasticsearch/pull/54572** https://github.com/elastic/elasticsearch/pull/72155
* [x] RestUpdateByQueryAction  (https://github.com/elastic/elasticsearch/pull/41640) **feature branch compatible https://github.com/elastic/elasticsearch/pull/54572**  https://github.com/elastic/elasticsearch/pull/72155
* [x] RestGetFieldMappingAction  (https://github.com/elastic/elasticsearch/pull/41676) **feature branch compatible draft https://github.com/elastic/elasticsearch/pull/58426** on master https://github.com/elastic/elasticsearch/pull/71721
* [x] RestGetMappingAction  (https://github.com/elastic/elasticsearch/pull/41676) **feature branch compatible draft https://github.com/elastic/elasticsearch/pull/58426** on master https://github.com/elastic/elasticsearch/pull/71721
* [x] RestPutMappingAction  (https://github.com/elastic/elasticsearch/pull/41676) **feature branch compatible draft https://github.com/elastic/elasticsearch/pull/58426** on master https://github.com/elastic/elasticsearch/pull/71721
* [x] RestValidateQueryAction  (https://github.com/elastic/elasticsearch/pull/46927) https://github.com/elastic/elasticsearch/pull/74171
* [x] RestBulkAction  (#46983) in master https://github.com/elastic/elasticsearch/pull/73571
* [x] RestDeleteAction  (#47671) **feature branch compatible https://github.com/elastic/elasticsearch/pull/58246** https://github.com/elastic/elasticsearch/pull/73115
* [x] RestGetAction  (https://github.com/elastic/elasticsearch/pull/46587) **feature branch compatible https://github.com/elastic/elasticsearch/pull/53228/** for get only in order to make index tests pass on master #69131
* [x] RestGetSourceAction  (https://github.com/elastic/elasticsearch/pull/46931) https://github.com/elastic/elasticsearch/pull/73957
* [x] RestIndexAction  (#47671) **feature branch compatible https://github.com/elastic/elasticsearch/pull/53228/**  on master https://github.com/elastic/elasticsearch/pull/69131
* [x] RestMultiGetAction  (https://github.com/elastic/elasticsearch/pull/46587) in master https://github.com/elastic/elasticsearch/pull/73878
* [x] RestMultiTermVectorsAction  (https://github.com/elastic/elasticsearch/pull/41640) **feature branch compatible https://github.com/elastic/elasticsearch/pull/54572** https://github.com/elastic/elasticsearch/pull/72155
* [x] RestTermVectorsAction  (https://github.com/elastic/elasticsearch/pull/41640) **feature branch compatible https://github.com/elastic/elasticsearch/pull/54572** https://github.com/elastic/elasticsearch/pull/72155
* [x] RestUpdateAction  (#47671) **feature branch compatible https://github.com/elastic/elasticsearch/pull/58246** https://github.com/elastic/elasticsearch/pull/73115
* [x] RestCountAction  (https://github.com/elastic/elasticsearch/pull/42112) https://github.com/elastic/elasticsearch/pull/73958
* [x] RestExplainAction  (https://github.com/elastic/elasticsearch/pull/46926) https://github.com/elastic/elasticsearch/pull/73901
* [x] RestMultiSearchAction  (https://github.com/elastic/elasticsearch/pull/41640) **feature branch compatible https://github.com/elastic/elasticsearch/pull/54572** https://github.com/elastic/elasticsearch/pull/72155
* [x] RestSearchAction  (https://github.com/elastic/elasticsearch/pull/41640) **feature branch compatible https://github.com/elastic/elasticsearch/pull/54572** https://github.com/elastic/elasticsearch/pull/72155
* [x] RestGraphAction  (https://github.com/elastic/elasticsearch/pull/46935) https://github.com/elastic/elasticsearch/pull/74185
* [x] RestSimulatePipelineAction  #50131 https://github.com/elastic/elasticsearch/pull/74222/
* [ ] Remove types from Request objects
* [x] SearchRequest  (https://github.com/elastic/elasticsearch/pull/42112)
*  [x] QueryShardContext  (https://github.com/elastic/elasticsearch/pull/42112)
* [x] TermVectorsRequest  (https://github.com/elastic/elasticsearch/pull/42198) and MoreLikeThisQuery https://github.com/elastic/elasticsearch/pull/75123
* [x] ValidateQueryRequest  (https://github.com/elastic/elasticsearch/pull/46927) https://github.com/elastic/elasticsearch/pull/74171
* [x] ExplainRequest  (https://github.com/elastic/elasticsearch/pull/46926)
* [x] RoutingMissingException  (https://github.com/elastic/elasticsearch/pull/46587) just a message has changed. not implementing
* [ ] Remove types from the query DSL
* [x] AbstractGeometryQueryBuilder  (#47792) https://github.com/elastic/elasticsearch/pull/74553
* [x] TermsQueryBuilder  (https://github.com/elastic/elasticsearch/pull/46943) https://github.com/elastic/elasticsearch/pull/74544
* [x] PercolateQueryBuilder  (https://github.com/elastic/elasticsearch/pull/46985) https://github.com/elastic/elasticsearch/pull/74698/
* [x] Remove support for `include_type_name` in index creation, mapping and template APIs. #48632 **feature branch compatible https://github.com/elastic/elasticsearch/pull/54197** on master https://github.com/elastic/elasticsearch/pull/70966
* [ ] Remove type parameters from the node client
* [ ] prepareIndex()
* [ ] prepareDelete()
* [ ] prepareUpdate()
* [ ] PutMappingRequest
* [x] Remove `_type` from GET responses  (https://github.com/elastic/elasticsearch/pull/46587)
* [x] Remove `_type` from `_search` responses.  (https://github.com/elastic/elasticsearch/pull/46942)
* [ ] Remove searches on the `_type` field (e.g. in terms lookup and percolator queries)
* [x] Remove `type` query https://github.com/elastic/elasticsearch/pull/47207
* [ ] Disallow using the `_type` field in queries (such as `term` and `wildcard`). (#51100)
* [ ] Remove types from watcher's `IndexAction` (https://github.com/elastic/elasticsearch/pull/47986)
* [ ] Remove types from WatcherSearchTemplateRequest. (#51112)
* [ ] Remove deprecated typed methods on the high-level REST client. #48471

**SHOULD**
* [x] Remove types from `TermsLookup`  (https://github.com/elastic/elasticsearch/pull/46943)
* [ ] Remove type from `SourceToParse` (#47229)
* [ ] Remove types from `IndexShard.applyXOperation` methods (#52977

* [ ] Remove code that is related to the `_default_` mapping.  (https://github.com/elastic/elasticsearch/pull/44945)
* [ ] Remove the `_type` mapping field? (#51100)
* [x] InternalIndexingStats only needs one stats instance https://github.com/elastic/elasticsearch/pull/47203

**KNOWN BUGS/ TRAPS**
* Index creation and put template requests can accept malformed mappings: https://github.com/elastic/elasticsearch/issues/38266

Remaining:
* [x] REST-layer version compatibility
* [ ] Rewrite `Removal of Types` doc to point to 7x branch https://github.com/elastic/elasticsearch/pull/53670
* [ ] Master nodes should refuse to join a cluster with multi-typed index templates #53018
* [ ] Test rolling upgrades from 7x with typed mappings and templates #48800
* [ ] Remove ability to reference `_type` in scripts via `LeafDocLookup` https://github.com/elastic/elasticsearch/pull/53605
* [ ] Add deprecation warning to `TermsLookup#parseTermsLookup()` in 7x when type is included https://github.com/elastic/elasticsearch/pull/53731
* [x] Remove TypeFieldMapper

Longer term:
* [ ] Merge back FieldMapper and MappedFieldType (issue: #41058)
* [ ] Remove `String type` parameter from all internal code, eg. `MapperService`.

**Comment by syedsouban** [comment]
Hi, I use elasticsearch at work. I would like to contribute to elasticsearch. I was thinking if there are issues which I can work on as a new contributor. Thanks!

**Comment by pgomulka** [comment]
@syedsouban thank you for your interest in contributing to Elasticsearch. Have a look into these issues for the work that might be good for new contributors. https://github.com/elastic/elasticsearch/labels/good%20first%20issue

**Comment by pgomulka** [comment]
all of the type related changes have been brought back under rest api compatibility (the rest layer only)
closing issue
