### ISSUE TITLE
Field retrieval API design + implementation

### ISSUE THREAD

**Issue by jtibshirani** [elastic/elasticsearch#55363]
Original issue: https://github.com/elastic/elasticsearch/issues/49028
Feature branch: [field-retrieval](https://github.com/elastic/elasticsearch/tree/field-retrieval)

### Motivation
Often a user wants to retrieve a particular set of fields during a search. Currently, we don't support this usage pattern in a good way. In short, given a list of fields, there is no easy way to load all of their values:
* We can’t load all of them from doc values. Some fields like text fields may not have doc values at all, or we may exceed the limit for a reasonable number of doc value fields to load.
* It’s not easy to load all of them through source. For example, if the field is a field alias, it’s difficult to determine where to find its value in the source.

Better field retrieval support is becoming even more important now that we're introducing more field types that don’t fit the typical pattern like `constant_keyword` and the proposed runtime fields (https://github.com/elastic/elasticsearch/issues/48063).

### Feature Summary
We plan to add a new `fields` section to the search request, which users would specify instead of using source filtering to load fields from source:

```
POST logs-*/_search
{
  "query": { "match_all": {} },
  "fields": [
    "file.*",
    {
      "field": "event.timestamp",
      "format": "epoch_millis"
    },
    ...
  ]
}
```

Both full field names and wildcard patterns are accepted. Only leaf fields are returned, the API will not allow for fetching object values. The fields are returned as a flat list in the `fields` section in each hit, the same as we do for `docvalue_fields` and `script_fields`.

Overall, the API gives a friendly way to load fields from source:
* If a non-standard field like a field alias, multi-field, or constant_keyword is specified in `fields`, then we’ll consult the mappings to find and return the right value.
* The fields are returned in a flat list, as opposed to structured JSON.
* For date and numeric field types, we would support the same `format` parameter as we do for `docvalue_fields` to allow for adjusting the format of the results.
* Each value would be returned in a 'canonical' format -- for example if a field is mapped as an integer, it will be returned as an integer even if it was specified as a string in the _source.

Some clarifications:
* In this first pass, the API will not attempt to load from stored fields or doc values.
* For simplicity of parsing, values will always be returned in an array, even if there is only one value present.

### Implementation Plan
- [x] Introduce a `fields` section in the search request that fetches values from source. (#55639)
- [x] Correctly resolve field aliases, multi-fields, and copy_to. (#55889)
- [x] Consult field mappings to parse and correctly format each value. Also handle constant_keyword. (#56928)
- [x] Handle `ignore_malformed`. (#56928)
- [x] Support `ignore_above`. (#57385) 
- [x] Support setting a format through the `format` parameter. (#57893) 
- [x] Measure performance and look into improvements. (#58196)
- [x] Support `null_value`. (#58623)
- [x] Improve documentation around field loading. (#57500, #58787)
- [x] Handle geo values. (#59821)

Future improvements:
* Move `FieldMapper#lookupValues` to `MappedFieldType`. (?)
* Handle meta fields like `_size`.
* Make use of more efficient source parsing: https://github.com/elastic/elasticsearch/issues/52591.
* Support the API in `inner_hits`.

### Open Questions
* If a wildcard pattern matches both a parent field and one of its multi-fields, should we just return the parent to avoid returning the same value twice? A similar question holds for field aliases and their target fields.
* Should the API return fields in `_source` that have been disabled in the mappings (`enabled: false`)?
* For `keyword` fields, should we apply the `normalizer` or return the original value?

**Comment by jtibshirani** [comment]
We discussed as a group, and decided that we want to support `ignore_malformed`, `ignore_above`, and `null_value` in the fields API.

The arguments in favor:
* We want the API to be consistent with queries and aggregations. For example, say there was a keyword field with `ignore_above` configured. In a search we could run a `terms` aggregation on the field and also load it through `fields`. It would be confusing if the output of `terms `was missing a large value that was ignored, but `fields` showed the value.
* The API always parses the values using their mapping type -- for example an integer field that's passed as the string `"42"` will be returned as the integer `42`. So it's very natural to ignore malformed values and avoid returning these. If we are respecting `ignore_malformed`, it is consistent to also respect the related option `ignore_above`.

There wasn't clear agreement on whether we should apply the `normalizer` to keyword fields. I'm working to

**Comment by jtibshirani** [comment]
I ran some benchmarks to check the performance wasn't too different from source filtering.

**Set-up**
Using the metricbeat rally track, I benchmarked searches with different field loading strategies:
* A baseline where no fields or `_source` data are requested.
* Load fields through `docvalues_fields`, disable `_source`.
* Load fields through source filtering.
* Load using new `fields` API, disable `_source`.

To make it a tough scenario for loading from source, I added a search filter so that documents tend to be quite large (~200 fields). We set `size: 100` to make the timing differences more noticeable.

Each experiment loads a different number of fields:

* `load-single-*`: load 1 field
* `load-small-*`: load ~5 fields
* `load-medium-*`: load ~35 fields

**Results**
```
| Metric |                        Task |       Value |   Unit |
|---------------------------------------------------------------:|----------------------------:|------------:|-------:|
|  50th percentile service time |                   load-none |      10.832 |     ms | 
|  90th percentile service time |                   load-none |     10.9151 |     ms |
        
|  50th percentile service time | load-single-docvalue-fields |     10.9799 |     ms |
|  90th percentile service time | load-single-docvalue-fields |     11.3019 |     ms |
|  50th percentile service time |   load-single-source-filter |     15.5808 |     ms |
|  90th percentile service time |   load-single-source-filter |     16.0853 |     ms |
|  50th percentile service time |          load-single-fields |     17.9226 |     ms |
|  90th percentile service time |          load-single-fields |     18.0486 |     ms |
        
|  50th percentile service time |  load-small-docvalue-fields |     11.8346 |     ms |
|  90th percentile service time |  load-small-docvalue-fields |     11.9437 |     ms |
|  50th percentile service time |    load-small-source-filter |     15.9773 |     ms |
|  90th percentile service time |    load-small-source-filter |     16.1746 |     ms |
|  50th percentile service time |           load-small-fields |     18.4241 |     ms |
|  90th percentile service time |           load-small-fields |     19.1415 |     ms |

|  50th percentile service time | load-medium-docvalue-fields |     13.4794 |     ms
|  90th percentile service time | load-medium-docvalue-fields |     13.5975 |     ms |
|  50th percentile service time |   load-medium-source-filter |     17.7839 |     ms |
|  90th percentile service time |   load-medium-source-filter |     18.5534 |     ms |
|  50th percentile service time |          load-medium-fields |     21.7517 |     ms |
|  90th percentile service time |          load-medium-fields |     22.1342 |     ms |
```

Notes:
* Loading from `fields` is consistently slower than source filtering. This seems related to source loading/ decompression: for source filtering, we make sure to load both the `_id` and the `_source` in the same 'load stored fields' call. However, in the new fetch fields phase, we need to make a separate call to 'load stored fields'. I tested a hacky version that shared the stored fields loading with `_id`, and it closed the timing gap.
* Using `docvalue_fields` was surprisingly fast, even for a decent number of fields (~35).

**Comment by nik9000** [comment]
> Using `docvalue_fields` was surprisingly fast, even for a decent number of fields (~35).

This is interesting! I wonder if it has to do with making those particular doc_values "hot" in the disk cache. In my head the tradeoff with doc_values has mostly to do with them being stored column-wise rather than grouped with the docs. Great for aggregations, but when you have fetch all of them you could end up with a bunch of random seeks. But in rally it is fairly easy to light up the disk cache just by requesting the same docs over and over again so those random seeks become cache hits.

I *guess* a similar thing happens comparing spinning disks with SSDs. And we have folks using both. Maybe searchable snapshots is sort of like that problem too, but even worse!

**Comment by jtibshirani** [comment]
> Loading from fields is consistently slower than source filtering. This seems related to source loading/ decompression: for source filtering, we make sure to load both the _id and the _source in the same 'load stored fields' call.

I opened a PR to refactor the fetch phase so that stored fields are only loaded once per hit: #58196. Here are the new performance numbers after that change. Now the times are very similar to source filtering:

```
| Metric                        |                        Task |       Value |   Unit |
|------------------------------:|----------------------------:|------------:|-------:|
|  50th percentile service time |          load-single-fields |     15.7337 |     ms |
|  90th percentile service time |          load-single-fields |     16.9116 |     ms |
|  50th percentile service time |           load-small-fields |     15.8501 |     ms |
|  90th percentile service time |           load-small-fields |     16.3547 |     ms |
|  50th percentile service time |          load-medium-fields |     18.9691 |     ms |
|  90th percentile service time |          load-medium-fields |      19.975 |     ms |
```

> I filed #58155 with more details on the first note.

I am going to close this issue, I was confused and thought the refactor was harder than it actually was.

**Comment by jtibshirani** [comment]
I thought more about the question of whether we should apply `normalizer` before returning a keyword, and to me it makes sense to apply normalization by default:
* The actual name `normalizer` suggests that it is performing standardization, which is exactly the sort of thing we claim to do when returning values. I was hesitant earlier because normalization felt more like text analysis to me, but I think it's really just value standardization (and we just happen to re-use the analyzer framework).
* It's most consistent with other parts of the search response, in particular `terms` aggregations.
* If the original value is actually interesting in terms of casing, accents, etc., then a user will probably avoid normalizing, and instead perform a case-insensitive search (coming soon :)). Or, they would set up a multi-field where one field contains the original, and the other a normalized form.

Tagging @jpountz @jimczi @javanna @nik9000 in case they have thoughts on the above, happy to discuss here!

**Comment by jimczi** [comment]
+1 to support `normalizer` ootb. As you said it's consistent with aggregations and script. That would also make the `docvalue_fields` alternative less appealing, which I find important since we want to simplify the reasoning when retrieving fields.

**Comment by javanna** [comment]
@jtibshirani when you say "by default" does that mean it can be disabled? From the point of view of "when you retrieve, you get what you sent, when you search and aggregate, you search on and get back what was indexed" I am torn, I would personally expect the raw value loaded from source. Though if users can control what they get, I would not mind that the default is normalized.

**Comment by jtibshirani** [comment]
@javanna I was indeed wondering if we could make the behavior configurable, but don't have immediate plans to do so. It's always nice to avoid configuration options and have strong defaults.

I have also been on the fence about this, I can see arguments both ways. I suggest that we move forward with normalizing the values for now. I'm going to ask the teams planning to use this feature (SQL, ML, Kibana) to try to integrate with it before we ship it, and have a short list of questions I plan to ask them which includes keyword normalization. The questions are tracked in the issue description.

**Comment by jtibshirani** [comment]
We discussed how geo fields should be returned with @talevy and @imotov. A summary of our discussion:
* Geo data should be returned in a consistent format. We accept a variety of formats during indexing, and feel it would be helpful for clients if all fields were returned in a single format. 
* The default format should be 'geojson', since this matches our usual JSON return format, and it's natural for Kibana. We should also support well-known text, which is best for SQL.
* The user will be able to select the format by setting `format: wkt` or `format: geojson`.
* Ideally if the source value is already in the right format to return, we won't re-parse it to a geolib object then re-serialize it.

**Comment by jtibshirani** [comment]
An additional note: now that we'll return points in geojson format by default, for consistency we should accept this format when indexing points. We currently don't allow geojson, the work to add support is tracked in #47815.

**Comment by jtibshirani** [comment]
The feature branch was merged in #60100. I'll open new issues/ PRs for the follow-up improvements mentioned in the description.
