### ISSUE TITLE
[DOCS] Add collapsible sections to 8.0 breaking changes

### ISSUE THREAD

**Issue by jrodewig** [elastic/elasticsearch#55629]
#55334 added collapsible sections to the 7.8 breaking changes. This issue will make similar changes to the 8.0 breaking changes.

This work will likely be spread out over multiple PRs to make the changes and reviews manageable:
- [x] Aggregations changes #55811
- [x] Allocation changes #55811
- [x] Analysis changes #55811
- [x] Circuit breaker changes #55862
- [x] Cluster changes #55862
- [x] Discovery changes #55862
- [x] HTTP changes #56297
- [x] Index Lifecycle Management changes #56297
- [x] Indices changes #56297
- [x] Java API changes #56356, #56510
- [x] Mapping changes #55862
- [x] Network changes #56356
- [x] Node changes #56356
- [x] Packaging changes #56356
- [x] Reindex changes #56356
- [x] REST API changes #56418, #56437
- [x] Rollup changes #56356
- [x] Search Changes #56418, #56437
- [x] Security changes #56418, #56439
- [x] Settings changes #56418, #56440
- [x] Snapshot and Restore changes #56418, #56441
- [x] Thread pool changes #56418, #56437
- [x] Transport changes #56418, #56437
- [x] Sort sections alphabetically #55828
- [x] Ensure all changes are included in Stack Install and Upgrade Guide

Relates to #53229

**Comment by jrodewig** [comment]
While a few of these changes are still waiting on `Impact` sections, they are all now collapsible.
