### ISSUE TITLE
[DOCS] Snapshot/restore APIs are missing from the REST APIs docs

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#56069]
A user on the forums [observed](https://discuss.elastic.co/t/recovering-from-missing-state-si-file/229744/7) that the snapshot APIs are documented under the "Snapshot/Restore" topic and not in the burgeoning "REST APIs" section of the reference manual. I suspect this isn't deliberate and we'll eventually add those docs, but I'm opening this issue to capture this observation in case it isn't tracked elsewhere.

Snapshots/restore APIs to document:
- [x] Clean up repository API #56519
- [x] Put repository API #56827
- [x] Delete repository API #57043
- [x] Get repository API #57150
- [x] Verify repository API #57253
- [x] Create snapshot API #58519 
- [x] Delete snapshot API #58865
- [x] Get snapshot API #59098
- [x] Get snapshot status API #59355 
- [x] Restore snapshot API #59937

**Comment by jrodewig** [comment]
I believe this was closed in error. Re-opening.

**Comment by jrodewig** [comment]
@lockewritesdocs I've left a checklist of APIs left to document in the description. Those with PRs listed to the right are already done or in flight. Thanks!

**Comment by lockewritesdocs** [comment]
All snapshot and restore APIs are documented 🎉  Marking this issue as closed.
