### ISSUE TITLE
Daylight Savings Time Optimization Followups

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#56124]
After we merge #55559 we'll have a few things to clean up:

* [ ] Implement interval rounding
* [ ] Cache `LocalTimeOffset.Lookup`s to avoid building them over and over again. They are quite expensive to build and would likely cache very well.
* [ ] Investigate how expensive loading the min and max is. Maybe we can cache them on the reader or something.
* [ ] Plug this in to `auto_date_histogram`. It could speed it up a *ton*.
* [ ] Remove the optimization that rewrites non-fixed time zones into fixed ones in `date_histogram`. It won't really do anything after we get interval rounding.

Maybe:
* [ ] Plug this in to `composite`. It might not benefit much from it but then again it might. It is worth checking.

**Comment by nik9000** [comment]
>     * Cache `LocalTimeOffset.Lookup`s to avoid building them over and over again. They are quite expensive to build and would likely cache very well.

The kind of cache that we'd need to build makes this maybe not something we should do. We'd get terrible hit rate if we just used the range and zone id as the key and java.util.time isn't *that* slow to give us the data that we need. I'll think about this one some more.
