### ISSUE TITLE
Rework FieldMapper and MappedFieldType

### ISSUE THREAD

**Issue by romseygeek** [elastic/elasticsearch#56814]
We currently have two abstractions that encapsulate different mapping types within elasticsearch.  `FieldMapper` defines how a particular field from a json document should be indexed into lucene, while `MappedFieldType` defines factory methods for building queries against those fields.  However, `MappedFieldType` also extends lucene's `FieldType` and so holds some index structure configuration, which really belongs on `FieldMapper`.  As a result, it also handles some merging and consistency checking logic dealing with mapping updates, which again only really effect index-time structures.

We should rework the relationship here, decoupling `MappedFieldType` from `FieldType` and keeping it as a simple source of query factory methods.  This would also make it easier to generate field types that point to other fields, adding functionality on the way.  For example, if we reworked field aliases to be a simple pointer field type, then we could remove a lot of special-casing logic in MapperService that has to handle normal fields and aliases separately.

Because of the fairly complex coupling already involved here, this will need to be done in several steps:
* [x] Move mapping update consistency checks from MappedFieldType to FieldMapper (#56915)
* [x] Stop MappedFieldType extending FieldType, and move index configuration to FieldMapper (#57666)
* [x] Add a new abstraction on MappedFieldType encapsulating 'text search' config - analyzers, FieldType, etc (#58023)
* [x] Remove base FieldMapper class references to lucene's FieldType
* [x] Remove 'global' FieldMapper fields that refer to specific data types
  * [ ] analyzers and similarity should move to TextSearchInfo
  * [ ] `eager_global_ordinals` only applies to keyword and join
  * [ ] `index`, `doc_values` and `store` won't apply to search-time only mappers, so maybe move them as well?
* [ ] Make FieldMapper.fieldType() abstract, and don't require a `MappedFieldType` to be passed to the base class constructor.  This will allow for late-binding of search fields, so that they can reference other field mappers.
* [ ] Rename MappedFieldType to SearchField

**Comment by romseygeek** [comment]
> *  Make FieldMapper.fieldType() abstract, and don't require a MappedFieldType to be passed to the base class constructor. This will allow for late-binding of search fields, so that they can reference other field mappers.
> * Rename MappedFieldType to SearchField

I don't think these two are necessary any more; the latter renaming is just noise now, and we already have MappedFieldTypes that are separate from FieldMappers in runtime fields.  So I think this can be closed as complete.
