### ISSUE TITLE
[DOCS] Document data streams

### ISSUE THREAD

**Issue by jrodewig** [elastic/elasticsearch#57905]
This is a meta issue to track the progress of documentation efforts for data streams in Elasticsearch. To monitor ongoing development, see #53100.

- [x] Reformat Data streams intro #57954
- [x] Reformat Data streams overview #57954
  - [x] Cannot close write index on a data stream #57954
  - [x] Cannot index new documents in read-only backing indices #57954
  - [x] Timestamp mapping #57954
- [x] Reformat tutorials #57883
- [x] Add additional tutorials/examples:
  - [x] Add resolve API check to set up a data stream tutorial #58167
  - [x] Index with ingest pipeline #58343
  - [x] Note that wildcard + comma-delimited is supported in ds search. Mixing indices + data streams is also supported. #58278
  - [x] Get data stream info #58068
  - [x] Delete a data stream #58068
  - [x] Update mappings/settings for a data stream's backing indices #58148
  - [x] Update/delete documents in a data stream #58194
  - [x] Reindex #58013
  - [x] Get stats for a data stream #57905
- [x] Update ILM docs to provide guidance for data streams, particularly automate rollovers #58035 
- [x] Update reindex API docs to provide guidance for data streams #58013
- [x] Review data stream API docs. Cross-link to data streams overview. #58322, #58344
- [x] Make existing docs aware of data streams:
  - [x] API conventions #58695
  - [x] Bulk API #58340
  - [x] Cat APIs #58699
  - [x] Clear indices cache API #59324
  - [x] Clear searchable snapshot cache API #59325
  - [x] Cluster health API #58945
  - [x] Cluster state API #58945
  - [x] Count API #58771
  - [x] Create snapshot API #58513
  - [x] Delete API #58340
  - [x] Delete by query API #58679
  - [x] EQL search API #58611
  - [x] Field caps API #59326
  - [x] Flush API #58950
  - [x] Force merge API #58951
  - [x] Get field mapping API #58689
  - [x] Get index API #59329
  - [x] Get mapping API #59329
  - [x] Get rollup index caps #59423
  - [x] Get settings API #59329
  - [x] Graph explore API #58683
  - [x] Ilm explain API #59343
  - [x] Index API #58340
  - [x] Indices segments API #59329
  - [x] Indices stats API #59329
  - [x] Migration deprecation info API #58685
  - [x] MSearch API #58610
  - [x] Open index API #58615
  - [x] Put index settings API #58849
  - [x] Put mapping API #58849
  - [x] Rank eval API #59069
  - [x] Recovery  API #59329
  - [x] Refresh API #59329
  - [x] Reindex API #58051
  - [x] Reload analyzers API #59422
  - [x] Remove ilm policy from index API #58777
  - [x] Rollover API #55551
  - [x] Rollup search API #59423
  - [x] Search API #58278
  - [x] Searchable snapshot stats API #59325
  - [x] Update by query API #58679
  - [x] Upgrade API (undocumented API)
  - [x] Upgrade status API (undocumented API)
  - [x] Validate query API #59420
- [x] Document prohibited write index actions: 
  - [x] Clone #58105
  - [x] Close #57770
  - [x] Delete #58341
  - [x] Freeze #58058
  - [x] Shrink #58105
  - [x] Split #58105
- [x] Document that a data stream's in-use composable template cannot be deleted #58347
- [x] Resolve index API docs #58206
- [x] Glossary definition #58014
- [x] Note that index aliases do not support data streams or backing indices #59321
- [x] Not that custom _routing is not supported for index requests targeting a data stream (#58749) #59323

**Comment by andreidan** [comment]
@jrodewig I've pushed an initial (rather raw) attempt at making the ILM docs data stream aware in https://github.com/andreidan/elasticsearch/tree/docs-ilm-data-stream 
Let me know if I can further help with the docs.

**Comment by jrodewig** [comment]
@andreidan  Thanks for sharing this branch.

@jakelandis mentioned that are still some Logstash use cases that may take advantage of the current index alias method. I could also see this method still being useful to users that want to update their existing data frequently.

If you don't mind keeping both the index alias and data stream versions, I think this branch is ready for a PR. I have some very minor wording suggestions, but this is very good as-is. Thanks very much for putting it together!

**Comment by andreidan** [comment]
@jrodewig sure, I'll add the index alias method back to the tutorial and open a PR tomorrow. Thanks for checking the branch
