### ISSUE TITLE
[ML] Update APIs that support _all to also use wildcarded parameters

### ISSUE THREAD

**Issue by benwtrent** [elastic/elasticsearch#58489]
Many ML APIs support `_all` and `*` as parameters to grab ALL entries in a collection.

All APIs that support `_all` or `*` for gathering data should also support comma delimited patterns (e.g. `foo*,bar`).

Here is a list of our APIs with incomplete support:

- [x] `GET _ml/calendars/<calendar_id>/events`
- [x] `GET _ml/calendars/<calendar_id>`
- [x] `GET _ml/anomaly_detectors/<job_id>/model_snapshots/<snapshot_id>` (support more than one snapshot id)
- [x] `DELETE _ml/anomaly_detectors/<job_id>/_forecast/<forecast_id>` (support more than one forecast id)

**Comment by benwtrent** [comment]
This is corrected in https://github.com/elastic/elasticsearch/pull/62563
