### ISSUE TITLE
Add support for runtime fields

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#59332]
### Runtime fields

We would like to increase the flexibility of the search API by introducing support for runtime fields. 

Runtime fields are not indexed and do not have doc_values, meaning Lucene is completely unaware of them, but they are consumed through the field capabilities API and the search API like any ordinary field. It is possible to retrieve them as well as query them, aggregate and sort on them. 

Runtime fields make searches slower, as computing their values for each document (that may match the query) is costly, depending on how they are calculated; it is highly recommended that the Async Search API is used to run searches that use runtime fields.

One limitation of runtime fields compared to ordinary fields is that they don’t support scoring as they are not indexed and we are not going to compute the document frequency for them, which is required for scoring.

Runtime fields are not part of the _source, hence they are not returned by default as part of the search hits. They can be specifically requested through the field retrieval API (#55363).

A runtime field is defined by its data type and the script that computes its values. As of today, each search section already supports scripting, but the contexts are different, as well as the required syntax. We want to unify this to a single place where a script can be specified. Such a script always has access to `_source`, any other stored fields as well as doc_values.

A runtime fields can be defined in the mappings by adding its definition to a new `runtime` section at the same level as `properties`, where fields that exist in _source are defined:

```
PUT /my-index/_mappings
{
    "runtime" : {
        "day_of_week" : {
            "type" : "keyword",
            "script" : {
                "source" : "emit(doc['timestamp'].value.dayOfWeekEnum.getDisplayName(TextStyle.FULL, Locale.ROOT))"
            }
        }
    }
}
```

The data types supported for runtime fields are initially `keyword`, `long`, `double`, `date`, `ip`, `boolean`, `geo_point`. In the example above, we extract the day of week (e.g. Monday) from another field called `timestamp` which is defined as a `date`. The script can refer to other fields, including other runtime fields: we need to implement a mechanism to resolve fields dependencies in the correct order, and prevent cyclic dependencies.

The defined field can then be used like any other field in the different sections of the search API:

```
GET my_index/_search
{
    "aggs" : {
        "days_of_week" : {
            "terms" : {
                "field" : "day_of_week"
            }
        }
    }
}
```

Each runtime field type will consist of a `MappedFieldType` that exposes a runtime fielddata implementation that generates doc_values on the fly for the needed data type. Additionally, all the basic Lucene queries for each runtime field type need to be written to query the corresponding fielddata/doc_values implementation.

Support for runtime fields in Elasticsearch will be released under the Elastic license.

The following is a high-level list of tasks required to develop the initial support for runtime fields, which will lay the foundations for the next phases:

#### Mappers and field types
- [x] make `ScriptService` available when parsing field mappers (#60933)
- [x] Implement `runtime` field mapper with dynamic mapped field type, one per supported runtime_type (#58939, #59391, #59659, #59813, #60029, #60027, #60580)
- [x] Implement fielddata and queries for `keyword` field type (#59372, #59527, #59523, #59630, #59672, #60463)
- [x] Implement fielddata and queries for number field types
  - [x] `long` (#59721, #59816, #59884)
  - [x] `double` (#59933)
- [x] Implement fielddata and queries for `date` field type (#60092, #60465, #61105)
- [x] Implement fielddata and queries for `ip` field type (#60533 + #61230)
- [x] Implement fielddata and queries for `boolean` field type (#60830)

#### API

- [x] Search API: integrate with field retrieval API to allow retrieval of runtime fields (#60775)
- [x] Search API: reject queries against runtime fields when expensive queries are disallowed (#59658) 
- [x] Disallow using runtime fields in index sorting (#60224, #60851)

#### Scripting
- [x] Define script syntax for emitting single value as well as arrays/collections: conversion functions VS emit value function (#59647, #61504, #61752)
- [x] Enable using regexes in painless by default (#49873)
- [x] Opt runtime fields scripts out of the script compilation limit. It'd be lame to fail a mapping update because you've compiled too many scripts lately. (#61238 + #61297)
- [x] Expose what fields a script refers to (#60001, #60995) (done but not back-ported yet)

#### Infrastructure
- [x] Protect against many values being returned from a script for the same document (#61938)
- [x] Protect against cyclic runtime fields references at runtime (#60318, #61430)
- [x] Make `SearchLookup` available to `MappedFieldType#fielddataBuilder` (#60224. #61430)
- [x] Introduce runtime fields in our existing integration tests for more extensive test coverage (#61114)

#### Security
- [x] Test behavior when a script is executed that accesses fields that the user is not authorized to see (#61820)

#### Telemetry
- [x] Add info and usage endpoints for runtime fields (#65600)

#### Docs

- [x] Document `runtime` section and corresponding field types (#62653)
  - [x] inconsistencies caused by updating a script while queries that rely on it are running
  - [x] existing queries / visualizations may break because runtime fields can be updated
  - [x] queries against runtime fields are deemed expensive and rejected when expensive queries are disallowed
- [x] Document how to define runtime fields in a search request
- [x] Document the ability to omit the script from the definition of a runtime field
- [x] Document the ability to shadow existing fields with a runtime field
- [x] Document dynamic runtime mode (#66304)

**Comment by Patrick0308** [comment]
Can I help you with this exciting work?

**Comment by nik9000** [comment]
> Can I help you with this exciting work? @javanna @nik9000

@Patrick0308, sorry I didn't get back to you weeks ago. I sort of thought @javanna would reply and that he thought I'd reply. So, here goes. Yes, we'd like help, but we're talking for like an hour every day debating the right way to do it. I don't know that we have a vision yet that is consistent that we'd know what to do with extra help. I think for now if you'd like the help Elasticsearch it'd be better to look elsewhere.

That said, I see you opened #60064. I it pretty close to what I would have done a few weeks ago. Like I said, we've been talking a bunch since then. And I've changed in my thinking somewhat. I'm not 100% convinced we want different contexts for integer, short, and byte. We probably will, but, yeah, we're not sure how yet. So as it stands I'd like to delay reviewing #60064 for a while. Once we're sure that we do want a context for `integer` I can review it because it'd be a shame to waste it. Things might have drifted a lot since then, but they might not!

**Comment by javanna** [comment]
All of the tasks for the first phase of Runtime Fields are completed. Runtime fields will ship with 7.11. Closing this.
