### ISSUE TITLE
EQL - query language for event data in Elasticsearch

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#59686]
Meta issue consolidating the EQL functionality released in Elasticsearch 7.9 as experimental.
EQL or Event Query Language is a declarative language dedicated for identifying patterns and relationships between events.

Consider using EQL if you:

- Use Elasticsearch for threat hunting or other security use cases
- Search time-series data or logs, such as network or system logs
- Want an easy way to explore relationships between events

A good intro on EQL and its purpose is available [here](https://www.elastic.co/blog/introducing-event-query-language). The language reference can be found at [this address](https://eql.readthedocs.io/en/latest/query-guide/index.html) while EQL on Elasticsearch is explained at length through a [dedicated chapter](https://www.elastic.co/guide/en/elasticsearch/reference/7.x/eql.html).

This release includes the following features:
- event queries
- sequences
- pipes

An in-depth discussion of EQL in ES scope can be found at https://github.com/elastic/elasticsearch/issues/49581.

Full history available [here](https://github.com/elastic/elasticsearch/issues?q=label%3A%22%3AQuery+Languages%2FEQL%22+is%3Aclosed+closed%3A%3C2020-07-17).

### High-level tasks

* [x] Create EQL plugin https://github.com/elastic/elasticsearch/issues/49583
* [x] Extract reusable components from SQL into common project https://github.com/elastic/elasticsearch/issues/49773
* [x] Synchronous EQL REST API for ad-hoc querying https://github.com/elastic/elasticsearch/issues/49634
* [x] Build query parser and plan on reusable SQL components
* [x] EQL transpiler for stateless EQL expressions to ES Search DSL https://github.com/elastic/elasticsearch/issues/49589 
* [x] Response format enhancements https://github.com/elastic/elasticsearch/issues/52845
* [x] Support existing EQL functions https://github.com/elastic/elasticsearch/issues/51556
* [x] Map EQL sequence parts to ES requests https://github.com/elastic/elasticsearch/issues/49590
* [x] Implement pipes logic in the plugin (not using aggregations) #49627
* [x] Head and Tail pipe #58536
* [x] Sequence implementation at #54227, #56300, #56768, #58635, #59292
* [x] High Level REST client support for EQL API https://github.com/elastic/elasticsearch/issues/51961
* [x] Cancelling a task's grandchildren when the task is cancelled #50990
* [x] Convert EQL REST API to be async (similar to async search) https://github.com/elastic/elasticsearch/issues/49638
* [x] Create documentation for using EQL #51057
* [x] Telemetry for EQL usage https://github.com/elastic/elasticsearch/issues/49630
* [x] Escape non-alphanumeric fields for EQL #51443
* [x] Remove feature flags and prepare for release https://github.com/elastic/elasticsearch/issues/51613

**Comment by costin** [comment]
Scheduled for release in Elasticsearch 7.9
