### ISSUE TITLE
EQL: Finalize EQL Request/Response API

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#59766]
There are several discussions around the API of EQL, in particular its response. The purpose of this meta issue is to have track all of them in one place.

- [x] ~~Response format~~ - whether to use the same structure across all responses or not (the current approach) #57018 
- [x] ~~Pagination~~; revisit whether it is needed for GA or not #52913
- [x] Replace `SearchHit` with something else #59764

**Comment by costin** [comment]
All issues have been addressed - closing the ticket.
