### ISSUE TITLE
[DOCS] Note whether cluster settings are dynamic or static

### ISSUE THREAD

**Issue by jrodewig** [elastic/elasticsearch#61236]
The following section defines dynamic and static settings:

https://www.elastic.co/guide/en/elasticsearch/reference/master/settings.html#cluster-setting-types

We should go through our setting documentation and note whether specific settings are dynamic or static.

- [x] Auditing settings #61235
- [x] Circuit breaker settings #61334
- [x] Cluster-level shard allocation and routing settings #61338
- [x] Cross-cluster replication settings
- [x] Discovery and cluster formation settings #61420
- [x] Field data cache settings #61424
- [x] HTTP #61424
- [x] Index lifecycle management settings #61745
- [x] Index management settings #61753
- [x] Index recovery settings
- [x] Indexing buffer settings #61753
- [x] License settings #61760
- [x] Local gateway settings #61760
- [x] Logging configuration
- [x] Machine learning settings https://github.com/elastic/elasticsearch/pull/61382
- [x] Monitoring settings https://github.com/elastic/elasticsearch/pull/61748
- [x] Node
- [x] Network settings #61760
- [x] Node query cache settings #61760
- [x] Search settings #61760
- [x] Security settings #62181
- [x] Shard request cache settings #61760
- [x] Snapshot lifecycle management settings #61760
- [x] Transforms settings https://github.com/elastic/elasticsearch/pull/61384
- [x] Transport #61760
- [x] Thread pools
- [x] Watcher settings #62218
