### ISSUE TITLE
Significant EQL changes in 7.10

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#62652]
This ticket serves as a central place for significant changes in EQL to better broadcast them to a larger group.
To keep things simple, please keep the discussions on each individual ticket.

### Concluded
- [x] Remove any overloading of `==` including that of wildcards `foo == "*.exe"`. May end up influencing the grammar.
Issue: #62651
- [x] Replace `` ` `` with `'` (available - see above) for quoting identifiers
Issues: #62663 PR: #62638 
- [x] Replace `?"` and `?'` for raw string literal `"""`
Issue: #62645 PR: #62539
- [x] Remove case-sensitivity parameter and make EQL case **in**-sensitive by default - impacted by #62651
Issue: #61883 and #62255 
- [x] Remove `'` for string literal declaration and keep only `"`
Issue: #61659 PR: #62458
- [x] Disallow 1 == 1 == 1
Issue: #61654, PR:#62567
- [x] Deprecate usage of `=` for equality checks in favor of `==`.
Issue: #62650 PR: #62756

(Edit: @rw-access changed the wording to "Proposed grammar changes" to be more clear)

**Comment by costin** [comment]
All issues have been addressed.
