### ISSUE TITLE
Convert remaining FieldMappers to parametrized form

### ISSUE THREAD

**Issue by romseygeek** [elastic/elasticsearch#62988]
The following field mappers still remain to be converted:

- [x] AbstractGeometryFieldMapper #63836
- [x] AbstractPointGeometryFieldMapper #63836
- [x] AbstractShapeGeometryFieldMapper #63836
- [x] AnnotatedTextFieldMapper
- [x] DenseVectorFieldMapper #62992 
- [x] ExternalMapper #63018 
- [x] FakeFieldMapper in DocumentFieldMapperTests #63018 
- [x] FakeStringFieldMapper
- [x] FlatObjectFieldMapper #63630 
- [x] HistogramFieldMapper #63004
- [x] ICUCollationKeywordFieldMapper
- [x] MetaJoinFieldMapper #63738
- [x] MockFieldMapper #63018 
- [x] Murmur3FieldMapper #63004
- [x] ParentIdFieldMapper #63738
- [x] ParentJoinFieldMapper #63738
- [x] PercolatorFieldMapper #63004
- [x] PhraseFieldMapper in TextFieldMapper
- [x] PrefixFieldMapper in SearchAsYouTypeFieldMapper #62938
- [x] PrefixFieldMapper in TextFieldMapper
- [x] RankFeatureFieldMapper #62938
- [x] RankFeaturesFieldMapper #62938
- [x] SearchAsYouTypeFieldMapper #62938
- [x] ShingleFieldMapper in SearchAsYouTypeFieldMapper #62938
- [x] SparseVectorFieldMapper #62992 
- [x] TextFieldMapper
- [x] TokenCountFieldMapper #62938
- [x] WildcardFieldMapper #63465

**Comment by romseygeek** [comment]
These are now all converted, and we can start merging FieldMapper and ParametrizedFieldMapper and cleaning up more generally.
