### ISSUE TITLE
EQL: remaining tasks for 7.11

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#64273]
The following features/bugs are desired for 7.11:

- [x] add wildcard pattern to `:` operator (#65154)
- [x] descending / tail ordering by default (#58646)
- [x] multiple arg for `:` ~~and wildcard / regex~~ (#64388)
- [x] add support for `?` in wildcard pattern for `:` operator (#65536)
- [x] enable all correctness tests (#65155)

Outside the scope but would be nice to have (moved after 7.11):
- a better language construct (keyword?) for wildcard / regex matching for one and multiple values (#64387)
- multi-value / array matching
- case-insensitive functions

**Comment by costin** [comment]
All features have been delivered.
