### ISSUE TITLE
Search layer / mappings improvements

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#64663]
This meta issue tracks some of the improvements and cleanups that we identified while working on the runtime fields project (#59332):

- [ ] Remove the last usage of `SearchContext#mapperService`: it is used for nested objects
- [ ] RemoveQueryShardContext#getObjectMapper : it is mostly used for nested objects and it indirectly exposes retrieving `MappedFieldType` going through `FieldMapper`s, which are not aware of runtime fields
- [ ] Clean up `SearchLookup` handling in `QueryShardContext`: a separate lookup object needs to be created for the fetch phase which is passed through to `MappedFieldFype#valueFetcher`, yet the (wrong) lookup can also be retrieved directly from the `QueryShardContext` 
- [ ] Clean up special handling for `allowUnmappedFields` and `mapUnmappedAsText` in `QueryShardContext`, they can be changed from consumers which seems dangerous and are only needed for the percolator.
- [ ] Review null checks on what `QueryShardContext#getFieldType` returns. They most likely need to be converted to use `QueryShardCOntext#isFieldMapped` instead which does not take the `allowUnmappedField` and `mapUnmappedAsString` flags into account
- [ ] Review calls to `FieldsVisitor#postProcess` and make sure that they are all necessary, in some cases we may be able to skip the call as it does nothing depending on which fields we are processing

**Comment by nik9000** [comment]
I've started to group things into themes for easier digestion. I've tried to sort the things for themes in rough priority order.

**Comment by javanna** [comment]
Thanks @nik9000 I plan to go through the list and re-sort things, possibly opening separate issues where we see fit.
