### ISSUE TITLE
Consolidate index version checks

### ISSUE THREAD

**Issue by jtibshirani** [elastic/elasticsearch#65399]
In order maintain compatibility with older indices, we sometimes need to check the index version and take special action. These index version checks happen in a variety of places and ways, making it hard to understand what logic depends on the index version. It also means that compatibility logic is scattered throughout various components, which hurts code quality.

It would be good to consolidate index version checks as much as possible. Some ideas:
- [x] Reduce ways of checking the index version setting, ideally to one. #65396
- [ ] Consolidate version checking logic into a small number of components, like `MapperService`.
  - Remove unnecessary references to index version. #65402, #65782, #65783, #65866
- [ ] Stop exposing the index version broadly through index settings (?)

**Comment by icemakegirl** [comment]
I have a question, is this issue still open? apparently all the quest are done
I am a beginner Dev

**Comment by javanna** [comment]
I think we can close this, what do you think @rjernst ?

**Comment by rjernst** [comment]
I agree, this can be closed. We now have IndexVersion which mostly satisfies the consolidation originally envisioned.
