### ISSUE TITLE
[DOCS] Rollup refactor docs

### ISSUE THREAD

**Issue by jrodewig** [elastic/elasticsearch#65515]
This meta issue tracks documentation efforts for the rollups refactor (AKA rollups v2).
To monitor ongoing development, see #42720.

### To Do:

- [x] Document rollup API #65398
- [x] Update rollup security privileges #65512
- [x] Document ILM rollup action #65633, ~#67108~, #68755
- [x] Update [rollup overview](https://www.elastic.co/guide/en/elasticsearch/reference/master/data-rollup-transform.html). Add redirects as needed. (https://github.com/jrodewig/elasticsearch/tree/docs__rollup-v2-overview)
  - [x] Add xref for overview page to legacy rollup API admon #68119
  - [x] Add xref to rollup glossary item #68119
- [x] Update [rollup glossary items](https://www.elastic.co/guide/en/elasticsearch/reference/master/glossary.html#glossary-rollup) #65519
- [x] Label legacy rollup APIs and add a deprecation warning. #65518
- [ ] Add support for multiple rollup configs
- [ ] Rollup migration API
- [ ] Note migrated rollup indices do not support automatic search resolution
- [ ] Note ES does not apply index templates to rollup indices
- [ ] Note runtime fields are not supported (in original index or search). Need to confirm.
- [ ] Release notes and highlights:
  - [x] Update [8.0 breaking changes](https://www.elastic.co/guide/en/elasticsearch/reference/master/breaking-changes-8.0.html#breaking_80_rollup_changes) for legacy rollups #66894
  - [ ] Document legacy API deprecation in breaking changes/migration guide (https://github.com/jrodewig/elasticsearch/tree/docs__rollup-deprecation)
  - [ ] Document new rollup functionality in release highlights (https://github.com/jrodewig/elasticsearch/tree/docs__rollup-release-highlights)
- [ ] UI changes:
  - [ ] Update reference in [Index Management](https://www.elastic.co/guide/en/elasticsearch/reference/master/index-mgmt.html#view-edit-indices) docs
  - [ ] Remove and/or combine the [Kibana rollup jobs docs](https://www.elastic.co/guide/en/kibana/current/data-rollups.html)
  - [ ] Differences between V2 and historical rollups

### Clean up before release:
 - [ ] Remove feature flag from docs integ test (c.f. https://github.com/elastic/elasticsearch/pull/65398)
 - [ ] Remove `permanently-unreleased-branch` conditionals
 - [ ] Update 7.x references to the actual release:
    - [ ] Rollup APIs: https://www.elastic.co/guide/en/elasticsearch/reference/master/rollup-apis.html#legacy-rollup-apis
    - [ ] Deprecation note: https://www.elastic.co/guide/en/elasticsearch/reference/master/rollup-put-job.html

**Comment by jrodewig** [comment]
We've decided to adopt a new approach to the rollup refactor.

I'm rolling back this work with https://github.com/elastic/elasticsearch/pull/70885 and closing this issue.
