### ISSUE TITLE
[DOCS] Put Security Privileges for every request

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch#66212]
While attempting to setup a fresh reindex from remote setup, I ran into trouble trying to figure out what I needed to provide for permissions for the remote user.

This problem logically extends to every API within Elasticsearch. Instead of making users jump to the security privileges page and try to determine what they need, it would help a lot to put a standardized section for every request in the docs with what privileges are needed (or are optional, such as what might be additionally necessary for reindex from remote) for that request.

### APIs to update

- [x] Autoscaling APIs
- [x] cat APIs #67467
- [x] Cluster APIs #67589
- [x] Cross-cluster replication APIs
- [x] Data stream APIs #67612
- [x] Document APIs #67843
- [x] Enrich APIs
- [x] Find structure API
- [x] Index APIs #68071
- [x] Index lifecycle management API
- [x] Ingest APIs #67845
- [x] Info API #67939
- [x] Licensing APIs
- [x] Machine learning anomaly detection APIs
- [x] Machine learning data frame analytics APIs
- [x] Migration APIs #67939
- [x] Reload search analyzers #67939
- [x] Repositories metering APIs #67944
- [x] Rollup APIs
- [ ] Search APIs #68009
- [x] EQL search APIs #68017
- [x] Searchable snapshots APIs
- [x] Security APIs
- [x] Snapshot and restore APIs #67955
- [x] Snapshot lifecycle management API
- [x] Transform APIs
- [x] Usage API #67939
- [x] Watcher APIs

**Comment by jrodewig** [comment]
Thanks for raising this @pickypg. I've added a list of APIs we need to audit to this description. I'll work on progressively working through those.
