### ISSUE TITLE
Block direct system index access

### ISSUE THREAD

**Issue by jaymode** [elastic/elasticsearch#67384]
This issue covers the work needed to fully enable blocking direct internal system index access via the REST API. This work depends on at least the following:

- [ ] System index deletion API https://github.com/elastic/elasticsearch/issues/62778
- [ ] Tests stop directly accessing system indices https://github.com/elastic/elasticsearch/issues/62501
- [ ] External system indices https://github.com/elastic/elasticsearch/issues/67383

**Comment by EricDavisX** [comment]
Would we also update any API Docs that relate to indices or perhaps a generic note in the docs for apis that hit indices?  I ran into internal team docs that noted to a /flush (with no index specified) and when it didn't work i checked the formal docs and didn't see anything calling out that it shouldn't work.  might be nice to help call it out as a task in the check-list to update docs.

this is the issue I logged thinking it was Kibana side:  https://github.com/elastic/kibana/issues/101294
