### ISSUE TITLE
System index upgrade mechanism

### ISSUE THREAD

**Issue by jaymode** [elastic/elasticsearch#67385]
This issue covers the building of an upgrade mechanism for system indices that will be utilized prior to a major version upgrade. This mechanism needs to be able to handle reindexing in the case of an index that would be too old to read any longer and also perform any necessary data transformation for system indices. Within a system index plugin, a definition would be provided to upgrade these indices.

More details will be added here after further investigation and design work is done.

Task list:

- [x]  [Create API Stubs and unit tests for both endpoints](https://github.com/elastic/elasticsearch/issues/77522)
- [x] [REST API for GET system feature upgrade method](https://github.com/elastic/elasticsearch/issues/77524)
- [x] [Evaluate and prototype persistent task framework](https://github.com/elastic/elasticsearch/issues/77525)

**Comment by rdnm** [comment]
This work is now complete, so closing this issue.
