### ISSUE TITLE
SQL: add multivalue field support (arrays)

### ISSUE THREAD

**Issue by bpintea** [elastic/elasticsearch#68066]
This is a meta issue for tracking multivalue support in SQL (arrays). The work should cover the following fields:
* [x] core support, extraction: #67883
* [x] CSV, TSV, TXT support: #68606
* [x] clients support (xDBC, CLI), BWC, QA tests: #68966
* [x] adapt to [new fields-API](https://github.com/elastic/elasticsearch/pull/68467): #68831
* [ ] multivalue filtering
* [ ] documentation

**Comment by luoyuctl** [comment]
Is this feature will be support in version 8.0.0?

**Comment by FreCap** [comment]
I second @luoyuctl that this is a really important feature, also for people evaluating other sql solutions.

E.g. opendistro-sql supports this pretty well
https://github.com/opendistro-for-elasticsearch/sql

It'd be great seeing this SQL plugin have a nice support for nested docs visualization

**Comment by wchaparro** [comment]
Superceded by ES|QL
