### ISSUE TITLE
Replace group settings with affix settings

### ISSUE THREAD

**Issue by williamrandolph** [elastic/elasticsearch#68143]
The core-infra team would like to remove group settings from our code, but there are remaining places where group settings must be replaced with affix settings first. It's possible that in some cases group settings are providing functionality that's not available with affix settings; if so, we ought to know about it so that we can try to provide that functionality with affix settings.

Replacing group settings with affix settings often requires additional definition of the settings in question, so the actual work of the conversion should be handled by the team that owns the setting, with core/infra providing help and advice if needed.

### Usages of GroupSettings in main code

- [ ] AwarenessAllocationDecider (`cluster.routing.allocation.awareness.force.\*`)
- [ ] HttpExporter (covered by #53081)
    * `xpack.monitoring.exporters.\*.headers` - uses a group settings validator *within* affix settings
    * `xpack.monitoring.exporters.\*.ssl`
- [ ] HunspellService (`indices.analysis.hunspell.dictionary.\*`)
- [ ] IndexScopedSettings
    * `index.analysis.\*`
    * `index.similarity.\*` - uses validator to validates that you can't redefine the builtins
- [ ] JvmGcMonitorService (`monitor.jvm.gc.collector.\*`)
- [ ] Licensing (`license.\*`)
- [ ] ThreadContext (`request.headers.\*`)
- [ ] TransportSettings (`transport.features.\*`)
- [ ] XPackClientPlugin (`license.\*`)

#### Notification services

These classes all use the same pattern, where group settings are nested within an affix setting definition

- [ ] EmailService (`xpack.notification.email.account.\*.email\_defaults`)
- [ ] JiraService (`xpack.notification.jira.account.\*.issue\_defaults`)
- [ ] PagerDutyService (`xpack.notification.pagerduty.account.\*.event\_defaults`)
- [ ] SlackService (`xpack.notification.slack.account.\*.message\_defaults`)

## Tests of groupSettings

These are tests of setting functionality and shouldn't be removed unless all usages of GroupSettings are removed.

- [ ] SettingsFilteringIT (`index.filter\_test.\*`)
    * Add use of prefix settings so that we can remove GroupSettings when it's time
- [ ] ScopedSettingsTests
- [ ] SettingTests
