### ISSUE TITLE
[Meta] GeoIPv2

### ISSUE THREAD

**Issue by probakowski** [elastic/elasticsearch#68920]
This is meta issue to track progress of GeoIPv2 work. There are currently these identified items we need to complete for GA:

- [x] downloader that uses GeoIP Database Service provided by Infra to download new versions - @probakowski (#68424)
- [x] verify downloaded databases with hash - @probakowski (#68424)
- [x] fix license checks @probakowski (#69862)
- [x] rework GeoIP cache - @martijnvg (#68581)
- [x] allow updating custom GeoIP databases at runtime - @martijnvg (#68901)
- [x] integrate downloader and ingest node so new databases can be used @martijnvg (#69540)
- [x] handle `.tgz` files from infra endpoint @probakowski (https://github.com/elastic/elasticsearch/pull/70725)
- [x] tool for preparing endpoint for air-gapped environments @probakowski (https://github.com/elastic/elasticsearch/pull/71018)
- [x] stats API @probakowski (https://github.com/elastic/elasticsearch/pull/70282)
- [x] add ToS parameter to call to GeoIP Database Service - @probakowski (#69495)
- [x] add qa module for air-gapped env @probakowski (https://github.com/elastic/elasticsearch/pull/71381)
- [x] documentation - @probakowski (https://github.com/elastic/elasticsearch/pull/71211)
- [x] setup 3rd party test on CI - @probakowski
- [x] flip feature flag to enable downloader by default - @probakowski (https://github.com/elastic/elasticsearch/pull/71505)
- [ ] remove built-in databases (in 8.0)

**Comment by joegallo** [comment]
@probakowski should this be relabeled to `v7.14.0`?

**Comment by probakowski** [comment]
it should, I've updated it

**Comment by probakowski** [comment]
As all work for 7.x is done and there's just 1 task left, I'll close this issue as done
