### ISSUE TITLE
Update plugin documentation

### ISSUE THREAD

**Issue by jakelandis** [elastic/elasticsearch#69300]
I was browsing https://www.elastic.co/guide/en/elasticsearch/plugins/current/intro.html and noticed some out of date information. 

- [x] x-pack is no longer a plugin that can be installed individually (since 6.3), and we should probably remove references to x-pack  #69304
- [x] geo-ip and user agent are no longer a plugins (it is installed by default) https://www.elastic.co/guide/en/elasticsearch/plugins/current/ingest.html (called out in the link, but probably no need to show in list) #69304
- [ ] should validate that the community plugins listed are are actively maintained and of reasonably recent version
- [ ] should validate that the integrations listed are are actively maintained and advertise working with a reasonably recent version
- [ ] Try to find any useful/popular plugins/integrations/tooling not listed here and get them added (for example https://github.com/spinscale/cookiecutter-elasticsearch-ingest-processor by @spinscale)
