### ISSUE TITLE
More super randomized tests

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#70929]
In #70278 I implemented a bunch of randomized tests for the `fields` API. In particular, all extensions of `MapperTestCase` must override `generateRandomInputValue` to generate a random input value to test. Once they do that they get `fields` tests for free. Here are some follow ups:

* [ ] Finish implementing `generateRandomInputValue`
  * [ ] `rank_feature`
  * [ ] `rank_features`
  * [ ] `murmur3`
  * [ ] `binary` (@mayya-sharipova #70826)
  * [ ] `geo_point`
  * [ ] `geo_shape`
  * [ ] `geo_shape` with doc values
  * [ ] `flattened`
  * [ ] `histogram`
  * [ ] `aggregate_metric_double`
  * [ ] `point`
  * [ ] `shape`
  * [ ] `dense_vector`
* [ ] Come up with a way to assert *something* for fields that don't have useful doc values
  * [ ] `text`
  * [ ] `annotated_text`
  * [ ] `completion`
  * [ ] `search_as_you_type`
  * [ ] `range` (See #70269)
  * [ ] `icu_collation_keyword` 
* [ ] Fix round trip test for `half_float_point`. We fixed the fetcher already but the test still assumes a still busted fetcher. (@nik9000 )
* [ ] Fix rounding for longs sent as floating point numbers in the json (#70585)
* [ ] `AbstractNumericFieldMapperTestCase#randomFetchTestFieldConfig` should return the type from its subclasses instead of a random type.

**Comment by javanna** [comment]
We did not get to this in a while and we don't foresee to be able to prioritize working on it further. Closing.
