### ISSUE TITLE
Implement APIs to provide fleet server access to new index documents

### ISSUE THREAD

**Issue by tbrooks8** [elastic/elasticsearch#71449]
**Phase 1 -** 

Implement global checkpoints API.

- [x] Introduce API to poll for global checkpoint advancements (#71093)
- [x] Allow the polling to wait on index creation if necessary (within timeout)
- [x] Implement appropriate documentation
- [ ] Separate basic validation logic tests into single node test cases (currently they are unnecessarily cluster test cases)

**Phase 2 -** 

Add functionality to remove the need for manual refreshes.

- [x] Add infrastructure for "wait on refresh" for searches (#73134)
- [x] Add specialized fleet search apis which forward the wait on refresh sequence numbers to search (#73134)
- [ ] Optimize can_match to work cleanly with `wait_for_refresh`

**Comment by tbrooks8** [comment]
Have spun phase 3 out into different issue (https://github.com/elastic/elasticsearch/issues/81178). Remaining meta tasks were not necessary for functionality.
