### ISSUE TITLE
Meta issue - new auto complete API

### ISSUE THREAD

**Issue by markharwood** [elastic/elasticsearch#71550]
This issue tracks various changes required to introduce a new fast API for offering autocomplete directly from index contents.

- [x] Introduce new Queryable _tier field (for filtering out indices in frozen/cold tiers) https://github.com/elastic/elasticsearch/issues/68135
- [x] New api for retrieving terms from index https://github.com/elastic/elasticsearch/pull/66452
- [ ] Improved error reporting e.g. when one index of several queried has different, unsupported field type.
- [x] Add rally benchmarks for term suggestion (add to existing Rally benchmarks on "http logs" dataset) https://github.com/elastic/rally-tracks/issues/178
- [x] Add cross-cluster support to terms retrieval API https://github.com/elastic/elasticsearch/pull/73478
- [x] Optimize terms retrieval impl so that queries defined in DLS security rules are run during canMatch to see if they rewrite to match all (common rule in datastreams is to have a query that denies/allows access to a whole index).UPDATE: this is now  in PR https://github.com/elastic/elasticsearch/issues/68135
- [ ] Support IP address fields
- [x] Add support for `search_after` a string to enable pagination https://github.com/elastic/elasticsearch/issues/72910
- [ ] Add support for shard-level caching

**Comment by javanna** [comment]
The new _terms_enum API has been integrated in Kibana, and the remaining improvements listed in this issue don't see high priority at the moment. Closing for now as we are not planning on working on these anytime soon. Feel free to leave comments if you disagree.
