### ISSUE TITLE
[DOCS] Update docs for data stream aliases

### ISSUE THREAD

**Issue by jrodewig** [elastic/elasticsearch#73044]
#72613 added data stream support to aliases, formerly known as index aliases. This tracks related work in the alias docs:

- [x] Update `index alias` glossary entry. #73065, https://github.com/elastic/stack-docs/pull/1664, #73169, https://github.com/elastic/stack-docs/pull/1666
- [x] Create an `alias` guide, pulling information from the existing index alias API reference. #73062
- [x] Update alias xrefs. #73380
- [x] Update alias API docs. #73419
- [x] Update `aliases` object in other API docs. #73421
- [x] Update security docs. #73436
- [x] Update snapshot/restore docs. #73438
- [x] Audit `alias` references. #73427
