### ISSUE TITLE
Upgrade to lucene 9

### ISSUE THREAD

**Issue by romseygeek** [elastic/elasticsearch#74057]
We will want to use Apache Lucene 9 once it has been released in the elasticsearch 8.x line.  This meta issue tracks updates that we need to make to our master branch in order to integrate this new release.

Snapshot upgrade PR: #73324

The following issues need to be addressed prior to merging the upgrade to Lucene 9, some of which may require deprecations in 7x:
- [x] CuckooFilter uses the `PackedInts.Mutable` class which is no longer available in lucene 9 (@iverase) #74736
- [x] SimpleFSDirectory is no longer available, so should be deprecated in 7.x (@dnhatn) #75156
- [x] SegmentStats reports RAM accounting information which is no longer available (@jpountz) #75274
- [x] Analyzer.version has been removed (@romseygeek) #74073
- [x] SpanBoostQuery has been removed (@romseygeek) #74432
- [x] Migration of `indices.query.bool.max_clause_count` wich is now for the entire query tree rather than per BooleanQuery. #75297

The following issues will need to be addressed after upgrading to Lucene 9:
 - [ ] Add support for vectors to the disk usage API. (8.x @jtibshirani)
 - [x] Add support for vectors to the field usage API. (8.x @ywelsch) #80608
 - [x] Remove verbose option from index segments stats https://github.com/elastic/elasticsearch/issues/75955 (@romseygeek)
 - [x] KeystoreWrapper should avoid using endianness utils for writing https://github.com/elastic/elasticsearch/pull/78304
 - [x] MetadataStateFormat should avoid using endianness utils for writing https://github.com/elastic/elasticsearch/pull/78309
 - [x] Deprecate and remove `max_merge_at_once_explicit` (https://github.com/elastic/elasticsearch/pull/80574) (8.0 @dnhatn)
 - [ ] Expose norwegiannormalization, swedishminimalstem, swedishminimalstem, telugustem, ~~japanese_completion~~ (8.x @romseygeek)
 - [ ] Sort optimizations: see TODO: IndexNumericFieldData  and  NumberFieldTypeTests#testIndexSortIntRange (8.x @mayya-sharipova)
 - [x] Review permission in server/src/main/resources/org/elasticsearch/bootstrap/security.policy https://github.com/elastic/elasticsearch/pull/78431
 - [x] https://github.com/elastic/elasticsearch/issues/46433 (8.0 @romseygeek)

**Comment by wchaparro** [comment]
@romseygeek this issue came up in our backlog review, any thing remaining on this one? I thought we already upgraded to Lucene 9?

**Comment by romseygeek** [comment]
There are a couple of things still to do, but they're follow-ups rather than blockers. I will open separate issues for those and then close this.

**Comment by romseygeek** [comment]
* Int and Float field types should use their corresponding Sort types #84799
* Expose new language analysis components in Elasticsearch #84800
* Add support for vectors to the disk usage API #84801
