### ISSUE TITLE
[DOCS] Document `null`/edge case handling for SQL functions

### ISSUE THREAD

**Issue by jrodewig** [elastic/elasticsearch#74193]
We don't consistently document how our [SQL functions](https://www.elastic.co/guide/en/elasticsearch/reference/current/sql-functions.html) handle `null` values and other edge cases (such as negative integers in string function args). We should update the docs for each function so users know what to expect.

Due to the number of functions, we'll likely need to break this up over several PRs. We should prioritize string functions so we can document the changes in https://github.com/elastic/elasticsearch/pull/68379

- [ ] Aggregate functions #74444
- [ ] Grouping functions #74444
- [ ] Date/Time and Interval Functions #74444
- [x] ~Full-Text Search Functions~ (already done)
- [ ] Mathematical Functions #74444
- [x] String Functions #74201, #74255
- [ ] Type Conversion Functions #74444
- [ ] Geo Functions #74444
- [x] ~Conditional Functions And Expressions~ (already done)
- [x] ~System Functions~ (already done)

CC @astefan

**Comment by matriv** [comment]
Similar to #68531. We should also check the way we document other edge case for args, to have a consistency across all functions, e.g. should it be marked with `NOTE`, or should it be with bullet points in the description of the args, or the description of the function.

**Comment by jrodewig** [comment]
> We should also check the way we document other edge case for args (e.g. a negative integer for string functions), to have a consistency across all functions, e.g. should it be marked with NOTE, or should it be with bullet points in the description of the args, or the description of the function.

Thanks @matriv. IMO it's more concise to provide this in the description of the arg. You avoid having to restate the arg name. I can work on making this consistent as part of my changes.

**Comment by matriv** [comment]
Yep, It's fine to have it there, I added this extra check for those cases, because back then I remember there were a few inconsistencies as well (apart from the null handling).
