### ISSUE TITLE
Improve Snapshot Repository Scalability

### ISSUE THREAD

**Issue by original-brownbear** [elastic/elasticsearch#74350]
Snapshot repositories do not scale well with large numbers of snapshots and indices in them. With the introduction of the cold and frozen tier compelling use cases for repositories containing tens of thousands of snapshots have emerged. This issue tracks the work required to enable larger snapshot repositories.

- [x] switch back to almost 7.x snapshot listing API responses #74451
- [x] enable efficient writing of large repository metadata blobs #74313
- [x] enable efficient reading of large repository metadata blobs #73149 
- [x] add parameter to filter by SLM policy #77321
- [x] add the ability to set an offset by concrete sort column value #77618
- [x] add exclude pattern support to snapshot and repository name path parts #77308
- [x] implement `next` field for pagination requests #74236
- [x] implement pagination parameters for get snapshots request #73952
- [x] adjust get snapshot-info API to allow for bulk snapshot-info fetches #73570
- [x] add new thread-pool for snapshot metadata and parallelize get-snapshot requests #73172   
- [x] add overall snapshot count to response and a numeric offset parameter to requests to allow for clean pagination in Kibana #76150
- [x] add query parameter to paginate by numeric offset so that Kibana can jump to page `n` efficiently https://github.com/elastic/elasticsearch/pull/76233
- [x] add sorting snapshots by shard count and failed shard count https://github.com/elastic/elasticsearch/pull/77011
- [x] add sorting snapshots by repository name https://github.com/elastic/elasticsearch/pull/77049
- [x] adjust docs that warn about excessive snapshot counts (e.g. [[1](https://www.elastic.co/guide/en/elasticsearch/reference/current/slm-api-put-policy.html)]) https://github.com/elastic/elasticsearch/pull/80745
- [x] adjust snapshot count limit mentioned in SLM UI (at least, open an issue and give guidance to the UI folks on the changes needed) https://github.com/elastic/kibana/pull/118634

**Comment by jrodewig** [comment]
I'm going to close as it looks like all tasks are complete.merged. Please re-open if I missed anything.
