### ISSUE TITLE
Add support for mvt format (GA)

### ISSUE THREAD

**Issue by wchaparro** [elastic/elasticsearch#77352]
Done:
- [x] Meet with Clients team to get help with Python and new REST client

In Progress:
- [ ]
- 

To Do:

- [ ]  provide sample data for clients team

Backlog:
- [ ]  Add support for cross cluster search
- [ ]  Rally tests
- [ ]  support for labels (Kibana)
