### ISSUE TITLE
Fix Large Shard Count Scalability Issues

### ISSUE THREAD

**Issue by original-brownbear** [elastic/elasticsearch#77466]
This meta issue tracks known issues with scaling clusters to large numbers of shards.

- Security
  - [ ] https://github.com/elastic/elasticsearch/issues/67987
     - [x] https://github.com/elastic/elasticsearch/issues/79632

- General
  - [ ] https://github.com/elastic/elasticsearch/issues/51992
  - [ ] https://github.com/elastic/elasticsearch/issues/87555
  - [x] https://github.com/elastic/elasticsearch/pull/77546
  - [ ] https://github.com/elastic/elasticsearch/issues/79563
  - [x] https://github.com/elastic/elasticsearch/pull/79793
  - [x] https://github.com/elastic/elasticsearch/issues/79906
  - [x] https://github.com/elastic/elasticsearch/pull/80064
  - [ ] https://github.com/elastic/elasticsearch/issues/80694
  - [x] https://github.com/elastic/elasticsearch/issues/81626
  - [x] https://github.com/elastic/elasticsearch/issues/81627
  - [x] https://github.com/elastic/elasticsearch/issues/81628
  - [ ] https://github.com/elastic/elasticsearch/issues/81846
  - [x] https://github.com/elastic/elasticsearch/issues/81880
  - [x] https://github.com/elastic/elasticsearch/issues/82337
  - [x] https://github.com/elastic/elasticsearch/issues/82342
  - [x] https://github.com/elastic/elasticsearch/pull/82608
  - [x] https://github.com/elastic/elasticsearch/pull/82227
  - [x] https://github.com/elastic/elasticsearch/pull/82830
  - [ ] https://github.com/elastic/elasticsearch/issues/83049
  - [ ] https://github.com/elastic/elasticsearch/issues/83203
  - [x] https://github.com/elastic/elasticsearch/issues/83204 -> #85380
  - [x] https://github.com/elastic/elasticsearch/issues/85839
  - [x] https://github.com/elastic/elasticsearch/issues/86639
  - [x] https://github.com/elastic/elasticsearch/issues/87681
  - [ ] https://github.com/elastic/elasticsearch/issues/90631
  - [x] https://github.com/elastic/elasticsearch/pull/92902
  - [x] https://github.com/elastic/elasticsearch/issues/97222
  - [x] https://github.com/elastic/elasticsearch/issues/97914
  - [ ] https://github.com/elastic/elasticsearch/issues/101805

- Snapshots + SLM
  - [x] https://github.com/elastic/elasticsearch/pull/80942 
  - [ ] https://github.com/elastic/elasticsearch/issues/82824
  - [x] https://github.com/elastic/elasticsearch/issues/82853
  - [x] https://github.com/elastic/elasticsearch/issues/82937
  - [x] https://github.com/elastic/elasticsearch/pull/88707
  - [x] https://github.com/elastic/elasticsearch/issues/88732
  - [ ] https://github.com/elastic/elasticsearch/issues/89163
  - [x] https://github.com/elastic/elasticsearch/issues/89952
  - [x] https://github.com/elastic/elasticsearch/issues/99953
 
- Metrics
  - [x] https://github.com/elastic/elasticsearch/issues/80428 

- ILM + Allocation
  - [x] https://github.com/elastic/elasticsearch/pull/78547
  - [x] #78235 
  - [x] https://github.com/elastic/elasticsearch/issues/78246
  - [x] #78075 
  - [x] #77965 
  - [x] https://github.com/elastic/elasticsearch/pull/77855
  - [x] https://github.com/elastic/elasticsearch/pull/77863 
  - [x] https://github.com/elastic/elasticsearch/pull/78742
  - [x] https://github.com/elastic/elasticsearch/pull/78668
  - [x] https://github.com/elastic/elasticsearch/pull/78672
  - [x] https://github.com/elastic/elasticsearch/pull/78609
  - [x] https://github.com/elastic/elasticsearch/pull/78745
  - [x] https://github.com/elastic/elasticsearch/pull/78813
  - [ ] https://github.com/elastic/elasticsearch/issues/78892
     - [x] https://github.com/elastic/elasticsearch/pull/80493
  - [x] https://github.com/elastic/elasticsearch/issues/77888
  - [x] https://github.com/elastic/elasticsearch/pull/78931
  - [x] https://github.com/elastic/elasticsearch/pull/78969
  - [x] https://github.com/elastic/elasticsearch/issues/78980
  - [x] https://github.com/elastic/elasticsearch/issues/79782
  - [x] https://github.com/elastic/elasticsearch/issues/79866
  - [x] https://github.com/elastic/elasticsearch/pull/79860
  - [x] https://github.com/elastic/elasticsearch/pull/79941
  -   [x] https://github.com/elastic/elasticsearch/pull/80179
  - [ ] https://github.com/elastic/elasticsearch/issues/80407
  - [x] https://github.com/elastic/elasticsearch/issues/81880
  - [x] https://github.com/elastic/elasticsearch/pull/82251
  - [x] https://github.com/elastic/elasticsearch/issues/82708
  - [x] https://github.com/elastic/elasticsearch/pull/83092
  - [x] https://github.com/elastic/elasticsearch/pull/83241
  - [x] https://github.com/elastic/elasticsearch/pull/83340
  - [x] https://github.com/elastic/elasticsearch/issues/83582
  - [x] https://github.com/elastic/elasticsearch/pull/84034
  - [x] https://github.com/elastic/elasticsearch/issues/89924
  - [ ] https://github.com/elastic/elasticsearch/issues/94933
  - [x] https://github.com/elastic/elasticsearch/issues/100230

- Search 
  - [x] https://github.com/elastic/elasticsearch/issues/74648
  - [x] https://github.com/elastic/elasticsearch/issues/78164
  - [x] https://github.com/elastic/elasticsearch/pull/76405
  - [x] https://github.com/elastic/elasticsearch/pull/77131
  - [x] https://github.com/elastic/elasticsearch/pull/77201
  - [x] https://github.com/elastic/elasticsearch/pull/77251
  - [x] https://github.com/elastic/elasticsearch/issues/78314
  - [x] https://github.com/elastic/elasticsearch/pull/78508
  - [x] https://github.com/elastic/elasticsearch/issues/82879
  - [ ] https://github.com/elastic/elasticsearch/issues/89309
  - [x] https://github.com/elastic/elasticsearch/issues/90622
  - [ ] https://github.com/elastic/elasticsearch/pull/99219
  - [ ] https://github.com/elastic/elasticsearch/issues/99220
  - [ ] https://github.com/elastic/elasticsearch/pull/99222

- Network
  - [x] https://github.com/elastic/elasticsearch/issues/82245
  - [x] https://github.com/elastic/elasticsearch/issues/79560
  - [ ] https://github.com/elastic/elasticsearch/pull/83846
  - [ ] https://github.com/elastic/elasticsearch/issues/84876
  - [ ] https://github.com/elastic/elasticsearch/issues/84887
  - [ ] https://github.com/elastic/elasticsearch/issues/89838
