### ISSUE TITLE
Eliminate split packages

### ISSUE THREAD

**Issue by ChrisHegarty** [elastic/elasticsearch#78166]
To allow for the future modularization of Elasticsearch with Java Modules, there are a number preparatory tasks that need be completed. This is one such task: eliminate split packages.

#### Split packages with Lucene:

  - [ ] plugins/analysis-ukrainian/src/main/java/org/apache/lucene/analysis/uk/XUkrainianMorfologikAnalyzer.java
  - [ ] x-pack/plugin/spatial/src/test/java/org/apache/lucene/geo/XShapeTestUtil.java
  - [x] x-pack/plugin/search-business-rules/src/main/java/org/apache/lucene/search/CappedScorer.java (#78139)
  - [x] x-pack/plugin/search-business-rules/src/main/java/org/apache/lucene/search/CappedScoreQuery.java
  - [x] x-pack/plugin/search-business-rules/src/main/java/org/apache/lucene/search/CappedScoreWeight.java
  - [x] server/src/main/java/org/apache/lucene/index/LazySoftDeletesDirectoryReaderWrapper.java
    - [x] Lucene PR https://github.com/apache/lucene/pull/596
    - [x] ES issue (#81981)
  - [x] ~server/src/main/java/org/apache/lucene/document/BinaryRange.java~ (#78186)
  - [x] ~server/src/main/java/org/apache/lucene/index/OneMergeHelper.java~
    - [x] ~[LUCENE-10118](https://issues.apache.org/jira/browse/LUCENE-10118)~
    - [x] ~ES leverage LUCENE-10118~
  - [x] ~server/src/main/java/org/apache/lucene/search/grouping/CollapsingTopDocsCollector.java~ (#79224)
  - [x] ~server/src/main/java/org/apache/lucene/search/grouping/CollapsingDocValuesSource.java~ (#79224)
  - [x] ~server/src/main/java/org/apache/lucene/search/uhighlight/BoundedBreakIteratorScanner.java~ (#78099)
  - [x] ~server/src/main/java/org/apache/lucene/search/uhighlight/Snippet.java~
  - [x] ~server/src/main/java/org/apache/lucene/search/uhighlight/CustomPassageFormatter.java~
  - [x] ~server/src/main/java/org/apache/lucene/search/uhighlight/CustomUnifiedHighlighter.java~
  - [x] ~server/src/main/java/org/apache/lucene/search/uhighlight/CustomFieldHighlighter.java~
  - [x] ~server/src/main/java/org/apache/lucene/search/grouping/CollapseTopFieldDocs.java~ (#79224)
  - [x] ~server/src/main/java/org/apache/lucene/search/vectorhighlight/CustomFieldQuery.java~ (#81041)
  - [x] ~server/src/main/java/org/apache/lucene/index/ShuffleForcedMergePolicy.java~
    - [x] ~[LUCENE-10132](https://issues.apache.org/jira/browse/LUCENE-10132)~
    - [x] ~ES leverage LUCENE-10132~
  - [x] ~server/src/main/java/org/apache/lucene/util/CombinedBitSet.java~ (#78189 )
  - [x] ~server/src/main/java/org/apache/lucene/queries/SpanMatchNoDocsQuery.java~ (#81043)
  - [x] ~server/src/main/java/org/apache/lucene/queries/BinaryDocValuesRangeQuery.java~ (#81043)
  - [x] ~server/src/main/java/org/apache/lucene/queries/BlendedTermQuery.java~ (#81043)
  - [x] ~server/src/main/java/org/apache/lucene/queryparser/classic/XQueryParser.java~
    - [x] ~Preparatory change committed in [LUCENE-10115](https://issues.apache.org/jira/browse/LUCENE-10115)~
    - [x] ~ES leverage LUCENE-10115 (#78307)~
  - [x] ~server/src/main/java/org/apache/lucene/analysis/miscellaneous/DisableGraphAttribute.java~ (#78205)
  - [x] ~server/src/main/java/org/apache/lucene/analysis/miscellaneous/DuplicateByteSequenceSpotter.java~
  - [x] ~server/src/main/java/org/apache/lucene/analysis/miscellaneous/DuplicateSequenceAttributeImpl.java~
  - [x] ~server/src/main/java/org/apache/lucene/analysis/miscellaneous/DeDuplicatingTokenFilter.java~
  - [x] ~server/src/main/java/org/apache/lucene/analysis/miscellaneous/DuplicateSequenceAttribute.java~
  - [x] ~server/src/main/java/org/apache/lucene/analysis/miscellaneous/DisableGraphAttributeImpl.java~
  - [x] ~server/src/main/java/org/apache/lucene/search/XCombinedFieldQuery.java~ (#77978)
  - [x] ~server/src/main/java/org/apache/lucene/search/XMultiNormsLeafSimScorer.java~
  

#### Split packages within ES itself:

 - [x] ~Fix split package in reindex module~ (#78141)
 - [x] ~Fix split package in search business rules module~ (#78139)
 - [x] ~Move ccr info/usage actions into ccr module~ (#78137)
 - [x] ~Fix split packages in external test modules~ (#78136)
 - [x] ~Fix split package in annotated text plugin~ (#78133)
 - [x] ~Fix split package in netty4 module~ (#78132)
 - [x] ~Fix split package in mapper-extras module~ (#78131)
 - [x] ~Fix split package in aggs-matrix-stats module~ (#78130)
 - [x] ~Fix split package in keystore-cli~ (#78047)
 - [x] ~Fix split packages in analysis-ukranian plugin~ (#78046)
 - [x] ~Fix split package in analysis-smartcn plugin~ (#78045)
 - [x] ~Fix split package in analysis-phonetic plugin~ (#78044)
 - [x] ~Fix split package in analysis-nori plugin~ (#78040)
 - [x] ~Fix split package in analysis-kuromoji plugin~ (#78039)
 - [x] ~Fix split package in analysis-icu plugin~ (#78037)
 - [x] ~Fix split packages in plugin cli~  (#78027)
 - [x] ~Fix split package org.elasticsearch.common.xcontent~ (#78831) 
 - [x] ~Fix split package org.elasticsearch.client~ (#81984)
 - [ ] ...

**Comment by DevWantJustHaveFun** [comment]
Hello, it's look like the changes in 
https://github.com/elastic/elasticsearch/pull/78831

are braking backwards compatibility (in a minor version update)
please see https://github.com/jobrunr/jobrunr/issues/291
