### ISSUE TITLE
Fields API Meta Issue

### ISSUE THREAD

**Issue by stu-elastic** [elastic/elasticsearch#78920]
Fields API:
* [X] Support `unsigned long` 
1. https://github.com/elastic/elasticsearch/issues/64361
2. https://github.com/elastic/elasticsearch/pull/78950
* [x] Support all basic types 
1. https://github.com/elastic/elasticsearch/issues/79105
2. https://github.com/elastic/elasticsearch/issues/79165
3. Documentation
* [ ] Ingest API
 * https://github.com/elastic/elasticsearch/issues/79155
* [ ] Source fallback
 * https://github.com/elastic/elasticsearch/issues/79157
* [ ] Document skipping
 * https://github.com/elastic/elasticsearch/issues/79164
* [ ] Document new way of accessing documents
 * https://github.com/elastic/elasticsearch/pull/83388

Related: https://github.com/elastic/elasticsearch/issues/61388

**Comment by jdconrad** [comment]
Closing this as it's unlikely to be prioritized.
