### ISSUE TITLE
[DOCS] Documentation for security ON by default [beta+]

### ISSUE THREAD

**Issue by lockewritesdocs** [elastic/elasticsearch#80170]
Security ON by default impacts the way we enable and configure security for the Stack. This meta issue tracks updating the documentation for both Elasticsearch and Kibana.

**Note**: these updates are for the beta documentation. Additional changes might be required before GA.

### Elasticsearch

- [x] [Starting Elasticsearch with security enabled](https://www.elastic.co/guide/en/elasticsearch/reference/8.0/configuring-stack-security.html) - #79641
- [x] [Manually configuring security](https://www.elastic.co/guide/en/elasticsearch/reference/8.0/manually-configure-security.html) - #80285
- [x] Connect clients to Elasticsearch - #81279
- [x] [Elasticsearch quick start](https://www.elastic.co/guide/en/elasticsearch/reference/8.0/getting-started.html) - https://github.com/elastic/elasticsearch/pull/80735
- [x] [Installing Elasticsearch](https://www.elastic.co/guide/en/elasticsearch/reference/8.0/install-elasticsearch.html)
   - [x] From archive on Linux or MacOS - #80375
   - [x] With .zip on Windows - #80552
   - [x] With Debian package - #80195
   - [x] With RPM - #80195
   - [x] With Docker - #80113
   - [x] ~On macOS with Homebrew~ (@mgreau indicated that Homebrew installation will not be supported for 8.0 beta. There is discussion of removing support for GA)
   - [x] With Docker Compose - #81786 (relies on elastic/stack-docs#1906)
   - [x] Enroll additional nodes in a single-node configuration - #81787
   - [x] With Windows MSI (MSI support is being dropped altogether - https://github.com/elastic/dev/issues/1850)
- [x] [Security settings](https://www.elastic.co/guide/en/elasticsearch/reference/8.0/security-settings.html) - #82692

### Kibana

- [x] [Configure security in Kibana](https://www.elastic.co/guide/en/kibana/8.0/using-kibana-with-security.html) 
  - [x] elastic/kibana#117223
  - [x] elastic/kibana#118088
- [x] [Install Kibana](https://www.elastic.co/guide/en/kibana/8.0/install.html)
  - [x] From archive on Linux or MacOS - elastic/kibana#118770
  - [x] With .zip on Windows - elastic/kibana#118770
  - [x] With Debian package - elastic/kibana#118770
  - [x] With RPM - elastic/kibana#118770
  - [x] With Docker - elastic/kibana#118809
- [x] [Kibana quick start](https://www.elastic.co/guide/en/kibana/8.0/get-started.html) - https://github.com/elastic/kibana/pull/118620
- [x] Kibana verification code tool - https://github.com/elastic/kibana/pull/120836

### Stack

- [x] [Getting started with the Elastic Stack](https://www.elastic.co/guide/en/elastic-stack-get-started/8.0/get-started-elastic-stack.html) - elastic/stack-docs#1883
- [x] [Running the Elastic Stack on Docker](https://www.elastic.co/guide/en/elastic-stack-get-started/8.0/get-started-docker.html)
  - [x] Add section for running Elasticsearch and Kibana securely without Docker Compose - elastic/stack-docs#1888
  - [x] Enhance the current documentation for running a multi-node cluster with Docker Compose - elastic/stack-docs#1906
  - [x] Enroll additional nodes in a single-node configuration - https://github.com/elastic/stack-docs/pull/1922

**Comment by jkakavas** [comment]
We also need to update all of the subpages in https://www.elastic.co/guide/en/elasticsearch/reference/master/install-elasticsearch.html

**Comment by lockewritesdocs** [comment]
This work is now complete, so I'm going to close this meta issue and use separate PRs for any related changes.
