### ISSUE TITLE
Java 17 features in Elasticsearch code base

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#81820]
This is a meta issue for tracking Java 17 features implementation in Elasticsearch. The work is composed of the following tasks:
* [ ] Pattern matching for `instanceof`. Tasks are divided between folders under https://github.com/elastic/elasticsearch. The split also takes into consideration that some of the above mentioned folders do not contain any `instanceof` occurrences that can be transitioned to pattern matching. 
  * [ ]  `x-pack/plugin/analytics` through `x-pack/plugin/enrich` #https://github.com/elastic/elasticsearch/pull/81812
  * [ ] `x-pack/plugin/eql` through `x-pack/plugin/searchable-snapshots`
  * [ ] `x-pack/plugin/security` through `x-pack/plugin/wildcard`
  * [ ] `build-conventions` through `modules`
  * [ ] `plugins` through `qa`, `server/internalClusterTest`
  * [ ] `server/main`
  * [ ] `server/test`
  * [ ] `test`, `x-pack/qa`
* [ ] Improved switch expressions
* [ ] Pattern matching for switch
* [ ] Sealed classes
* [ ] Records
