### ISSUE TITLE
[ML] Improve reporting of memory requirements for trained models

### ISSUE THREAD

**Issue by dimitris-athanasiou** [elastic/elasticsearch#81854]
### Background

There are two broad types of models currently: java models (most likely trained from DFA jobs) and pytorch models.
Calling the GET api for java models returns the respective `model_size_bytes`. That is the amount of memory required
to load those models into the JVM. Pytorch models, on the other hand, will have a `0` values for that field as things stand for 8.0. Note that pytorch models are not loaded in JVM memory but require native machine memory instead.
Pytorch model definition docs, contain a field called `total_definition_length` which informs us of the total number of bytes that the model zip file representation requires. Once a pytorch model is deployed, calling the _stats API returns a field called `deployment_stats.model_size_bytes` which currently is the `total_definition_length`.

### Problems

For pytorch models, the `total_definition_length` is not how much memory the model requires in memory. In particular, the memory required for the model for its in-memory representation is currently unknown. When a model is allocated, we use the `total_definition_length` as a proxy for its in-memory size requirements. In addition, we double that as during startup the process holds in memory both the model definition (which requires `total_definition_length` bytes in memory) and the loaded model (which requires unknown but we currently use `total_definition_length`). 

Moreover, when a pytorch model is not deployed, there is no way to find out how much memory is required.

### Solutions

- [ ] For 8.0, change `deployment_stats.model_size_bytes` for pytorch models to be the same as what we require in the allocation logic. This will at least not lead to problems where there appears to be enough memory for a model to be deployed yet deployment fails due to not enough memory.
- [ ] For 8.1, require that when the PUT model api is called, the `model_size_bytes` are set and reflect how much memory the model requires in its in-memory representation.
- [ ] For 8.1, change eland script for importing pytorch models to populate that field with a good value.
- [ ] For 8.1, change the _stats API to return a new top-level field (outside of `deployment_stats`) with the required native memory for a model. That should be the `model_size_bytes` plus the `total_definition_length`.
- [ ] For 8.1, notify UI team to use that new value for pytorch models.

**Comment by dimitris-athanasiou** [comment]
This has been addressed in a different way by #82000
