### ISSUE TITLE
Add Elasticsearch Health API

### ISSUE THREAD

**Issue by tbrooks8** [elastic/elasticsearch#83303]
### Description

We intend to implement a new health reporting API which will return actionable health information about a Elasticsearch cluster. At a high level we intend the API to split Elasticsearch health into 8-10 components (coordination, backups, data, etc) with lower level indicators describing the current health of the components. Each indicator will have a health status (green/yellow/red). Each health indicator will be documented with actionable steps to fix indicators that are in a bad state.

Phase 1

We have identified the following 3 components will be introduced in the first phase.

- Controller/Coordination
- Data/Indices
- Backup/Snapshots

If possible, we will limit the first phase to extracting information from the cluster state. But future phases will require some type of coordination to ensure non-cluster state health data is in a single place to be gathered.

The specific development tasks are still being planned.

- [ ] Add new API endpoint
- [ ] Add high level documentation for API
- [ ] Add param functionality to support return just red, just red/yellow, all red/yellow/green indicators
- [ ] Allow drilling down to a single component or indicator
