### ISSUE TITLE
Remove HLRC from ES codebase

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#83423]
### Description

With the launch of the [new Java client](https://www.elastic.co/guide/en/elasticsearch/client/java-api-client/8.0/introduction.html) the Elasticsearch High Level Rest Client (HLRC) is deprecated, no longer shipped as an artifact, and can be removed from the ES codebase. This meta issue is to track the the removal of the HLRC for 8.x.

Steps (subject to change):
- [x] Remove all HLRC tests #83425
- [x] Remove all usages of HLRC sub-clients by tests, replacing them with the low-level `RestClient`. These classes can be found inside of [`RestHighLevelClient.java`](https://github.com/elastic/elasticsearch/blob/master/client/rest-high-level/src/main/java/org/elasticsearch/client/RestHighLevelClient.java#L278)
  - [x] Remove usages of `IndicesClient` (`indices()`) (@martijnvg, #85492)
  - [x] Remove usages of `ClusterClient` (`cluster()`) (@gmarouli, https://github.com/elastic/elasticsearch/pull/83593) 
  - [x] Remove usages of `IngestClient` (`ingest()`) (@martijnvg, #85483)
  - [x] Remove usages of `SnapshotClient` (`snapshot()`) (@dakrone, https://github.com/elastic/elasticsearch/pull/85845)
  - [x] Remove usages of `TasksClient` (`tasks()`) (@danhermann, https://github.com/elastic/elasticsearch/pull/83649)
  - [x] Remove usages of `XPackClient` (`xpack()`) (@gmarouli, https://github.com/elastic/elasticsearch/pull/83593)
  - [x] Remove usages of `GraphClient` (`graph()`) (@danhermann, https://github.com/elastic/elasticsearch/pull/83471)
  - [x] Remove usages of `IndexLifecycleClient` (`indexLifecycle()`) (@dakrone, #83476)
  - [x] Remove usages of `SearchableSnapshotsClient` (`searchableSnapshots()`) (@dakrone, #85472)
  - [x] Remove usages of `FeaturesClient` (`features()`) (@danhermann, https://github.com/elastic/elasticsearch/pull/83651)
  - [x] Remove usages of `MigrationClient` (`migration()`) (@joegallo, https://github.com/elastic/elasticsearch/pull/83609)
  - [x] Remove usages of `MachineLearningClient` (`machineLearning()`) (#83885, #83912)
  - [x] Remove usages of `SecurityClient` (`security()`)
    - [x] Remove unused methods (@tvernum, #83571)
    - [x] Remove "user" methods (@tvernum #83626, #84011)
    - [x] Remove role & role mapping methods (@tvernum #84206)
    - [x] Remove token & api key methods
    - [x] Remove remaining methods (@tvernum #85983)
  - [x] Remove usages of `TransformClient` (`transform()`) (https://github.com/elastic/elasticsearch/issues/83921)
  - [x] Remove usages of `EqlClient` (`eql()`) (@joegallo, https://github.com/elastic/elasticsearch/pull/85730)
  - [x] Remove unused clients (@danhermann, https://github.com/elastic/elasticsearch/pull/83472)
    - [x] Remove usages of `CcrClient` (`ccr()`)
    - [x] Remove usages of `WatcherClient` (`watcher()`)
    - [x] Remove usages of `EnrichClient` (`enrich()`)
    - [x] Remove usages of `LicenseClient` (`license()`)
    - [x] Remove usages of `TextStructureClient` (`textStructure()`)
    - [x] Remove usages of `AsyncSearchClient` (`asyncSearch()`)
    - [x] Remove usages of `RollupClient` (`rollup()`)
- [x] Remove remaining usages of `RestHighLevelClient`
  - [x] `RestHighLevelClient(RestClientBuilder restClientBuilder) (constructor)`
    - [x] `getLowLevelClient() `
    - [x] `close()`
    - [x] `bulk(BulkRequest bulkRequest, RequestOptions options)`
    - [x] `bulkAsync(BulkRequest bulkRequest, RequestOptions options, ActionListener<BulkResponse> listener) `
    - [x] `reindex(ReindexRequest reindexRequest, RequestOptions options)`
    - [x] `updateByQuery(UpdateByQueryRequest updateByQueryRequest, RequestOptions options)`
    - [x] `deleteByQuery(DeleteByQueryRequest deleteByQueryRequest, RequestOptions options)`
    - [x] `info(RequestOptions options)`
    - [x] `get(GetRequest getRequest, RequestOptions options)`
    - [x] `multiGet(MultiGetRequest multiGetRequest, RequestOptions options)`
    - [x] `mget(MultiGetRequest multiGetRequest, RequestOptions options)`
    - [x] `multiGetAsync(`
    - [x] `mgetAsync(MultiGetRequest multiGetRequest, RequestOptions options, ActionListener<MultiGetResponse> listener) `
    - [x] `exists(GetRequest getRequest, RequestOptions options)`
    - [x] `existsSource(GetRequest getRequest, RequestOptions options)`
    - [x] `existsSourceAsync(GetRequest getRequest, RequestOptions options, ActionListener<Boolean> listener) `
    - [x] `getSource(GetSourceRequest getSourceRequest, RequestOptions options)`
    - [x] `index(IndexRequest indexRequest, RequestOptions options)`
    - [x] `count(CountRequest countRequest, RequestOptions options)`
    - [x] `update(UpdateRequest updateRequest, RequestOptions options)`
    - [x] `delete(DeleteRequest deleteRequest, RequestOptions options)`
    - [x] `search(SearchRequest searchRequest, RequestOptions options)`
    - [x] `searchAsync(SearchRequest searchRequest, RequestOptions options, ActionListener<SearchResponse> listener) `
    - [x] `multiSearch(MultiSearchRequest multiSearchRequest, RequestOptions options)`
    - [x] `msearch(MultiSearchRequest multiSearchRequest, RequestOptions options)`
    - [x] `multiSearchAsync(`
    - [x] `msearchAsync(`
    - [x] `searchScroll(SearchScrollRequest searchScrollRequest, RequestOptions options)`
    - [x] `scroll(SearchScrollRequest searchScrollRequest, RequestOptions options)`
    - [x] `searchScrollAsync(`
    - [x] `scrollAsync(`
    - [x] `explain(ExplainRequest explainRequest, RequestOptions options)`
    - [x] `termvectors(TermVectorsRequest request, RequestOptions options)`
    - [x] `fieldCaps(FieldCapabilitiesRequest fieldCapabilitiesRequest, RequestOptions options)`

As each sub client is removed its creator inside of `RestHighLevelClient` to indicate that portion of the removal is "done".

**Comment by joegallo** [comment]
```
joegallo@galactic:~/Code/elastic/elasticsearch $ git grep 'SuppressWarnings' | grep 'removal' | wc -l
      51
joegallo@galactic:~/Code/elastic/elasticsearch $ git grep 'SuppressWarnings' | grep 'removal' | tail -3
x-pack/qa/runtime-fields/with-security/src/javaRestTest/java/org/elasticsearch/xpack/security/PermissionsIT.java:@SuppressWarnings("removal")
x-pack/qa/security-example-spi-extension/src/javaRestTest/java/org/elasticsearch/example/role/CustomRolesProviderIT.java:@SuppressWarnings("removal")
x-pack/qa/smoke-test-plugins-ssl/src/test/java/org/elasticsearch/smoketest/SmokeTestMonitoringWithSecurityIT.java:@SuppressWarnings("removal")
```

We should audit the remaining `removal` warning suppressions when this is done, I think most (all?) of them are related to classes that used (or used to use) the HLRC, so we can probably drop most/all of them. I know I haven't been looking for that with each individual PR, it's an easy thing to miss.

**Comment by joegallo** [comment]
Only 8 public (well, `public final`) methods remaining on `RestHighLevelClient`, all of which have some actual caller somewhere. And only 12 java files left in the `rest-high-level` directory. 🎉

**Comment by joegallo** [comment]
```
joegallo@galactic:~/Code/elastic/elasticsearch $ git ls-files | grep rest-high-level | grep analytics
client/rest-high-level/src/main/java/org/elasticsearch/client/analytics/ParsedStringStats.java
client/rest-high-level/src/main/java/org/elasticsearch/client/analytics/ParsedTopMetrics.java
client/rest-high-level/src/main/java/org/elasticsearch/client/analytics/StringStatsAggregationBuilder.java
client/rest-high-level/src/main/java/org/elasticsearch/client/analytics/TopMetricsAggregationBuilder.java
joegallo@galactic:~/Code/elastic/elasticsearch $ git grep 'import org.elasticsearch.client.analytics' | grep -v rest-high-level
x-pack/plugin/analytics/src/test/java/org/elasticsearch/xpack/analytics/stringstats/InternalStringStatsTests.java:import org.elasticsearch.client.analytics.ParsedStringStats;
x-pack/plugin/analytics/src/test/java/org/elasticsearch/xpack/analytics/topmetrics/InternalTopMetricsTests.java:import org.elasticsearch.client.analytics.ParsedTopMetrics;
```

I chatted with @nik9000 about these four classes today, specifically around the and he brought up https://github.com/elastic/elasticsearch/issues/26220. Those classes do still (or, well, _may_ still have) value w.r.t. to testing bwc of json responses. Added better testing of that via our normal rest tests is under the banner of https://github.com/elastic/elasticsearch/issues/26220, so at some point I expect that we'll just be able to drop those entirely, as long as we're sure the for-testing-bwc-purposes value of them has already been captured elsewhere.

**Comment by nik9000** [comment]
I think it's worth confirming that we get good coverage of the json response in the yaml tests and then removing our usage of the classes in ES. It's a little bit of surgery, but we are capable of it.

**Comment by joegallo** [comment]
```
joegallo@simulacron:~/Code/elastic/elasticsearch $ git grep 'import org.elasticsearch.client.RestHighLevelClient'
qa/ccs-unavailable-clusters/src/javaRestTest/java/org/elasticsearch/search/CrossClusterSearchUnavailableClusterIT.java:import org.elasticsearch.client.RestHighLevelClient;
qa/multi-cluster-search/src/test/java/org/elasticsearch/search/CCSDuelIT.java:import org.elasticsearch.client.RestHighLevelClient;
joegallo@simulacron:~/Code/elastic/elasticsearch $ git ls-files | grep rest-high-level | grep java
client/rest-high-level/src/main/java/org/elasticsearch/client/RequestConverters.java
client/rest-high-level/src/main/java/org/elasticsearch/client/RestHighLevelClient.java
client/rest-high-level/src/main/java/org/elasticsearch/client/Validatable.java
client/rest-high-level/src/main/java/org/elasticsearch/client/ValidationException.java
client/rest-high-level/src/main/java/org/elasticsearch/client/analytics/ParsedStringStats.java
client/rest-high-level/src/main/java/org/elasticsearch/client/analytics/ParsedTopMetrics.java
client/rest-high-level/src/main/java/org/elasticsearch/client/analytics/StringStatsAggregationBuilder.java
client/rest-high-level/src/main/java/org/elasticsearch/client/analytics/TopMetricsAggregationBuilder.java
client/rest-high-level/src/main/java/org/elasticsearch/client/asyncsearch/AsyncSearchResponse.java
client/rest-high-level/src/main/java/org/elasticsearch/client/core/MainResponse.java
```

Only two more test classes left using `RestHighLevelClient`. 🎉

**Comment by iverase** [comment]
FYI: https://github.com/elastic/elasticsearch/pull/102049

**Comment by iverase** [comment]
FYI: https://github.com/elastic/elasticsearch/pull/102222

**Comment by joegallo** [comment]
#102305 drops `RestHighLevelClient` itself (as well as some supporting classes and files), but the `client/rest-high-level` directory isn't empty, so we're not finished here yet:

```
joegallo@simulacron:~/Code/elastic/elasticsearch $ git ls-files | grep client/rest-high-level
client/rest-high-level/build.gradle
client/rest-high-level/src/main/java/org/elasticsearch/client/analytics/ParsedStringStats.java
client/rest-high-level/src/main/java/org/elasticsearch/client/analytics/ParsedTopMetrics.java
client/rest-high-level/src/main/java/org/elasticsearch/client/analytics/StringStatsAggregationBuilder.java
client/rest-high-level/src/main/java/org/elasticsearch/client/analytics/TopMetricsAggregationBuilder.java
client/rest-high-level/src/main/java/org/elasticsearch/client/asyncsearch/AsyncSearchResponse.java
client/rest-high-level/src/main/resources/forbidden/rest-high-level-signatures.txt
joegallo@simulacron:~/Code/elastic/elasticsearch $ git grep 'import org.elasticsearch.client.analytics'
x-pack/plugin/analytics/src/test/java/org/elasticsearch/xpack/analytics/stringstats/InternalStringStatsTests.java:import org.elasticsearch.client.analytics.ParsedStringStats;
x-pack/plugin/analytics/src/test/java/org/elasticsearch/xpack/analytics/topmetrics/InternalTopMetricsTests.java:import org.elasticsearch.client.analytics.ParsedTopMetrics;
joegallo@simulacron:~/Code/elastic/elasticsearch $ git grep 'import org.elasticsearch.client.asyncsearch'
x-pack/plugin/async-search/qa/security/src/javaRestTest/java/org/elasticsearch/xpack/search/AsyncSearchSecurityIT.java:import org.elasticsearch.client.asyncsearch.AsyncSearchResponse;
```

There are still five classes remaining in `client/rest-high-level` and they are used by three distinct tests. The `AsyncSearchResponse` change looks like relatively low-hanging fruit, and then there's still the conversation from https://github.com/elastic/elasticsearch/issues/83423#issuecomment-1335557294.

**Comment by joegallo** [comment]
```
joegallo@simulacron:~/Code/elastic/elasticsearch $ git ls-files | grep rest-high-level
client/rest-high-level/build.gradle
client/rest-high-level/src/main/java/org/elasticsearch/client/analytics/StringStatsAggregationBuilder.java
client/rest-high-level/src/main/java/org/elasticsearch/client/analytics/TopMetricsAggregationBuilder.java
client/rest-high-level/src/main/java/org/elasticsearch/client/asyncsearch/AsyncSearchResponse.java
client/rest-high-level/src/main/resources/forbidden/rest-high-level-signatures.txt
joegallo@simulacron:~/Code/elastic/elasticsearch $ git grep -E '(org.elasticsearch.client.analytics|org.elasticsearch.client.asyncsearch)' | grep -v package | sed -e "s/:.*//g" | sort | uniq
x-pack/plugin/analytics/src/test/java/org/elasticsearch/xpack/analytics/stringstats/StringStatsAggregationBuilderTests.java
x-pack/plugin/analytics/src/test/java/org/elasticsearch/xpack/analytics/topmetrics/TopMetricsAggregationBuilderTests.java
x-pack/plugin/async-search/qa/security/src/javaRestTest/java/org/elasticsearch/xpack/search/AsyncSearchSecurityIT.java
```

Not much change since [November](https://github.com/elastic/elasticsearch/issues/83423#issuecomment-1814663850), there are three classes remaining in `client/rest-high-level` and three distinct tests that rely on them.

**Comment by iverase** [comment]
FYI: https://github.com/elastic/elasticsearch/pull/105294
