### ISSUE TITLE
Remove usages of LegacyClusterTaskResultActionListener

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#83784]
### Description

In https://github.com/elastic/elasticsearch/pull/83562 we introduced a new API for better batching of master tasks, and also the `LegacyClusterTaskResultActionListener` to adapt old implementations to the new API as a temporary measure. This issue tracks the work to remove this adapter.

- [x] `o.e.cluster.LocalMasterServiceTask` and `o.e.cluster.ClusterStateTaskExecutor#unbatched()` (#83796)
- [x] `o.e.cluster.coordination.NodeRemovalClusterStateTaskExecutor` (#83797)
- [x] `o.e.cluster.coordination.JoinTaskExecutor` (#83803)
- [x] `o.e.cluster.metadata.MetadataIndexStateService` (#83807)
- [x] `o.e.cluster.metadata.MetadataMappingService` (#83811)
- [x] `o.e.cluster.service.MasterServiceTests` (#83840)
- [x] `o.e.cluster.action.shard.ShardStateAction` (#83842)
- [x] `o.e.action.admin.indices.create.AutoCreateAction` (#84170)
- [x] `o.e.action.admin.indices.rollover.TransportRolloverAction` (#84166)
- [x] `o.e.action.admin.cluster.desirednodes.DesiredNodesClusterStateTaskExecutor` (#85984)
- [x] `o.e.snapshots.SnapshotsService` (#86178)
- [x] `o.e.ingest.IngestService` (#86446)
- [x] `o.e.cluster.metadata.MetadataIndexTemplateService` (#86459)
- [x] `o.e.cluster.metadata.MetadataUpdateSettingsService` (#88643)
- [ ] `o.e.xpack.ilm.IndexLifecycleRunner` (#89459)
- [ ] Finally, push `o.e.cluster.ClusterStateTaskListener#clusterStateProcessed()` down to `o.e.cluster.ClusterStateUpdateTask` since it only makes sense for unbatched tasks (#89459)

**Comment by PDTCCLF** [comment]
Hi, @DaveCTurner. It looks like no one is assigned for the last item "to push o.e.cluster.ClusterStateTaskListener#clusterStateProcessed() down to o.e.cluster.ClusterStateUpdateTask". As a first time contributor, I believe I could do it.

**Comment by DaveCTurner** [comment]
Thanks for the offer @PDTCCLF. This item is blocked on other work in the list but when it becomes unblocked it will only take us a few minutes to do so it's not something that will need external help.
