### ISSUE TITLE
[DOCS] Update ingest docs for Kibana's ECS mapper feature

### ISSUE THREAD

**Issue by jrodewig** [elastic/elasticsearch#83813]
https://github.com/elastic/kibana/pull/101216 adds a new ECS mapper feature to the Ingest Pipelines UI. We should update our ingest and ECS documentation for this feature.

Tasks:

- [x] Add a tutorial to the [ECS custom implementation docs](https://www.elastic.co/guide/en/ecs/current/ecs-converting.html) https://github.com/elastic/ecs/pull/1772
- [x] Update the [ES ingest pipeline](https://www.elastic.co/guide/en/elasticsearch/reference/current/ingest.html) and [tutorial](https://www.elastic.co/guide/en/elasticsearch/reference/current/common-log-format-example.html) docs with new screenshots https://github.com/elastic/elasticsearch/pull/83845
- [x] Update the doc links in Kibana https://github.com/elastic/kibana/pull/125456
- [ ] Update ECS Mapper tool repo to indicate it's no longer maintained. https://github.com/elastic/ecs-mapper/pull/21
- [ ] Archive ECS Mapper repo. https://github.com/elastic/ecs-mapper/issues/22
- [ ] Update spreadsheet template to remove references to the ECS Mapper tool. https://github.com/elastic/ecs-mapper/issues/22

CC @kgeller @ebeahan @jamiehynds This is my general game plan for the docs. Feedback welcome!

**Comment by jrodewig** [comment]
@kgeller @ebeahan I'm going to close this issue. However, there are two remaining tasks that aren't strictly docs related:

- Archive ECS Mapper repo
- Update spreadsheet template to remove references to the ECS Mapper tool

I opened https://github.com/elastic/ecs-mapper/issues/22 to track that work and listed you as assignees. Let me know if there's anything I can do to help. Thanks!

**Comment by kgeller** [comment]
Sounds good, and thanks so much!

Those items have been on my own backlog, but not documented anywhere, so this is great.
