### ISSUE TITLE
ANN search improvements

### ISSUE THREAD

**Issue by jtibshirani** [elastic/elasticsearch#84324]
This meta issue tracks our work on ANN search. It is not an exhaustive plan and items might be changed/ added over time.

### Features/ enhancements
- [ ] #81788 @jtibshirani 
- [ ] Support "hybrid retrieval", where ANN results are combined with matches from another query
- [ ] Allow aggregations on ANN results
- [ ] Respect search timeouts and cancellation
- [ ] Support other vector element types
  * https://github.com/elastic/elasticsearch/issues/48322
  * https://github.com/elastic/elasticsearch/issues/72067
- [ ] Investigate support for "maximum inner product search" (dot product similarity with unnormalized vectors)
- [ ] #72068
- [ ] Can we remove need for tuning by automatically choosing good index + search parameters?

### Performance improvements
**Search performance**
  - [x] [Handle hierarchy in HNSW graph](https://issues.apache.org/jira/browse/LUCENE-10054) @mayya-sharipova 
  - [x] [Streamline lookups in case when all docs have a vector](https://issues.apache.org/jira/browse/LUCENE-10408) @mayya-sharipova 
  - [ ] Improve search performance in incremental indexing case (when there are many segments)
  - [ ] [Investigate recall gap between Lucene and hnswlib](https://issues.apache.org/jira/browse/LUCENE-9937)

**Indexing performance**
  - [x] [Speed up HNSW flush + merge by writing vectors to file](https://issues.apache.org/jira/browse/LUCENE-10375) @jtibshirani 
  - [x] [Reuse data structures across HnswGraph invocations](https://issues.apache.org/jira/browse/LUCENE-10391) @jtibshirani
  - [ ] [Reexamine graph diversity checks](https://issues.apache.org/jira/browse/LUCENE-9848)
  - [ ] [Reuse HNSW graphs when merging segments?](https://issues.apache.org/jira/browse/LUCENE-10318)

### Tooling
- [ ] Make sure ANN supports search profiling
- [ ] Ability to measure recall of ANN query by comparing to exact scan

### Tech Debt
- [ ] https://github.com/elastic/rally-tracks/issues/234
- [ ] Add Lucene to ann-benchmarks?
- [ ] [Remove VectorValues#randomAccess](https://issues.apache.org/jira/browse/LUCENE-9583)
- [ ] [Remove VectorValues#binaryValue](https://issues.apache.org/jira/browse/LUCENE-10175)
- [ ] [Revisit design of VectorSimilarityFunction](https://issues.apache.org/jira/browse/LUCENE-10191)
- [ ] Revisit our temporary workaround class PerFieldKnnVectorsFormatFieldMapper?

**Comment by S-Dragon0302** [comment]
@jtibshirani  https://github.com/elastic/elasticsearch/issues/72068, Is there an online time node or version

**Comment by benwtrent** [comment]
> Support sparse vectors of terms with fractional weights (for approaches like SPLADE)

This is possible with the use of `rank_features` mapping and a `term` query with boosting over the features. If performance issues arise here, then we can revisit making a specific mapping.

**Comment by JakeWinter** [comment]
Is there any documentation on applying SPLADE retrieval using rank_features mapping?

**Comment by benwtrent** [comment]
@JakeWinter not yet, We will have something documented soon. But `rank_features` has been around for a while now and it has always worked just fine for this use case. Its just not well advertised. 

```
PUT sparse_index
{
"rank_features_field": {
"feature_0": 1.2,
"feature_14": 0.2,
...
}
}
```
Then search is:

```
POST sparse_index/_search
{
  "query": {
    "bool": {
      "min_should_match": 1
      "should": [
      {"rank_feature": {"field": "rank_features_field.feature_0", "linear": {}, "boost": 0.4}},
      {"rank_feature": {"field": "rank_features_field.feature_12", "linear": {}, "boost": 12.1}},
...
      ]
    }
  }
}
```

`boost` is the feature score output from our sparse model. `linear` does similar scoring to the SPLADE++ paper (dot-product of sparse dimensions).

**Comment by S-Dragon0302** [comment]
Does ann search support scroll? @jtibshirani

**Comment by benwtrent** [comment]
@S-Dragon0302 , could you clarify by what you mean by "scroll"? Do you mean find `k` nearest neighbors, and then on a second call find `[k, 2*k]` neighbors?

Or that you can use scroll over BM25 combined with the results of the k nearest neighbors?

**Comment by S-Dragon0302** [comment]
> @S-Dragon0302，你能解释一下你所说的“滚动”是什么意思吗？你的意思是找到`k`最近的邻居，然后在第二次调用时找到`[k, 2*k]`邻居？
> 
> 或者你可以使用 scroll over BM25 结合 k 个最近邻居的结果？



> @S-Dragon0302 , could you clarify by what you mean by "scroll"? Do you mean find `k` nearest neighbors, and then on a second call find `[k, 2*k]` neighbors?
> 
> Or that you can use scroll over BM25 combined with the results of the k nearest neighbors?

https://www.elastic.co/guide/en/elasticsearch/reference/8.5/scroll-api.html

**Comment by benwtrent** [comment]
@S-Dragon0302 that doesn't really answer my question. What is the behavior you expect from `KNN` results?

Right now, the original global top `k` found can be paginated, and so can the query. You can use: https://www.elastic.co/guide/en/elasticsearch/reference/8.5/paginate-search-results.html#search-after

**Comment by mu4farooqi** [comment]
For anyone planning to use Elasticsearch for Hybrid Search (Sparse and Dense Embeddings), I have written a small tutorial. It covers SPLADE++ as well. 

https://ufarooqi.com/blog/hybrid-search-with-elasticsearch/

**Comment by vatsl23** [comment]
@benwtrent Was going through implementation of thread - "Support for reciprocal rank fusion to combine traditional query and ANN results" which seems to be - https://www.elastic.co/guide/en/elasticsearch/reference/current/rrf.html so i was just wondering if instead of considering rank while fusion can we also/only consider score, do we have such implementation planned or executed ?
