### ISSUE TITLE
Instrument Elasticsearch with APM

### ISSUE THREAD

**Issue by pugnascotia** [elastic/elasticsearch#84369]
**NOTE**: this issue will evolve as we scope out this work.

## Description

"Why is Elasticsearch slow?" is a common question from users. We have tools to investigate certain aspects of this question already, for instance the search slowlog (good if the shard-level searches are slow) and the hot threads API (good if the slowness is an ongoing thing) but there are many gaps too. For instance, how would we discover that a Kibana dashboard triggers unreasonably many searches if each of those searches completes fairly quickly? How would we discover that requests are spending unexpectedly long in queues? How do we see if the slow steps all involve a particular node? What if that node is on a remote cluster? It's hard to take a structured approach to performance questions with the tools we have today.

Distributed tracing is a great way to answer questions of this nature. Elastic has a distributed tracing product, [APM](https://www.elastic.co/apm/), which sits on top of Elasticsearch, but today Elasticsearch itself is opaque to APM: we cannot trace the execution of a request through Elasticsearch. Let's fix that.

This work will build on an existing exploratory project that instrumented a number of "tasks" in Elasticsearch. More types of tasks will be instrumented, as well as requests / responses at the REST level.

## Tasks

   * Technical integration
      * [x] Update the proof-of-concept branch of APM in ES
      * [x] Engage with the APM team to check what is the currently recommended way of integrating a Java application with APM
      * [x] Benchmark the overhead of running with APM disabled, to determine if we can merge safely
      * [x] Ensure that distributed tracing works with other Elastic stack components
      * [x] Add testing that uses the APM agent
      * [x] Make sure using APM agent gives the same results
         * [x] https://github.com/elastic/apm-server/issues/8067
         * [x] https://github.com/elastic/apm-agent-java/pull/2657
      * Code changes
         * [x] #87917
         * [x] #87921 
         * [x] #88443
         * [ ] Add docs for tracing ⚠️ Need to check whether we want to document APM at this time ⚠️ 
         * [ ] Developer education / awareness
         * [x] Raise Cloud issue for wiring up APM
   * Documentation
      * [x] Document how to extend tracing in Elasticsearch e.g. coding conventions, what attributes to apply, how to model spans.
   * Span / transaction modelling
      * [x] Check whether the way we are capturing spans in Elasticsearch works with what Kibana etc are doing. The end-to-end picture needs be coherent.
   * Configuration:
      * [x] Provide richer options for filtering captured spans
      * [ ] ~Make sampling rate configurable~ - handled by APM agent
      * [ ] ~More flexible configuration of connection to APM server (TLS features, proxy support, protocol selection etc)~ - handled by APM agent
      * [x] Ensure configuration can be dynamically changed, whether the options sits in ES or on the APM agent.
      * [x] Ensure potentially sensitive fields are filtered out (depends on elastic/apm-server#8067)

## Out-of-scope

The focus of this work is making is instrumenting Elasticsearch for Elastic's own purposes. Making it available to users and licensing it for that purpose is not currently in scope.

**Comment by pugnascotia** [comment]
> Do you have a rough estimate what would be the initial release version of this?

@lizozom  It should be in 8.5.0.

**Comment by pugnascotia** [comment]
I think we've done everything that we intended to be covered by this issue 🎉

**Comment by nicholas-r-king** [comment]
@pugnascotia is this ever going to be released publicly or will customers ever be able to take advantage of tracing/APM metrics for monitoring our Elasticsearch clusters?

**Comment by pugnascotia** [comment]
It depends what you mean by "publicly" - on-prem customers could use this today. Cloud customers cannot, since APM data collection is not multi-tenant. If a Cloud customer has an issue that required APM data to resolve, they'd have to engage with Support. This would likely be necessary in any case since the APM data is a very low-level tool for investigating Elasticsearch issues.

**Comment by nicholas-r-king** [comment]
We are an enterprise customer with several on-prem installations (aws/govcloud) and have a use for this.

**Comment by pugnascotia** [comment]
In that case you can definitely configure APM yourselves. We don't have user-facing documentation yet, but you can consult [TRACING.md](https://github.com/elastic/elasticsearch/blob/main/TRACING.md) for how to get started.

**Comment by ramdaspotale** [comment]
Hi @pugnascotia is there similar feature available for kibana?

**Comment by philippkahr** [comment]
@ramdaspotale , yes you have `traces@custom` as an ingest pipeline and there you can do whatever you want to the data, same for metrics, logs, so you would do that after the data is sent and not inside the APM.

Just keep in mind that changing the data_stream and namespace can have negative consequences if you do not do it correctly (index templates, component templates).

Use the reroute processor (https://www.elastic.co/guide/en/elasticsearch/reference/current/reroute-processor.html).

**Comment by ramdaspotale** [comment]
Hi @philippkahr - i am using this https://github.com/elastic/apm-data/pull/201 feature from apm server to segregate traces coming from different applications in our environment so that search against each application can be done separately without overloading ES.

using traces@custom ingest pipeline with reroute processor would add some load on ES given how busy our prod elasticsearch is.

and as this feature is already there in APM 8.13 i was curious if i could use it in this scenario as well. add `data_stream.dataset`, `data_stream.namespace`  and rest assured that it will happen automatically.

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch @ramdaspotale.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can move this conversationthere, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I lock this thread.
