### ISSUE TITLE
Expand CCS tests coverage

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#84481]
We currently have [integration tests](https://github.com/elastic/elasticsearch/tree/master/qa/multi-cluster-search) that cover cross-cluster search. What they don't cover is cross-cluster communication across multiple versions. We should make sure that these tests run against the previous minor version and double check their coverage (e.g. do they use the fields API? do they also cover field_caps? Which features of search and field_caps they cover?).

As a natural follow-up, it might make sense to consider reusing the existing field_caps and search tests yaml tests and run them in a CCS scenario, so that we don't need to maintain parallel CCS tests manually, as they tend to be forgotten over time.

Perhaps related to #78472 as it involves more CCS testing

Currently the steps we identified to reach better coverage are

- [x] run the existing qa:multi-cluster-search also against the previous minor version (#85281)
- [x] extend the ability to skip yaml for certain remote cluster versions (#85566) (follow up needed for #85281)
- [x] investigate if we should extend qa:multi-cluster-search to also test forward compatibility, i.e. all wire compatible local cluster versions agains a "current" remote ( #86521)
- [x] investigate if we can re-use existing search rest tests in a multi-cluster CCS setup (#86521)
- [x] investigate if the `proxy mode` in CCS is covered well in tests or if it also needs more coverage
* we decided that the [current coverage](https://github.com/elastic/elasticsearch/issues/84481#issuecomment-1128842367) is okay and added randomization of the connection mode for better coverage in (#86865)

**Comment by javanna** [comment]
> From what I can see so far it seems to me we do have some good coverage of the basic scenarios here. We might consider moving randomization of the connection to AbstractMultiClustersTestCase (similar to the setup in SearchStatesIT) and see if that breaks any existing tests. Also we can probably randomize the connection mode for the CCS test we currently add in https://github.com/elastic/elasticsearch/pull/86521

Agreed @cbuescher thanks for digging.

**Comment by javanna** [comment]
@cbuescher sounds like this can be closed? :)
