### ISSUE TITLE
Include aggs specific challenges to nightly benchmarks

### ISSUE THREAD

**Issue by salvatore-campagna** [elastic/elasticsearch#84570]
### Description

The Analytics and Geo team wants to run performance tests on aggregations using Rally.
The goal is to have the ability to spot any performance regression on different aggregations and possibly affecting products, solutions or any other customer.

Once performance test results are stable enough we will be able to rely on them to identify possible performance issues and  performance regressions.

The idea is also to evaluate if we need to remove `target-throughput` and `target-interval` from selected challenges and if we would like to use one or more clients to run performance tests.

When it comes to the Elasticsearch deployment and architecture the idea is to have simple deployment with just one machine and two configurations: `default` and `8gheap`. Given the goal of being able to spot (pure) performance regressions for aggregations, we would like to avoid a complex setup (involving networks, interaction between coordinator node and data node, multiple shards, unbalanced document distribution,..).

### Tasks
- [x] [Add the existing `aggs` challenge under the `noaa` track to nightly benchmarks](https://github.com/elastic/elasticsearch/issues/84573)

- https://github.com/elastic/night-rally/pull/605 
- https://github.com/elastic/rally-tracks/pull/240
- https://github.com/elastic/rally-tracks/pull/243

- [x] [Refactor `noaa` and `nyc_taxis` tracks to include more aggregations](https://github.com/elastic/elasticsearch/issues/84809)

- https://github.com/elastic/rally-tracks/pull/250

- [x] Add the `aggs` challenge under the `nyc_taxis` track to nightly benchmarks

- https://github.com/elastic/night-rally/pull/634

- [ ] [Add a new performance test for a high cardinality aggregation](https://github.com/elastic/elasticsearch/issues/85991)
- [x] (Optional) Add a new `aggs` challenge under the empty `tsdb` track with time series related aggregations
- [x] (Optional) Add the `aggs` challenge under the `tsdb` track to nightly benchmarks
- [ ] (Optional) Collect all aggregations challenges across different tracks under a single view
- [x] Establish a process to review results

**Comment by salvatore-campagna** [comment]
I created two new dashboards in the `rally-metrics` deployment to have a better understanding of performance for both **nyc_taxis** and **noaa**.
* https://rally-metrics.kb.eu-central-1.aws.cloud.es.io:9243/goto/1248d84edaf2d03c4dc869ab9b617fe1
* https://rally-metrics.kb.eu-central-1.aws.cloud.es.io:9243/goto/6bcb3f9d6b0e8b5ba499c3fffe951ccd

**Comment by salvatore-campagna** [comment]
I am collecting some resources and hints for investigating performance issues in the following document: https://docs.google.com/document/d/1kMotGUtZXB6HeY0F5lrpgbdVplwNqv_VlLbbALlry1I/edit?usp=sharing

**Comment by wchaparro** [comment]
Hey @salvatore-campagna can you please open an issue for the line item " Collect all aggregations challenges across different tracks under a single view"? 
Closing this item as the other tasks have been completed. The other remaining item is captured in this issue: https://github.com/elastic/elasticsearch/issues/85991
