### ISSUE TITLE
Remove direct uses of hppc

### ISSUE THREAD

**Issue by rjernst** [elastic/elasticsearch#84735]
This is a meta issue for removing most uses of hppc from Elasticsearch.

Like any complex software project, Elasticsearch uses various data structures from computer science: lists, maps, sets, etc. Java provides interfaces for these structures (Java Collections Framework, JCF), and concrete implementations using well known techniques, like a hashtable based Map implementation, HashMap. The Java provided implementations are used throughout Elasticsearch.

Additionally, Elasticsearch server depends on the HPPC library. It provides alternatives to Java’s builtin collections that attempt to provide efficient, fast and “open” implementations (open here means easily hackable). The library is mostly wrapped with our own classes, namely ImmutableOpenMap and ImmutableOpenIntMap, but it is also used sporadically throughout the codebase. But when to use the HPPC based collections vs the Java ones has never been well defined within the team.

HPPC has been around for more than a decade, and while it once provided major performance benefits over JCF, Java has changed a lot in that time, especially in hotspot. It is unclear if HPPC actually provides advantages over JCF anymore. On top of this, the HPPC based collections are more difficult to use, and don’t easily interoperate with JCF interfaces, requiring conversion, or more often, forcing a developer to use HPPC because an upstream object used it, like when dealing with cluster state.

We have decided to try to move away from using hppc. Doing so is tricky since swapping out JCF classes are not trivial in most uses. This meta issue lists direct uses of hppc that should be either removed entirely, or evaluated for performance differences with JCF. Whether performance tests are needed would depend on the use case, and whether it is expected to be sensitive to memory footprint, and the objects lifetime.

- [x] `server`
  - [x] `o.e.action.admin.cluster.stats` (#85639)
  - [x] `o.e.action` Multi* request/response (https://github.com/elastic/elasticsearch/pull/85888)
  - [x] `o.e.action.admin.indices` (https://github.com/elastic/elasticsearch/pull/85911)
  - [x] `o.e.common` (https://github.com/elastic/elasticsearch/pull/85957)
  - [x] `o.e.http` (https://github.com/elastic/elasticsearch/pull/86024)
  - [x] `o.e.index.engine` (https://github.com/elastic/elasticsearch/pull/86072)
  - [x] `o.e.index.mapper.BinaryFieldMapper` (#85352)
  - [x] `o.e.index.mapper` (#85417, #85475)
  - [x] `o.e.index.seqno` (https://github.com/elastic/elasticsearch/pull/86073)
  - [x] `o.e.index.translog` (https://github.com/elastic/elasticsearch/pull/85657)
  - [x] `o.e.indices` (https://github.com/elastic/elasticsearch/pull/85911)
  - [x] `o.e.rest.action.cat` (https://github.com/elastic/elasticsearch/pull/85842)
  - [x] `o.e.search.aggregations.bucket.nested` (https://github.com/elastic/elasticsearch/pull/86078)
  - [x] `o.e.search.aggregations.bucket.terms` (https://github.com/elastic/elasticsearch/pull/86151)
  - [x] `o.e.search.aggregations.metrics` (https://github.com/elastic/elasticsearch/pull/86150)
  - [x] `o.e.search.aggregations.pipeline` (https://github.com/elastic/elasticsearch/pull/86023)
  - [x] `o.e.search.dfs` (https://github.com/elastic/elasticsearch/pull/84688)
  - [x] `o.e.tasks` (https://github.com/elastic/elasticsearch/pull/85889)
  - [x] `o.e.transport` (https://github.com/elastic/elasticsearch/pull/85843)
- [x] `server` unit tests 
  - [x] `o.e.action.fieldcaps` (#85236)
  - [x] `FieldMemoryStatsTests` (#85240)
  - [x] `o.e.common.util` (#85406)
  - [x] `o.e.index` (#85297)
  - [x] `SearchServiceTests` (#85188)
  - [x] `BinaryRangeAggregatorTests` (#85468)
  - [x] `o.e.search.aggregations.metrics` (#85468)
  - [x] `o.e.search.runtime`
  - [x] `o.e.search.slice`
- [x] `server` integ tests
  - [x] `AllocationAwarenessIT` (https://github.com/elastic/elasticsearch/pull/84736)
  - [x] `aggs and search tests` (https://github.com/elastic/elasticsearch/pull/84963)
- [x] test framework
  - [x] `LinearizabilityChecker` (https://github.com/elastic/elasticsearch/pull/84878)
  - [x] `InternalTestCluster` (https://github.com/elastic/elasticsearch/pull/84882)
  - [x] `TestCluster` (https://github.com/elastic/elasticsearch/pull/84850)
- [x] x-pack 
  - [x] core module (https://github.com/elastic/elasticsearch/pull/84783)
  - [x] analytics module (https://github.com/elastic/elasticsearch/pull/84849)
  - [x] ccr module (https://github.com/elastic/elasticsearch/pull/84782)
  - [x] ml module (https://github.com/elastic/elasticsearch/pull/84815)
  - [x] sql qa (`JdbcAssert`) (https://github.com/elastic/elasticsearch/pull/84782)

**Comment by rjernst** [comment]
With the exception of ImmutableOpenIntMap and ImmutableOpenMap, the uses of hppc have been removed. I opened a followup for those classes, as they are used quite extensively: https://github.com/elastic/elasticsearch/issues/86239
