### ISSUE TITLE
Cluster coordination indicator - report if the master is stable and an impact/troubleshoot guide otherwise

### ISSUE THREAD

**Issue by andreidan** [elastic/elasticsearch#85624]
Each node will need to keep track of the last few master node changes (this should be fine in memory) and its local node information (a node might _see_ the master node flapping, but the master node itself is fine). e.g. if the master node has changed >3 times in the last 30 minutes, then it's not stable. otherwise, nothing to report.

The coordinating node might have to contact a master eligible node which in turn might have to contact other master eligible nodes, but this is the worst-case scenario and definitely does not involve fanning out to all nodes.

- [x] Store a view of the last 30 minutes of master history on each node, and add the ability to query any node for its view of master history #85941
- [x] Determine if the node has master (if one is present in the cluster state or otherwise if it has seen one in the last 30 seconds) #86524

In case the node has master according to above definition:
- [x]  Check if a seen master is stable - master did not go `null` repeatedly in the last 30 *minutes*. Report GREEN #86524
- [x] Check if master is UNSTABLE - did it change more than 3 times in the last 30 *minutes* ? Report YELLOW (add history info on who was master and when) #86524
   - [x] RCA for unstable master - try and contact a previous master about the reason it stepped down (take disconnect/timeout of the network call into account). For this we'll need to expose the "master history log" we built at the above points over the wire. #86524
- [x] Check if *we* (the node coordinating this check) are unstable - has the witnessed master gone null/not-null more than 3 times in the last 30 minutes but the identity hasn't changed? Report the unstable master case above (report YELLOW) with the same RCA #86524

In case the node does not have a master node: 
- [x] Check if we know of any master-eligible nodes - in case we don't know of any report RED due to a discovery problem (include witnessed masters history). #87482
In case we know of some use the `PeerFinder` to check:
  - [x] Check if one of them is master - in which case report RED as we are having issues joining a cluster #87482
  - [x] None of them is master and we aren't master eligible 
       - [x] RCA reach out to a master eligible node and run the same checks (take disconnect/timeout of the network call into account)
- [x] If *we* are master eligible nodes collect the information form all known master eligible nodes (the information about term/version/voting config should be available in `ClusterFormationFailureHelper`, however we'd need that exposed over the wire #87306 ) -  take disconnect/timeout of the network call into account

- [x] Document the settings we create for the master stability and cluster diagnostics service(s) #87901

- [x] Create `master-is-stable` indicator
  - [x] Outline the details we'll be able to provide on drill down
  - [x] Add impacts
  - [x] Add user-actions
    - [x] Investigate what troubleshooting docs we can offer

**Comment by masseyke** [comment]
![2022-04-18 Coordination health](https://user-images.githubusercontent.com/453603/177401768-adda0bc7-112b-4b39-943f-202cfc4d142e.png)
Adding the diagram we're using to drive this work.
