### ISSUE TITLE
Remove uses of ImmutableOpen*Map

### ISSUE THREAD

**Issue by rjernst** [elastic/elasticsearch#86239]
After https://github.com/elastic/elasticsearch/issues/84735, hppc usage in Elasticsearch is now isolated to `ImmutableOpenMap` and `ImmutableOpenIntMap`. This is a meta issue delineating the remaining uses of those classes that need to be removed.

- [ ] ImmutableOpenIntMap
  - [ ] server
    - [ ] o.e.Version
    - [ ] o.e.action.admin.cluster.reroute
    - [ ] o.e.action.admin.indices.shards
    - [ ] o.e.cluster.DiffableUtils
    - [ ] o.e.cluster.metadata.IndexMetadata
    - [ ] o.e.cluster.routing.IndexRoutingTable
  - [ ] server tests
    - [ ] o.e.action.admin.indices.shards
    - [ ] o.e.cluster.health
    - [ ] o.e.cluster.serialization
  - [ ] server integ tests
    - [ ] o.e.action.admin.indices.shards
    - [ ] o.e.cluster.routing
- [ ] ImmutableOpenMap
  - [ ] server
  - [ ] server tests
  - [ ] server integ tests
  - [ ] test framework
  - [ ] xpack core
  - [ ] data streams
  - [ ] autoscaling
  - [ ] ccr
  - [ ] deprecation
  - [ ] enrich
  - [ ] ilm tests
  - [ ] ML
  - [ ] QL
  - [ ] rollup
  - [ ] searchable snapshots
  - [ ] security
  - [ ] node shutdown
  - [ ] transforms
  - [ ] watcher

**Comment by dakrone** [comment]
@rjernst do we still plan to keep some (most?) of these as immutable maps, or are we converting to mutable `HashMap`-like maps for these?

**Comment by rjernst** [comment]
Yes I think they can and should remain immutable, just immutable Map instances with Map.of or Map.copyOf.

**Comment by thecoop** [comment]
`ImmutableOpenMap` was *added* to the cluster/index metadata classes in #86673 for performance reasons. So we need to find a different collection type (maybe guava immutablemap?) if we want to remove `ImmutableOpenMap`

**Comment by thecoop** [comment]
https://github.com/elastic/elasticsearch/pull/90006 caused a performance drop, needs to be thought about more
