### ISSUE TITLE
Snapshots as archives improvements

### ISSUE THREAD

**Issue by ywelsch** [elastic/elasticsearch#87291]
This issue is to capture future enhancements for snapshots as archives (#81210).

Phase 1 of the project still required users during a major version upgrade to take extra steps: snapshot the data that can't make it to the next major version, and delete it from the cluster, then do the upgrade, and finally restore / mount the data against as legacy indices. The goal of phase 2 is to automatize some of this, making it easier for user to go through a major version upgrade. Some steps could include providing an ILM integration so that indices can be transitioned to an "archive" where they will be limited to doc-values / source-only access, as well as allow users to upgrade to the next major version by auto-converting indices to archival. Other tasks:

- [ ] auto-map source-only indices (from source-only snapshot repositories) automatically as runtime fields
- [ ] better error messages on nested fields
- [ ] running queries on _id or disallowing it
