### ISSUE TITLE
Follow-ups to ANN with filtering

### ISSUE THREAD

**Issue by jtibshirani** [elastic/elasticsearch#87490]
This meta issue tracks follow-up work to ANN with filtering (https://github.com/elastic/elasticsearch/pull/84734).

- [x] Fix rare failure case with very selective filters. ([LUCENE-10611](https://issues.apache.org/jira/browse/LUCENE-10611))
- [x] Make sure that the kNN search takes advantage of the [node query cache](https://www.elastic.co/guide/en/elasticsearch/reference/8.3/query-cache.html). Currently, even when the filter is cached, all its results are copied before performing the HNSW graph search. ([LUCENE-10606](https://issues.apache.org/jira/browse/LUCENE-10606))
- [x] [Add rally benchmarks for kNN search with filters.](https://github.com/elastic/rally-tracks/issues/272)
- [x] https://github.com/elastic/night-rally/issues/685
