### ISSUE TITLE
Enhancing Async Search 

### ISSUE THREAD

**Issue by mayya-sharipova** [elastic/elasticsearch#88658]
### Description

This is a meta issue on enhancing Async Search:

**Bugs/Clarifications**
- [ ] https://github.com/elastic/elasticsearch/issues/55572
- [ ] Follow-ups for circuit breaker work ([#67594](https://github.com/elastic/elasticsearch/issues/67594)):
  - Should we enable the soft-limit by default in 7.15? 
  - Should we enable the limit for EQL responses as well?

**New Feature requests**
- [x] https://github.com/elastic/elasticsearch/issues/88640
- [x] https://github.com/elastic/elasticsearch/issues/86009
- [x] https://github.com/elastic/elasticsearch/issues/86011
  - https://github.com/elastic/elasticsearch/pull/67877 reverted
  -https://github.com/elastic/elasticsearch/issues/86012 duplicate ?
- [ ] https://github.com/elastic/elasticsearch/issues/70037
- [x] https://github.com/elastic/elasticsearch/issues/62935

**Enhancements for stability and more robust performance**
- [x] https://github.com/elastic/elasticsearch/issues/71223
- [x] https://github.com/elastic/elasticsearch/issues/73971
- [ ] https://github.com/elastic/elasticsearch/issues/55464
- [ ] https://github.com/elastic/elasticsearch/issues/37867
   -  should async searches share the same thread pool?

**Comment by javanna** [comment]
I am closing this meta issue in favour of the sub-issues that it points to that have remained open.
