### ISSUE TITLE
Make REST API syntax errors and the use of deprecated APIs easier to discover

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#8989]
In the past, we have silently ignored unknown parameters.  While this has greatly improved, it is not 100% consistent and, for instance, we still silently ignore illegal combinations of parameters (eg in the `match` query). 

As a user, it is much easier to understand why something isn't working if an exception is thrown instead of an error being silently ignored.  Also, we currently have no way of indicating to a user that they are using deprecated syntax which will disappear in the next version.

This issue is a meta-issue to list the various improvements that we need to make:
- [x] Warn when using deprecated syntax https://github.com/elastic/elasticsearch/pull/11033
- [x] Use `parseField` to parse all parameter names #8964
- [x] ~~Replace hand parsing of requests/queries/mappings/etc with a grammar #8965~~
- [x] Verify that source object is ended properly and does not contain any trailing tokens #11414
- [x] Deprecate camel casing #8988
- [ ] Don't accept invalid UTF8 #9538
- [x] URL param parsing should not be lenient #14719

**Comment by nik9000** [comment]
I think it is safe to close this because we still have #9538 open.

@clintongormley, if you object then please reopen.
