### ISSUE TITLE
[HealthAPI] Warn when max shards per node setting is reached

### ISSUE THREAD

**Issue by andreidan** [elastic/elasticsearch#91119]
The Health API should signal when a deployment is closing the `max_shards_per_node` limit.  

Due to this does not relate to the `shard_availability` information, it should be a new indicator.

The settings keys are `cluster.max_shards_per_node & cluster.max_shards_per_node.frozen`

Thresholds:
* Yellow: room for < 10 shards
* Red: room for < 5 shards

## Tasks

- [x] In order to maintain feature parity with the old [`checkShards`](https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/deprecation/src/main/java/org/elasticsearch/xpack/deprecation/ClusterDeprecationChecks.java#L23), it should use the configurations provided by the master node. The Health API information is fetched from any node, so there could be a mismatch between the setting values by hence an incorrect indicator status. It's necessary to create a new `HealthMetadata` entry to use the values from the master node. (PR #94116)
- [x] Create a new Health Indicator that makes use of `ShardLimitValidator.canAddShardsToCluster` to validate the status of the cluster (PR #94552)
- [x] Add mappings for new impacts and diagnoses (PR https://github.com/elastic/telemetry/pull/2123)
- [x] Add documentation for the new indicator https://github.com/elastic/elasticsearch/blob/main/docs/reference/health/health.asciidoc  
  - [x] #94738 
  - [x] #95208
- [x] Validate that the new indicator it's correctly displayed in the Deployment > monitoring > health pages

### Open questions:

* What capabilities will be affected by this indicator?
* Should it be checked only for hot and content tiers? 
  * We'll use the current `checkShards` method, which it's already considering the frozen or regular tiers.

### Related

* [System indices should be exempt from shard limits](https://github.com/elastic/elasticsearch/issues/71486)
* Here's how to fix it https://www.elastic.co/guide/en/elasticsearch/reference/current/size-your-shards.html#_this_action_would_add_x_total_shards_but_this_cluster_currently_has_yz_maximum_shards_open

**Comment by HiDAl** [comment]
![Screenshot 2023-05-23 at 16 17 07](https://github.com/elastic/elasticsearch/assets/284537/3d53b8a9-3163-4716-9cd2-9b044edc584a)
![Screenshot 2023-05-23 at 16 17 19](https://github.com/elastic/elasticsearch/assets/284537/d59bf758-7007-4ac7-af51-a85b260460bb)
![Screenshot 2023-05-23 at 16 18 33](https://github.com/elastic/elasticsearch/assets/284537/84acb459-bf62-4803-9685-ea5979e11cf6)
![Screenshot 2023-05-23 at 16 18 42](https://github.com/elastic/elasticsearch/assets/284537/9051801c-c283-4a11-97fa-534082f0b9db)
