### ISSUE TITLE
Follow-up work for desired balance allocator

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#91386]
- [ ] https://github.com/elastic/elasticsearch/pull/91343#discussion_r1015250509: extract common code from `ResizeAllocationDecider#canAllocate` and `ResizeAllocationDecider#getForcedInitialShardAllocationToNodes`.

- [ ] https://github.com/elastic/elasticsearch/pull/91343#discussion_r1015376521: confirm whether it's enough to rely on the invariants of `RoutingNodes` to protect against assigning multiple copies of a shard to a node.

- [ ] https://github.com/elastic/elasticsearch/pull/91343#discussion_r1015387753: confirm whether the new comment is sufficient

- [ ] https://github.com/elastic/elasticsearch/pull/91343#discussion_r1015436861: is `findLatest` doing the right thing?

- [ ] https://github.com/elastic/elasticsearch/pull/91343#discussion_r1015625531: is `PendingListenersQueue#completeAllAsNotMaster()` safe?

- [ ] https://github.com/elastic/elasticsearch/pull/91343#discussion_r1016235756: `ContinuousComputation` has lacklustre rejection handling

- [ ] https://github.com/elastic/elasticsearch/pull/91343#discussion_r1016240398: make explicit the assumption that `onNewInput` is called in order with increasing indices

- [ ] https://github.com/elastic/elasticsearch/pull/91343#discussion_r1016254823: do we want to bail out on all empty balances or just `INITIAL`?

- [ ] https://github.com/elastic/elasticsearch/pull/91343#discussion_r1016269907: should we also use `canAllocate(shard, allocation)` to short-circuit cases where a shard cannot be assigned anywhere?

- [ ] Possible improvements to code copied from existing implementation:

  - [ ] https://github.com/elastic/elasticsearch/pull/91343#discussion_r1015444100: should `failAllocationOfNewPrimaries` check the recovery source?

  - [ ] https://github.com/elastic/elasticsearch/pull/91343#discussion_r1015445384: use `!=` instead of `^`.

  - [ ] https://github.com/elastic/elasticsearch/pull/91343#discussion_r1015449380: `.compareTo() == 0` vs `.equals()`

  - [ ] https://github.com/elastic/elasticsearch/pull/91343#discussion_r1015463215: comparator efficiency
