### ISSUE TITLE
[Meta] Data Lifecycle Management

### ISSUE THREAD

**Issue by andreidan** [elastic/elasticsearch#93596]
### Description

The Data Lifecycle Management (DLM) service handles the lifecycle of data streams based on a declarative configuration that describes the desired end state.

Phase 1:

### Before removing the feature flag

* [X] Introduce the `Lifecycle` model in existing data stream configuration (including the feature flag) @gmarouli (https://github.com/elastic/elasticsearch/pull/93652)  
* [x] Introduce the `cluster.dlm.default.rollover` cluster setting and enable the data stream GET to display the configuration @gmarouli (https://github.com/elastic/elasticsearch/pull/94240)
* [x] PUT/GET/DELETE `_data_stream/logs/_lifecycle` APIs @gmarouli ( https://github.com/elastic/elasticsearch/pull/94590 )
* [ ] Create a `manage_dlm` privilege and use it for the `_lifecycle` APIs @masseyke ( https://github.com/elastic/elasticsearch/pull/95512 )
* [X] Introduce the DLM module @andreidan 
* [x] Implement the `DataLifecycleManagementService` @andreidan (https://github.com/elastic/elasticsearch/pull/94012, https://github.com/elastic/elasticsearch/pull/94391)
* [ ] Implement the DLM Service security model
* [x] `DataLifecycleManagementService` execution error tracking @andreidan (https://github.com/elastic/elasticsearch/pull/94391)
* [x] The `POST indexname/_lifecycle/explain` API (note it should report the errors from execution too) @andreidan ( https://github.com/elastic/elasticsearch/pull/94621 )
* [x] Optionally add the `index.lifecycle.prefer_ilm` setting (defaults to `true`) @andreidan ( https://github.com/elastic/elasticsearch/pull/95423 )
* [x] Introduce the include_defaults parameter to the simulate index template and simulate index APIs @gmarouli (https://github.com/elastic/elasticsearch/pull/94861)
* [x] Add origination_date support (similar to ILM) https://github.com/elastic/elasticsearch/pull/95113  @masseyke 
* [x] Implement support for automatic rollover parameter for max_age @gmarouli  (https://github.com/elastic/elasticsearch/pull/94950)
* [x] Implement executing forcemerge for a backing index on the first run after rollover @masseyke (https://github.com/elastic/elasticsearch/pull/95204)
* [x] Document the feature in a holistic way (linking to APIs and such) @gmarouli (https://github.com/elastic/docs/pull/2658, https://github.com/elastic/elasticsearch/pull/95326, ...)

Phase 2:

* [x] Compose lifecycle from component templates @gmarouli (https://github.com/elastic/elasticsearch/pull/96027)
* [x] Allow lifecycle and data retention to be explicitely nullyfied @gmarouli (https://github.com/elastic/elasticsearch/pull/95979)
* [x] Add telemetry for DLM @masseyke (https://github.com/elastic/elasticsearch/pull/96177)
* [x] https://github.com/elastic/elasticsearch/issues/96875

**Comment by andreidan** [comment]
This work is complete 🎉
