### ISSUE TITLE
Move `checkShards` from Deprecation API to Health API

### ISSUE THREAD

**Issue by HiDAl** [elastic/elasticsearch#94079]
## What?

Currently, in order to upgrade a cluster to a newer version, a set of checks are run validating that it's safe to upgrade. [One of these checks validates](https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/deprecation/src/main/java/org/elasticsearch/xpack/deprecation/ClusterDeprecationChecks.java#L23) that there's enough room in the cluster to create new shards for (potential) intermediate indices. 

## How

The main idea it creates a new indicator into the new [Health API](https://www.elastic.co/guide/en/elasticsearch/reference/master/health-api.html), in such a way it'll be displayed on the `Deployment Management > Monitoring > Health page`. Later, the Cluster Upgrade Tool should use this indicator to validate that upgrading the cluster is safe. Also, the check should be removed from the Deprecation API.

## Tasks

- [x] Talk with the UI team to confirm that the new indicator, once exposed in the UI, will automatically appear in the UI or it must be developed involved
- [x] Create all the machinery in Elasticsearch repo to expose the new Health API indicator (ticket tracking this work #91119)
- [x] Start the conversations with the Cloud team about the needed changes on their side to use this indicator –or any other new indicator– to block upgrades in case the cluster is Unhealthy.
- [ ] Removes the old check from the Deprecation API #95177

### Related

* PR introducing the check https://github.com/elastic/elasticsearch/pull/85967

**Comment by HiDAl** [comment]
Asked to @ElenaStoeva and @sabarasaba from UI team. Both have indicated that to show the new indicator, we should have to update the [Scala code here](https://github.com/elastic/cloud/blob/63541ed2baf72c5473e0ab65443442a454ad890f/scala-services/adminconsole/src/main/scala/no/found/adminconsole/api/v1/routes/deployments/health/HealthValidators.scala#L351). After that it'd automatically appear on the UI.
