### ISSUE TITLE
Failed document handler

### ISSUE THREAD

**Issue by felixbarny** [elastic/elasticsearch#95534]
Instead of dropping documents that have failed ingestion due to an exception during pipeline execution or indexing, it should be possible to store the failed document.

High-level options where to store the failed documents:
1. In a dedicated data stream
2. Within the same data stream, in dedicated failure backing indices
3. Within the same index, only storing the _source and with an indicator that these reflect failed documents

```[tasklist]
### Tasks
- [x] Basic functionality of data streams that can have failure store backing indices with a hard-coded shard count of one https://github.com/elastic/elasticsearch/pull/99134
- [ ] Send failures during ingest pipeline execution to the failure store
- [ ] Send failures during shard-level failures to the store (mapping issues etc.)
- [ ] Flag for search API to be able to search items in the data store
- [ ] Lazily create the failure store
- [ ] Turn the failure store on by default
- [ ] Testing edge cases: verify CCR, modify APIs, snapshot/restore, etc.
- [ ] Evaluate scalability and make sure this plays nicely with  shard auto-scaling

```

**Comment by lachlann562** [comment]
This would be extremely helpful, we recently discovered we were losing a huge number of messages because of inconsistency in data type and we couldn't find any easy way to identify these messages or recover the data associated with them. The abscence of log records is a huge risk when you are reliant on ELK as the "source of truth".

**Comment by flash1293** [comment]
@felixbarny can this be closed?

**Comment by wolframhaussig** [comment]
> [@felixbarny](https://github.com/felixbarny) can this be closed?

Why should this be closed? It would be extremely helpful and reduce our effort to look for the missing data in a long pipe of components (app->openshift->ingest pipeline root->ingest pipeline app->index).

**Comment by felixbarny** [comment]
Because this has been delivered. I'll defer to @mattc58 to check if we can close this out or if there's anything left.

**Comment by dakrone** [comment]
Yes, I believe this can be closed as resolved by https://github.com/elastic/elasticsearch/pull/126973.
