### ISSUE TITLE
[Transform][Search] Meta Issue: improve Transform robustness in case of search errors

### ISSUE THREAD

**Issue by hendrikmuhs** [elastic/elasticsearch#96296]
Based on recent feedback we discovered some shortcomings in transforms when search experiences a problem. This meta issue lists improvements.

This is not a transform issue, but covers _search_, which builds the foundation for transform.

/CC @dnhatn, @javanna, @przemekwitek, @wchaparro, @droberts195, @sophiec20, @dimkots 

My suggestions, feel free to add yours. I suggest to spawn new issues for every task and discuss the details there, to keep this meta issues clean.

- [ ] point in time breaks on shard relocation, @dnhatn is already looking into this
- [ ] search fails with a `QueryShardException`, this exception type classifies itself as [`BAD_REQUEST`](https://github.com/elastic/elasticsearch/blob/b8f170db95483c631669e21f0ca718504ca8b44a/server/src/main/java/org/elasticsearch/index/query/QueryShardException.java#LL46C29-L46C29), but not every `QueryShardException` is a `BAD_REQUEST`. A bad request is considered an irrecoverable error, that's why transform decides not to retry(except it is configured as `unattended`)
- [ ] `SearchExecutionContext` treats a generic [`Exception` as `QueryShardException`](https://github.com/elastic/elasticsearch/blob/b8f170db95483c631669e21f0ca718504ca8b44a/server/src/main/java/org/elasticsearch/index/query/SearchExecutionContext.java#L571)
    - [ ] the underlying Lucene exception of type `AlreadyClosedException` is a subtype of `IllegalStateException`, this is more of a 409, if the exception wouldn't have been turned into `QueryShardException`, it would have been treated as internal server error. In both cases transform would have retried. 
    - [ ] The Lucene exception lacks useful  information, e.g. the name of the analyzer (not sure if this is possible)
    - [ ] `SearchExecutionContext` should add important information to the exception, if possible, e.g. name of the field, the sub-query, ...
 - [ ] Transform uses `getDetailedMessage()` to populate the `reason` field in `_stats` to persist the error(`_stats` is used in the diagnostics bundle). The `reason` field lacks useful information. Here are some requirements, proper naming, API design, UI implications, to be discussed as separate issue:
    - [ ] transform should log/persist the last executed query in order to help debugging, this could be added as additional field (only visible via `_stats`, no UI)
    - [ ] transform should use the `toXContent(...)` method of [`ElasticsearchException`](https://github.com/elastic/elasticsearch/blob/ff5c86eb7c98036040e4d8853fb3c92037b47291/server/src/main/java/org/elasticsearch/ElasticsearchException.java#L339) together with proper [params](https://github.com/elastic/elasticsearch/blob/ff5c86eb7c98036040e4d8853fb3c92037b47291/server/src/main/java/org/elasticsearch/ElasticsearchException.java#LL387C57-L387C57) to populate another field with the full JSON output of this method. In contrast to `getDetailedMessage()`, this includes the stack trace
