### ISSUE TITLE
[Meta] Providing information needed for better Stack Monitoring

### ISSUE THREAD

**Issue by tylerperk** [elastic/elasticsearch#98288]
### Description

Stack Monitoring relies on information gathered from various stats APIs into .monitoring indices for the graphs it displays. In order to satisfy the evolving needs of our customers, some additional information needs to be provided in these APIs (or maybe new ones). 

Enhancements: 
- [ ] [Ability to group index stats by Data Stream](https://github.com/elastic/elasticsearch/issues/98289)
- [ ] [Cluster name and ID in every stats response to enable filtering by cluster](https://github.com/elastic/elasticsearch/issues/98301)
- [ ] Node names and roles in every stat
