### ISSUE TITLE
ESQL: Documentation meta issue

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#99072]
### Description

There are a number of gaps in the ES|QL documentation that need addressing.
I'm pointing them out in this ticket in no particular order:

Pre 8.11 release:

- [x] Overview / Introductory page - what and why is ES|QL
- [x] Getting started with ESQL - basic ingestion plus querying and examples
- [x] Limitations (we already have a paragraph - this needs to be extracted out)
- [x] Improve the consistency of functions page
- [x] section on Task management
- [x] section on Kibana interaction / screenshots
- [x] self-contained section on Enrich, Dissect and Grok
- [ ] Security (role/permissions)
- [x] REST Endpoint (including different data formats, passing params to the query and the various other options like time_zone) - see https://github.com/elastic/elasticsearch/issues/99071 / https://github.com/elastic/elasticsearch/issues/99284
- [x] Add release highlight content - https://github.com/elastic/elasticsearch/pull/100191

Post 8.11 release:

- [x] section on Multi-value handling and semantics
- [x] Validate all code snippets are in spec files (so they're tested) and move them if not
- [ ] Expand Examples page (observability examples)

**Comment by abdonpijpelink** [comment]
I'm going to close this issue, as all items have been addressed, except:

- documentation around ES|QL and security. I've created a separate issue to track that: https://github.com/elastic/elasticsearch/issues/104805
- adding more examples is an ongoing effort.
