### ISSUE TITLE
ESQL: Major Issues for 8.11

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#99460]
### Description

A meta ticket tracking the main issues we want to solve for the 8.11:

- [x] Accurate memory tracking https://github.com/elastic/elasticsearch/issues/99173
- [x] add warning header for default limit - https://github.com/elastic/elasticsearch/issues/100555
- [x] Prevent unsupported data extraction from blowing up https://github.com/elastic/elasticsearch/issues/99506
	- [ ] fallback to source extraction for fields that have field data disabled https://github.com/elastic/elasticsearch/issues/99213
	- [x] fall back to field loading to keyword, if subfield exists https://github.com/elastic/elasticsearch/issues/99183
- [x] default limit in Kibana https://github.com/elastic/elasticsearch/issues/99458
- [x] count(*) / count() + push down filtered count https://github.com/elastic/elasticsearch/issues/99459
- [x] request timeout - https://github.com/elastic/elasticsearch/pull/99526

Bugs:
- [x] EsqlSpecIT test {ints.MultipleWarnings} failing https://github.com/elastic/elasticsearch/issues/98719
- [ ] adding _query endpoint to the Elasticsearch specification https://github.com/elastic/elasticsearch/issues/99533
- [x] mv_expand after sort fails https://github.com/elastic/elasticsearch/issues/99971
- [x] RestEsqlIT testTextMode #100257
- [ ] ESQL: Comparing a large long to an int field fails when pushed to source https://github.com/elastic/elasticsearch/issues/99960
- [ ] ESQL: date_extract using a constant/literal chrono_field fails to record the warning  https://github.com/elastic/elasticsearch/issues/100038
- [ ]  syntax error on date math if date period variable is at the end of the expression https://github.com/elastic/elasticsearch/issues/99293
- [ ] https://github.com/elastic/elasticsearch/issues/99672
- [x] drop date_xxx() warning when arguments are in reverse order https://github.com/elastic/elasticsearch/issues/99562
- [ ] emit warnings from all functions returning nulls on multivalues https://github.com/elastic/elasticsearch/issues/98743
- [ ] Incorrect error messages - https://github.com/elastic/elasticsearch/issues/100047
- [x] Improve parsing of query parameters  https://github.com/elastic/elasticsearch/issues/99570
- [x] null layout on ECS schema with WHERE + STATS https://github.com/elastic/elasticsearch/issues/100807
- [x] missing field in filter https://github.com/elastic/elasticsearch/issues/100869
- [x] Relax ValueSources check in OrdinalsGroupingOperator https://github.com/elastic/elasticsearch/pull/100566
- [x] Improve verifier for incorrect agg declaration https://github.com/elastic/elasticsearch/pull/100650
- [x] Aggregation don't preserve projection #99936
- [x] Grouping on ordinals ignore null group #100109 
- [x] Unhandled error when using multi-value as function argument  https://github.com/elastic/elasticsearch/issues/100497
- [x] org.elasticsearch.xpack.esql.qa.single_node.EsqlSpecIT failing https://github.com/elastic/elasticsearch/issues/100081
- [x] When double limiting the limit after mv_expand is not applied anymore https://github.com/elastic/elasticsearch/issues/100774
### Nice to have:
- [ ] expose source as a metadata field https://github.com/elastic/elasticsearch/issues/99456

### Postponed:
- [ ] default project for Kibana queries https://github.com/elastic/elasticsearch/issues/99457
- [ ] ES|QL does not consistently handle field names starting with a number https://github.com/elastic/elasticsearch/issues/100312
