### ISSUE TITLE
Roadmap for 2.0

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#9970]
* [x] #8312 Use doc values by default
* [x] #8870 Field/type mapping refactor
* [x] #9876 Perform computation on aggregations
* [x] #6295 Update cluster state using diffs
* #10217 ~~Refactor query and filter, agg, suggester parsing/serialization~~ (bumped to 3.0)
* [x] #8963 Warn when using deprecated syntax
* #3226 ~~Upgrade to Netty 4~~ 
* [x] Lucene 5.1
* [x] Lucene 5.2
* [x] #12768 Tests and packaging changes 
* [x] #11271 Shards should rebalance across multiple path.data on one node 
* [x] #12783 Remove spawn modules

Index migration:
* [x] #9498 Move to one datapath per shard
* [x] #10213 Allow upgrade API to only upgrade too-old segments
* [x] #10214 Migration advisory _site plugin
* [x] #10215 Don't allow indices containing too-old segments to be opened

**Comment by joealex** [comment]
#6295 will be pretty important to have for very large clusters and have the flexibility to keep adding Nodes

#8312 is very much awaited along with #9498 which seems like got moved to 2.0 ?

**Comment by lenniboy** [comment]
I know it's a little impatient to ask, but is there any indication when an ES2 beta will be released?

**Comment by dmitry** [comment]
Looks like there are still a lot of unclosed issues: https://github.com/elastic/elasticsearch/labels/v2.0.0

**Comment by runarmyklebust** [comment]
Does this mean that the suggested removal of having to separate filter and queries are postponed to v3? Would be nice to know, since it will impact our development plans.

**Comment by clintongormley** [comment]
@runarmyklebust no - that's already merged.  the query refactoring is about the java api and where requests get parsed: coordinating node or shard level.  unrelated to the query/filter merging

**Comment by runarmyklebust** [comment]
Ok, thanks a lot, got me a bit worried there.
