### ISSUE TITLE
ESQL: Search-level stats operator

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#99842]
### Description

Meta-ticket around aggregations that can be handled at the search level as the query features a filter/query:

- [ ] Min/Max for numeric types - https://github.com/elastic/elasticsearch/issues/99838
- [ ] unique terms / grouping key - https://github.com/elastic/elasticsearch/issues/99839
- [ ] count(field) - https://github.com/elastic/elasticsearch/issues/99840
- [ ] allow multiple search sources - https://github.com/elastic/elasticsearch/issues/99841
